src/lib/tvgTaskScheduler.cpp
This patch will fix runtime crash caused by incorrect init variables.
=> taskscheduler: initialize member correctly

src/lib/sw_engine/tvgSwShape.cpp
free dash outline stroke data memory properly.
=> sw_engine: fix memory leak.

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h, src/loaders/svg/tvgSvgSceneBuilder.cpp
vector is designed for c++ syntaxes,
it works properly when c++ memory allocator is applied,
Here svg_loader uses c style structures which allocated using malloc()/calloc().
That brings the memory broken of stl vectors.
So, we replaced it with our customized SvgVector to easily fix it.
=> svg_loader: fix vector memory leaks.

src/loaders/svg/tvgSvgLoader.cpp
If there is an empty (unused) <defs /> inside the svg file, this can cause problems.
<defs> node is managed separately in loader->def.
So it doesn't have to be added to loader's list.
=> SvgLoader: Defs type nodes are not saved in loader's node list.

src/loaders/svg/tvgSvgLoader.cpp
In several cases of svg loaders, segfaults have occurred.
most cases, it refers to wrong node.
These two commits are fixed to refer to the correct node.
=> Fix svg loader's segfualt

src/loaders/svg/tvgSvgSceneBuilder.cpp
Follow color policy of tvg:Shape.
=> SvgLoader: Use non-premultipied color

src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.h
As profiled, raster parallelization is not so efficient,
we revert this behavior.
We will come again with a better fine-tuned method.
=> sw_engine: step backward optimization.

src/loaders/svg/tvgSvgSceneBuilder.cpp
Follow color policy of tvg:Shape.
+  The fillOpacity default value is 255.0.
So far, fillOpacity is not used. Afterwards fillOpacity will be changed to refer to the parent's opacity.
=> SvgLoader: Gradient use non-premultipied color

src/loaders/svg/tvgSvgLoaderCommon.h
A segfault occurs when calling clear() a list without push.
This patch prevents it.
=> SvgLoaderCommon: Add initialization in SvgVector

src/loaders/svg/tvgSvgLoader.cpp
Since the pointer actually used inside the if condition is loader->def,
add a null check for this.
=> SvgLoader: Add null check

src/loaders/svg/tvgSvgLoader.cpp
Release the memory that was not released.
=> SvgLoader: Fix memory leak for loader's gradient

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h, src/loaders/svg/tvgSvgSceneBuilder.cpp
It supports stroke-dasharray, one of the stroke properties of svg.
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-dasharray
=> SvgLoader: Support DashArray attribute for stroke

src/loaders/svg/tvgSvgLoader.cpp
Mask and clippath TAG are not supported yet.
If this TAG is used, the Child TAG declared with this TAG may cause problems.
To prevent that, declare them as Unknown types until they are supported. (display=none)
=> SvgLoader: Add Mask, ClipPath nodees as dummy.

.gitignore, src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/gl_engine/tvgGlRenderer.h, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.h, src/lib/tvgCanvasImpl.h, src/lib/tvgGlCanvas.cpp, src/lib/tvgRender.h, src/lib/tvgSwCanvas.cpp, test/makefile, test/testCommon.h
previous implementation didn't consider multiple canvases,
multiple canvas shared one renderer engine that brought corrupted contexts.
Thus, each canvas instances should have designated renderer engine instances.
Now fixed.
=> common: fix context corruption among the multiple canvases.

src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.h, test/testDirectUpdate.cpp
tvg canvas must draw retained shapes for every draw call
even though user missed call update() for shapes.
that case canvs must draw shapes without update,
it means drawing them within previous condition.
=> sw_engine: fix shape rendering skip issue.

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h
In relation to the declaration of rx and ry attribute of rect, the following three cases occur.
rx="10" (or ry="10")
rx="10" ry = "0" (or rx="0" ry = "10")
rx="10" ry = "10"
To cover these case, we check the rx and ry declarations.
=> SvgLoader: Supports case when only rx or ry is declared

src/loaders/svg/tvgSvgSceneBuilder.cpp
When there is a matrix of linear gradient, the applied formula is this.
= T(x - cx, y - cy) x g->transform x T(cx, cy)
This patch has modified this formula to work properly.
this PR solve https://github.com/Samsung/thorvg/issues/33
=> SvgLoader: Modify calculation formula of linear gradient matrix

src/loaders/svg/tvgSvgLoader.cpp
When both defs and svg gradients are declared,
the update of gradient declared in <svg> is omitted.
Therefore, this patch fixes any missing gradient updates.
=> SvgLoader: Fix missing doc.gradients update

src/loaders/svg/tvgSvgPath.cpp
1. Cmd 'A' from an svg path should not be connected with any other commands via the control points. -> changes moved to #42
2. When the sweep flag is given as a float it draws an elliptic arc different from what the user intended.
Right now if large_arc is given as a float, the 'A' command won't be plotted at all (and nothing after it). _parseLong function called for the first time will read only the part of a float until the dot character. The second call of this function will return 'false', since the strtol function finds a dot as the first char in a given string. This is the desired behavior.
If sweep is given as a float, the svg path will be plotted until a new cmd will occur (a new letter in an svg path). It's because after the second _parseLong call there is a _parseNumber call, …
=> svg_loader: fixing issues with a A/a command

src/loaders/svg/tvgSvgPath.cpp
Cmd 'A' from an svg path should not be connected with any other commands via the control points.
This change will be excluded from #25
=> Fixing issues with a A/a command

src/loaders/svg/tvgSvgLoader.cpp
If dash array size is 1, it means that dash and gap size are the same.
#47
=> SvgLoader: Fix wrong display when dasharray size is 1

src/lib/sw_engine/tvgSwFill.cpp
warning: absolute value function 'fabsf' given an argument of type 'double' but has parameter of type 'float' which may cause truncation of value [-Wabsolute-value]
=> sw_engine: fix build warning

src/lib/tvgPaint.h
warning: some methods overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
=> common: fix compiler warnings.

src/bindings/capi/tvgCapi.cpp
init/term method allows mixing enum values,
we don't need to call them separatetly.
=> capi: code refactoring 

inc/thorvg.h, src/lib/tvgFill.cpp, src/lib/tvgFill.h, src/lib/tvgLinearGradient.cpp, src/lib/tvgPaint.h, src/lib/tvgPictureImpl.h, src/lib/tvgRadialGradient.cpp, src/lib/tvgSceneImpl.h, src/lib/tvgShapeImpl.h
removed unique_ptr in the interface because it's hard to get polymorphism benefits in programming perspective.
=> common fill: code refactoring

src/lib/tvgRadialGradient.cpp
Removed check for gradient radius. Because of check, x and y values
was ignored when radius equals 0 and api was not usable
in integration with external libs which sets gradient center and
radius in separeted functions.
=> gradient: Fixed radial gradient setter.

src/lib/gl_engine/tvgGlCommon.h, src/lib/gl_engine/tvgGlGeometry.cpp, src/lib/gl_engine/tvgGlGeometry.h, src/lib/gl_engine/tvgGlGpuBuffer.cpp, src/lib/gl_engine/tvgGlGpuBuffer.h, src/lib/gl_engine/tvgGlProgram.cpp, src/lib/gl_engine/tvgGlProgram.h, src/lib/gl_engine/tvgGlPropertyInterface.cpp, src/lib/gl_engine/tvgGlPropertyInterface.h, src/lib/gl_engine/tvgGlRenderTask.cpp, src/lib/gl_engine/tvgGlRenderTask.h, src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/gl_engine/tvgGlRenderer.h, src/lib/gl_engine/tvgGlRendererProperties.h, src/lib/gl_engine/tvgGlShader.cpp, src/lib/gl_engine/tvgGlShader.h, src/lib/gl_engine/tvgGlShaderSrc.cpp
After refactoring header includsion, gl_engine has a break at file dependencies.
now this fixes it.
=> gl_engine: fix compile error.

src/examples/testStrokeLine.cpp
Added dashed lines to circles and arcs.
Right now there is a problem with dashed curves (fixed in #86 ) and arcs with pie argument = 1. (fixed in #87)
=> examples: testStrokeLine example expanded

src/lib/tvgShape.cpp
For a dashed arc with pie = 1 the closing line was missing.
=> shape: fixing 'pie' option

src/lib/sw_engine/tvgSwFill.cpp, src/lib/sw_engine/tvgSwRaster.cpp
This will fix problem with gradient start and stop set for (0, 0) (0, 0). It filled shapes with random color lines then. Now it won't fill in this case at all.
=> gradient: added check for gradient start and end set for 0

inc/thorvg.h, src/examples/meson.build, src/examples/testClipPath.cpp, src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/gl_engine/tvgGlRenderer.h, src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.h, src/lib/sw_engine/tvgSwRle.cpp, src/lib/sw_engine/tvgSwShape.cpp, src/lib/tvgCanvasImpl.h, src/lib/tvgPaint.cpp, src/lib/tvgPaint.h, src/lib/tvgPictureImpl.h, src/lib/tvgRender.h, src/lib/tvgSceneImpl.h, src/lib/tvgShapeImpl.h
#49 
Paint object can composite by using composite API.
ClipPath composite is clipping by path unit of paint.
The following cases are supported.
Shape->composite(Shape);
Scene->composite(Shape);
Picture->composite(Shape);
Add enum
enum CompMethod { None = 0, ClipPath };
Add APIs
Result Paint::composite(std::unique_ptr<Paint> comp, CompMethod methd);
=> SwRender & tvgPaint: Implement ClipPath feature

src/lib/tvgShape.cpp, src/lib/tvgShapeImpl.h
Previous reset() doesn't implemented properly.
It resets only path data.
Now Shape resets all drawing properties.
https://github.com/Samsung/thorvg/issues/56
`tvg_engine_init(TVG_ENGINE_SW | TVG_ENGINE_GL, 0);
Tvg_Canvas* canvas = tvg_swcanvas_create();
tvg_swcanvas_set_target(canvas, buffer, WIDTH, WIDTH, HEIGHT, TVG_COLORSPACE_ARGB8888);
Tvg_Paint* shape = tvg_shape_new();
tvg_shape_append_rect(shape, 0, 0, 200, 200, 0, 0);
tvg_shape_set_stroke_color(shape, 255, 0, 0, 255);
tvg_shape_set_stroke_width(shape, 4);
tvg_shape_set_fill_color(shape, 0, 0, 255, 255);
tvg_canvas_push(canvas, shape);
tvg_canvas_draw(canvas);
tvg_canvas_sync(canvas);
tvg_shape_reset(shape);
tvg_canvas_update_paint(canvas, shape); …
=> common shape: fix reset() bug.

src/loaders/svg/tvgSvgPath.cpp
fabs() is designed for double type,
but here it uses float type.
=> svg_loader: use designated fabsf() for float values.

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h, src/loaders/svg/tvgSvgSceneBuilder.cpp
#49
Supports case of using style attribute for defined `<clipPath>`.
In SVG, `<clipPath>` can be used as a `"clipPath"` attribute or a style `"clip-path"`.
This patch only supports when `"clip-path"` of style is declared.
The remaining features will be added later.
[Spec]
https://drafts.fxtf.org/css-masking-1/#elementdef-clippath
[Example SVG case]
```html
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
viewBox="0 0 64 64" enable-background="new 0 0 64 64" xml:space="preserve">
<defs>
<clipPath id="clipPath">
<rect x="15" y="15" width="40" height="40" fill="#F00" />
<circle cx="20" cy="20" r="10" fill="#F00" />
</clipPath>
</defs>
<circle cx="25" cy="25" r="20"
style="fill: #0000ff; clip-path: url(#clipPath); " …
```
=> SvgLoader: Implement ClipPath style

src/loaders/svg/tvgSvgLoader.cpp
When using `<use>` node, do atrribute copy.
At that time, when target(`url`) is `polygon` or `polyline`,
points array is not copied, causing a problem in output.
So, add missing `memcpy()`
Test SVG Sample
```html
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
viewBox="0 0 64 64" enable-background="new 0 0 64 64" xml:space="preserve">
<g opacity="0.5">
<defs>
<polygon id="test" opacity="0.5" points="41.8,14.5 22.2,14.5 22.2,22.8 41.8,40.7"/>
</defs>
<use xlink:href="#test"  overflow="visible"/>
</g>
</svg>
```
=> tvgSvgLoader: Add points copy of missing polygon/polyline

src/examples/Stress.cpp, src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwShape.cpp
It missed to update shape data if visilibity is changed from false to true by alpha.
Also, it needs to update engine shape data for every requests.
There scenario can be allowed,
1. update shape
2. change shape property
3. update shape
4. draw
previously engine could skip step 3, its result was not properly expected.
@fix #84
=> sw_engine: fix missing shape update issue.

src/wasm/thorvgwasm.cpp
The 'getDefaultData' interface will be used when the svg data area
of thorvg viewer does not have any value.
=> thorvg viewer: add getDefualtData interface

src/wasm/thorvgwasm.cpp
If viewer calls load() with a data which does not have size changes of both
viewbox and canvas, then load() does not set a scale value.
This makes incorrect result on viewer side.
So thorvg wasm should set a scale value, whenever load() is called.
=> thorvg viewer: fix scale problem

src/lib/tvgBezier.cpp, src/lib/tvgBezier.h
Added a condition that prevents bezLength() function
from making infinite number of calls.
Plotting a curve with a dashed stroke in some cases crashed. This is because the condition for the termination of the bezLength() function was never satisfied. There was still a discrepancy , which was greater than 
The difference between the length of two approximations of the Bezier curve:
- the straight line from the start to the end point 
and 
- the length calculated as a sum of three lines (start-ctrl1, ctrl1-ctrl2 and ctrl2-end) 
was > FLT_EPSILON.
In such a case, the algorithm splits the curve into two smaller ones, but because of the finite density of floats, the calculation of of the points of the new Bezier curves ended with one of them being exactly same as the other (or …
=> Bezier curve: extension of the termination condition in bezLength()

src/lib/sw_engine/tvgSwRenderer.cpp
There a scenario detected that stroke 2 is not enough to cover
shape outlines. So make it bigger size.
- Tests or Samples (if any) : examples Svg
=> sw_engine renderer: fix aliasing shape outline result.

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwRle.cpp, src/lib/sw_engine/tvgSwShape.cpp
this change supports EvenOdd fillrule in shape rendering
@Examples: examples/FillRule.cpp
@Isuses: 97
=> sw_engine shape: support fillRule method

inc/thorvg.h, src/bindings/capi/tvgCapi.cpp, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/tvgShape.cpp, src/loaders/svg/tvgSvgSceneBuilder.cpp
returning color fill() method renamed to fillColor() as like others-strokeXXX, fillRule- do.
This change is for naming consistency.
=> common api: interface refactoring

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwShape.cpp, src/lib/tvgShape.cpp
For the dash pattern values (both, length and gap) < 1 the program crashed.
curLen - variable type changed from int to float.
For the dash pattern values (both, length and gap) < 1, the program crashes, because it falls into the infinite while loop (the total length of the dashed outline is reduced in each step by a value of zero, so it never gets smaller and the while loop termination condition is never satisfied).
The curLen variable changed to be float type instead of int, as it holds the current value of the plotted pattern, which is a float type.
Example that crashes without this correction: SmallDashPatterns.cpp
https://github.com/mgrudzinska/thorvg/tree/mgrudzinska/curLen_ex_crash
=> dash pattern: handling dash patterns < 1

src/lib/sw_engine/tvgSwShape.cpp
Preventing switching to the next dash pattern for a line with a length of zero.
It may happen, that the length of the final piece of the drawn dashed curve when converted to SW_COORD is 0. Nothing is plotted even though the dash pattern can be considered used (if the remaining length of the pattern to be drawn < 1). This results in an unexpected extended gap. 
Example file: UnexpectedGap.cpp
https://github.com/mgrudzinska/thorvg/tree/mgrudzinska/dash_gap_ex
=> sw_engine shape: adding a dash pattern switch condition

inc/thorvg.h, src/examples/Opacity.cpp, src/examples/meson.build, src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/gl_engine/tvgGlRenderer.h, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.h, src/lib/tvgCanvasImpl.h, src/lib/tvgPaint.cpp, src/lib/tvgPaint.h, src/lib/tvgPictureImpl.h, src/lib/tvgRender.h, src/lib/tvgSceneImpl.h, src/lib/tvgShapeImpl.h
We introduced separate opacity interface to adjust alpha value by paint.
This opacity will affect to whole paint image if paint is a group of paints.
Also, this opacity is to multipy with fill/stroke alpha values.
This means if the opacity is valid, the paint might deal with a composition step,
which is very expensive due to additional rendering step.
One tip is, if you want to toggle on/off for a certian paint,
you can set opacity to 255 or 0.
@API Additions:
Result Paint::opacity(uint8_t o) noexcept;
uint8_t Paint::opacity() const noexcept;
@Examples: examples/Opacity
@Issues: 94
=> common paint: introduce opacity() method.

src/loaders/svg/tvgSvgLoader.cpp
When copying tagName, if length of referenced string is longer
than general case, it is not used as tagName.
=> svg_loader SvgLoader: Prevent memory overflow for tagName

meson.build, meson_options.txt, test/meson.build, test/test_canvas.cpp, test/testsuite.cpp
In test directory, set up unit_test based on gtest
First, add a test for SwCanvas generate.
https://github.com/Samsung/thorvg/issues/45
[meson build]
sudo ninja -C {builddir} test
=> test Canvas: Set up unit test based on gtest.

src/lib/sw_engine/tvgSwShape.cpp
The algorithm erroneously treated some shapes (like isosceles trapezoids  and specifically arranged zero width parallelograms) as rectangles, witch causes the whole bbox to be filled - undesirable behavior.
- Issue Tickets (if any) : #77 
a) Stress.cpp from examples 
b) Svg.cpp for the image errorsStress.svg:
https://github.com/mgrudzinska/thorvg/tree/mgrudzinska/Stress_ex_error
errorsStress.svg:
Before (wrong):
After (correct):
=> sw_engine shape: improvement of the rectangle fast tracking algorithm

src/lib/tvgLoaderMgr.cpp, src/lib/tvgLoaderMgr.h, src/lib/tvgPictureImpl.h
Delegates extension string check and header(open) check
for file to LoaderMgr.
This makes it easy to add a loader afterwards.
https://github.com/Samsung/thorvg/issues/61
=> svg_loader LoaderMgr: Delegates file validation check to LoaderMgr.

inc/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp
- Descriptions:
Added opacity setter/getter to CAPI. They will be useful to simplify
code responsible for set visiblility of paint.
@API Additions:
Tvg_Result tvg_paint_set_opacity(Tvg_Paint* paint, uint8_t opacity)
Tvg_Result tvg_paint_get_opacity(Tvg_Paint* paint, uint8_t* opacity)
#94
=> common capi: Added opacity C bindings.

src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/gl_engine/tvgGlRenderer.h, src/lib/sw_engine/meson.build, src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.h, src/lib/sw_engine/tvgSwResMgr.cpp, src/lib/sw_engine/tvgSwShape.cpp, src/lib/tvgInitializer.cpp, src/lib/tvgTaskScheduler.cpp, src/lib/tvgTaskScheduler.h, src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoader.h
we introduced shared memory pool for avoiding reallocate memory
while it process the stroke outlines, It experimentally increase
the outline data if we use the allocated memory for multiples shape strokes,
we don't need to alloc/free memory during the process.
This shared outline memory is allocated for threads count
so that we don't interrupt memory access during the tasks.
- Issue Tickets (if any) : https://github.com/Samsung/thorvg/issues/75
=> sw_engine: performance optimization.

src/examples/Arc.cpp, src/examples/Blending.cpp, src/examples/Boundary.cpp, src/examples/ClipPath.cpp, src/examples/Duplicate.cpp, src/examples/FillRule.cpp, src/examples/LinearGradient.cpp, src/examples/MultiCanvas.cpp, src/examples/MultiShapes.cpp, src/examples/Opacity.cpp, src/examples/Path.cpp, src/examples/PathCopy.cpp, src/examples/RadialGradient.cpp, src/examples/Scene.cpp, src/examples/Shape.cpp, src/examples/Stroke.cpp, src/examples/StrokeLine.cpp, src/examples/Svg.cpp, src/examples/Svg2.cpp, src/examples/Update.cpp, src/lib/sw_engine/tvgSwResMgr.cpp
Move the Clear call to the end of drawing those scenarios doesn't need to retain paints resources.
We should show the examples as the best usage.
@Issues: 75
=> examples: revise example code.

src/bindings/capi/tvgCapi.cpp, src/lib/tvgFill.h, src/loaders/svg/tvgXmlParser.cpp
alloca.h does not exist on Windows
include string in the C api, neccesary to cas a char * to a std::string
=> fix compilation on Windows

src/lib/sw_engine/tvgSwMemPool.cpp
These memory pools requires very simple mechanism.
Remove stl vector but use direct memory for less binary size.(2127696 -> 2094094)
@Issues: 75
=> sw_engine mempool: ++optimization

src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/gl_engine/tvgGlRenderer.h, src/lib/tvgCanvas.cpp, src/lib/tvgRender.h
renamed internal methods from flush() to sync()
since flush() is reserved for caching flush.
=> common renderer: code refactoring.

inc/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp, src/examples/Capi.cpp
Scene CAPI allows to use scene functionaliy in C applications such as
set opacity to few shapes at one time or implement transparent layers.
@API Additions:
```c
Tvg_Paint* tvg_scene_new();
Tvg_Result tvg_scene_reserve(Tvg_Paint* scene, uint32_t size);
Tvg_Result tvg_scene_push(Tvg_Paint* scene, Tvg_Paint *paint);
```
Examples:
```c
Tvg_Paint *scene = tvg_scene_new();
Tvg_Paint *shape1 = tvg_shape_new();
tvg_shape_append_rect(shape1, 10, 10, 100, 100, 0, 0);
tvg_shape_set_fill_color(shape1, 255, 0, 0, 255);
Tvg_Paint *shape2 = tvg_shape_new();
tvg_shape_append_rect(shape2, 120, 10, 100, 100, 0, 0);
tvg_shape_set_fill_color(shape2, 255, 0, 0, 255);
tvg_scene_push(scene, shape1);
tvg_scene_push(scene, shape2);
tvg_paint_set_opacity(scene, 100);
tvg_canvas_push(canvas, scene);
```
=> capi examples: Added scene API C bindings.

inc/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp
Cpp implementaiton of library has free flag which was not used in
capi bindings.
@API changes
from: tvg_canvas_clear(Tvg_Canvas *canvas);
to: tvg_canvas_clear(Tvg_Canvas *canvas, bool free);
=> capi: Added free flag to clear API.

src/examples/MultiCanvas.cpp, src/examples/Svg.cpp
in the last commit, it added a raw image file in the images folder.
It breaks Multicanvas, Svg which try to load all kinds of files in it.
We don't need to load all files by figuring out file extension name.
=> examples: ignore loading raw image file.

inc/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp
Description:
Added capi binding for fill rule setter and getter.
@API changes:
```c
enum Tvg_Fill_Rule {
TVG_FILL_RULE_WINDING = 0,
TVG_FILL_RULE_EVEN_ODD = 1,
}
Tvg_Result     tvg_shape_set_fill_rule(Tvg_Paint* paint, Tvg_Fill_Rule rule)
Tvg_Fill_Rule  tvg_shape_get_fill_rule(Tvg_Paint* paint, Tvg_Fill_Rule* rule)
```
=> capi: Added fill rule API.

src/lib/sw_engine/tvgSwRaster.cpp
If transform is null, identify matrix is used.
https://github.com/Samsung/thorvg/issues/150
=> sw_engine Raster: Add null check for transform

src/lib/tvgSceneImpl.h, test/meson.build, test/test_paint.cpp
Fix typo. and Change return to continue.
Even if the child's boundary calculation is wrong,
other child's boundary should be calculated.
./test/test_paint.c : SceneBounds
=> common Scene: Fix validation check for child's bounds

inc/thorvg.h, inc/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp, src/lib/tvgScene.cpp
Scene::clear() API allows users to remove shapes on their own, without
a crash in paint->dispose() or tvg_paint_del() methods. This case is
needed especially when thorvg is used to draw frames, when in one frame
we have scene with shape, and in next frames (future time stamps) user
deletes shapes
@API additions
```cpp
Result Scene::clear();
```
```c
Tvg_Result tvg_scene_clear(Tvg_Paint *scene);
```
Example:
```c
Tvg_Paint *scene = tvg_scene_new();
Tvg_Paint *shape = tvg_shape_new();
tvg_scene_push(scene, shape);
tvg_scene_clear();
//Now we can safelly free resources manually
tvg_paint_del(scene);
//Without tvg_scene_clear() memory allocatad for shape was double released
tvg_paint_del(shape);
```
=> common capi: Added scene clear API

src/examples/Opacity.cpp, src/examples/Stress.cpp, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.h, src/lib/tvgSceneImpl.h
This implementation supports shape + stroke opacity composition.
Currently, tvg shape provides individual alpha values for filling & stroking
These alpha values are working individually, meaning that if stroking is half translucent,
user can see that translucent stroking is crossed the shape outlines.
Sometimes this result can be expected but user also expects the shape filling is invisible
behind of translucent stroking.
For this reason, Paint provides an additional api opacity()
that applies opacity value to whole paint attributes.
This is a little expensive job, please consider if you can possibly avoid that usage.
See Opacity example.
@Issues: 94
=> sw_engine raster: support opacity composition.

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgXmlParser.cpp
Existing parser functions always return true.
Parser function's return value was not being properly used.
So, add a return to check whether it is parsed or not.
https://github.com/Samsung/thorvg/issues/152
=> svg_loader Loader,XmlParser: String that has not been parsed returns false

src/loaders/svg/tvgSvgSceneBuilder.cpp
If opacity value is set in node,
opacity() API is used without composing alpha color.
https://github.com/Samsung/thorvg/issues/94
=> svg_loader SceneBuilder: Use opacity() without using alpha color

src/lib/sw_engine/tvgSwRaster.cpp, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.h
Move the prepare stage of shape & stroking composition stage to a separate function
this returns SwImage to use in composite stage.
Also clear partial region buffer since we know composition area.
=> sw_engine renderer: refactoring code & optimize composition.

inc/thorvg.h, src/examples/Svg.cpp, src/lib/tvgLoader.h, src/lib/tvgPicture.cpp, src/lib/tvgPictureImpl.h, src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgSceneBuilder.cpp, src/loaders/svg/tvgSvgSceneBuilder.h
Add picture's resize API. The file loaded by picture may or may not have a size.
Therefore, if there is a size, it transforms the size of the Vector object of the picture.
When resizing, if preserveAspect is true, the aspect ratio is kept.
If false, the aspect ratio is not kept.
[Added APIs]
Result size(uint32_t w, uint32_t h) noexcept;
Result size(uint32_t* w, uint32_t* h) const noexcept;
https://github.com/Samsung/thorvg/issues/148
src/example/Svg
=> common Picture : Introduce Picture's size setter, getter APIs

src/examples/Opacity.cpp, src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/gl_engine/tvgGlRenderer.h, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.h, src/lib/tvgRender.h, src/lib/tvgSceneImpl.h, src/lib/tvgShapeImpl.h
this is an additional enhancement of af8c278c5e2a47c21f44440cdb0a7aaf6f6d3baa
Now scene opacity composition is supported.
Also, this implementaion fixes an incorrect scene bounding box computation.
Plus, adding stroking feathering to shape bounding box size.
=> sw_engine renderer: support scene opacity composition

inc/thorvg.h, src/lib/tvgLoader.h, src/lib/tvgPicture.cpp, src/lib/tvgPictureImpl.h, src/loaders/svg/tvgSvgLoader.cpp
In perspective of Picture, Size of Picture should be view size
of the svg. Not content size.
Even viewbox is mandatory used but not content size.
Thus we can't use it.
=> picture svg_loader: use viewbox size as default image size.

src/wasm/thorvgwasm.cpp
Use Picture::size() method instead of scale()
Picture newly supports size() method to resize image.
It's more convenient for users in its usage.
=> wasm: code refactoring.

src/lib/tvgArray.h, src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h, src/loaders/svg/tvgSvgPath.cpp, src/loaders/svg/tvgSvgSceneBuilder.cpp
This Array is promoted from SvgVector to use it widely in tvg.
It's similar with std::vector, we can use it instead of it.
Also, svg_loader replaced with it subsequently.
=> common array: Introduce Array function to common.

src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/gl_engine/tvgGlRenderer.h, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.h, src/lib/sw_engine/tvgSwRle.cpp, src/lib/tvgArray.h, src/lib/tvgCanvasImpl.h, src/lib/tvgPaint.h, src/lib/tvgPictureImpl.h, src/lib/tvgRender.h, src/lib/tvgScene.cpp, src/lib/tvgSceneImpl.h, src/lib/tvgShapeImpl.h, src/loaders/svg/tvgSvgLoader.cpp
Apply tvg Array instead of std::vector
Fix Composition Target memory leak
binary comparison:
[libthorvg.so] 1785376 >> 1607416
[text] 121255 >> 118277
[data] 7792 >> 7736
[dec] 129119 >> 126085
=> common sw_engine: code refactoring & stabilizing.

src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.h
Use cache mechanism for composition data so that we don't reallocate
composition memory several times in one frame rendering.
@Issues: 168
=> sw_engine renderer: optimize composition data usage.

src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/gl_engine/tvgGlRenderer.h, src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwImage.cpp, src/lib/sw_engine/tvgSwRaster.cpp, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.h, src/lib/sw_engine/tvgSwShape.cpp, src/lib/tvgPaint.h, src/lib/tvgPictureImpl.h, src/lib/tvgRender.h, src/lib/tvgSceneImpl.h, src/lib/tvgShapeImpl.h
Introduce RendererMethod::renderRegion() to return acutal drawing region info.
That is used by scene composition to composite actual partial drawing region
for better performance.
@Issues: 173
=> common sw_engine: apply partial composition.

meson.build, meson_options.txt, src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgXmlParser.cpp
* Using printf is temporary. We are planning a proper way to print the log.
When parsing a Svg file, Loader print unsupported elements and attributes.
https://github.com/Samsung/thorvg/issues/152
[Enable log]
meson_option -> add 'debug' value in 'log' option
=> svg_loader XmlParser: Print unsupported elements, attribute with log option

src/lib/sw_engine/tvgSwImage.cpp, src/loaders/svg/tvgXmlParser.cpp, src/wasm/thorvgwasm.cpp, wasm_build.sh
The wasm is using the ThorVG output starting whith "SVG:" to show
unsupported element and attribute of svg file.
This patch updates wasm_build.sh to make ThorVG prints log,
and removes build errors.
- Following commit needs to include 'algorithm'
1ed6113 common sw_engine: code refactoring & stabilizing.
- Following commit needs to include 'string'
5481633 svg_loader XmlParser: Print unsupported elements, ...
=> wasm: work with log option

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h, src/loaders/svg/tvgXmlParser.cpp
Opacity is 0
both Fill.Opacity and Stroke Opacity are 0
point is 0 in Path
declared display="none"
width or height of bounds becomes 0
https://github.com/Samsung/thorvg/issues/153
=> svg_loader SvgLoader: Print inefficient elements

src/lib/tvgShape.cpp
The _appendArc function allows to draw angles only in a clockwise direction.
The introduced improvement allows to change this direction by giving the 'sweep' argument
with a negative value.
- Tests or Samples:
https://github.com/mgrudzinska/thorvg/blob/mgrudzinska/arc_example/src/examples/Arc_fix_example.cpp
- Screen Shots:
results from the above example
current version of tvg:
with this commit:
=> sw_engine shape: expand the algorithm to draw arcs with negative angles

src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/gl_engine/tvgGlRenderer.h, src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwFill.cpp, src/lib/sw_engine/tvgSwRaster.cpp, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.h, src/lib/tvgPaint.h, src/lib/tvgRender.h, src/lib/tvgSceneImpl.h
Renamed internal interfaces.
We need both blender & compositor interfaces.
Renamed SwCompositor -> SwBlender which is for pixel joining methods.
Added (SwCompositor, Compositor) which is designed for compositing images.
=> common sw_engine: code refactoring

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwFill.cpp, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwShape.cpp, src/lib/tvgRender.h
previously, opacity value is ignored to gradient fill.
This patch implements that case.
=> sw_engine: apply opacity to graident fill case.

src/lib/tvgCanvasImpl.h, src/lib/tvgPaint.h, src/lib/tvgPictureImpl.h, src/lib/tvgSceneImpl.h, src/lib/tvgShapeImpl.h
remove the opacity argument in the render method.
Considered again, this opacity value is not commonly used yet.
we can introduce it when it's necessary.
=> common paint: code refactoring.

src/loaders/svg/tvgSvgLoader.cpp
When OOM of SvgLinear/RadialGradient occurs,
the allocated id, ref, transform may become a memory leak.
Therefore, add free memory.
=> svg_loader SvgLoader: Prevent memory leak

src/lib/sw_engine/tvgSwRenderer.cpp
For solid shapes without strokes, the value of 'a' was incorrectly assigned,
which resulted in unnecessary calls to raster functions.
The variable holding the value 'a' is now reset before being used again.
=> sw_engine renderer: rendering optimization of shapes without strokes

src/lib/tvgRender.h
All flag should have all bits set to 1. If flag = 64 rendering task don't update anything, because all checked bits in flag are not set.
=> renderer: Fixed RenderUpdate::All flag fields.

src/lib/sw_engine/tvgSwRaster.cpp
Shifting the 32-bit number by 24 bits leaves only 8 bits,
so there is no need to mask them with 0xFF.
=> sw_engine raster: removing unnecessary logical 'and' operation

src/examples/ClipPath.cpp
Added example with non-overlaping clip and shape.
Modified example to show the issue solved in https://github.com/Samsung/thorvg/pull/237
=> example ClipPath: update

src/lib/tvgRender.cpp
The rotation part of the transformation matrix can be assigned,
it does not have to be multiplied by the identity matrix.
The values of e13 and e23 of the transformation matrix represents the translation,
so they don't need to be taken into account in the rotation part.
=> common render: removed unnecessary assignments in update() fun

.github/workflows/actions.yml
github action started updating to ubuntu20.04 for ubuntu-latest.
So fix Ubuntu version 18.04 as we are not ready enough to test for 20.04 yet.
=> common: Fix ubuntu version in build test

src/lib/sw_engine/tvgSwRle.cpp
For clip that did not overlap with the plotted source, the whole
source was plotted - the size of the rle data was not updated.
- Tests or Samples:
Modified ClipPath -  https://github.com/Samsung/thorvg/pull/238
- Screen Shots from modified ClipPath:
current:
expected:
=> sw_engine rle: fixing clipping with non overlaping figures

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h, src/loaders/svg/tvgSvgSceneBuilder.cpp
Support case when style is defined as <mask> attribute.
[Example SVG file]
```
<svg version="1.1" id="Layer_1" viewBox="0 0 64 64" enable-background="new 0 0 64 64" xml:space="preserve"
xmlns="http://www.w3.org/2000/svg">
<defs>
<mask id="myMask">
<circle id="maskID" cx="40" cy="40" r="10" fill="white" fill-opacity="1" />
</mask>
</defs>
<rect x="0" y="0" width="64" height="64" style="fill: skyblue; mask: url(#myMask);"/>
</svg>
```
=> SvgLoader: Mask style implementation

src/lib/tvgSceneImpl.h
If a scene has another scene as a child and
the number of children is 1, the composition of the child does not work.
Therefore, fix that composition works as long as the number of children is not 0.
```cpp
auto rootScene = tvg::Scene::gen();
rootScene->opacity(255);
//Create a Scene
auto childScene = tvg::Scene::gen();
childScene->opacity(175);              //Apply opacity to scene (0 - 255)
childScene->reserve(2);
//Prepare Circle
shape1->appendCircle(400, 400, 250, 250);
shape1->fill(255, 255, 0, 255);
childScene->push(move(shape1));
rootScene->push(move(childScene));
canvas->push(move(rootScene));
```
=> common Scene: Fix translucent composition condition

src/lib/sw_engine/tvgSwMath.cpp
Unnecessary rounding during matrix transformation has been removed.
The problem occured when scaling a shape with a dashed stroke.
https://github.com/mgrudzinska/thorvg/tree/mgrudzinska/Scaled_dashed_stroke_example
ScaledShape.cpp
before changes:
after changes:
=> sw_engine math: fixing matrix transformation

src/lib/sw_engine/tvgSwRaster.cpp
In case of the image rasterization with an inverse mask the opacity
was omitted and the alpha value instead of the inverse alpha value was used.
The result of the InvMasking:
expected (see comment below):
current (wrong):
=> sw_engine raster: fixing rasterization of an image with InvMask

src/lib/sw_engine/tvgSwCommon.h
Description:
Crash was observed in examples when composite object was used.
It was caused because __m256i object was used on non aligned
memory to 32bit. Algorithm in this function was changed to use
unaligned __m256i_u object. Code was also simplified.
- Issue Tickets: #247 
- Tests or Samples: To verify check if crash occurs on examples: ClipPath, Opacity, Capi or Masking.
=> sw common: Fixed crash in rasterRGBA32

src/lib/tvgCanvasImpl.h, src/lib/tvgGlCanvas.cpp, src/lib/tvgSwCanvas.cpp
When canvas target size is changed, it need to update all retained paints again
so that they cannot redraw onto out of buffer boundary.
=> canvas: fix crash issue.

src/lib/sw_engine/tvgSwFill.cpp
There transformation logic was not identical between shape & gradient
gradient transform was applied into center of gradient world,
while shape wasn't. So... we correct gradient transform metric to shape like.
@Issues: 255
=> sw_engine fill: fix wrong gradient transformation.

src/lib/tvgCanvasImpl.h
Bitwise logical operators do not perform short-circuiting.
=> canvas: replacement of the bitwise OR operator with the logical one

src/loaders/svg/tvgSvgSceneBuilder.cpp
The value was loadeed but not set to the shape.
- Issue Tickets (if any) : #257
=> svgloader: fillRule value passed to the shape

src/lib/sw_engine/tvgSwFill.cpp
Fixed in the fillFetchLinear() function.
=> sw_engine fill: fixing the infinite loop condition

src/loaders/svg/tvgSvgLoader.cpp
When the viewBox is not given its dimensions should be determined
by the height and width parameters
example:
```
<svg height="80" width="80">
<path d="M 10 10 h 60 v 60 h -60 z" fill="none" stroke="#FF0000"stroke-width="6"/>
</svg>
```
current result:
after changes:
=> svgloader: fixing SVG image display when viewBox size is not given

inc/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp
Api prototype is completely wrong, now it's corrected.
=> capi: fix incorrect composite api.

src/loaders/svg/tvgSvgSceneBuilder.cpp
Gradient stop points were incorrectly transformed when building
the scene in the SVG loader.
example:
```
<svg viewBox="0 0 200 200" height="200" width="200">
<defs>
<linearGradient id="grad" gradientTransform="matrix(0 1 -1 0 0 0)" x1="0" y1="0" x2="1" y2="0">
<stop offset="0" stop-color="#FF0000"/>
<stop offset="1" stop-color="#0000FF"/>
</defs>
<path d="M 10 10 h 180 v 180 h -180 z" fill="url(#grad)"/>
</svg>
```
current result:
after changes:
=> svgloader: fixing linear gradient transformation

src/loaders/svg/tvgSvgLoader.cpp
When getting a linked stop list, if there is no existing stop list
in current gradient, it is copied.
=> svg_loader SvgLoader: Fix copy conditions for stop of gradient

src/loaders/svg/tvgSvgPath.cpp
This condition(optimization) is not a step suggested by arc implementation.
https://www.w3.org/TR/SVG11/implnote.html#ArcCorrectionOutOfRangeRadii (Step2)
This code is useful if the arc is too small to represent.
However, scaling often occurs in vectors, which can create unnecessary problems.
example path
```html
<path d="M32.41,20.49a.41.41,0,1,1-.41-.42A.41.41,0,0,1,32.41,20.49Z" transform="translate(0)" fill="#020202"/>
```
=> svg_loader SvgPath: Remove unnecessary optimization code for small arc draw

src/lib/sw_engine/tvgSwImage.cpp, src/lib/sw_engine/tvgSwShape.cpp
In the case when the height or width of the bounding box is 0
it is not necessary to calculate Rle.
=> sw_engine shape/image: substituting logical 'and' with 'or'

src/lib/sw_engine/tvgSwRaster.cpp
The alpha value calculation pulled out outside the inner loop
to reduce the number of unnecessary operations.
Added local variables to reduce the number of costly
multiplications performed in a loop.
=> sw_engine raster: functions optimization in the image block

src/loaders/svg/tvgSvgSceneBuilder.cpp
The 'viewBox' element given in the svg file determines
the coordinates of the plotted area.
- Tests or Samples:
<svg viewBox="0 0 200 200" height="200" width="200">
<rect x="0" y="0" width="150" height="150" fill="#FF0000"/>
<circle cx="150" cy="150" r="100" fill="#0000FF"/>
</svg>
- Screen Shots:
current:
expected:
=> svg_loader: limiting the ploted area of svg to viewBox

src/lib/tvgShape.cpp, src/lib/tvgShapeImpl.h
reset Path is useful rather than reset all properties.
=> common shape: revise Shape::reset() api.

src/lib/sw_engine/tvgSwRle.cpp
When updating rle for clipped area, realloc size should be larger than spans size.
so this patch prevents the problem while realloc.
https://github.com/Samsung/thorvg/issues/291
Test ./Stress.cpp
=> sw_engine rleClipPath: Modify clippath spans creation size.

src/lib/sw_engine/tvgSwRle.cpp
We don't need to copy the rle data unecessarily,
we can just replace the completed clip rle.
=> sw_engine: optimize rle clipping

src/lib/tvgShape.cpp
Description:
Fixed appendArc API for -90 angles. In that case it was drawn in wrong
direction.
@Examples
```cpp
float x = 40.0, y = 40.0;
//OK
shape1->appendArc(x + 50, y, 25, 0, -91, false);
//NOK
shape1->appendArc(x + 100, y, 25, 0, -90, false);
//OK
shape1->appendArc(x + 150, y, 25, 0, -89, false);
```
=> common shape: Fixed appendArc for negative values.

src/lib/tvgPaint.h
Only ClipPath composite method should cause clips subtraction.
- Tests or Samples:
modified ClipPath.cpp:
```
scene->reserve(2);
auto star1 = tvg::Shape::gen();
tvgDrawStar(star1.get());
star1->fill(255, 255, 0, 255);
star1->stroke(255 ,0, 0, 255);
star1->stroke(10);
//Move Star1
star1->translate(-10, -10);
auto clipStar = tvg::Shape::gen();
clipStar->appendCircle(200, 230, 110, 110);
clipStar->fill(255, 255, 255, 255); // clip object must have alpha.
clipStar->translate(10, 10);
star1->composite(move(clipStar), tvg::CompositeMethod::AlphaMask);    //CHANGED
auto star2 = tvg::Shape::gen();
tvgDrawStar(star2.get());
star2->fill(0, 255, 255, 255);
star2->stroke(0 ,255, 0, 255);
star2->stroke(10);
star2->opacity(100);
//Move Star2
star2->translate(10, 40); …
```
=> paint: clip was substracted from the array for any composite method

src/examples/Duplicate.cpp, src/examples/PixelImage.cpp, src/lib/tvgLoaderMgr.cpp, src/lib/tvgLoaderMgr.h, src/lib/tvgPictureImpl.h
A duplicated picture needs to access internal picture loader data
to get its properties while rasterizing.
But it missed the loader since it's not copied from origin.
Thus, we fix this by sharing the internal loader among the duplications and origin.
@Examples: Duplicate
=> common picture: fix crash at picture duplication.

src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/tvgInitializer.cpp
Introduced the reference counting for the backend engines so that
tvg prevents unpaired engine initialization/termination calls by user mistake.
@Issues: 296
=> initializer: add reference counting for the engines initialization.

src/loaders/svg/tvgSvgSceneBuilder.cpp
The AlphaMask composition case was omitted in the _sceneBuilderHelper().
- Tests or Samples :
```
<svg width="800" height="500" viewBox="0 0 800 500" >
<defs>
<mask id="Mask">
<rect x="20" y="250" width="400" height="125" fill="#FFFFFF"  />
</mask>
<rect id="Rect" x="0" y="250" width="800" height="250" />
</defs>
<rect x="0" y="0" width="800" height="500" fill="#00FFFF" />
<rect x="0" y="100" width="800" height="300" fill="#FF0000" />
<use xlink:href="#Rect" fill="#00FF00" mask="url(#Mask)" />
</svg>
```
- Screen Shots:
current:
expected:
=> svg_loader: applying AlphaMask during scene building

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgXmlParser.cpp, src/loaders/svg/tvgXmlParser.h
SVG files created using 'sketch' may contain xml entities,
which are not understandable by the svg loader.
For now only '&quot;' is ommitted.
- Tests or Samples :
<svg viewBox="0 0 500 300" width="500" height="300">
<defs>
<rect id="mask_path" x="50" y="100" width="400" height="100" />
</defs>
<rect fill="#FF0000" x="0" y="0" width="500" height="300" />
<mask id="mask" fill="white">
<use xlink:href="#mask_path" />
</mask>
<circle fill="#0000FF" mask="url(&quot;#mask&quot;)" cx="250" cy="150" r="200" />
</svg>
- Screen Shots:
current:
expected:
=> svg_loader: ommiting xml entities in the svg file

src/bindings/capi/tvgCapi.cpp
For uniformity of the functions naming the function name
tvg_shape_stroke_get_gradient changed to tvg_shape_get_stroke_gradient.
=> capi: changing function name

meson.build, meson_options.txt, src/loaders/meson.build, src/loaders/png/meson.build, src/meson.build
We hate spagettie code, not even build script.
this revise it to keep the build script consistency.
Enable png loader by this:
$meson . build -Dexamples=true -Dloaders="svg, png"
=> meson: revise png loader meson script.

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwRaster.cpp
previously alpha multiplying operation doesn't have perfect precision,
could loss 1 pixel since it divides 255 values by 256.
This improved operation comply with both precision & performance.
=> sw_engine raster: ++ precise alpha multiplying

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwFill.cpp, src/lib/sw_engine/tvgSwRaster.cpp
The gradient rastering functions with composition did not take
antialiasing into account. The missing part has been added.
contains #320, #318 and #316
before:
after:
=> sw_engine raster: adding antialiasing to gradient rastering functions

src/loaders/svg/tvgSvgSceneBuilder.cpp
tvg engine expects the valid clippath with valid colors,
loaders set any colors values to enable it.
this fixes invalid clippath behavior.
=> loaders svg: fix invalid clip path result.

src/loaders/svg/tvgSvgSceneBuilder.cpp
not only clippath but alpha compositions might also have any valid color.
Set it default and let it override values while appending shapes if it's necessary.
=> loaders svg: set default color for composition paint.

src/lib/sw_engine/tvgSwRaster.cpp
Instead of checking the stroke's fill, the shape's fill was checked.
As a result the improper rastering function was called (or none).
issue #327
=> sw_engine: fixing stroke gradient

src/loaders/svg/tvgSvgLoader.cpp
Stop the internel loop quick as possible, and state must be reset.
=> loaders svg: fix a wrongly handles the corner case.

src/loaders/svg/tvgSvgLoader.cpp
In transform matrix parsing, null is returned if any of the matrices are invalid.
=> loader SvgLoader: return null if transform attribute invalid

src/examples/Stress.cpp
The picture->size() function does not work for raw/png pictures.
As a consequence enabling both, the svg and png file loaders,
resulted in the unintended behavior of the example.
=> examples: ignoring pictures other than svgs in Stress.cpp

src/lib/sw_engine/tvgSwRaster.cpp
The crash was observed for empty shapes.
=> sw_engine: adding a check before stroke fill dereference

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgSceneBuilder.cpp
1.
Modify that attribute information used for use type
looks like it was used for g type.
2.
Fix clippath node looking like setting "none"
(clippath's display = false is intentional)
=> loader SvgLoader: Fix wrong debug log

inc/thorvg.h
- Description : 
Write documentation for some of the APIs that have already been cleared up.
https://github.com/Samsung/thorvg/issues/27
=> doc common: Draft documentation for C++ header APIs

inc/thorvg.h
=> doc common: Fix typo and missing parameter

README.md
The badge provided by travis-ci is no longer used.
Use the badge provided by github action.
=> doc README: Update build status badge

src/lib/tvgPaint.cpp
A possible error is due to erroneous arguments, so
InvalidArgument is return instead of InsufficientCondition
=> common paint: changed result in composite API

src/lib/tvgPaint.cpp
The buffer to which the mask is rastered is only partially cleared.
If the object to which the mask is applied overlaps an area where
another mask was used, an erroneous image is generated. The buffer
clearing area has been increased to the size of the object to which
the mask is applied.
before:
after:
=> sw_engine: fixing overlapping masks

meson_options.txt, src/examples/meson.build
capi is not mandatory option in v0.1.
we can manually toggle it on when it's necessary.
=> infra: disable capi in default.

src/lib/sw_engine/tvgSwRenderer.cpp
This commit fixes crash when update target surface is not created yet.
- Tests
```c
void testCapi()
{
Tvg_Paint* scene1 = tvg_scene_new();
canvas = tvg_swcanvas_create();
Tvg_Paint* scene2 = tvg_scene_new();
tvg_canvas_push(canvas, scene2);
Tvg_Paint* shape1 = tvg_shape_new();
tvg_scene_push(scene1, shape1);
tvg_paint_set_opacity(shape1, 255);
Tvg_Paint* shape2 = tvg_shape_new();
tvg_canvas_push(canvas, shape2);
tvg_swcanvas_set_target(canvas, buffer, WIDTH, WIDTH, HEIGHT, TVG_COLORSPACE_ARGB8888);
tvg_shape_append_circle(shape1, 50, 50, 100, 100);
tvg_shape_set_stroke_width(shape1, 10);
tvg_shape_set_stroke_color(shape1, 255, 0, 0, 0);
tvg_canvas_update_paint(canvas, shape1);
tvg_canvas_draw(canvas);
tvg_canvas_sync(canvas);
}
```
=> sw_engine: Added sanity checks.

src/loaders/svg/tvgSvgLoader.cpp
Add memory release for style->comp.url, which is the leaking memory.
[Valgrind Test Result]
```
==21595== 32 bytes in 1 blocks are definitely lost in loss record 29 of 152
==21595==    at 0x4C3217F: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==21595==    by 0x5C248C6: _idFromUrl(char const*) (tvgSvgLoader.cpp:272)
==21595==    by 0x5C24DE1: _handleClipPathAttr(SvgLoaderData*, SvgNode*, char const*) (tvgSvgLoader.cpp:860)
==21595==    by 0x5C260CC: _attrParseGNode(void*, char const*, char const*) (tvgSvgLoader.cpp:953)
==21595==    by 0x5C2ABA9: simpleXmlParseAttributes(char const*, unsigned int, bool (*)(void*, char const*, char const*), void const*) (tvgXmlParser.cpp:272)
==21595==    by 0x5C26F6E: …
```
=> loader SvgLoader: Fix memory leak

inc/thorvg.h, src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwImage.cpp, src/lib/sw_engine/tvgSwMemPool.cpp, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.h, src/lib/sw_engine/tvgSwShape.cpp, src/lib/sw_engine/tvgSwStroke.cpp, src/lib/tvgSwCanvas.cpp
We have encountered that multi-threading usage that user creates,
multiple canvases owned by multiple user threads.
Current sw_engine memory pool has been considered only for multi-threads,
spawned by tvg task scheduler.
In this case it's safe but when user threads introduced, it can occur race-condition.
Thus, Here is a renewal policy that non-threading tvg(initialized threads with zero),
takes care of multiple user threads, each of canvases should have each own memory pool
to guarantee mutual-exclusion.
Instead, when tvg threads of task scheduler are enabled, we don't gurantee user threads safety.
All in all, if user calls multiple threads, they should initalize tvg thread zero.
=> sw_engine: fix invalid data sharing at multi-threading.

inc/thorvg.h
- the file description is added
- @defgroup requires 2 args - label and a name
- I changed '@return Result::Success when succeed' to '@return Result::Success' everywhere, where this is the only result that can be returned. I find it confusing as it was, since the question arises "and what if it does not succeed? "
- using @c before Result::Success doesn't look good - it is already marked as link, so do we have to change its font?
before:
after:
=> doc: linguistic changes in C++ API docs

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwFill.cpp
Removing the 'inv2a' variable reduced the number of multiplications.
=> sw_engine: removing unnecessary variable from SwRadial struct

src/lib/sw_engine/tvgSwRaster.cpp
The cases with gradient shapes with composition are handled
in the same function as gradint shapes with opacity < 255.
Parts of the code from _rasterOpaque... grad functions moved to
_rasterTranslucent... grad functions.
before:
after:
This pr contains #384 
Please note, that the only change is that I moved some part of the code from one function into another.
=> sw_engine: gradient shapes with opacity < 255 rastered properly

src/lib/tvgInitializer.cpp
Calling init repeatedly doesn't increment count.
This leads to unwanted termination due to mismatch of the pair.
=> common Initializer: Fix init count

inc/thorvg.h, inc/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp, src/lib/tvgCanvasImpl.h, src/lib/tvgPictureImpl.h, src/lib/tvgScene.cpp, src/lib/tvgSceneImpl.h
Paints must clear canvas engine data if they were dismissed from the canvas,
1. Canvas::clear(free = false) must retain all the paints from the paints hierarchy
so that user keeps the all dangled paints lifecycle.
In this scenario, it could leak the engine data of paints, this patch fixes it.
2. Previously, t just keeps the immediate paints lives of canvas, but not them of children of scene nor picture.
This patch changes a policy which was not considered seriously,
Now it keeps the all paints lives through the tree-hieararchy.
3. Also changed the Scene::clear() behavior identical to Canvas::clear() for consistency.
@API Modification:
From: Result Scene::clear() noexcept;
To: Result Scene::clear(bool free = true) noexcept;
=> common: fix a potential memory leak after clear()

src/lib/sw_engine/tvgSwCommon.h
Calculations accuracy in ALPHA_BLEND function has been
improved. Until now blending resulted in a slight hue change
(all color channels affected).
=> sw_engine common: improving the alpha blending algorithm

src/bindings/capi/thorvg_capi.h
Included <stdint.h> into thorvg_capi.h to eliminate "uint8_t/uint32_t has not been declared"
=> capi: include <stdint.h> into thorvg_capi.h

src/lib/tvgFill.cpp
Memcpy is not allowed on nullptr. If colorStops is invalid colors are cleared.
=> common gradient: Fix possible crash in color setter

src/loaders/svg/tvgSvgLoader.cpp
The 'loader->svgParse->global' variable was uninitialized when no viewBox attribute
was set. If gradient was applied, the division by zero occured and no gradient was drawn.
before:
after:
=> svg_loader: initializing uninitialized variables

src/loaders/svg/tvgSvgSceneBuilder.cpp
Calculation of objectBoundingBox case in gradient is incorrect code.
This causes the x,y coordinates of the gradient to be calculated incorrectly.
So remove it.
=> svg_loader SceneBuilder: Remove incorrect calculation for gradient

src/lib/sw_engine/tvgSwRenderer.cpp
When canvas width was smaller than its stride and a composition is used,
the plots were drawn incorrectly. This is fixed by setting the image width
(image from a compositor) to be equal to the surface stride, instead of its width.
The image data are now allocated accordingly the fixed image width.
before:
after:
=> sw_engine: fixing the composition for canvas width != canvas stride

src/lib/sw_engine/tvgSwRenderer.cpp
In a case width > stride segf occured. Such a case should be treated
as an invalid arg.
=> sw_engine: added check whether surface width <= surface stride

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgSceneBuilder.cpp
The loader was ready to handle the gradient stroke, but there was no API to support
it when the loader was introduced. We've had this API for a while already, so
its call has been added.
code:
```
<svg viewBox="0 0 300 300">
<defs>
<radialGradient id="phpg" gradientUnits="userSpaceOnUse" cx="250" cy="0" r="300">
<stop offset="0.3" stop-color="#CCF"/>
<stop offset="0.6" stop-color="#334"/>
</defs>
<ellipse stroke="url(#phpg)" stroke-width="18" fill="#000" cx="150" cy="80" rx="143" ry="73"/>
</svg>
```
before:
after:
=> svg_loader: support stroke gradient

src/examples/CustomTransform.cpp, src/examples/GradientStroke.cpp, src/examples/GradientTransform.cpp, src/examples/SceneTransform.cpp, src/examples/Stacking.cpp, src/examples/Transform.cpp
remove the show-cases that accessing the raw memory from the unique_ptr
we don't like to use those cases without any inevitable excuse.
=> examples: revise examples

src/loaders/tvg/tvgTvgLoader.cpp
Fixed missed 'this->' in `tvgTvgLoader.cpp`
=> tvg_loader: Fixed missing 'this->' keyword

src/lib/tvgLoaderMgr.h
`FileType` order was changed in `tvgLoaderMgr.h` to move Tvg at the beginning.
When raw data loading [`LoaderMgr::loader(data, size)`], loaders are tried
one by one (in order according to the FileType enum) until the correct loader
is found.
When using EFL and load edj, multiple loader(data, size) with tvg data may be
called. This change should improve performance in that case.
Please merge after https://github.com/Samsung/thorvg/pull/437
=> loader_mgr: FileTypes order changed

src/loaders/svg/tvgSvgLoader.cpp
For shapes with a grad fill and a grad stroke only the fill was drawn.
After this fix both can have a valid gradient.
svg example:
```
<svg viewBox="0 0 100 100">
<defs>
<linearGradient id="gradientFill" x1="0" y1="0" x2="0" y2="1">
<stop offset="0%" stop-color="#f00" />
<stop offset="100%" stop-color="#00f" />
<linearGradient id="gradientStroke" x1="0" y1="0" x2="1" y2="1">
<stop offset="0%" stop-color="#0f0" />
<stop offset="100%" stop-color="#f0f" />
</defs>
<circle cx="50" cy="50" r="40" fill="url(#gradientFill)" stroke-width="30"  stroke="url(#gradientStroke)"/>
</svg>
```
before:
after:
=> svg_loader: gradient update takes into account a stroke and a fill

src/loaders/svg/tvgSvgLoader.cpp
The stroke-dasharray value equal to "none" was causing a segfault
during a conversion to float. Fixed now.
sample code:
```
<svg viewBox="0 0 30 10" xmlns="http://www.w3.org/2000/svg">
<line x1="0" y1="3" x2="30" y2="3" stroke="black"
stroke-dasharray="none" />
</svg>
```
=> svg_loader: adding check if stroke-dasharray attribute != none

src/loaders/svg/tvgSvgLoader.cpp
For colors given in a style attribute in the format "rgb(rrr, ggg, bbb)"
a parsing was incorect. Now fixed.
code:
```
<svg height="300" width="300">
<path d="M 0 0 h 200 v 200 z" style="fill: rgb(255, 155, 55);"/>
</svg>
```
before:
after:
=> svg_loader: fixing color parsing

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgSceneBuilder.cpp
For now the gradient radius is scales like x-axis - it has to be changed
after issue #37 will be resolved.
issue #40 
code:
```
<svg viewBox="0 0 420 200">
<radialGradient id="gradient1" gradientUnits="userSpaceOnUse"
cx="100" cy="100" r="100" fx="100" fy="100"
gradientTransform="scale(2) translate(-50, 0)">
<stop offset="0%" stop-color="darkblue" />
<stop offset="50%" stop-color="skyblue" />
<stop offset="100%" stop-color="darkblue" />
<rect x="0" y="0" width="200" height="200" fill="url(#gradient1)" />
</svg>
```
before:
after:
=> svg_loader: radial gradient transformation support

test/testScene.cpp
Split some tests into SECTIONs based on their type.
This improves the readability of TC.
And developer can run test in SECTION unit.
ex)
./build/test/tvgUnitTests "Pushing Paints Into Scene" -c "Pushing Null Pointer"
=> test Scene: Separate tests into SECTION()

inc/thorvg.h, src/bindings/capi/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp, src/lib/tvgLoader.h, src/lib/tvgLoaderMgr.cpp, src/lib/tvgLoaderMgr.h, src/lib/tvgPicture.cpp, src/lib/tvgPictureImpl.h, src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoader.h, src/loaders/tvg/tvgTvgLoader.cpp, src/loaders/tvg/tvgTvgLoader.h
@API Changed:
Result Picture::load(const char* data, uint32_t size, bool copy /*=false*/) noexcept
TVG_EXPORT Tvg_Result tvg_picture_load_data(Tvg_Paint* paint, const char *data, uint32_t size, bool copy);
=> loaders: added copy param for Picture::load

src/lib/tvgSceneImpl.h
If renderer was null, paints was cleared (count set to zero), but data was not deleted regardless the free boolean.
@Issue: https://github.com/Samsung/thorvg/issues/442
=> common: fix a memory leak after scene->clear(true)

src/loaders/svg/tvgXmlParser.cpp
While skipping the string, check the end of the string first.
Prevents an invalid read when parser really get to the end of the string.
issue: https://github.com/Samsung/thorvg/issues/461
=> svg_loader XmlParser: Fix check the end of string

src/loaders/svg/tvgSvgLoader.cpp
If there is no path information, it is not copied.
=> svg_loader SvgLoader: Prevent invalid access

src/loaders/svg/tvgSvgLoader.cpp
When copying an attribute, url information of stype's composite is overwritten with memcpy.
This causes double free by deleting the wrong string in freeNodeStyle.
issue: https://github.com/Samsung/thorvg/issues/455
=> svg_loader SvgLoader: Copy the missing composite url

src/loaders/svg/tvgSvgLoader.cpp
Values different from numbers and percentages should be ignored
and the default values should be applied (zeros).
We need this change to solve issue #457 (example e-stop-019.svg) - but there are also other problems with this svg file.
example:
```
<svg viewBox="0 0 200 200">
<linearGradient id="grad" x1="0" y1="0" x2="1" y2="1">
<stop offset="10%" stop-color="white"/>
<stop offset="20% " stop-color="red"/>
<stop offset="30% k" stop-color="blue"/>
<stop offset="40%" stop-color="yellow"/>
<stop offset="0.5m" stop-color="red"/>
<stop offset="0.6 " stop-color="green"/>
<stop offset="70%m" stop-color="black"/>
<stop offset="80%" stop-color="white"/>
<rect x="20" y="20" width="160" height="160" fill="url(#grad)"/>
</svg>          
```
The results after applying #475 
before: …
=> svg_loader: correct parsing ColorStop offset values

meson.build, src/meson.build
for optimial library, we removed some peripheral information in default,
this breaks asan environment.
This patch changes it to make it both.
if you want to use asan, please change the meson option.
default is disabled.
example)
$meson . build -Db_sanitize=address
$meson . build -Db_sanitize=address,undefined
=> infra: add memory sanitize option in meson

src/lib/sw_engine/tvgSwFill.cpp
There was a call to the ctable element from outside its boundaries, because
the check was misplaced.
code:
```
<svg id="svg1" viewBox="0 0 200 200">
<linearGradient id="grad" x1=".4" y1="0" x2=".6" y2="0" spreadMethod="repeat">
<stop offset="0" stop-color="red"/>
<stop offset="1" stop-color="black"/>
<rect id="rect1" x="20" y="20" width="160" height="160" fill="url(#grad)"/>
</svg>
```
=> sw_engine fill: fixing gradient calculations for 'repeat' spread value

src/lib/tvgShape.cpp, src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgPath.cpp
Math Constants are not defined in Standard C/C++
for this, we can use _USE_MATH_DEFINES before math headers.
=> common: fix compatibility issue for MSVC

src/lib/tvgCommon.h
__attribute__ syntax is not supported by MSVC.
We can turn it on optionally.
=> common: fix compatibility issue for MSVC.

src/lib/sw_engine/tvgSwMath.cpp
clz (count leading zero) is builtin function
that is not available in MSVC.
This patch replace clz for MSVC env.
Thanks @fire for pointing out this.
Refers: https://stackoverflow.com/questions/355967/how-to-use-msvc-intrinsics-to-get-the-equivalent-of-this-gcc-code
=> common: fix MSVC compatibility problem.

src/loaders/svg/tvgSvgPath.cpp
It handles the case what the flag of the arc of the path is defined
without spaces or commas, such as 00, 01, 11 or 10.
issue: https://github.com/Samsung/thorvg/issues/455
=> svg_loader SvgPath: Added corner case handling for flags of Arc

src/loaders/svg/tvgSvgSceneBuilder.cpp
if the input points are odd-numberd, it could access invalid memory.
Prevents it just in case.
=> svg_loader: prevent heap memory overflow.

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwStroke.cpp
This valid tag is used for further progress.
we don't need it actually since we can count by points number.
=> sw_engine stroke: set stroke invalid if points are zero.

src/loaders/svg/tvgSvgLoader.cpp
copy attribute must copy the url data,
otherwise, url memory can be atempted freeing twice.
=> svg_loader: fix double-free memory.

inc/thorvg.h, src/lib/tvgCommon.h, src/lib/tvgPaint.h, src/lib/tvgPicture.cpp, src/lib/tvgScene.cpp, src/lib/tvgSceneImpl.h, src/lib/tvgShape.cpp
The PaintType enum was used to set the paint type in the internal Paint
implementation. This solution is switched to an identifier with id() getter,
so that the information about the type can be reached from outside the Paint.
I'd like to use the information about the Paint type in the saver module.
=> common: PaintType enum changed to identifier in Paint class

inc/thorvg.h, src/lib/tvgPaint.cpp
The new API gets the composite method and the pointer to the composite
target of the given paint object.
I'd like to use this API in the saver module. 
The alternative would be to change the iterator and for example set the first node to be the composite target (if it exists) - in this approach I would need to mark the paint whether it is a comp target or not.
=> common: introducing the composite API (getter)

src/loaders/svg/tvgSvgSceneBuilder.cpp
Before this change the 'stroke-opacity' and the 'fill-opacity'
grad style attributes were not taken into account.
code:
```
<svg height="400" width="400" viewBox="0 0 400 400" >
<defs>
<radialGradient id="grad" gradientUnits="userSpaceOnUse" cx="125" cy="125" r="25">
<stop offset="0.000" style="stop-color: rgb(0, 0, 255); stop-opacity: 1;"/>
<stop offset="1.000" style="stop-color: rgb(0, 0, 255); stop-opacity: 1;"/>
</defs>
<path d="M 0,0 h 180 v 180 h -180 z" style="stroke: url(#grad); stroke-width:18 ; stroke-opacity: 1; fill: url(#grad); fill-opacity: 1;"/>
<path d="M 0,200 h 180 v 180 h -180 z" style="stroke: url(#grad); stroke-width:18 ; stroke-opacity: 0.5; fill: url(#grad); fill-opacity: 1;"/>
<path d="M 200,0 h 180 v 180 h -180 z" style="stroke: url(#grad); …
```
=> svg_loader: applying opacity to the gradient

src/loaders/svg/tvgSvgLoader.cpp
In the _toColor func, after founding the proper color, the search
should be finiched.
=> svg_loader: finish the search after founding the proper color

src/loaders/svg/tvgSvgLoader.cpp
../src/loaders/svg/tvgSvgLoader.cpp: In function ‘void _copyAttr(SvgNode*, const SvgNode*)’:
../src/loaders/svg/tvgSvgLoader.cpp:1598:60: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct SvgStyleProperty’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
memcpy(to->style, from->style, sizeof(SvgStyleProperty));
@Issue: 498
=> svg_loader: fix trivial build warnings.

src/loaders/svg/tvgSvgLoader.cpp
After finding no attributes but white spaces, attrsLength could be negative
that resulted in segmentation fault in simpleXmlParseAttributes function.
Minimal svg that caused segmentation fault before this patch applied:
```
<?xml version="1.0" encoding="UTF-8"?>
<svg><g ></g></svg>
```
@Issue: https://github.com/Samsung/thorvg/issues/487
=> svg_loader: negative attrs length fix

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h
The 'currentColor' attribute value was not inherited. Fixed.
`curColorSet ` is used to distinguish between the two cases from the example below:
code:
```
<svg id="svg1" viewBox="0 0 200 200">
<g color="green">
<rect id="rect1" x="0" y="0" width="100" height="200"
fill="currentColor" color="red"/>
</g>
<g color="green">
<rect id="rect1" x="100" y="0" width="100" height="200"
fill="currentColor"/>
</g>
</svg>
```
before:
after:
=> svg_loader: currentColor - inheritance from a parent

src/lib/sw_engine/tvgSwRle.cpp
The code is actually intended, we can modify it to ignore the
annoying sanitizer reports.
@Issue: https://github.com/Samsung/thorvg/issues/483
=> sw_engine rle: -- sanitizer reports.

src/loaders/svg/tvgSvgUtil.cpp
svg may have 'em' unit for fonts, strtof() must handle this case to not
drop in the infinite loop.
Yet thorvg doesn't support font feature in svg,
it must multiply values with font size if those values have 'em' size.
@Issue: https://github.com/Samsung/thorvg/issues/488
=> svg_loader: fix the inifite loop bug when size has 'em' unit.

src/loaders/svg/tvgSvgLoader.cpp
If the svg file contained multiple defs tags, each subsequent tag
overwritten the previous one. This resulted in incorrect rendering of the
file and memory leaks.
Minimal svg that resulted in a memory leak:
```
<svg>
<defs></defs>
<defs></defs>
</svg>
```
Example svg file:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200">
<defs id="defs01">
<linearGradient id="Gradient01"
x1="0" y1="0" x2="1" y2="1">
<stop offset="10%" stop-color="#000" />
<stop offset="90%" stop-color="#fff" />
</defs>
<defs id="defs02">
<linearGradient id="Gradient02"
x1="0" y1="0" x2="1" y2="1">
<stop offset="0" stop-color="#00bacc" />
<stop offset="1" stop-color="#ccba00" />
</defs>
<rect x="0" y="0" width="200" height="100" fill="url(#Gradient01)" />
<rect x="0" …
```
=> svg_loader: allow multiple <defs> tags without data and memory leak

src/lib/sw_engine/tvgSwFill.cpp
The opacity value is interpolated as are all color channels.
example with apis:
```
shape1->appendRect(0, 0, 400, 400, 0, 0);    
auto fill = tvg::LinearGradient::gen();
fill->linear(0, 0, 400, 400);
colorStops[0] = {0, 255, 0, 0, 255};
colorStops[1] = {1, 0, 0, 255, 0};
fill->colorStops(colorStops, 2);
shape1->fill(move(fill));
if (canvas->push(move(shape1)) != tvg::Result::Success) return;
```
svg xample (same result as from apis):
```
<svg viewBox="0 0 800 800">
<defs>
<linearGradient id="grad" x1="0" y1="0" x2="1" y2="1">
<stop style="stop-color:#0000ff;stop-opacity:1;" offset="0"/>
<stop style="stop-color:#ff0000;stop-opacity:0;" offset="1"/>
</defs>
<rect x="0" y="0" width="400" height="400" …
```
=> sw_engine: stop-opacity value should be interpolated between stops

src/lib/sw_engine/tvgSwRle.cpp
error: use of undeclared identifier 'ulong'
@Issue: https://github.com/Samsung/thorvg/issues/541
=> sw_engine: fix broken MSVC compatibility.

src/loaders/svg/tvgSvgLoader.cpp
The default values of gradient properties were handled differently
than the values given by a user/in an svg file.
before:
after:
this helps in #430 and solves e-stop-019.svg from #457
=> svg_loader: recalculating the default values of grads

src/lib/tvgArray.h
runtime error: null pointer passed as argument 1, which is declared to never be null
=> common array: -- sanitizer errors

test/testScene.cpp
Dismiss this usage for consistency.
Yet we have no practical necessity,
we can apply this to *all test suites later.
=> test scene: revert section usage.

src/lib/tvgPicture.cpp
size() returns invalidArgument if it doesn't have any loaded data.
=> common picture: ++ exception case.

src/loaders/svg/tvgSvgLoader.cpp
`<stop>` tag should be always a child of a `<linearGradient>` or `<radialGradient>` element, but there were files with `<stop>` tag inside `<rect>`.
This patch fixes a memory leak if no gradient is defined before `<stop>` tag.
@issue: #545
=> svg_loader: memory leak after improper stop tag

src/loaders/svg/tvgSvgLoader.cpp
Multiple composition are still not supported, but this patch fixes a
memory leak if it is tried to be applied.
@issue: #546
=> svg_loader: multiple composition memory leak

src/lib/tvgPictureImpl.h, src/loaders/raw/tvgRawLoader.cpp
picture/raw should update the size if the raw image
with size values are entered.
=> common picture: fix invalid size returns from raw image.

test/capi/capiPaint.cpp, test/testPicture.cpp
use catch Approx functions to compare floating-point values.
=> test capi: code refactoring

src/loaders/svg/tvgSvgLoader.cpp
Any non digit character in `stroke-dasharray` resulted in a dead looping
@issue: #542
=> svg_loader: fix dead loop on non-digit char in stroke-dasharray

src/lib/tvgBinaryDesc.h
It's a middle stage leading to removing flags from the tvgBinaryDesc.h file
and use the corresponding enums from the thorvg.h file.
In the saver module I'm using the enums and in the tvg loader the flags are used.
With this change the enums and flags are compatible. 
In the future I'd like to use enums in both cases.
=> tvg_loader: change values of flags

src/loaders/svg/tvgSvgLoader.cpp
Refers to the diagonal length of the viewport.
https://www.w3.org/TR/SVG2/coords.html#Units
issue: https://github.com/Samsung/thorvg/pull/572 , https://github.com/Samsung/thorvg/issues/542
=> svg_loader: Support percentage unit of dash-array

meson.build, meson_options.txt, src/lib/tvgLoaderMgr.cpp, src/loaders/jpg/meson.build, src/loaders/jpg/tvgJpgLoader.cpp, src/loaders/jpg/tvgJpgLoader.h, src/loaders/meson.build
This patch introduces a jpg loader.
For decoding the image, libjpeg-turbo library is used. Library was found to be
fast (SIMD instructions accelerated), light and portable.
@issue: #517
=> jpg_loader: introduced jpg decode using libjpeg-turbo

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h
Some svg export software puts `<defs>` element at the end of the file.
If so, the `<defs>` element won't be found, when parsing `<use>`.
In such scenario, this patch postpone node cloning until the whole file
is parsed.
@issue: #568
=> svg_loader: postpone cloneNode()

src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.h
prepared compositors can be dangled if the rendering is not occured.
free them by doubl-checking in the destructor.
=> sw_engine renderer: fix memory leak.

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h, src/loaders/svg/tvgSvgSceneBuilder.cpp, src/loaders/svg/tvgSvgUtil.cpp, src/loaders/svg/tvgSvgUtil.h
This patch introduces embeded `<image>` tag for svg files.
Images can be now loaded from local path or using data URI Scheme (RFC2397).
Base64 and UTF8/URI encoded data are welcome.
example svg file:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200">
<defs>
<clipPath id="circleView">
<circle cx="100" cy="100" r="40" fill="#FFFFFF" />
</clipPath>
</defs>
<image href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3Ccircle cx='50' cy='50' r='48' fill='none' stroke='%23000'/%3E%3Cpath d='M50,2a48,48 0 1 1 0,96a24 24 0 1 1 0-48a24 24 0 1 0 0-48'/%3E%3Ccircle cx='50' cy='26' r='6'/%3E%3Ccircle cx='50' cy='74' r='6' fill='%23FFF'/%3E%3C/svg%3E%0A" height="100" width="100" x="0" y="0" />
<image …
```
=> svg_loader: <image> tag introduced

src/loaders/jpg/tvgJpgLoader.cpp
If the copied data in JpgLoader's data open is invalid,
it is processed without being cleared.
Therefore, data memory free is handled in the destructor.
=> jpg_loader JpgLoader: Prevent memory leak

src/loaders/svg/tvgSvgLoader.cpp
Duplicate declaration of id attribute is invaild.
We do not have a separate policy for invalid svg files.
Therefore, it is a priority to prevent crashes or memory leaks.
If an id is declared as duplicate, the last declared id is used.
issue: https://github.com/Samsung/thorvg/issues/593
=> svg_loader SvgLoader: Fix memory leak of duplicate declared id

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h
This patch fixes valgrind detection
$valgrind --leak-check=yes ./Svg
==21410== Conditional jump or move depends on uninitialised value(s)
==21410== at 0x505DB66: _attrParseStops(void*, char const*, char const*) (tvgSvgLoader.cpp:2099)
==21410== by 0x5064F6D: simpleXmlParseAttributes(char const*, unsigned int, bool ()(void, char const*, char const*), void const*) (tvgXmlParser.cpp:319)
==21410== by 0x5061774: _svgLoaderParserXmlOpen(SvgLoaderData*, char const*, unsigned int, bool) (tvgSvgLoader.cpp:2387)
==21410== by 0x5061857: _svgLoaderParser(void*, SimpleXMLType, char const*, unsigned int) (tvgSvgLoader.cpp:2408)
==21410== by 0x5065052: simpleXmlParse(char const*, unsigned int, bool, bool ()(void, SimpleXMLType, char const*, unsigned int), void const*) (tvgXmlParser.cpp:425)
==21410== …
=> svg_loader SvgLoader: Initialize to flag value of SvgParser

src/loaders/svg/tvgSvgPath.cpp
If the d attribute of SVG path is not parsed through _nextCommand(),
it is regarded as an invalid data.
issue: https://github.com/Samsung/thorvg/issues/595
=> svg_loader SvgPath: Skip invalid path

src/loaders/svg/tvgSvgPath.cpp
Unneeded static keyword in _pathAppendArcTo function led to race conditioning
@issue: #604
=> svg_loader: race condition on arc processing

src/loaders/svg/tvgSvgUtil.cpp
Fixed svgUtilURLDecode function.
Deleted snippet was not needed and it broken decoding when space.
=> svg_loader: image tag: fixed utf8 decode

test/testPicture.cpp
Added SVG file loading and rendering for increasing TC Line coverage
Line coverage for `src/loaders/svg`: 85.5%
=> test: svg rendering

src/loaders/svg/tvgSvgSceneBuilder.cpp
For some svg files it is needed to force size equal the viewbox
for proper scaling
=> svg_loader: image tag: force size equal to the viewbox

src/examples/MultiCanvas.cpp, src/examples/Stress.cpp, src/examples/Svg.cpp
snprintf() is more preferred to use in preventing buffer overflow.
=> examples: replace sprintf() with snprintf()

src/lib/gl_engine/tvgGlCommon.h, src/lib/gl_engine/tvgGlProgram.cpp, src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/gl_engine/tvgGlShader.cpp, src/lib/sw_engine/tvgSwRaster.cpp, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRle.cpp, src/lib/tvgCommon.h, src/lib/tvgLoader.cpp, src/lib/tvgPaint.h, src/lib/tvgSaver.cpp, src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgSceneBuilder.cpp, src/loaders/svg/tvgXmlParser.cpp, src/loaders/tvg/tvgTvgLoadParser.cpp
We can replace the system logger method by changing single line print source in common,
This also helps to remove the THORVG_LOG_ENABLED macro from each use-cases.
TVGLOG(): To print the hint & tip messages for users.
TVGERR(): To print the error message for debugging.
@Issues: https://github.com/Samsung/thorvg/issues/36
=> common log: use the log macro to replace the print method easier.

src/savers/tvg/tvgTvgSaver.cpp, src/savers/tvg/tvgTvgSaver.h
The default values (stroke cap/join, fill rule or color with alpha = 0)
were unnecessarily saved in the tvg format file.
=> tvg_saver: removing saving the default values

meson_options.txt, src/bin/meson.build, src/bin/svg2tvg/meson.build, src/bin/svg2tvg/svg2tvg.cpp
This is an utility to convert a file from svg to tvg
To use this, enable the feature by toggling in the meson option.
$meson build -Dtools="svg2tvg" ...
See also the usage:
Usage:
svg2tvg [SVG file]
Examples:
$ svg2tvg input.svg
=> tools svg2tvg: introduce a new tool for exporting tvg.

inc/thorvg.h, src/bindings/capi/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp, src/lib/sw_engine/tvgSwImage.cpp, src/lib/tvgPicture.cpp, src/lib/tvgPictureImpl.h, src/loaders/svg/tvgSvgSceneBuilder.cpp, test/capi/capiPicture.cpp
picture provides size() interface to return the image size,
viewbox() is conceptually not correct with the Picture.
Remove it under the beta api.
=> common picture: remove viewbox() api.

src/lib/tvgLoadModule.h, src/lib/tvgPictureImpl.h, src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoader.h, src/loaders/tvg/tvgTvgLoader.cpp, src/loaders/tvg/tvgTvgLoader.h
replace from Scene to Paint at the internal interface.
Picture doesn't need to know the returned Node type.
base class, Paint is enough to in the data passing.
=> common loader: code refactoring.

src/lib/tvgLoadModule.h, src/lib/tvgPictureImpl.h, src/loaders/jpg/tvgJpgLoader.cpp, src/loaders/png/tvgPngLoader.cpp, src/loaders/raw/tvgRawLoader.cpp, src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoader.h, src/loaders/tvg/tvgTvgLoader.cpp, src/loaders/tvg/tvgTvgLoader.h
Bitmap based pictures doesn't need the viewbox,
LoaderModule should delegate the viewbox to the derived classes which
having vector-based image loaders such as svg, tvg.
In that case, paint resizing can be performed by the loaders by own
policy.
=> common loader: code refactoring

src/lib/sw_engine/tvgSwMemPool.cpp, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRle.cpp, src/lib/sw_engine/tvgSwStroke.cpp
if many canvas instances own private memory pool,
the memory usage can be increased linearly.
To prevent memory usage, flush out memory pool from the clear()
if the canvas uses private memory pool.
=> sw_engine: flush memory pool after drawing.

inc/thorvg.h, src/examples/PictureJpg.cpp, src/examples/PicturePng.cpp, src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwImage.cpp, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/tvgPicture.cpp, src/lib/tvgPictureImpl.h, src/savers/tvg/tvgTvgSaver.cpp
Pixel-based image picture doesn't work at size() method.
Obvisouly, we missed to implement it properly.
This patch correct it.
@Issue: https://github.com/Samsung/thorvg/issues/656
=> common picture: correct non-working size() behavior.

src/loaders/svg/tvgSvgLoader.cpp
If svg contained multiple defs tags only the first one was handled correctly.
Every next 'defs' tag was skipped and its inner elements parsed as it was
outside the defs.
This pr fixes the requested svg files:
before:
after:
=> svg_loader: allow multiple defs tags

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwRaster.cpp
Apply bilinear interpolation when drawing images with transformation
If the mapped coordinate value is a floating point value,
bilinear interpolation is performed using adjacent pixel values.
Interpolation is not performed in cases when the color values to be interpolated
are the same or scale down case.
issue : https://github.com/Samsung/thorvg/issues/373
[left before right after]
(scale down case is same result)
(scale up x3)
(Translucent Image with clippath)
(Image with clippath)
(Translucent Image)
(Translucent Image with mask)
(Translucent Image with inverse mask)
=> sw_engine Raster: Apply bilinear interpolation to images

src/loaders/svg/tvgSvgLoader.cpp
"xlink:href" will be deprecated.
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href
=> svg_loader SvgLoader: Add 'href' attribute for parser

src/lib/tvgLoader.cpp
LoaderMgr::loader(data, w, h, copy) is dedicated for raw images only.
No need to try other loaders.
=> loader: removed loader finding for LoaderMgr::loader(data, w, h, copy)

meson.build, src/lib/tvgCommon.h, src/lib/tvgInitializer.cpp, src/loaders/tvg/tvgTvgLoadParser.cpp, src/loaders/tvg/tvgTvgLoadParser.h, src/loaders/tvg/tvgTvgLoader.cpp, src/loaders/tvg/tvgTvgLoader.h, src/savers/tvg/tvgTvgSaver.cpp
tvg file stores the version info of thorvg when it's generated,
in order to compare it with the runtime thorvg version when it's loaded.
For this, thorvg builds up the current version of symbol on the initilaization step,
that can be referred by the tvg loader.
=> tvg_format: force to check for compatibility by version comparision.

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwRaster.cpp
Changes:
- Prepare neon verison of ALPHA_BLEND API.
- Use ALPHA_BLEND_NEON in _translucentRle
Notes:
- _translucentRle with neon support reduces execution time of this
function ~ 300 % (measured on uint32_t 400 x 400 buffer).
- API was tested on ARMv7l device with GCC 9.2 based toolchain. Results
on other devices could be different.
=> sw_engine common: Added neon alpha blending.

src/lib/sw_engine/meson.build, src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwRaster.cpp, src/lib/sw_engine/tvgSwRasterAvx.h, src/lib/sw_engine/tvgSwRasterC.h, src/lib/sw_engine/tvgSwRasterNeon.h
Separate simd implementation by files to maintain them easier.
Now we have avx, c, neon version implementation base.
we can add implementations to them.
=> sw_engine raster: code refactoring.

inc/thorvg.h, src/bindings/capi/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp, src/examples/PictureJpg.cpp, src/examples/PicturePng.cpp, src/examples/Svg2.cpp, src/lib/tvgLoader.cpp, src/lib/tvgLoader.h, src/lib/tvgPicture.cpp, src/lib/tvgPictureImpl.h, src/loaders/svg/tvgSvgSceneBuilder.cpp, test/capi/capiPicture.cpp, test/testPicture.cpp
Added mimetype attribute to enfaster loading using a proper loader.
@Changed api: Picture::load(const char* data, uint32_t size, const std::string& mimeType, bool copy = false)
@issue: #571
=> loaders: Pass mimetype to picture::load

src/lib/tvgPictureImpl.h
if the picture has a bitmap-based image,
it can return the bounding box size with the current image size.
=> common picture: return bounding box size with the current image size.

src/loaders/tvg/meson.build, src/loaders/tvg/tvgTvgBinInterpreter.cpp, src/loaders/tvg/tvgTvgCommon.h, src/loaders/tvg/tvgTvgLoader.cpp, src/loaders/tvg/tvgTvgLoader.h
tvg binary format might break the compatibility if any major features have been changed.
It's allowed to do it when the major version is upgraded.
In that case, still we need to support the backward compatibility,
we can provide multiple binary interpreters and choose the proper one
based on the current loading tvg binary format version.
Thus, you can add further interpreters if it's necessary in the future.
Our policy is to derive the TvgBinInterpreterBase class to make it running on
the interface.
for example, if the major version is upgraded 1.x, you can implement TvgBinInterpreter1.
=> tvg_loader: introduce tvg interpreter base class for future extension.

src/loaders/jpg/tvgJpgLoader.cpp
Added error string printing on jpg image loading failure.
The error message help developer find the corrupted jpg file.
Error message is not printed for open from char* data as there the
loaders are tried on by one.
=> JPG loader: print error string on failure

inc/thorvg.h, src/bindings/capi/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp, src/lib/tvgLoadModule.h, src/lib/tvgPicture.cpp, src/lib/tvgPictureImpl.h, src/loaders/svg/tvgSvgLoader.h
though picture has size() api, we have a regression issue in tizen,
we can't remove this api until we resolve any regression conditions.
=> common picture: recover viewbox() api.

src/lib/tvgInitializer.cpp
String must be finished at termination charactor,
previous logic missed that handling, now fixed.
@Issue: https://github.com/Samsung/thorvg/issues/690
=> common initializer: fix out of buffer access by the version info string.

meson.build
=> common: meson.build added default_options cpp_std=gnu++14

src/lib/tvgPaint.cpp, src/lib/tvgPictureImpl.h, src/loaders/svg/tvgSvgSceneBuilder.cpp
This change protects against negative value in unsigned int of
RenderRegion.x/y. This fixes a problem of invisible paint if ClipPath
bounds was negative.
@issue: fixes #704
=> common: RenderRegion x, y protect against negative value in unsigned int

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwImage.cpp, src/lib/sw_engine/tvgSwMemPool.cpp, src/lib/sw_engine/tvgSwShape.cpp, src/lib/sw_engine/tvgSwStroke.cpp
This patch enhanced the sw raster engine to allow the both closed & open pathes
in one shape rendering.
@issue: #266
=> sw_engine: allow sharing shapes & connected strokes all in one.

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwImage.cpp, src/lib/sw_engine/tvgSwShape.cpp, src/lib/sw_engine/tvgSwStroke.cpp
Save the size of the Countour array,
16 bits is large enough to count the points number in one Shape.
=> sw_engine: memory optimization.

src/lib/tvgPictureImpl.h
Calling picture->load after it was already once called resulted in
segmentation fault or memory leak (depending on whether the vector (svg, tvg)
or raster (jpg, png, raw) file was loaded).
This patch adds buffers disposing before loading new image.
To dispose already drawn elements, renderer is kept.
@issue: fixes #719
=> picture: fix reloading images

src/bin/svg2png/svg2png.cpp
Svg2png fully redesigned.
Introduced wildcards and multiple files testing. Created naming and colorspace flags.
```
Usage: 
svg2png [svgFileName] [Resolution] [bgColor] [flags]
Flags:
-d Disable looking in subdirectories for wildcard
-c Use ABGR8888 colorspace. Default is ARGB8888.
-s Don't save png file. Useful for testing memory leaks.
Examples:
$ svg2png input.svg
$ svg2png input.svg 200x200
$ svg2png input.svg 200x200 ff00ff
$ svg2png *.svg
$ svg2png *.svg 200x200 #ff0000 -d -c
$ svg2png *.svg -d -c -s
```
@Issue: #459
=> svg2png: redesigned

src/loaders/svg/tvgSvgLoader.cpp
Percentage values wasn't handled by _toOpacity() function. Other incorrect values was handled wrongly. Now fixed.
=> svg: fix opacity percentage value parsing

src/wasm/thorvgwasm.cpp, wasm_cross.txt
This patch adds saveTvg() function into thorvgwasm.cpp.
Functions saves tvg using File System API.
To enable fs, changed build flag: -s FORCE_FILESYSTEM=1.
Increase in result thorvg-wasm.js size: about 68kB to about 125kB.
=> wasm: intoduce saveTvg via File System API

src/lib/sw_engine/tvgSwShape.cpp
add an exception handling,
if the given points count is not matched with expected points count from commands.
@Issue: https://github.com/Samsung/thorvg/issues/735
=> sw_engine shape: prevent crash when wrong pair of commands & points.

src/wasm/thorvgwasm.cpp
This patch changes load function in thorvgwasm.cpp for using size()
instead of strlen(). It fixes loading of binary files like .tvg.
=> wasm: fix loading for binary files

src/savers/tvg/tvgTvgSaver.cpp, src/savers/tvg/tvgTvgSaver.h
A gradient transformation was omitted when saving
into the tvg format. Fixed
Before:
After:
SVG:
```
<svg width="500" height="300">
<radialGradient cx="80" cy="150" r="40" id="radGrad" gradientUnits="userSpaceOnUse">
<stop style="stop-color:#ff0000" offset="0.0"/>
<stop style="stop-color:#00ff00" offset="0.7"/>
<stop style="stop-color:#0000ff" offset="1.0"/>
<path d="M 0 0 h 100 v 200 h -100 z" transform="matrix(1, 0, 0, 1, 100, 0)" style="fill:url(#radGrad)"/>
</svg>
```
=> tvg saver: enabling gradient transformation

src/lib/sw_engine/tvgSwRasterNeon.h
In the case, when the dst memory was not aligned,
we went out of the dst range in the 'neon loop'.
=> sw_engine neon: fix the iterations number of 'neon calls'

src/bin/svg2png/svg2png.cpp
The background color was misinterpreted and its value was treated
as an svg file name (warning was returned).
The color format can not be passed in a "#ffffff" format, since
the '#' sign is used in bash to comment a line and nothiing after
it is loaded.
```./svg2png ../../../../src/examples/images/bojo.svg -b ff0000```
before:
```
Generated PNG file: /home/m.grudzinska/thorvg/src/examples/images/bojo.png
Warning: File "ff0000" is invalid.
```
after:
```
./svg2png ../../../../src/examples/images/bojo.svg -b ff0000
Generated PNG file: /home/m.grudzinska/thorvg/src/examples/images/bojo.png
```
=> svg2png: fixing the args interpretation

src/lib/sw_engine/tvgSwRaster.cpp
For avx vector support the avxRasterTranslucentRect should be called
instead of cRasterTranslucentRect (mischanged in 01e1fec367e0ed7cf2bb052089b12e9c406f30d8).
=> sw_engine: calling avxRasterTranslucentRect instead of its c version

test/testSwEngine.cpp
All image rastering funcions called in the 'Image Draw' test case.
sw engine LC: 72.6% -> 84.7%
=> test SwEngine: raster image functions included into the unit tests

src/lib/sw_engine/tvgSwRasterAvx.h
Reverts Samsung/thorvg#753
oop sorry, i confused the history of the commit.
=> Revert "sw_engine avx: the not aligned memory separated in the rasterRGBA32 func"

src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/tvgPaint.cpp
Clips from outside the rendering region were ignored resulting
in rendering shapes, which should be completely clipped.
In case of the clip fast track, the bounding box width/height
overflow occured and shape, that should be clipped, could be
visible (not always).
before:
after (black screen, as expected):
code:
```
if (!canvas) return;
auto star1 = tvg::Shape::gen();
star1->appendRect(400, 400, 300, 300, 30, 30);
star1->fill(255, 255, 0, 255);
star1->stroke(255 ,0, 0, 255);
star1->stroke(10);
auto clipStar = tvg::Shape::gen();
clipStar->appendRect(-450, 430, 110, 110, 0, 0);
clipStar->fill(255, 255, 255, 255);
star1->composite(move(clipStar), tvg::CompositeMethod::ClipPath);
canvas->push(move(star1));
string path(EXAMPLE_DIR"/rawimage_200x300.raw");
ifstream file(path);
if …
```
=> sw_engine: handling clips from outside the rendering region

src/lib/tvgBinaryDesc.h, src/loaders/tvg/tvgTvgBinInterpreter.cpp
Skip the reassigning values by the flags,
We assume those property values are reserved,
leave to apis that handle the invalids if the exceptions.
=> tvg_loader: code refactoring & optimization loading.

src/loaders/svg/tvgSvgPath.cpp
Since the arc flags can have values 0 or 1, we reported as
an error cases, when a float value was given.
Since the EBNF grammar can be used, we misread some paths.
Removing the condition that prevents giving a float as a flag solves
this problem and is in agreement with the w3 specs.
before:
after:
code:
```
<svg viewBox="0 0 4 4">
<path d="M.604.605L.75.922C.754.896.77.877.783.855l.356.354a.9.9 0 00-.239.535H.7c-.081-.006-.081.118 0 .111h1.1c.03 0 .055-.024.055-.054V.699A.056.056 0 001.8.643a.056.056 0 00-.055.056V.9a.9.9 0 00-.535.239L.857.785C.88.773.897.755.922.752L.604.605zM1.744 1v.674l-.463-.465A.832.832 0 011.744 1zm-.537.28l.467.464H1a.778.778 0 01.207-.465z" stroke="#F00" stroke-width="0.05" fill="blue"/>
</svg>
```
It was reported as an issue in nanoSVG: …
=> svg_loader: parsing flags in the elliptical arc curve

src/savers/tvg/tvgTvgSaver.cpp, src/savers/tvg/tvgTvgSaver.h
Saver tries to pre-transfom to skip the matrix data,
but it missed the case - transformed stroking,
we skip it also only when xy scaling factors are same excluding the dash properties,
because scaled of the stroking is depent on the engines,
we have no idea of the proper input data in advance.
@Issues: https://github.com/Samsung/thorvg/issues/773
=> tvg_saver: fix the incorrect stroke transformation

src/lib/sw_engine/tvgSwShape.cpp
A square or a round cap was mistakenly added to the parts
of the dashed lines that should be continuous. Fixed
@Issues: Samsung#777
before:
after:
=> sw_engine: overlaping stroke cap

src/savers/tvg/tvgTvgSaver.cpp
To get the scaling factor from the transformation matrix we have
to use two of its elements.
this patch fixes the gradient_stroke.tvg problem from 
issue: #783
=> tvg_saver: fix the stroke width scaling factor

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwImage.cpp, src/lib/sw_engine/tvgSwRenderer.cpp
there was a wrong condition introduced the bug that image was not updated,
because transformation is not re-applied after the first created the internal image data.
@Issues: https://github.com/Samsung/thorvg/issues/751
=> sw_engine image: fix the clipped image issue.

src/wasm/thorvgwasm.cpp
This patch adds the mimetype parameter for load() function and adds storing of
an original size after successful loading. Added function originalSize().
=> wasm: pass mimetype on loading and store original size

src/savers/tvg/tvgTvgSaver.cpp
'preTransform = false' makes sense in case a stroke exist,
so not only when the stroke-width > 0 but when it's color
is valid as well.
=> svg_saver: shifting 'preTransform' value changing

src/savers/tvg/tvgTvgSaver.cpp, src/savers/tvg/tvgTvgSaver.h
In the case when a gradinet fill is present, the transformation matrix
can't be preapplied.
issue #783 pt 5 (gallardo.svg)
=> tvg_saver: proper serialization of a grad fill

src/loaders/svg/tvgSvgSceneBuilder.cpp
If 'fill="url(#image)"' and defs with id 'image' was not found, the paint was
improperly filled with color.
Issue: #820
=> svg: fix url property

src/lib/tvgPictureImpl.h
The API expected floats, whereas the called impl function expected
ints. The values were saved as floats, so the float->int->float conversion
is not needed.
=> common: change args type in the internal size() implementation

src/lib/sw_engine/tvgSwRaster.cpp
An average value sampled based on adjacent pixels of the target pixel is used.
[Before / After / ubuntu image viewer ]
[Before / After ](opacity 200)
=> sw_engine Raster: Improving image quality in image scale down

inc/thorvg.h, src/lib/tvgPicture.cpp, src/loaders/tvg/tvgTvgBinInterpreter.cpp
tvg::Picture is replaced to tvg::Scene if the picture has the vector tree,
Thus it's useless since it won't be reached logically.
=> api: remove the redundant api, Picture::paint().

inc/thorvg.h
tvg picture is going to be released, we need the Saver as well.
Also, two stable periperal apis are released in v0.5
@APIs:
Result Picture::load(const char* data, uint32_t size, const std::string& mimeType, bool copy = false) noexcept;
CompositeMethod Paint::composite(const Paint** target) const noexcept;
Result Saver::save(std::unique_ptr<Paint> paint, const std::string& path, bool compress = true) noexcept;
Result Saver::sync() noexcept;
static std::unique_ptr<Saver> Saver::gen() noexcept;
=> apis: release official apis.

README.md
This is just a suggestion. Feel free to edit or ignore as you see fit!
There may be others I have missed. I also didn't know where to link EGL and GLESv2.
As a user, it is helpful to know these possible dependencies rather than finding out after I change an option that I need additional libraries :)
=> Updated readme with optional dependencies

src/bindings/capi/thorvg_capi.h, src/loaders/tvg/tvgTvgBinInterpreter.cpp, src/savers/tvg/tvgTvgSaver.cpp, test/capi/capiLinearGradient.cpp, test/capi/capiRadialGradient.cpp
Recommend the following changes to support building on MSVC:
- Define capi export visibility for WIN32. Equivalent to `__attribute__ ((visibility ("default")))` is `__declspec(dllexport)`
- Replace variable length arrays (not supported by MSVC) with stack allocation via `alloca` (note: same code used as already found in `tvgXmlParser`)
- Changed designated initlializers in arrays of structs (`test/capi/capi[Linear/Radial]Gradient` to avoid `error C7555: use of designated initializers requires at least '/std:c++latest'` since default for thorvg is c++14
Happy for any feedback and further changes you recommend!
Relates to #844
=> portability: Changes to support MSVC

src/lib/tvgCanvasImpl.h
If there was an empty scene (empty scene, so bounds equal zero) with a mask composition applied,
Paint::Impl::render failed on checking size and Canvas::draw() returned Result::InsufficientCondition.
As a result no other paints was rendered.
@issue: fixes #842
=> common: allow composition on empty scene without Result::InsufficientCondition error

src/bindings/capi/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp
Changes:
- Removed beta api tag from CAPI module
- For some APIs, the tag has not been changed due to main API status
- Moved some documentation changes to have similar descriptions in main
API and CAPI
- Removed deprecation warnings.
=> capi: Release official CAPI's.

src/lib/gl_engine/tvgGlGeometry.cpp, src/lib/tvgCommon.h
Define a portable version of  `__attribute__ ((fallthrough))` to `tvgCommon.h` and replaced it's use in `gl_engine/tvgGlGeometry.cpp`.
The attribute is only available from c++17 onward and has a different syntax in MSVC.
See #863
Could somebody please test this change on non-windows systems, please?
=> common, gl_engine: portable fallthrough attribute

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h
Units of the svg width and height tags were incorrectly assigned.
issue #850
=> svg_loader: proper handling width/height units

src/loaders/external_jpg/meson.build, src/loaders/external_jpg/tvgJpgLoader.cpp, src/loaders/external_jpg/tvgJpgLoader.h, src/loaders/external_png/meson.build, src/loaders/external_png/tvgPngLoader.cpp, src/loaders/external_png/tvgPngLoader.h, src/loaders/jpg/meson.build, src/loaders/jpg/tvgJpgLoader.h, src/loaders/meson.build, src/loaders/png/meson.build, src/loaders/png/tvgPngLoader.h
This patch has 2 purposes,
1. revise the loaders infrastructure to support both static/external linking loaders.
2. add a template for static jpg/png loaders after external jpg/png.
Our default loaders prefer static linking, external loaders are only available
when dependent libraries on the build system are found.
You might wonder why we have the external loaders together,
they might be faster than static loaders since the popular libraries are likely to be well maintained,
fine-grained optimized.
Thus in this patch, meson tries to apply the external loaders first
then see if the dependencies were found or not,
if it's failed, it turns to the default static loaders.
Next this patch, we need the contribution for actual static jpg/png loaders implementation.
@Issue: …
=> loaders: prepare for static jpg/png loaders.

meson.build, src/lib/sw_engine/tvgSwRenderer.cpp
According to the svg standard, in a case when 'x1==x2 and y1==y2'
for a linear gradient or when 'r==0' for a radial gradient, the area
should be painted as a single color - the last gradient stop color.
before:
empty plot
after:
code:
```
<svg viewBox="0 0 100 100">
<defs>
<linearGradient id="lin" x1="0" y1="0" x2="0" y2="0">
<stop style="stop-color:#ff0000;" offset="0"/>
<stop style="stop-color:#0000ff;" offset="1"/>
<radialGradient id="rad" r="0" cx="0.3" cy="0.3">
<stop style="stop-color:#ffff00;" offset="0"/>
<stop style="stop-color:#00ffff;" offset="1"/>
</defs>
<rect x="0" y="0" width="100" height="50" fill="url(#lin)"/>
<rect x="0" y="50" width="100" height="50" fill="url(#rad)"/>
</svg>
```
=> sw_engine: border cases for gradients

test/images/tag.svg, test/testPicture.cpp
=> tests: ++LOC svg loader, tvg saver

inc/thorvg.h, src/lib/sw_engine/tvgSwMath.cpp, src/lib/tvgCommon.h, src/savers/tvg/tvgTvgSaver.cpp
fopen->fopen_s, strdup -> _strdup, strncpy -> strncpy_s
__declspec(dllexport) -> __attribute__ ((visibility ("default")))
I didn;t want to define _CRT_NONSTDC_NO_DEPRECATE to eliminate some warnings.
=> all: fixing clang warnings

src/bindings/capi/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp, test/capi/capiPaint.cpp
The next api of c++ version has been deprecated
Tvg_Result tvg_paint_get_bounds(const Tvg_Paint* paint, float* x, float* y, float* w, float* h);
instead, we introduce the next one under the beta.
Tvg_Result tvg_paint_get_bounds(const Tvg_Paint* paint, float* x, float* y, float* w, float* h, bool transformed);
=> capi: replaced bounds() api with the latest.

meson.build
Replace backslashes with forward slashes in `EXAMPLE_DIR` and `TEST_DIR` (meson).
These path defines had backslashes in windows, which were acting as escape characters in strings.
=> examples, tests: replace backslashes with forward slashes for portability

src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/sw_engine/tvgSwMemPool.cpp, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/tvgFill.cpp, src/lib/tvgFill.h, src/lib/tvgLoader.cpp, src/lib/tvgPaint.cpp, src/lib/tvgShapeImpl.h, src/loaders/svg/tvgSvgLoader.cpp
removed invalid nullptr checks.
New allocation doesn't gurantee that returns nullptr when it's failed.
It's useless on the modern compliers and our policy respects it.
=> common: code refactoring

src/loaders/tvg/tvgTvgBinInterpreter.cpp
After #948 is merged, the previous version of the tvg saver will skip tags like TVG_TAG_FILL_TRANSFORM. In such a case a log info will be printed
=> tvg_loader: TVGLOG added in case an unknown fill or stroke tag used

src/savers/tvg/tvgTvgSaver.cpp
A stroke is irregularly scaled in case when:
1) m11 != m22
2) m11 == m22 == 0 and m12 != m21
The second case was missing in the code.
=> tvg_saver: preTransform condition

inc/thorvg.h, src/bin/svg2png/svg2png.cpp, src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwRaster.cpp, src/lib/sw_engine/tvgSwRenderer.cpp, src/wasm/thorvgwasm.cpp
This patch introduces lowercase colorspaces (abgr8888 and argb8888) whose
colors are un-alpha-premultiplied. Unmultiplicated colors are especially
needed for wasm thorvg viewer and svg2png / tvg2png.
Only C version now.
@issue: #791
=> common: Unmultiplicated colorspace

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwShape.cpp
After 362d2df the fastTrack cases were applied even for shapes with clips.
These changes fixed this - the check whether a shape is a rect should be done
only if it has no clips.
=> sw_engine: fastTrack with clips

src/loaders/svg/tvgSvgSceneBuilder.cpp
In the case when bounds should not include a stroke width, width
and height values were reduced by half of a stroke width, instead
of the full width.
=> svg_loader: fix bounds for gradient

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwImage.cpp, src/lib/sw_engine/tvgSwMath.cpp, src/lib/sw_engine/tvgSwRaster.cpp, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwShape.cpp
Changed names:
shape->rect -> shape->fastTrack
_factTrack -> _axisAlignedRect
The check whether a shape is an axis aligned rectangle should be done
only if the shape has no clips.
(a shape can be a rect but still its `fastTrack` can be false)
=> sw_engine: var/funct renaming

meson_options.txt, src/loaders/meson.build
Add an option for use in environments where
the use of static libraries must be enforced.
=> infra meson: Add -Dstatic_library option

src/loaders/svg/tvgSvgLoader.cpp
The values in absolute units are calculated based on the pixel unit.
Till now the default value of 90dpi was used. The necessary constants
are kept, but the new ones for 96dpi are defined as well and used by default.
=> svg_loader: define the scaling factors for units changing

src/lib/sw_engine/tvgSwImage.cpp
reset rle is supposed to be reused, image should keep its pointer.
@Issue: https://github.com/Samsung/thorvg/issues/982
=> sw_engine image: fix memory leak.

src/lib/tvgBinaryDesc.h, src/loaders/tvg/tvgTvgBinInterpreter.cpp, src/savers/tvg/tvgTvgSaver.cpp, src/savers/tvg/tvgTvgSaver.h
Introducing the gradient transform() apis and changing the grad
algorithms made it possible to apply the shape's transformation
before saving the tvg file, in case the shape (or its stroke)
has a fill.
=> tvg_saver/tvg_loader: gradient fill in the tvg format

src/loaders/jpg/tvgJpgd.cpp
"warning: shifting a negative signed value is undefined [-Wshift-negative-value"
=> jpg_loader: fix compiler warnings.

src/savers/tvg/tvgTvgSaver.cpp
If paint has no path information or stroke information,
it is not referenced inside bounds.
This will access the uninitialized variable at line 759, 760.
issue :https://github.com/Samsung/thorvg/issues/995
=> tvg_saver TvgSaver: Initialize local value

test/capi/capiScene.cpp, test/testScene.cpp, test/testSwCanvasBase.cpp
On large memory machines, if machine have enough memory,
tests failed because it doesn't return null.
=> test Array: Remove too big size test

test/testInitializer.cpp
This test depends on the machine environment.
it's not guaranteed the same result so we remove it.
=> test initializer: remove a invalid test case.

src/lib/tvgSaver.cpp, src/savers/tvg/tvgTvgSaver.cpp
In the case save() api is called, memory is released in all
scenarios but Result::MemoryCorruption - consistent with other apis
and less confiusing for the user.
=> tvg_saver: fix memory leaks

src/lib/sw_engine/tvgSwRaster.cpp
current image interpolation method is a bit awkward,
because xy scale different scale factor is not allowed.
we must improve the algorithm,
but now considering floating point precision,
we allow the interpolation by less ratio floating fraction.
=> sw_engine raster: allow image interpolation by increasing tolerance.

src/lib/tvgPaint.cpp, src/lib/tvgPaint.h
applying fast track approach to the alpha mask when its condition is matched.
(simple rectangle alpha masking which isn't half-translucent)
From time to time, designers brutally use the alpha masking to clip simple region,
thorvg can help the situation by avoiding masking usage internally.
This can reduce the 1-step render pass composition.
@Issue: https://github.com/Samsung/thorvg/issues/344
=> common paint: alpha masking optimization

.github/workflows/actions.yml, .github/workflows/memcheck_valgrind.sh
If the unit test is successful, valgrind memory check is executed based on the test.
If a leak occurs in the test result, the bot notifies the PR as a comment.
This notify may not be directly related to the created current PR.
(Asan is on hold because it is not well tested in the github action CI environment.)
(test example)
issue: https://github.com/Samsung/thorvg/issues/1032
=> infra bot: Add Memcheck bot (valgrind)

src/lib/tvgPaint.cpp
casting the paint to shape is not allowed if the compositor target
is not shape, here it concretely checking the the type before casting....
=> common paint: fix invalid memory access in unit test

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwImage.cpp, src/lib/sw_engine/tvgSwRaster.cpp
apply fast track to fast up the image rasterization.
only shifted image doesn't need to have the matrix-transform computation,
we can avoid it by just shifting offset xy by simple caculating.
@Issue: https://github.com/Samsung/thorvg/issues/206
=> sw_engine image: ++optimization

src/lib/tvgCommon.h, src/savers/tvg/tvgTvgSaver.cpp
Thorvg couldn't be compiled on macos as non-portable microsoft calls used.
Changed definitions checking to Visual Studio only.
=> all: fix compilation errors on non-windows clang

test/capi/capiSwCanvas.cpp
This test depends on the machine environment.
it's not guaranteed the same result so we remove it.
=> test capiSwCanvas: remove a invalid test case.

src/loaders/tvg/tvgTvgBinInterpreter.cpp
When parsing a binary stored as a char type,
interpreter can access the misaligned memory while accessing it with a pointer.
To prevent that, pass the array copied to memcpy as tvg Object.
issue: https://github.com/Samsung/thorvg/issues/1074
=> tvg_saver TvgBinInterpreter: Prevent misaligned memory access

src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/tvgPaint.cpp, src/lib/tvgRender.h, src/lib/tvgSceneImpl.h
There was a missing sorting between the left-top & right-bottom corner.
that results in the negative values of the viewport...
Now fixed it.
+ refactored to use math functions...
=> common paint: fix the wrong fast track logic.

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwImage.cpp, src/lib/sw_engine/tvgSwRaster.cpp
These raster functions are accelerated only for the scaled images.
(no rotation, skrewed)
=> sw_engine image: introduced scaled image raster logics.

src/lib/tvgPaint.cpp
The problem was observed for empty masked scenes (except the fastTrack
cases). Solved by immediate returning from the func without passing 'false'
as its result.
issue #1082
before:
after:
code:
```
if (!canvas) return;
//Mask
mask->appendRect(10, 10, 35, 35, 10, 10);
mask->fill(255, 0, 0, 255);
//Solid Rectangle
shape1->appendRect(20, 20, 50, 50, 0, 0);
shape1->fill(255, 0, 0, 155);
scene->push(move(shape1));
//Empty scene (masked)
auto emptyScene = tvg::Scene::gen();
emptyScene->composite(move(mask), tvg::CompositeMethod::AlphaMask);
scene->push(move(emptyScene));
//Solid Rectangle
auto shape2 = tvg::Shape::gen();
shape2->appendRect(40, 40, 50, 50, 0, 0);
shape2->fill(0, 255, 0, 155); …
```
=> common: nothing was rendered after an empty masked node came across

src/lib/sw_engine/meson.build, src/lib/sw_engine/tvgSwRaster.cpp, src/lib/sw_engine/tvgSwRasterTexmap.h
Introduced the texture-mapping algorithm for the image-scaler.
With this approach, we can support any arbitrary forms of the transformed shapes
while appling the scale factors - x/y separately.
Also this is more efficient when the transformed image is far from the rectangular form
because our current normal image rasterizer based on the given drawing region whereas
our new approach is span-based.
Thus, we applied this mechanism only for the transformed images.
=> sw_engine texmap: introduced texture mapping polygon drawing.

src/lib/sw_engine/tvgSwCommon.h
The x and y of spans cannot be negative
because they are specified as coordinates inside the buffer.
Change the type to fix warnings and potential problems
that occur in conversion between int16_t and uint32_t.
=> sw_engine SwCommon: Change spans's x,y value type

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwRaster.cpp, src/lib/sw_engine/tvgSwRasterAvx.h, src/lib/sw_engine/tvgSwRasterC.h, src/lib/sw_engine/tvgSwRasterNeon.h, src/lib/sw_engine/tvgSwRasterTexmapInternal.h
These alpha/inverse alpha blender table is not useful so far,
we remove them since it just decrease the performance by by-pass addressing.
=> sw_engine raster: remove unnecessary functions.

src/lib/tvgPaint.cpp, src/lib/tvgPaint.h, src/lib/tvgPictureImpl.h, src/lib/tvgSceneImpl.h, src/lib/tvgShapeImpl.h
Grouping the composite data to add source paint necessarily.
this refactoring is a prerequisite job for the texmap anti-aliasing.
=> common paint: code refactoring

src/examples/PicturePng.cpp, src/loaders/external_png/tvgPngLoader.cpp, src/loaders/png/tvgPngLoader.cpp
It should not modify the alpha channel value while premultiplying
that turned out with the wrong visual result.
@Issue: https://github.com/Samsung/thorvg/issues/655
=> png_loaders: fix the wrong premultiplying operations.

src/lib/sw_engine/tvgSwShape.cpp
strokeOutline returned strokeExportOutline() is the address of mpool->strokeOutline[idx].
Assuming this value is null, mpoolRetStrokeOutline on line 617 will access mpool->strokeOutline[idx].
Logically, the logic of the mpool* functions does not occur in this case.
However, in the case of the strokeOutline pointer of shapeGenStrokeRle,
static analyzer may occur a warning depending on the implementation of mpool.
=> sw_engine SwShape: Prevent null access

src/lib/sw_engine/tvgSwRaster.cpp, src/lib/sw_engine/tvgSwRasterTexmapInternal.h
Prevent out of buffer boundary access.
@Issues: https://github.com/Samsung/thorvg/issues/1118
=> sw_engine raster: ++safety of the scaled image rasterization

src/lib/sw_engine/tvgSwRasterTexmapInternal.h, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/tvgPaint.cpp, src/lib/tvgRender.h
Handle correctly duplicated spans from the multiple y span data.
Previous logic only expected the one single y span data from the rle.
but rle might have multiple y span data if the anti-aliasing is applied.
=> sw_engine raster: fix a crash at the texmap clipping.

src/lib/tvgLzw.cpp
Use an anonymous namespace so that I can compile on Godot Engine.
Godot uses Dictionary() too.
=> Hide the thorvg LZW implementation.

inc/thorvg.h, src/examples/Accessor.cpp, src/examples/meson.build, src/lib/meson.build, src/lib/tvgAccessor.cpp
Basically, this Accessor is a utility to debug the Scene structure,
by traversing the scene-tree by users.
You can search specific nodes to read the property information,
figure out the structure of the scene tree and its size.
We actually don't recommend you to touch the property unless you really
know the each paint's position and role because it's not visible, difficult to
understand its anatomy.
Also, You must underatnd that modifying the nodes of the scene will be going
well with both the art-design structure and the prorgram logic.
In this first version, Accessor only supports for the Picture class.
@example:
```
auto picture = tvg::Picture::gen();
picture->load("test.svg");
//The callback function from lambda expression.
//This function will be called for every paint nodes of the …
```
=> common: Introduced Accessor for traversing the scene-tree.

inc/thorvg.h, src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwRaster.cpp
Introduced CompositeMethod::ColorMask that converts the source pixels to the
grayscale before alpha blending. Thanks to it, mask works more like typical
mask in graphics editor software.
Grayscale is calculated as an average value: A*(R+G+B)/3
@issue: #428
=> compositeMethod: introduced ColorMask

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h
The SvgCompositeNode is replaced by the SvgMaskNode and SvgClipNode.
This is needed for using Luma/AlphaMask in the svg loader and in the future,
when we introduce other mask's features.
=> svg_loader: composite node splitted on mask and clip nodes

src/lib/sw_engine/tvgSwRaster.cpp
Picture example were broken by 90fa26b7bb75cb938290170882e65da8d9fc5d9e
the correct condition must be like this change.
=> sw_engine raster: fix a regression bug.

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h, src/loaders/svg/tvgSvgSceneBuilder.cpp
In an svg file the mask-type attribute can be specified.
It takes one of the two values: Luminosity or Alpha.
After the LumaMask is introduced into TVG, this attribute can be
properly read by the svg loader.
Please be aware that this pr contains 2 commits - I'll change it after #1128 is merged. 
before:
after:
code:
- test the attribute:
```
<svg viewBox="0 0 200 200">
<defs>
<mask id="ml1" mask-type="Luminance">
<rect x="10" y="10" width="80" height="80" fill="red" fill-opacity="0.7"/>
</mask>
<mask id="ml2" mask-type="Luminance">
<rect x="110" y="10" width="80" height="80" fill="blue" fill-opacity="0.5"/>
</mask>
<mask id="ma1" mask-type="Alpha">
<rect x="10" y="110" width="80" height="80" fill="green" fill-opacity="0.7"/>
</mask>
<mask id="ma2" mask-type="Alpha">
<rect x="110" y="110" …
```
=> svg_loader: mask-type attribute introduced 

src/loaders/svg/tvgSvgLoader.cpp
A memory leak occured when the 'id' attribute was given multiple times
for a given gradient element. Fixed.
=> svg_loader: preventing memory leak

src/loaders/svg/tvgSvgLoader.cpp
The grad update should be handled after the postponed nodes are cloned.
=> svg_loader: fix grad update

src/loaders/svg/tvgSvgLoader.cpp
The clip-path and the mask attributes are both parsed in _attrParseGNode
function, which is called in th _attrParseUseNode.
=> svg_loader: removing repeated lines

src/loaders/svg/tvgSvgLoader.cpp
The color attribute hat to be inherited regardles whether it is used
in the child node or not - it may be used i.e. in the grandchild node.
before:
after:
code:
```
<svg viewBox="0 0 30 10" xmlns="http://www.w3.org/2000/svg">
<g id="myCircle" color="red">
<g fill="currentColor">
<circle cx="5" cy="5" r="4" stroke="green"/>
</g>
</g>
</svg>
```
=> svg_loader: the color attribute properly inherited

src/loaders/svg/tvgSvgLoader.cpp
In a case when no defs tag was used, no child node was find.
Also the node attributes should not override those set in the ancestor.
before:
after:
code:
```
<svg viewBox="0 0 30 30" xmlns="http://www.w3.org/2000/svg">
<use href="#myCircle1" x="10" fill="blue"/>
<use href="#myCircle1" x="20" fill="white" stroke="red"/>
<use href="#myCircle2" x="10" y="10" fill="blue"/>
<use href="#myCircle2" x="20" y="10" fill="white" stroke="red"/>
<circle id="myCircle1" cx="5" cy="5" r="4" stroke="blue"/>
<defs>
<circle id="myCircle2" cx="5" cy="5" r="2" stroke="green"/>
</defs>
</svg>
```
=> svg_loader: postponed nodes properly cloned

src/loaders/svg/tvgSvgLoader.cpp
Memory was not freed before reallocation (grad->ref can be overwritten
without freeing memory first) - fixed.
=> svg_loader: fixing memleak

src/lib/sw_engine/tvgSwRaster.cpp
Some gcc versions and configurations was giving an error:
error: "declaration of 'i' shadows a previous local"
This patch should fix these errors
=> sw_engine: fixed declaration of 'i' shadows a previous local

src/lib/sw_engine/tvgSwRaster.cpp
Some gcc versions and configurations was giving an error:
error: "comparison of integer expressions of different signedness: 'const SwCoord'
{aka 'const long int'} and 'uint32_t' {aka 'unsigned int'} [-Werror=sign-compare]"
This patch should fix the error
=> sw_engine: fix comparison of integer expressions of different signedness

src/loaders/svg/tvgSvgLoader.cpp
The reference node doesn't have to be placed inside the defs block,
so when reffering to it, it is necessary to search the entire node tree.
In case of invalid svg file this can lead to circular references.
Added prevention against such a situation.
issue #1148
=> svg_loader: fixing cyclic cloning of nodes

src/loaders/svg/tvgSvgLoader.cpp
In a case when a polygon/polyline had no points, there is nothing
to be copied.
issue #1149
=> svg_loader: preventing memcpy from a nullptr

src/loaders/svg/tvgSvgLoader.cpp
If image href set more than once, the memory was not freed.
=> svg_loader: memleak prevention

src/lib/gl_engine/tvgGlRenderer.cpp
Change id() to identifier().
error log
```
../src/lib/gl_engine/tvgGlRenderer.cpp:333:19: error: ‘const class tvg::Fill’ has no member named ‘id’
333 |     switch (fill->id()) {
```
=> gl_engine GlRenderer: Fix build error

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgPath.cpp, src/loaders/svg/tvgSvgSceneBuilder.cpp, src/loaders/svg/tvgSvgUtil.cpp, src/loaders/svg/tvgXmlParser.cpp, src/savers/tvg/tvgTvgSaver.cpp
Fixes downstream issue in Godot:
- https://github.com/godotengine/godot/issues/56894
This could also go in `lib/tvgCommon.h` or `include/thorvg.h` to be available everywhere IINM. For now I chose to put it where it's used like for other standard library headers like `math.h`, but that means other missing includes might be introduced if your pipelines don't test against MinGW (as apparently it's fine without for MSVC).
=> build: Add missing <cstring> includes for MinGW compatibility

src/loaders/svg/tvgSvgLoader.cpp
Group tags in a format <tag .../> finds no application
to the rest of the svg file and should be skipped.
issue #1162 - the 90.svg file
=> svg_loader: group tags misinterpreted as parent nodes

AUTHORS, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/tvgMath.h
This would fail building with Visual Studio 2017, at least downstream in Godot
where we undefine old Windows compilers' non-standard `min`/`max` macros (see
`minmax.h`/`NOMINMAX`).
**Note:** I didn't actually test this against VS 2017 nor VS 2019 - but it builds fine with GCC on Linux at least.
This aims at fixing the following bug report: https://github.com/godotengine/godot/issues/56894#issuecomment-1015956706
> I can't compile on MSVC2017 (14.1) because of the same library. I get the following error:
> ```
> tvgSwRenderer.cpp
> thirdparty\thorvg\src\lib\sw_engine\tvgSwRenderer.cpp(597): error C3861: 'max': identifier not found
> thirdparty\thorvg\src\lib\sw_engine\tvgSwRenderer.cpp(598): error C3861: 'max': identifier not found
> …
```
=> sw_engine: Replace non-portable min/max with std version

src/loaders/svg/tvgSvgLoader.cpp
Prevent recursive calls by counting just in case.
The size is arbitrary value, we can adjust it experimentally.
@Issue: https://github.com/Samsung/thorvg/issues/1161
=> svg_loader: ++robustness

src/loaders/jpg/tvgJpgLoader.cpp, src/loaders/jpg/tvgJpgd.cpp
These were detected by asan with PictureJpg example,
fixed them all.
=> loaders jpg: fix all memory leaks.

src/loaders/png/tvgPngLoader.cpp
These were detected by asan with PicturePng example,
fixed them all.
=> loader png: fix all memory leaks.

src/loaders/svg/meson.build, src/loaders/svg/tvgSvgCssStyle.cpp, src/loaders/svg/tvgSvgCssStyle.h, src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h, src/loaders/svg/tvgXmlParser.cpp, src/loaders/svg/tvgXmlParser.h
svg_loader: a basic implementation of the css internal style sheets
Support for class and type selectors (for the graphics elements) introduced.
The geometric attributes are not supported in the style attribute (feature added in SVG2 standard).
issue #702 
https://github.com/Samsung/thorvg/wiki/CSS-styling
---------
summary for a reviewer:
- tvgXmlParser.cpp - simpleXmlParseCSSAttribute() - parsing targets in formats: tag {}, tag.name {}, .name {}
- all methods _create...Node() has one additional arg - a pointer to a function. till now the simpleXmlParseAttributes() was used inside _create...Node() to determine the attributes values. Since the same functions (_create...Node()) are used to create the nodes with css style and the format of the data is different, I need to use there …
=> introducing css internal style sheets

src/examples/images/cssStyle.svg
For now it's a simple file used to check the styling precedence
and overall correctness.
After the css stylling will be fully introduced a more complex file
can be used.
current result;
after #1160 (the expected result):
=> example: cssStyle.svg add

src/loaders/svg/tvgSvgSceneBuilder.cpp
For the performance reasons, regardless of the set/default
mask-type value, if the mask is white, the alpha masking is
used. To qualify a mask as white, not only its fill has to be
checked, but its stroke as well. The second was missing.
=> svg_loader: fixing the used mask-type

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgSceneBuilder.cpp
One of the image's attributes can be a transformation matrix.
Now it's applied.
issue: #1177
=> svg_loader: proper image transformation

.github/workflows/build_win.yml
Symbol file generation for compiling test code in CI fails.
It's not caused by recent patches.
We don't test until we know the exact cause.
However, loader test is added to check the safety of window build.
Error Log
[45/68] Generating symbol file src/thorvg-0.dll.p/thorvg-0.dll.symbols
FAILED: src/thorvg-0.dll.p/thorvg-0.dll.symbols
"C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\meson" "--internal" "symbolextractor" "D:\a\thorvg\thorvg\build" src/thorvg-0.dll "src\thorvg.lib" src/thorvg-0.dll.p/thorvg-0.dll.symbols
=> infra: Disable unit test in window CI

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h
The css style node was improperly freed.
=> svg_loader: fixing memory leak

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h, src/loaders/svg/tvgSvgSceneBuilder.cpp, src/loaders/svg/tvgXmlParser.cpp
The 'symbol' tag introduced. It can be used to define graphical
template objects which can be instantiated by a 'use' tag.
issue #1177 
TODO:
- tested for 'preserveAspectRatio="none" since the issue #1181
- I need to work on the behavior in a case when no width/height/viewbox is set - issue #1183 - SOLVED
=> svg_loader: symbol tag implemented

src/loaders/svg/tvgSvgLoader.cpp
viewBox doesn't expect the missing attributes,
it won't have any default values.
So we can decide the fault when the values are missed.
=> svg_loader: handle the exception properly.

src/loaders/svg/tvgSvgSceneBuilder.cpp
The default value should be xMidYMid, now it is.
issue #1181
=> svg_loader: preserveAspectRatio fix

src/loaders/svg/tvgSvgSceneBuilder.cpp
The symbol node was properly scaled only for 'preserveAspectRatio=none'.
Now it works also for the default value of this attribute (xMidYMid).
in the [comment](https://github.com/Samsung/thorvg/pull/1184#issuecomment-1042456898) I pointed out that preserveAspectRatio="none" has to be set. now also the default value of the preserveAspectRatio works correctly
=> svg_loader: symbol preserveAspectRatio attribute fixed

src/loaders/svg/tvgSvgSceneBuilder.cpp
By mistake the use node was improperly transformed and/or displayed
for a reference node other than a symbol node.
=> svg_loader: use node fixed

src/lib/tvgPaint.cpp
For a very specific scaling factors shapes were to much clipped
because of wrong rounding of the viewport.
example:
```
<svg viewBox="0 0 80 20" xmlns="http://www.w3.org/2000/svg">
<clipPath id="myClip">
<rect  width="12" height="12" x="4" y="4"/>
</clipPath>
<circle clip-path="url(#myClip)"  cx="10" cy="10" r="6" />
</svg>
```
before:
after:
=> common: viewport values improperly rounded

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h, src/loaders/svg/tvgSvgSceneBuilder.cpp
=> svg_loader: symbol node without any viewbox/width/height info handled properly

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwImage.cpp, src/lib/sw_engine/tvgSwShape.cpp, src/lib/sw_engine/tvgSwStroke.cpp
An overflow occurred for big shapes with a dashed stroke,
since a contour end points were stored as the uint16 type
(instead of the uint32 type).
example:
```
if (!canvas) return;
shape->appendCircle(400, 400, 200, 200);
shape->appendCircle(400, 400, 198, 198);
shape->appendCircle(400, 400, 196, 196);
shape->appendCircle(400, 400, 194, 194);
shape->appendCircle(400, 400, 192, 192);
shape->appendCircle(400, 400, 190, 190);
shape->appendCircle(400, 400, 188, 188);
shape->appendCircle(400, 400, 186, 186);
shape->appendCircle(400, 400, 184, 184);
shape->appendCircle(400, 400, 182, 182);
shape->appendCircle(400, 400, 180, 180);
shape->stroke(0, 255, 0, 255);
shape->stroke(1.0);
float dashPattern[2] = {1.1, 1.1};
shape->stroke(dashPattern, 2);
if …
```
=> sw_engine: fixing oveflow

src/loaders/svg/tvgSvgLoader.cpp
This occurred when a gradient has no 'id' attribute.
issue #1211
=> svg_loader: fixing segf when passing a nullptr to strcmp

src/loaders/svg/tvgXmlParser.cpp
When Type is DOCTYPE, Child Entities start with '<'.
This condition is valid when general Elements (svg, g, path etc) are used.
Add a Doctype check to if condition.
(There can be various cases related to '<' nested case.
But for now, I only add Doctype considering the side effect.)
=> svg_loader: Fix invaild '<' nested check

src/loaders/svg/tvgXmlParser.cpp
Fix compile errors on FreeBSD.
- alloca is defined in stdlib.h on [freeBSD](https://www.freebsd.org/cgi/man.cgi?alloca)
Issue in [godot](https://cirrus-ci.com/task/5485473287110656?logs=build#L657)
=> Fix alloca on FreeBSD

src/lib/sw_engine/tvgSwRaster.cpp, src/loaders/tvg/tvgTvgBinInterpreter.cpp, src/savers/tvg/tvgTvgSaver.cpp
alloca is defined in stdlib.h on [freeBSD](https://www.freebsd.org/cgi/man.cgi?alloca)
additional fix to 75c1314ab0297f59cc26b7876d7b60e751d4d85c
=> fix FreeBSD compile issue.

src/lib/tvgLzw.h
Fixes the following error:
`../src/lib/tvgLzw.h:27:5: error: ‘uint8_t’ does not name a type`
=> Fix building with GCC 13.

src/lib/sw_engine/tvgSwRaster.cpp, src/loaders/svg/tvgXmlParser.cpp, src/loaders/tvg/tvgTvgBinInterpreter.cpp, src/savers/tvg/tvgTvgSaver.cpp
Should be equivalent but checking if the value is defined (`#ifdef`) is cleaner
than checking if it is set to something different from 0 (`#if`).
=> Cleanup FreeBSD preprocessor checks (if vs ifdef)

src/lib/sw_engine/tvgSwRaster.cpp, src/loaders/svg/tvgXmlParser.cpp, src/loaders/tvg/tvgTvgBinInterpreter.cpp, src/savers/tvg/tvgTvgSaver.cpp
This is a similar, slightly more generic way to fix the issue (partially) fixed in #1223 and #1224.  I've found this issue trying to build Godot on OpenBSD.
Linux seems the only system AFAICS to provide `alloca.h`.  All the BSDs have the declaration in `stdlib.h`.
Truth be told, we could just as well use `stdlib.h` on linux too (at least when building on glibc) but [the alloca manpage for linux](https://man.voidlinux.org/alloca#Notes_on_the_GNU_version) lists some caveats that I don't know if apply in this case (and I don't have a linux machine at hand to properly test.)
=> fix OpenBSD compile issue (alloca strikes again)

src/loaders/raw/tvgRawLoader.cpp
fix the invalid conversion from float to uint32_t.
@Issue: https://github.com/Samsung/thorvg/issues/1229
=> loaders raw: fix a compiler warnings on Windows.

src/lib/sw_engine/tvgSwRasterTexmapInternal.h
warning message
[35/42] Compiling C++ object src/libthorvg-0.dll.p/lib_sw_engine_tvgSwRaster.cpp.obj
In file included from ../src/lib/sw_engine/tvgSwRasterTexmap.h:96,
from ../src/lib/sw_engine/tvgSwRaster.cpp:83:
../src/lib/sw_engine/tvgSwRasterTexmapInternal.h: In function 'void _rasterPolygonImageSegment(SwSurface*, const SwImage*, const SwBBox*, int, int, uint32_t (*)(uint32_t), AASpans*)':
../src/lib/sw_engine/tvgSwRasterTexmapInternal.h:76:9: warning: 'maxx' may be used uninitialized [-Wmaybe-uninitialized]
76 |         if (x2 > maxx) x2 = maxx;
|         ^~
../src/lib/sw_engine/tvgSwRasterTexmapInternal.h:33:19: note: 'maxx' was declared here
33 |     int32_t minx, maxx;
|                   ^~~~
../src/lib/sw_engine/tvgSwRasterTexmapInternal.h:75:9: warning: 'minx' may be used …
=> sw_engine: Fix uninitialized variable

inc/thorvg.h
In addition, remove TVG_EXPORT from enum class. They are types
not symbols
=> Windows: set TVG_EXPORT to dllexport also for mingw

src/loaders/jpg/tvgJpgLoader.cpp, src/loaders/jpg/tvgJpgd.cpp, src/loaders/png/tvgPngLoader.cpp, test/testScene.cpp, test/testSwCanvas.cpp, test/testSwCanvasBase.cpp
Fixed compiler warnings that occur with MSVC (cl) and with LLVM (clang-cl) on windows.
- Conversion from float to uint32_t
- Negating an unsigned (tvgJpgd.cpp). Note that (-1u) and (~0u) are identical. They both set all bits of unsigned to 1 to give max unsigned, but `-1u` gives a compiler warning whereas `~0u` does not.
- Calling `scene->push(move(Shape::gen())` results in a `moving temporary variable prevents copy elision` warning. The move is not required here.
=> Fix compiler warnings on windows

src/loaders/svg/tvgSvgSceneBuilder.cpp
Fix the error
```
../src/lib/tvgMath.h:52:56: error: use of undeclared identifier 'M_PI_2'
if (radian < FLT_EPSILON || mathEqual(radian, float(M_PI_2)) || mathEqual(radian, float(M_PI))) return true;
^
../src/lib/tvgMath.h:52:92: error: use of undeclared identifier 'M_PI'
if (radian < FLT_EPSILON || mathEqual(radian, float(M_PI_2)) || mathEqual(radian, float(M_PI))) return true;
^
../src/lib/tvgMath.h:122:37: error: use of undeclared identifier 'M_PI'
auto radian = degree / 180.0f * M_PI;
^
```
Indeed:
* First, on Windows, one must define _USE_MATH_DEFINES before including math.h to get M_PI and other macros.
* tvgSvgSceneBuilder.cpp includes first cstring, which includes math.h, and after, it includes tvgMath.h. So _USE_MATH_DEFINES is not defined when math.h is included from cstring
* …
=> Fix compilation error on Windows with clang toolchain: M_PI undeclared

src/loaders/svg/tvgSvgLoader.cpp
Since the css id selector is not supported in TVG, only the first
style node is taken into account.
issue #1257 (for ex ABCD_10191.svg)
=> svg_loader: only the first css style node is interpreted

src/loaders/svg/tvgSvgLoader.cpp
The url were copied in the _copyAttr and in the _styleCopy
functions.
a memory leak could have been observed on the ex below:
```
<svg width="400" height="400">
<defs>
<linearGradient id="myGradient">
<stop offset="5%"  stop-color="gold" />
<stop offset="95%" stop-color="red" />
<path fill="url(#myGradient)" id="path1" d="m 100 100 h 300 v 100 z"/>
</defs>
<use width="100%" x="0" y="0" height="100%" xlink:href="#path1"/>
</svg>
```
issue: #1257
=> svg_loader: fill and stroke paiint url were copied twice

src/loaders/svg/tvgSvgCssStyle.cpp, src/loaders/svg/tvgSvgLoader.cpp
A necessary check added before strdup function is called.
svgs with mem leaks:
```
<svg viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg"
xmlns:xlink="http://www.w3.org/1999/xlink">
<path d="M 0 0 h 100 v 100 z" fill="red" d="M 0 0 h 100 v 100 h -100 z"/>
</svg>
```
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200">
<clipPath id="myClip1">
<circle cx="40" cy="35" r="75" />
</clipPath>
<clipPath id="myClip2">
<circle cx="40" cy="35" r="55" />
</clipPath>
<rect x="5" y="90" width="50" height="50" class="mineStyle" clip-path="url(#myClip1)"/>
<defs>
<style>
rect.mineStyle {
fill: blue;
stroke: #3399ff;
clip-path: url(#myClip2);
}
</style>
</defs>
</svg>
```
=> svg_loader: prevent mem leaks

src/loaders/svg/tvgSvgSceneBuilder.cpp
issue #1267 
sample:
```
<svg width="1" height="1">
<g id="d">
<use href="d">
</use>
</g>
</svg>
```
=> svg_loader: prevent stack-overflow for nested nodes

src/loaders/svg/tvgSvgLoader.cpp
Till now the proper node was searched only among children,
now all the nodes are checked.
sample svg (+ ABCD_297.svg from #1255):
```
<svg viewBox="0 0 50 50" xmlns="http://www.w3.org/2000/svg">
<defs>
<g stroke="blue" stroke-width="2" id="gID">
<circle id="myCircle" cx="0" cy="0" r="5" />
</g>
</defs>
<use x="5" y="5" href="#myCircle" fill="green" />
<use x="5" y="15" href="#gID" fill="red" />
</svg>
```
before:
after:
=> svg_loader: deeper search for postponed nodes

src/lib/tvgLoadModule.h, src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoader.h, src/loaders/svg/tvgSvgLoaderCommon.h, src/loaders/svg/tvgSvgSceneBuilder.cpp, src/loaders/svg/tvgSvgSceneBuilder.h
issue #1181 
sample file to test the bug:
```
<svg viewBox="0 0 15 15" xmlns="http://www.w3.org/2000/svg">
<symbol id="myDot" width="10" height="5" viewBox="0.5 -1 4 4" preserveAspectRatio="none">
<circle cx="0.1" cy="1" r="2" />
</symbol>
<use href="#myDot" x="0" y="5" height="4" style="opacity:0.8" />
<use href="#myDot" x="5" y="5" width="5" style="opacity:0.6" />
</svg>
```
before:
after:
to test the aspect ratio:
```
<svg id="svg1" width="200" height="100" viewBox="0 0 200 200" preserveAspectRatio="xMinYMin slice"
xmlns="http://www.w3.org/2000/svg">
<rect id="rect1" x="70" y="20" width="60" height="60" fill="green"/>
<rect id="frame" x="1" y="1" width="198" height="98" fill="none" stroke="black"/>
</svg>
<svg id="svg1" width="200" height="100" viewBox="0 0 200 200" …
```
=> svg_loader: preserveAspectRatio attrib handled according to the svg standard

src/wasm/thorvgwasm.cpp
revised the logic to align svg images in the center of the view.
this is the subsequent changes to 3939b61770c14602d7e349ba0baa21d9f4d97a44.
=> wasm: Update size calculation logic

wasm_cross.txt
Clang 16 of emsdk(Latest) does not support `-flto=0` option. so I temporarily add -flto option.
```
clang-16: error: unsupported argument '0' to option '-flto='
em++: error: '/home/junsu/dev/os/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -I/home/junsu/dev/os/emsdk/upstream/emscripten/cache/sysroot/include/SDL --sysroot=/home/junsu/dev/os/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -O2 -Werror -fno-unroll-loops -g3 -flto=0 -c /home/junsu/dev/os/emsdk/upstream/emscripten/system/lib/embind/bind.cpp -o /home/junsu/dev/os/emsdk/upstream/emscripten/cache/build/libembind-rtti/bind.o' failed (returned 1)
```
=> wasm: add -flto option

src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/gl_engine/tvgGlRenderer.h
The implementation of the virtual prepare() method is different from that of RenderMethod, so the compilation fails. This modification solves the problem.
=> gl_engine: fixed the signature of the prepare() method in GlRenderer

src/lib/sw_engine/tvgSwRasterTexmapInternal.h
If vv goes out of buffer, it can cause potential memory problems.
Therefore, an `if condition` is added so that it does not exceed the height of the image.
This is temporary fix.
Test)
```
meson -Db_sanitize=address,undefined -Dexamples=true . build
$ ./build/src/examples/Texmap
```
```
==6298==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7f37fd6c2180 at pc 0x7f380d884599 bp 0x7fffb02b2db0 sp 0x7fffb02b2da0 READ of size 4 at 0x7f37fd6c2180 thread T0
#0 0x7f380d884598 in _rasterPolygonImageSegment ../src/lib/sw_engine/tvgSwRasterTexmapInternal.h:107
#1 0x7f380d887694 in _rasterPolygonImage ../src/lib/sw_engine/tvgSwRasterTexmap.h:271
#2 0x7f380d88a598 in _rasterTexmapPolygonMesh ../src/lib/sw_engine/tvgSwRasterTexmap.h:639
#3 0x7f380d89828d in _transformedRGBAImageMesh …
```
=> SwRaster: Prevent memory issue

src/bin/svg2png/svg2png.cpp
In case the svg file size is too large, a heap overflow occurred when conversting to png. To prevent this a size limitation has been added - the resolution of the resulting png file cannot be higher than 8k (7680 x 4320).
=> [svg2png] size limitation while converting the file

inc/thorvg.h, src/lib/tvgAccessor.cpp
the old version of Accessor::access() is redundant, we replaced it with set().
It's still under the beta, we can remove it immediately. Note that we've planned to promote them official APIs in v0.9,
Newly changed, tagging beta again...
=> common Accessor: removed deprecated api.

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h
The viewbox and size(width, height) defined in SVG can be float type.
This prevents matrix calculation errors caused by this.
=> svg_loader: Change SVG viewbox variable type from int to float

src/loaders/svg/tvgSvgUtil.cpp
Some SVG parsers allow parsing of "0."
If there is a space after the dot, skip to the next step.
[example]
```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<defs id="defs3051">
<style type="text/css" id="current-color-scheme">
.ColorScheme-Text {
color:#31363b;
}
.ColorScheme-Highlight {
color:#3daee9;
}
</style>
</defs>
<path 
style="fill:currentColor;fill-opacity:0.6;stroke:none" 
d="m 15,12 v 3 h 1 v -3 z m -2,1 v 2 h 1 v -2 z m 4,0 v 2 h 1 v -2 z m -6,1 v 1 h 1 v -1 z m -1,2 v 4 c 0,1.813 1.01,3 3,3 h -2 v 1 h 8 v -1 h -2 c 1.572,0 2.507,-0.727 3,-2 h 1 c 1,0 1,-0. 1,-1.1 v -1.1 c 0,-1.8 0,-1.8 -1,-1.813 h -1 v -1 z m 1,1 h 8 v 3 c 0,1.5 -1.3,2 -3,2 h -2 c -1.662,0 -3,-0.489 -3,-2 z m 9,1 h 1 v 2 h -1 z"
/>
</svg>
```
=> common Util: Skip if there is a space after the dot

src/lib/tvgMath.h, src/lib/tvgPaint.cpp
=> paint: fastTrack should return false for the skew transformations

src/lib/tvgScene.cpp, src/lib/tvgSceneImpl.h
For any type of masking composition may be required.
@Issue: https://github.com/Samsung/thorvg/issues/1295
=> scene: fixing nested masking

src/examples/MultiCanvas.cpp, src/examples/Stress.cpp
changed by 3939b61770c14602d7e349ba0baa21d9f4d97a44
=> examples: keep aspect ratio of svg images.

src/loaders/svg/tvgXmlParser.cpp
Crash observed on macOS for the image-embeded-*.svg files. Since the alloca function was used the stack allocation failure could not be handled.
=> svg_loader: fixing crash for to big buffer

src/loaders/svg/tvgSvgSceneBuilder.cpp
According to the svg standard the clips opacity
doesn't affect the final rendering. In order to
avoid any confusion the opacity values are
overwritten by the max possible value.
sample:
```
<svg viewBox="0 0 100 100">
<g fill-opacity="0">
<clipPath id="myClip">
<circle cx="40" cy="35" r="35" opacity="0" fill-opacity="0.9"/>
<circle cx="70" cy="35" r="15" fill-opacity="0"/>
</clipPath>
</g>
<path d="M10,30 A20,20,0,0,1,50,30 A20,20,0,0,1,90,30 Q90,60,50,90 Q10,60,10,30 Z" clip-path="url(#myClip)" />
</svg>
```
before:
after:
=> svg_loader: overwrite the clip's opacity/alpha

inc/thorvg.h, src/examples/ClipPath.cpp, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/tvgPaint.cpp, src/lib/tvgPaint.h
According to the svg specs clip's fill and opacity should be ignored. Till now setting the alpha/opacity value to zero resulted in the shape's rendering abort.
part of the #1192 issue
=> common: ignoring color/alpha/opacity of a clip object

src/examples/PictureRaw.cpp
it has been changed by 0de3872be33793d2c8db03d5b85da38670410626
=> example: correct clipper usage.

src/loaders/svg/tvgSvgSceneBuilder.cpp
that has been changed by 0de3872be33793d2c8db03d5b85da38670410626
=> svg loader: correct clipper usage.

.github/workflows/actions_cpplint.yml
When we do 1.0 release, we clean up the coding style of all codes.
Currently, there are limitations in our coding style and lint settings.
This results in unnecessary bot comments.
=> infra: Disable cpp lint checker

src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/gl_engine/tvgGlRenderer.h, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.h, src/lib/tvgLoadModule.h, src/lib/tvgPictureImpl.h, src/lib/tvgRender.h, src/loaders/external_jpg/tvgJpgLoader.cpp, src/loaders/external_jpg/tvgJpgLoader.h, src/loaders/external_png/tvgPngLoader.cpp, src/loaders/external_png/tvgPngLoader.h, src/loaders/jpg/tvgJpgLoader.cpp, src/loaders/jpg/tvgJpgLoader.h, src/loaders/png/tvgPngLoader.cpp, src/loaders/png/tvgPngLoader.h, src/loaders/raw/tvgRawLoader.cpp, src/loaders/raw/tvgRawLoader.h
Since the color space is set at the time of specifying the target buffer of the canvas, there is no way to know the color space when the picture is loaded. So, check the color space applied to SwCanvas at the time of reload() and change the color space.
There is an issue of BGR color space support for each loader. The external_jpg loader resets the TJPF color space and calls read() to get a new buffer. In the case of external_png, we need to change the color value directly because it have to start over from begin_read_*.
This solution can affect performance as much as it access again image buffer that have already been `read()` done. However, this only happens once.
issue: https://github.com/Samsung/thorvg/issues/1310
=> loader: Support ABGR colorspace

src/loaders/png/tvgPngLoader.cpp
Set colorspace to ABGR when colortype of lodepng is LCT_RGBA.
Since an image without an alpha channel becomes an ARGB colorspace with LCT_RGB,
it is the same as the default colorspace.
related issue : https://github.com/thorvg/thorvg/issues/1320
=> png_loader(static): Fix the colorspace of an image with an alpha channel

src/lib/tvgPicture.cpp, src/lib/tvgPictureImpl.h, src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoader.h, src/loaders/svg/tvgSvgLoaderCommon.h, src/loaders/svg/tvgSvgSceneBuilder.cpp, src/loaders/svg/tvgSvgSceneBuilder.h
the first approach was made in #1248 but since many changes have been made since then,  a new pr is opened.
this solves #1239 and hopefully https://github.com/godotengine/godot/issues/72478
=> svg_loader: handling svgs without the viewBox attribs

src/loaders/svg/tvgSvgSceneBuilder.cpp
In case the "stroke" attrib is set to "none",
the width of the stroke is set to zero. Thanks
to that it isn't taken into account while
establishing the viewbox boundaries for svgs
without a viewbox and width/height information.
```
<svg>
<linearGradient id="Gradient" x1="0" x2="50%" y1="3" y2="1" gradientUnits="userSpaceOnUse">
<stop offset="0%" stop-color="red" />
<stop offset="50%" stop-color="black" stop-opacity="0" />
<stop offset="100%" stop-color="green" />
<path fill="blue" d="M 0 0 h 400 v 400 z"/>
<path stroke="pink" stroke-width="80" fill="green" d="M -100 400  h 400 v -300 z"/>
<path stroke="none" fill="url(#Gradient)" d="M0 0 L100 0 100 100 0 100 0 0"/>
<path fill="none" stroke="#00ff00" stroke-width="80" d="M0 0 L 100 100"/>
</svg>
```
before:
after:
=> svg_loader: invalid strokes' width set to zero

src/lib/sw_engine/tvgSwRasterTexmap.h
An incorrect check introduced in bf07eb11f25909d2c73aa7e5baeb01a80af384d0 as a solution of the #1327 issue. As a consequence rotated images were not drawn. Fixed.
=> sw_engine: fix safety check

src/loaders/external_jpg/tvgJpgLoader.cpp
When reload is called from tvgPicture, clear() of external_jpg loader is called and 'data' is freed.
In the past, there was no case where reload was called until bitmap() was called after load.
Currently I have to consider reload() for a none-viewbox svg case.
So change the color myself because loader can't call open() again.
=> external_jpg_loader: Fix crash when loader is reloaded

src/loaders/svg/tvgSvgLoader.cpp
Svgs without any viewbox and width/height information have to be loaded before any other action is taken. This is necessary to get the valid sive/viewbox info.
I'd use this instead of #1335 and extra reload() calls added in the picture code
=> svg_loader: forcing file loading completion

src/lib/tvgPicture.cpp, src/lib/tvgPictureImpl.h
After #1338 is applied there is no need to reload
the pictures while aksing about its viewbox or its size.
=> picture: remove unnecessary reloads

src/loaders/svg/tvgSvgSceneBuilder.cpp
For svgs without any viewbox and width/height
information the established width and height
values of the viewbox should be increased
by its initial x and y values - the reason is
that the viewbox starting point is forced to
be (0,0).
=> svg_loader: fixing viewbox width/height

src/examples/ImageScaleDown.cpp, src/examples/ImageScaleUp.cpp
Calling get() on a unique pointer after
it has been moved is the undefined behavior.
=> examples: preventing undef behavior

src/lib/sw_engine/tvgSwStroke.cpp
We have an incorrect value comparison when the stroke corner center is adjusted. All coordinates in the stroke raster have been scaled by the given values (sx, sy), while the stroke width remains at its original size due to it not being clear how it should be scaled.
This brings wierd rendering results at times. Now fix it.
@Issue: https://github.com/thorvg/thorvg/issues/1336
=> sw_engine: fix the inproper stroke raster.

src/lib/tvgAccessor.cpp, src/lib/tvgIteratorAccessor.h, src/lib/tvgSaveModule.h, src/savers/tvg/tvgTvgSaver.cpp, src/wasm/thorvgwasm.cpp
The instantiation of the accessor is unnecessary
as it does not require any internal context.
Simplifying its usage would be beneficial.
=> common: code refactoring for the IteractorAccessor.

src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/tvgTaskScheduler.cpp, src/lib/tvgTaskScheduler.h
Revise the logic to avoid potential blocking of the main thread. Move the clippers job completion to worker-threads to prevent main thread blocks and enhance maximum parallelization efficiency.
=> common taskscheduler: increase thread efficiency.

.github/workflows/actions.yml, .github/workflows/actions_cpplint.yml, .github/workflows/build_win.yml
Node.js 12 actions were deprecated.
Updated the script to use a more recent version.
=> infra github: bump up version

src/lib/tvgCommon.h
Logging tags are marked with the corresponding
log type color, the file and the line information
in gray, and the message content in the default
color.
@Issue: https://github.com/thorvg/thorvg/issues/1351
=> common: enhancement++ of the logging method

src/lib/tvgCommon.h
@issue: https://github.com/thorvg/thorvg/issues/1351
contains #1363 
logs:
errors (these are logs, just force to be printed as errors):
=> common: adding [E]/[L] markers to errors/logs

src/loaders/svg/tvgSvgLoader.cpp
Self-closing tags (empty elements) were parsed until
the appearance of the '>' character, causing the '/'
char to be appended to the tag name. The final '/'
char should be omitted.
sample:
```
<svg
viewBox="0 0 10 10"
xmlns="http://www.w3.org/2000/svg"
xmlns:xlink="http://www.w3.org/1999/xlink">
<defs/>
<defs>
<linearGradient id="myGradient" gradientTransform="rotate(90)">
<stop />
<stop offset="95%" stop-color="red" />
</defs>
<circle cx="5" cy="5" r="4" fill="url('#myGradient')" />
</svg>
```
before:
after:
=> svg_loader: fixing parsing empty tags

src/loaders/svg/tvgSvgSceneBuilder.cpp
If no viewbox is given, vx and vy were set to values
corresponding to the svg's bounding box. This is now
applied only if no viewbox and no width/height information
is given. Otherwise, vx and vy are set to the default
values (0, 0).
@issue: https://github.com/thorvg/thorvg/issues/1368
=> svg_loader: fix vx and vy

src/loaders/svg/tvgSvgSceneBuilder.cpp
In a case where both the clipper and the clippee
are transformed, the final clipper transformation
matrix should be calculated as the multiplication
of both matrices.
@Issue: https://github.com/thorvg/thorvg/issues/1255
KOSZ_893:
before:
after:
=> svg_loader: fixing clipper transformation

test/capi/capiLinearGradient.cpp, test/capi/capiRadialGradient.cpp
Error while comparing a pointer and an integer.
Solved by using a null pointer const instead of
the NULL macro.
@issue: https://github.com/thorvg/thorvg/issues/1382
=> tests: fixing error on windows (mingw-64)

test/capi/capiSwCanvas.cpp
Because of this tests for SwCanvas were
not performed.
=> tests capi: missing header added

src/loaders/svg/tvgSvgUtil.cpp
The word 'infinity' was not read to the end due to the pointer shifting.
=> svg_loader: fixing 'infinity' handling in svgUtilStrtof

src/loaders/svg/tvgSvgLoader.cpp
The gradient was updated before the style,
which resulted in only the URL tag being
inherited, but the gradient itself was not
applied to the node.
sample (modified logo):
```
<svg height="1000" viewBox="0 0 1000 1000" width="1000" xmlns="http://www.w3.org/2000/svg">
<linearGradient id="grad1" gradientTransform="translate(0, 0)" x1="0" y1="0" x2="100%" y2="0">
<stop offset="0%" stop-color="red"/>
<stop offset="100%" stop-color="blue"/>
<g stroke-width="2" stroke="black">
<path d="M-.01986229-.01483051 999.12603.51483051 999.95363 999.91554.07944915 999.94865Z" fill="#fff" stroke-width="3.910218"/><g fill="url(#grad1)"><g stroke-width="3.864492"><path d="M256.61221 100.51736H752.8963V386.99554H256.61221Z"/><path d="M201.875 100.51736H238.366478V386.99554H201.875Z"/><path …
```
=> svg_loader: changed update order

src/bindings/capi/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp
The tvg_gradient_get_identifier and tvg_paint_get_identifier apis have been introduced. They set the newly introduced Tvg_Type_Identifier enum, which indicates the paint and gradient types, respectively.
=> capi: type identifier apis added

src/loaders/svg/tvgSvgPath.cpp
The locale was set while reading the path attr,
which could have caused race conditions between
threads and potentially led to crashes.
Now removed as unnecessary.
@Issue: https://github.com/thorvg/thorvg/issues/1389
=> svg_loader: removing setting the locale

src/lib/tvgCommon.h
Removed 'l.'. It just bothers in reading numbers.
example:
(../../filename.cpp l.231)
(../../filename.cpp 231)
=> common: polished the log message.

src/loaders/svg/tvgSvgLoader.cpp
Gradient was mistakenly overridden in
files in which the <def> section existed,
but grad was defined outside it.
contains #1396 
(results with #1396)
before:
after:
sample:
```
<svg height="400" viewBox="0 0 400 400" width="400" xmlns="http://www.w3.org/2000/svg">
<g fill="url(#grad1)">
<path  d="M0 0 h 200 v 200 z"/>
</g>
<g fill="url(#grad2)">
<path  d="M200 0 h 200 v 200 z"/>
</g>
<linearGradient id="grad1" gradientTransform="translate(0, 0)" x1="0" y1="0" x2="100%" y2="0">
<stop offset="0%" stop-color="red"/>
<stop offset="100%" stop-color="blue"/>
<defs>
<linearGradient id="grad2" gradientTransform="translate(0, 0)" x1="0" y1="0" x2="100%" y2="0">
<stop offset="0%" stop-color="green"/>
<stop offset="100%" stop-color="yellow"/>
</defs>
<g …
```
=> svg_loader: fixing grad overriding 

src/loaders/svg/tvgSvgCssStyle.cpp
While css styling applied one of conditions was
always false. It is now removed and the function
that was called is refactored
=> svg_loader: removed unused code

.github/workflows/regression.yml, .github/workflows/regression_check.sh, .gitignore, test/regression/settings.toml
This is only proof of concept of possible solution to find regressions
Logic of checking for regressions: 
- Compile thorvg from this PR
- Download and compile thorvg from develop branch
- Download and compile regression finder - https://github.com/qarmin/SVG-regression-finder - allow to find differences between png generated by two apps(or same app with two versions)
- Downloads pack with ~1000 SVG files
- Run tests
- Store files that looks different between versions
- Store files that failed to test(crashes/fails to open them etc.)
Regression finder(some of parameters are available to set via config file): 
- Collect svg files to test(removes from list files with filters, text etc.)
- Creates png files from SVG with same resolution
- Removes alpha channel(used algorithms have problems …
=> Poc Regression finder

src/savers/tvg/tvgTvgSaver.cpp
Opening files in text mode on windows can
cause issues. Fixed by changeing the mode
to binary.
@Issue: https://github.com/thorvg/thorvg/issues/957
@Issue: https://github.com/thorvg/thorvg/issues/1380
=> tvg_saver: fixing file opening mode

.gitignore, src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/gl_engine/tvgGlRenderer.h, src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwRaster.cpp, src/lib/sw_engine/tvgSwRasterC.h, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.h, src/lib/tvgLoadModule.h, src/lib/tvgPicture.cpp, src/lib/tvgPictureImpl.h, src/lib/tvgRender.h, src/lib/tvgSwCanvas.cpp, src/loaders/external_jpg/tvgJpgLoader.cpp, src/loaders/external_jpg/tvgJpgLoader.h, src/loaders/external_png/tvgPngLoader.cpp, src/loaders/external_png/tvgPngLoader.h, src/loaders/jpg/tvgJpgLoader.cpp, src/loaders/jpg/tvgJpgLoader.h, src/loaders/png/tvgPngLoader.cpp, src/loaders/png/tvgPngLoader.h, src/loaders/raw/tvgRawLoader.cpp, src/loaders/raw/tvgRawLoader.h
Migrated the color space conversion to the backend engine side. This would increase the chances of performance acceleration (via threading and SIMD), and also remove duplicated conversion logic.
=> Enhance the Colorspace conversion

src/lib/gl_engine/tvgGlRenderer.h, src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwRaster.cpp, src/lib/sw_engine/tvgSwRasterC.h, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/tvgPictureImpl.h, src/lib/tvgRender.h, src/loaders/external_jpg/tvgJpgLoader.cpp, src/loaders/external_png/tvgPngLoader.cpp, src/loaders/jpg/tvgJpgLoader.cpp, src/loaders/png/tvgPngLoader.cpp, src/loaders/raw/tvgRawLoader.cpp
It's not efficient to handle alpha premultiplying in every loader. The backend engine should be responsible for it.
Now, we can remove duplicate code.
=> engine/loaders: Migrate alpha premultiplying to the engine side.

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h, src/loaders/svg/tvgSvgSceneBuilder.cpp
The percentages should refer to the size of the viewbox. This was not the case for not knowing the viewbox before reading the width/height.
@Issue: https://github.com/thorvg/thorvg/issues/1409
=> svg_loader: handling svg width/height in percentages

src/lib/tvgCommon.h
By mistake, stdout was switched to stderr
for logs. Fixed.
=> common: fixing log std stream

src/loaders/svg/tvgSvgLoader.cpp
The conversion to percentages was applied twice.
Additionally, when a viewbox value was provided before the width/height, incorrect scaling occurred.
@Issue: https://github.com/thorvg/thorvg/issues/1414
=> svg_loader: fixing percent. calculations of width/height

src/bin/svg2png/svg2png.cpp
For resolution > 8k image's width and height are changed, but the change was not applied to the image itself. Now fixed.
=> svg2png: changing image size

src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/tvgTaskScheduler.h
There is a report of the thread sanitizer.
It could be a false-positive as far as I reviewed,
but we hate to be bothered by it. So let's revert it.
@Issue: https://github.com/thorvg/thorvg/issues/1409
=> common taskscheduler: revert - 4db25db962c6cdf311012ffb94fc4a67e1d58f24

src/bin/svg2png/svg2png.cpp
The svg width/height values were cast to int,
which could result in cutting off a small part
of the image. Now, in the case of a non-integer
size, it will be rounded up.
@Issue: https://github.com/thorvg/thorvg/issues/1414
=> svg2png: rounding up svg width and height

src/lib/sw_engine/tvgSwRenderer.cpp
The implementation has been reverted by https://github.com/thorvg/thorvg/issues/1409
Since the sanitizer is not matured fully and it's false positive as far as I figured, We revert the scene clipping part.
@Issue: https://github.com/thorvg/thorvg/issues/524
=> sw_engine: fix the broken scene clipping.

src/examples/AnimateMasking.cpp, src/examples/InvMasking.cpp, src/examples/LumaMasking.cpp, src/examples/Masking.cpp, src/examples/Performance.cpp, src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/gl_engine/tvgGlRenderer.h, src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwRaster.cpp, src/lib/sw_engine/tvgSwRasterAvx.h, src/lib/sw_engine/tvgSwRasterC.h, src/lib/sw_engine/tvgSwRasterNeon.h, src/lib/sw_engine/tvgSwRasterTexmap.h, src/lib/sw_engine/tvgSwRasterTexmapInternal.h, src/lib/sw_engine/tvgSwRenderer.cpp, src/lib/sw_engine/tvgSwRenderer.h, src/lib/tvgPaint.cpp, src/lib/tvgPicture.cpp, src/lib/tvgRender.h, src/lib/tvgSceneImpl.h, src/loaders/external_jpg/tvgJpgLoader.cpp, src/loaders/external_png/tvgPngLoader.cpp, src/loaders/jpg/tvgJpgLoader.cpp, src/loaders/png/tvgPngLoader.cpp, src/loaders/raw/tvgRawLoader.cpp
https://github.com/thorvg/thorvg/issues/976
Currently, TVG uses a 4-channel (RGBA) masking buffer. However, it could be optimized by replacing it with a one-byte buffer.
Theoretical, alpha masking memory usage can be reduced by 3x.
Test case: examples/Performance, (single picture, resolution: 800x800)
Memory Usage: 41,012kb -> 39,336kb (-1,676kb)
Rendering Time (on my local machine): 0.0145 -> 0.0143 (-0.0002s)
=> Masking feature optimization

src/lib/sw_engine/tvgSwRasterAvx.h, src/lib/sw_engine/tvgSwRasterNeon.h
the 'buffer' doesn't exist any more in the Surface struct. Replaced by tjhe 'buf32' - error visible
only while avx and neon rendering supported.
=> sw_renderer: fixing names after refactor

src/lib/tvgPictureImpl.h
In the event that malloc returns a nullptr while copying loaded raw data, a Result::NonSupport value is returned. However, it appears that Result::FailedAllocation would be more accurate.
=> common: changed a returned value from load function

src/savers/tvg/tvgTvgSaver.cpp
Similar shapes are merged to improve
performance. This should not be the case
with a semi-transparent fill.
@Issue: https://github.com/thorvg/thorvg/issues/1440
sample:
```
<svg width="100%" height="100%" viewBox="0 0 144 144" version="1.1" >
<path d="M18.341,82.683c0,0 0.264,-3.777 -4.742,-7.114c-5.006,-3.337 -4.303,-11.153 3.249,-13.172c7.553,-2.02 3.513,-10.363 0.615,-11.329c7.026,1.054 8.694,2.898 9.397,6.147c0.702,3.25 0.091,8.386 -7.289,10.714c-5.622,1.773 4.303,5.533 -1.23,14.754Z" style="fill:#c3c3bd;fill-opacity:0.7;"/>
<path d="M20.586,72.784c0,0 -0.626,-2.941 2.942,-6.121c3.567,-3.181 2.148,-9.251 -4.017,-10.002c-6.165,-0.751 -3.913,-7.762 -1.74,-8.843c-5.41,1.608 -6.518,3.244 -6.71,5.878c-0.192,2.633 0.859,6.606 6.922,7.619c4.619,0.771 -2.771,4.829 2.603,11.469Z" …
```
=> tvg_saver: fixing unwanted merging

inc/thorvg.h, src/lib/tvgPaint.cpp, src/lib/tvgPicture.cpp
- Result Paint::bounds(float* x, float* y, float* w, float* h) const noexcept;
- Result Picture::load(const char* data, uint32_t size, bool copy = false) noexcept;
@Issue: https://github.com/thorvg/thorvg/issues/1372
=> api: remove deprecated apis

src/loaders/svg/tvgSvgLoader.cpp
A bug was observed when a 'use' node was
referenced in another 'use' node.
@Issue: https://github.com/thorvg/thorvg/issues/1451
sample:
```
<svg viewBox="0 0 80 20" xmlns="http://www.w3.org/2000/svg">
<use id="a" href="#myDot" x="5" y="5" style="fill:red" />  
<use href="#a" x="20" y="5" style="fill:blue; opacity:0.4" />
<symbol id="myDot" width="10" height="10" viewBox="0 0 2 2">
<circle cx="1" cy="1" r="1" />
</symbol>
</svg>
```
before:
after:
=> svg_loader: copy the use node properties

src/loaders/svg/tvgSvgLoader.cpp
In the case when a 'use' node was used
in a 'defs' block  and the element it
referenced was also defined within the same
'defs' block, the reference node could not
be cloned. This was because the 'defs' node
could not be located.
@Issue: https://github.com/thorvg/thorvg/issues/1451
sample: https://github.com/thorvg/thorvg/issues/1451#issuecomment-1548089583
=> svg_loader: fixing finding defs node

inc/thorvg.h, src/bin/meson.build, src/bin/svg2png/meson.build, src/bin/svg2tvg/meson.build, src/bindings/capi/thorvg_capi.h, src/examples/meson.build, src/meson.build, test/meson.build
Rule of thumb on Windows:
* for a DLL: * if the library is built, set TVG_API to __declspec(dllexport) * if the library is used, set TVG_API to __declspec(dllimport)
* for a static library, set TVG_API to nothing
To set TVG_API for a static library, TVG_STATIC is defined when the stataic library is built. Otherwise, TVG_API is correctly set for a DLL.
Also sun and intel compilers are handled
@issue: https://github.com/thorvg/thorvg/issues/1446
=> portability: fix usage of TVG_API

src/bin/svg2png/meson.build, src/bin/svg2tvg/meson.build
Meson can install stripped versions to
the standards-compliant (or --prefix) location.
I made some ci's to get the static and dynamic svg2xxx binaries:
https://github.com/capnm/thorvg_exp/actions
It seems to work.
```
[47/48] Linking target src/bin/svg2tvg/svg2tvg.exe
[48/48] Linking target src/bin/svg2png/svg2png.exe
Installing src\libthorvg.a to D:\a\thorvg_exp\thorvg_exp/thorvg\lib
Installing src\bin\svg2png\svg2png.exe to D:\a\thorvg_exp\thorvg_exp/thorvg\bin
Stripping target 'src\\bin\\svg2png\\svg2png.exe'.
Installing src\bin\svg2tvg\svg2tvg.exe to D:\a\thorvg_exp\thorvg_exp/thorvg\bin
Stripping target 'src\\bin\\svg2tvg\\svg2tvg.exe'.
```
=> infa: Install svg2png and svg2tvg.

inc/thorvg.h, src/bin/svg2png/svg2png.cpp, src/bindings/capi/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp, src/lib/tvgLoadModule.h, src/lib/tvgPicture.cpp, src/lib/tvgPictureImpl.h, src/loaders/svg/tvgSvgLoader.h, test/capi/capiPicture.cpp, test/testShape.cpp, test/testSwEngine.cpp
BETA -> Official 0.10
- unique_ptr<Picture> Accessor::set(std::unique_ptr<Picture> picture, std::function<bool(const Paint* paint)> func);
- static Accessor::std::unique_ptr<Accessor> gen();
- Result Shape::order(bool strokeFirst);
Modify:
- SwCanvas::Colorspace::ABGR8888_STRAIGHT -> SwCanvas::Colorspace::ABGR8888S
- SwCanvas::Colorspace::ARGB8888_STRAIGHT -> SwCanvas::Colorspace::ARGB8888S
Removal:
- Result Picture::viewbox(float* x, float* y, float* w, float* h) const;
@Issue: https://github.com/thorvg/thorvg/issues/1372
=> API clean up

src/bindings/capi/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp, test/capi/capiShape.cpp
[capi: tvg_shape_set_paint_order introduced](https://github.com/thorvg/thorvg/commit/da7c2498a44becee610cfc4aaf293c08796a6ac6) 
[tests: capi test for tvg_shape_set_paint_order](https://github.com/thorvg/thorvg/commit/ac21accf97844fa57a13fad8cc75f870fb05d2c7)
=> capi order

src/bin/svg2png/svg2png.cpp, src/bin/svg2tvg/svg2tvg.cpp, src/wasm/thorvgwasm.cpp
[clang] Warn on unqualified calls to std::move and std::forward. See: https://reviews.llvm.org/D119670
I have found some others.
=> Fix clang compiler warnings.

src/examples/meson.build
WARNING: You should add the boolean check kwarg to the run_command call.
It currently defaults to false,
but it will default to true in future releases of meson.
See also: https://github.com/mesonbuild/meson/issues/9300
Breaks my CI ...
Regression Testing / test (pull_request) Failing after 9s – that seems to be github issue:
https://github.com/thorvg/thorvg/actions/runs/5037647542/jobs/9034626080?pr=1467#step:3:88
=> infra: Avoid meson warning.

src/lib/sw_engine/tvgSwRasterAvx.h
Hi,
Thorvg does not compile on x64, due to an invalid conversion in tvgSwRasterAvx.h.
The compiler says:
```
./src/lib/sw_engine/tvgSwRasterAvx.h: In function ‘bool avxRasterTranslucentRect(SwSurface*, const SwBBox&, uint8_t, uint8_t, uint8_t, uint8_t)’:
../src/lib/sw_engine/tvgSwRasterAvx.h:97:53: error: invalid conversion from ‘unsigned int’ to ‘uint8_t*’ {aka ‘unsigned char*’} [-fpermissive]
97 |     auto ialpha = 255 - static_cast<uint8_t>(_alpha(color));
|                                                     ^~~~~
|                                                     |
|                                                     unsigned int
../src/lib/sw_engine/tvgSwRaster.cpp:53:39: note:   initializing argument 1 of ‘uint8_t _alpha(uint8_t*)’
53 | static inline uint8_t _alpha(uint8_t* a) …
```
=> Fix invalid conversion error in Avx raster.

src/loaders/jpg/tvgJpgd.cpp
[41/145] Compiling C++ object src/libthorvg.a.p/loaders_jpg_tvgJpgd.cpp.o ../src/loaders/jpg/tvgJpgd.cpp:1339:17: warning: variable 'bytes' set but not used [-Wunused-but-set-variable]
uint32_t c, bytes = 0;
^
../src/loaders/jpg/tvgJpgd.cpp:1773:29: warning: variable 'row_block' set but not used [-Wunused-but-set-variable]
int mcu_row, mcu_block, row_block = 0;
^
../src/loaders/jpg/tvgJpgd.cpp:1876:9: warning: variable 'row_block' set but not used [-Wunused-but-set-variable]
int row_block = 0;
^
3 warnings generated.
=> tvgJpgd.cpp: compiler warnings

test/testAccessor.cpp, test/testFill.cpp, test/testPaint.cpp, test/testPicture.cpp, test/testSavers.cpp, test/testScene.cpp, test/testSwCanvasBase.cpp, test/testSwEngine.cpp
[clang] Warn on unqualified calls to std::move and std::forward See: https://reviews.llvm.org/D119670
```
[141/166] Compiling C++ object test/tvgUnitTests.p/testAccessor.cpp.o ../thorvg-git/test/testAccessor.cpp:58:29: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
picture = accessor->set(move(picture), nullptr);
^
std::
...
```
fgrep -rlZ '(move(' test/ |  xargs -0 sed -i 's/(move(/(std::move(/g' :)
@jsuya perhaps remove the optional alpha values (except two for test) here as well.
=> Fix clang compiler warnings in unit tests.

inc/thorvg.h, src/bindings/capi/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp, src/examples/Blending.cpp, src/examples/Capi.cpp, src/examples/ClipPath.cpp, src/examples/Duplicate.cpp, src/examples/LinearGradient.cpp, src/examples/MultiShapes.cpp, src/examples/Opacity.cpp, src/examples/RadialGradient.cpp, src/examples/Scene.cpp, src/examples/SceneTransform.cpp, src/examples/Stacking.cpp, src/lib/tvgCanvas.cpp, src/lib/tvgCanvasImpl.h, src/lib/tvgScene.cpp, src/lib/tvgSceneImpl.h, src/lib/tvgSwCanvas.cpp, src/loaders/tvg/tvgTvgBinInterpreter.cpp, test/capi/capiScene.cpp, test/capi/capiSwCanvas.cpp, test/testScene.cpp, test/testSwCanvasBase.cpp
These new apis would enable users to dynamically modify the motion scene, The data structure of the paints has been changed from an array to a list.
@APIs:
std::list<Paint*>& Canvas::paints() noexcept;
std::list<Paint*>& Scene::paints() noexcept;
@Deprecated:
Result Canvas::reserve(uint32_t size) noexcept;
Result Scene::reserve(uint32_t size) noexcept;
@Issue: https://github.com/thorvg/thorvg/issues/1203
=> introduce paints() apis that returns the list of paints

inc/thorvg.h, src/examples/AnimateMasking.cpp, src/examples/Async.cpp, src/examples/ClipPath.cpp, src/examples/DirectUpdate.cpp, src/examples/Duplicate.cpp, src/examples/GradientMasking.cpp, src/examples/GradientTransform.cpp, src/examples/InvLumaMasking.cpp, src/examples/InvMasking.cpp, src/examples/LinearGradient.cpp, src/examples/LumaMasking.cpp, src/examples/Masking.cpp, src/examples/MaskingMethods.cpp, src/examples/PicturePng.cpp, src/examples/PictureRaw.cpp, src/examples/PictureWebp.cpp, src/examples/RadialGradient.cpp, src/examples/Shape.cpp, src/examples/Stress.cpp, src/examples/Stroke.cpp, src/examples/StrokeLine.cpp, src/examples/Svg.cpp, src/examples/Svg2.cpp, src/examples/Texmap.cpp, src/examples/Transform.cpp, src/examples/Tvg.cpp, src/examples/Update.cpp, test/testSwCanvasBase.cpp, test/testSwEngine.cpp
Set the default values of rx = 0 and ry = 0 for the shape. 
Only the round rectangle shape requires the usage of these values.
=> api: enhance API usability

src/bindings/capi/tvgCapi.cpp, src/lib/tvgFill.h, src/lib/tvgPaint.cpp, src/lib/tvgPaint.h, src/lib/tvgPictureImpl.h, src/lib/tvgRender.h, src/lib/tvgShapeImpl.h
packing the data fields with the appropriate size.
96 -> 24 (-9 bytes per one paint)
=> common: optimize paint data size.

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwRaster.cpp, src/lib/sw_engine/tvgSwRasterAvx.h, src/lib/sw_engine/tvgSwRasterNeon.h, src/lib/sw_engine/tvgSwRasterTexmap.h
Considering the fundamental scenario,
the masking feature would likely be used less frequently.
We sacrifice a small amount of performance
by substituting the multiple implementations with blender calls.
However, this trade-off can result in a reduction in binary size.
Bin size: 212089 -> 205907 (-6kb)
=> sw_engine: optimize code.

src/examples/Stacking.cpp
use paints() method instead of grabbing a manual list.
@Issue: https://github.com/thorvg/thorvg/issues/1501
=> example stack: updated sample.

src/lib/gl_engine/tvgGlGeometry.cpp
Hi, 
due to the recent change to RenderShape the opengl backend no longer compiles. This commit fixes that. 
Thank you.
Vincenzo
=> Refactoring of GlGeometry::decomposeOutline due to an internal change  in RenderShape data structure.

src/lib/sw_engine/tvgSwCommon.h, src/lib/sw_engine/tvgSwRaster.cpp, src/lib/sw_engine/tvgSwStroke.cpp
[29/73] Compiling C++ object src/libthorvg.a.p/lib_sw_engine_tvgSwStroke.cpp.obj ../src/lib/sw_engine/tvgSwStroke.cpp(258): warning C4244: 'argument': conversion from 'float' to 'int64_t', possible loss of data [32/73] Compiling C++ object src/libthorvg.a.p/lib_sw_engine_tvgSwRaster.cpp.obj ../src/lib/sw_engine/tvgSwRaster.cpp(259): warning C4244: 'initializing': conversion from 'float' to 'uint32_t', possible loss of data ../src/lib/sw_engine/tvgSwRaster.cpp(260): warning C4244: 'initializing': conversion from 'float' to 'uint32_t', possible loss of data
=> sw_engine: fix clang compiler warnings.

src/examples/PictureWebp.cpp
1 warning generated.
[122/183] Compiling C++ object src/examples/PictureWebp.p/PictureWebp.cpp.o ../thorvg-git/src/examples/PictureWebp.cpp:38:18: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
canvas->push(move(bg));
^
std::
../thorvg-git/src/examples/PictureWebp.cpp:53:26: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
if (canvas->push(move(picture)) != tvg::Result::Success) return;
^
std::
../thorvg-git/src/examples/PictureWebp.cpp:77:18: warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]
canvas->push(move(picture));
^
std::
=> examples webp: --compiler warning.

src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgUtil.cpp, src/loaders/svg/tvgSvgUtil.h, src/loaders/svg/tvgXmlParser.cpp
The custom _strndup was used only in one file
as an internal function and wasn't accessible
in other parts of the code. Now function
is available as svgUtilStrndup.
=> svg_loader: custom strndup moved into utils

src/lib/sw_engine/tvgSwRle.cpp, src/lib/sw_engine/tvgSwStroke.cpp
At the construction stage, some stroke points can be skipped if the distance between the points is too narrow.
Previously, this was assumed to be an error case,
but it's clearly intended to remove unnecessary points introduced in a small area of drawing.
This sometimes leads to a flickering issue when super small-sized vector images are drawn.
Now, it's fixed.
=> sw_engine: enforce the drawing of small stroke cubic outlines.

src/loaders/svg/tvgSvgCssStyle.cpp, src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoaderCommon.h
The directive is used to give a specific style property higher priority, ensuring that it overrides other style declarations for the same property.
@Issue: https://github.com/thorvg/thorvg/issues/1255
=> svg_loader: support the '!important' directive

src/loaders/svg/tvgSvgLoader.cpp
In the defs node the style was not updated, hence
the inheritance wasn't applied causing wrong results.
sample:
```
<svg id="svg1" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
<defs>
<mask id="myMaskUS" fill="red" maskContentUnits="userSpaceOnUse" >
<circle cx="50" cy="50" r="30" />
<circle cx="90" cy="30" r="10" />
</mask>
</defs>
<rect x="0" y="-4" width="110" height="50"  fill="red" 
mask="url(#myMaskUS)"/>
</svg>
```
before:
after:
=> svg_loader: update style in defs

src/lib/sw_engine/tvgSwRaster.cpp
it's a regression bug.
@Issue: https://github.com/thorvg/thorvg/issues/1540
=> sw_engine raster: fixed a wrong composition instruction.

src/lib/tvgBinaryDesc.h, src/lib/tvgMath.h, src/lib/tvgShapeImpl.h, src/loaders/tvg/tvgTvgBinInterpreter.cpp, src/savers/tvg/tvgTvgSaver.cpp
tvg binary missed the stroke order,
this patch implements the missing condition.
@Issue: https://github.com/thorvg/thorvg/issues/1499
=> loader tvg: add missing strokeFirst property.

src/lib/sw_engine/tvgSwRasterC.h
[31/75] Compiling C++ object src/thorvg-0.dll.p/lib_sw_engine_tvgSwRaster.cpp.obj D:\Projects\thorvg\src\lib\sw_engine\tvgSwRasterC.h(29): warning C4311: 'type cast': pointer truncation from 'PIXEL_T *' to 'long'
with
[
PIXEL_T=uint8_t
]
../src/lib/sw_engine/tvgSwRaster.cpp(1900): note: see reference to function template instantiation 'void cRasterPixels<uint8_t>(PIXEL_T *,PIXEL_T,uint32_t,int32_t)' being compiled
with
[
PIXEL_T=uint8_t
]
D:\Projects\thorvg\src\lib\sw_engine\tvgSwRasterC.h(29): warning C4302: 'type cast': truncation from 'PIXEL_T *' to 'long'
with
[
PIXEL_T=uint8_t
]
D:\Projects\thorvg\src\lib\sw_engine\tvgSwRasterC.h(29): warning C4311: 'type cast': pointer truncation from 'PIXEL_T *' to 'long'
with
[
PIXEL_T=uint32_t
]
../src/lib/sw_engine/tvgSwRaster.cpp(1911): note: …
=> sw_engine c: fix compile warnings on windows.

inc/thorvg.h, test/testPaint.cpp
The 'transformed' arg of the 'bounds' api
wasn't tested. Added.
=> tests: bounds test ++

src/loaders/lottie/tvgLottieLoader.cpp, src/loaders/svg/tvgSvgLoader.cpp
The math.h was included before the _USE_MATH_DEFINES was defined causing an error while MinGw was used.
=> lottie_loader: fixing error with math consts

src/loaders/external_webp/meson.build
While building on windows (MinGW) no 'libwebp' was found, which resulted in build errors. The building process should have been stopped earlier for clarity.
=> webp_loader: libwebp set to be a required depend

meson_options.txt, src/bindings/capi/meson.build, src/bindings/meson.build, src/meson.build
The thorvg lib should not have a dependency on the bindings. In fact, it's inverted.
=> infra build: revise the binding builds.

src/utils/tvgStr.cpp
the compiler would remove the code if nowhere uses the internal functions.
=> utils str: remove unencessary definitions.

src/bindings/wasm/tvgWasm.cpp
clear the buffer memory properly when a canvas size is changed.
=> binding wasm: fix a memory leak.

src/lib/tvgCanvasImpl.h, src/lib/tvgPaint.h, src/lib/tvgPictureImpl.h, src/lib/tvgSceneImpl.h, src/lib/tvgShapeImpl.h
Pictures can be shared with Animation instances.
The condition can now be distinguished by checking the `dispose()` return value.
=> common: deleted paints only when they are no longer valid.

src/lib/gl_engine/tvgGlGeometry.h
This PR add a new method to get 4x4 matrix directly from exsited 3x3 matrix in column major order.
This is also a basic math calculations required by #1531
=> common: add new method to get mat4x4 directly from mat3x3

src/examples/Common.h, src/lib/gl_engine/meson.build, src/lib/gl_engine/tvgGlCommon.h
This PR changes the min gl version used inside GL Engine
Since most device supported morden gl (GLES 3.0 for mobile GPU, GL 3.3 for desktop GPU)
And I plan to use some advance and convenient API like [VAO](https://www.khronos.org/opengl/wiki/Vertex_Specification#Vertex_Array_Object) and [UBO](https://www.khronos.org/opengl/wiki/Uniform_Buffer_Object)
So I changed the example code to create a GLES3.x context with EFL. And the header file included inside GL Engine.
And the rest code in #1531 rely on this.
=> gl_engine: upgrade min gl version

src/lib/gl_engine/tvgGlGeometry.cpp, src/lib/gl_engine/tvgGlGeometry.h, src/lib/gl_engine/tvgGlGpuBuffer.h
This PR use [Vertex Array Object](https://www.khronos.org/opengl/wiki/Vertex_Specification#Vertex_Array_Object) and `Element Array Buffer`  in GlGeometry 
VAO is new object in modern GL API, which can split and manage vertex buffer and attribute state. This is optional in GLES and is mandatory in GL.
Also index buffer is faster then pass cpu data in GL draw call, and must be used with a valid `Vertex Array Object`
=> gl_engine: use vertex array and index buffer when render primitive

src/loaders/png/tvgLodePng.cpp, src/loaders/png/tvgPngLoader.cpp
We have a base color space conversion in the renderer, so there's no need to forcefully align with BGRA.
=> loader/png: revert force colorspace conversion.

src/loaders/lottie/tvgLottieParser.cpp
Image padding size should be increased by 1 for '\0'."
=> loader\lottie: Fixed incorrect b64 decoding

src/lib/gl_engine/tvgGlRenderTask.cpp, src/lib/gl_engine/tvgGlRenderTask.h, src/lib/gl_engine/tvgGlShader.cpp, src/lib/gl_engine/tvgGlShaderSrc.cpp
This PR upgrade the used glsl version in GL shader source.
With the modern syntax:
1.  the attribute location can be specified directly in shader.
2. can use uniform block and uniform buffer to send many uniform data with single gl function call which is used in #1531
=> gl_engine: use modern glsl syntax in shader source

src/loaders/svg/tvgSvgSceneBuilder.cpp
Up until now, loading a clip composed of multiple
shapes worked correctly provided that they did not
undergo separate transformations. Now, such a case
has been handled.
Also the 'use' node inside the clip is supported.
this pr is a response to the [comment](https://github.com/thorvg/thorvg/pull/985#discussion_r746232286)
sample:
```
<svg id="svg1" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
<clipPath id="clip">
<circle cx="30" cy="50" r="30" transform="matrix(1 0.44 1 1 0 10)"/>
<circle cx="40" cy="60" r="10" transform="matrix(1 0.4 0 1 30 -50)"/>
</clipPath>
<rect x="20" y="20" width="60" height="60" fill="blue" fill-opacity="0.2"/>
<rect x="0" y="0" width="100" height="100"  fill="red" clip-path="url(#clip)"
fill-opacity="0.5"/>
<circle cx="30" cy="50" r="30" …
```
=> svg_loader: clip composed of multiple transformed shapes

src/lib/gl_engine/tvgGlGeometry.cpp, src/lib/gl_engine/tvgGlGeometry.h, src/lib/gl_engine/tvgGlRenderTask.cpp, src/lib/gl_engine/tvgGlRenderTask.h, src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/gl_engine/tvgGlShaderSrc.cpp
This PR doing the following things:
1. convert mat4 directly from exist mat3, and remove unused calculation code.
2. since normalized position is only meaningful in vertex shader stage. Change to use logical position in fragment shader stage for all gradient pipeline.
=> gl_engine: refactor matrix calculation

src/loaders/lottie/tvgLottieLoader.cpp
Loading a png file without giving a mimetype, resulted in an error from the lottie loader.
=> lottie_loader: return false for frameRate = 0

src/lib/gl_engine/tvgGlGpuBuffer.cpp
`GL_INVALID_VALUE` is generate during `glGenBuffers` and is checked by calling `glGetError()` inside `GL_CHECK` macro.
While the buffer id is valid if the value is not zero.
=> gl_engine: Fix mistake in glbuffer id check

src/lib/tvgShapeImpl.h
In the case of a gradient stroke and a valid
fill, the composition wasn't applied correctly,
resulting in an unexpected overlap between
the fill and stroke.
@Issue: https://github.com/thorvg/thorvg/issues/445
sample:
```
tvg::Fill::ColorStop colorStops2[2];
colorStops2[0] = {0, 255, 0, 0, 255};
colorStops2[1] = {1, 0, 0, 255, 255};
auto fillStroke = tvg::RadialGradient::gen();
fillStroke->radial(250, 250, 400);
fillStroke->colorStops(colorStops2, 2);
shape1->appendRect(100, 100, 400, 400);
shape1->fill(0, 255, 0, 255);
shape1->stroke(150);
shape1->stroke(std::move(fillStroke));
shape1->opacity(155);
canvas->push(std::move(shape1));
```
before:
after:
=> common: shape's composition fixed

AUTHORS, src/lib/gl_engine/meson.build, src/lib/gl_engine/tvgGlGeometry.cpp, src/lib/gl_engine/tvgGlGeometry.h, src/lib/gl_engine/tvgGlRenderer.cpp, src/lib/gl_engine/tvgGlRenderer.h, src/lib/gl_engine/tvgGlTessellator.cpp, src/lib/gl_engine/tvgGlTessellator.h, src/utils/meson.build, src/utils/tvgList.h
This PR change changed the tessellate function in GlGeometry to use the new algroithm to break polygon into triangles. 
The algorithm is based on my previouse PR #1342 . It can handle [Concave Polygon](https://en.wikipedia.org/wiki/Concave_polygon) and [Even-odd](https://en.wikipedia.org/wiki/Even%E2%80%93odd_rule) fill rule.
| FillRule | Tiger SVG | Custom Transform |
| -------- | ---------| -------------------|
|<img src="https://github.com/thorvg/thorvg/assets/26308154/c4ac4d95-b8c3-4600-9319-0f0c86114b6f" width=200 />|<img src="https://github.com/thorvg/thorvg/assets/26308154/029c2c2d-7a5a-4406-b8b7-b2a77a58e30a" width=200 /> | <img src="https://github.com/thorvg/thorvg/assets/26308154/76671429-6ba1-468e-b030-07a2ea8e07e8" width=200 /> | 
> * This is a big patch, I tried to split the …
=> gl_engine: Use advance tessellate algorithm

src/renderer/tvgCommon.h
Godot CI:
Error: (thirdparty/thorvg/)src/renderer/tvgPaint.h:85:80: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
85 |             if (refCnt == 255) TVGERR("RENDERER", "Corrupted reference count!");
...
Hi @hermet I quickly tested the current ThorVG main + Godot. This broke the Godot CI, but the change  breaks here
the Lottie parser, so I think it would be better to insert the braces around the LOG macros everywhere...
https://github.com/capnm/godot4/commits/update_thorvg_main
++ I get now
`WARNING: ThreadSanitizer: data race`. Could you take a look if it's a ThorVG issue?
-> https://github.com/capnm/godot4/actions/runs/6004479786/job/16285182152
```
#0 std::vector<std::thread, std::allocator<std::thread> >::size() const …
```
=> THORVG_LOG: --compiler -Werror=empty-body

src/renderer/gl_engine/tvgGlGeometry.cpp, src/renderer/gl_engine/tvgGlGeometry.h, src/renderer/gl_engine/tvgGlGpuBuffer.cpp, src/renderer/gl_engine/tvgGlGpuBuffer.h, src/renderer/gl_engine/tvgGlRenderer.cpp, src/renderer/gl_engine/tvgGlRenderer.h
This PR changed GPU buffer management and pack all data into one gpu buffer to avoid memory fragmentation in GPU.
Some reference:
[Best Practices for Video Memory Management](https://docs.nvidia.com/drive/drive_os_5.1.6.1L/nvvib_docs/index.html#page/DRIVE_OS_Linux_SDK_Development_Guide/Graphics/graphics_opengl.html#wwpID0EXHA)
=> gl_engine: pack all data into one gpu buffer

src/renderer/sw_engine/tvgSwRenderer.cpp
zero scale would not produce any visible artifacts. we can skip the further processing sonner.
=> sw_engine: skip the rendering if possible.

src/renderer/gl_engine/tvgGlGeometry.h, src/renderer/gl_engine/tvgGlGpuBuffer.h, src/renderer/gl_engine/tvgGlTessellator.h
Fix the following error during gl_engine compile
```
In file included from ../src/renderer/gl_engine/tvgGlGpuBuffer.h:28,
from ../src/renderer/gl_engine/tvgGlGeometry.cpp:24:
../src/common/tvgArray.h: In instantiation of ‘tvg::Array<T>::~Array() [with T = tvg::PathCommand]’:
../src/renderer/tvgRender.h:161:5:   required from here
../src/common/tvgArray.h:154:13: error: ‘free’ was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
154 |         free(data);
|         ~~~~^~~~~~
```
=> gl_engine: fix compilation erros due to redundant header inclusion

src/renderer/sw_engine/tvgSwShape.cpp, src/renderer/sw_engine/tvgSwStroke.cpp
While it may represent a dot with a stroke width,
ignoring its length is not a good idea.
this also eliminates 0 size dash dots caused by unexpected empty lengths.
=> sw_engine: Do not handle exceptions for zero line length.

src/loaders/lottie/tvgLottieBuilder.cpp, src/loaders/svg/tvgSvgSceneBuilder.cpp, src/renderer/tvgTaskScheduler.cpp, src/renderer/tvgTaskScheduler.h
This fix introduces a workaround to enforce synchronous tasking on worker threads. Sometimes, out of threads get stuck in a deadlock condition.
@Issue: https://github.com/thorvg/thorvg/issues/1636
=> taskschduler: fix a regression deadlock issue

src/renderer/sw_engine/tvgSwRaster.cpp, src/renderer/sw_engine/tvgSwRasterTexmap.h
The 8-bit masking target is the destination with a 32-bit source image and 8-bit composition.
=> sw_engine: properly implemented the missing image composition.

src/renderer/sw_engine/tvgSwRenderer.cpp, wasm_cross.txt
the surface and mesh data can be missed by an invalid condition. this fixes an invalid memory access problem.
Issue: https://github.com/thorvg/thorvg/issues/1671
=> sw_engine: fix an invalid memory access.

src/renderer/sw_engine/tvgSwRaster.cpp
The color conversion is supposed to take into account the differences between straight alpha premultiplied color and pre-multiplied alpha color.
The previous logic does not perfectly cover these conditions.
The problem was occured in the thorvg viewer with a jpeg bgra format.
=> sw_engine: Correct the color conversion condition.

src/renderer/sw_engine/tvgSwCommon.h, src/renderer/sw_engine/tvgSwShape.cpp, src/renderer/sw_engine/tvgSwStroke.cpp
Previously, the engine didn't properly cover the dash line corner styles because it considered a new line to start at the corner.
This update modifies the logic to recognize curved lines as a single line, including the corners.
There may still be some quality issues,
but it's an improvement over the previous version.
@Issue: https://github.com/thorvg/thorvg/issues/121
=> sw_engine/stroke: Enhance the quality of the dash line corners.

src/loaders/svg/tvgSvgSceneBuilder.cpp
Fixes #1694
@hermet Quick fix, checked only the examples in the issue.
=> loader/svg: Fix maskContentUnits userSpaceOnUse/objectBoundingBox

src/renderer/gl_engine/tvgGlGeometry.cpp, src/renderer/gl_engine/tvgGlGeometry.h, src/renderer/gl_engine/tvgGlRenderTask.cpp, src/renderer/gl_engine/tvgGlRenderTask.h, src/renderer/gl_engine/tvgGlRenderer.cpp, src/renderer/gl_engine/tvgGlRenderer.h
This PR add scissor box info in GLRenderTask, and enable `GL_SCISSOR_TEST` during rendering to support the fast path clip (Rect Clip)
The reason we choose glScissor instead of glViewport is that if drawCall is outside the viewport it is still executed in the gpu but can be discared by GL_SCISSOR_TEST
=> gl_engine: use glScissor to support fast clip

inc/thorvg.h, meson.build, meson_options.txt, src/renderer/meson.build, src/renderer/tvgInitializer.cpp, src/renderer/tvgWgCanvas.cpp, src/renderer/wg_engine/meson.build, src/renderer/wg_engine/tvgWgRenderer.cpp, src/renderer/wg_engine/tvgWgRenderer.h
Issue: https://github.com/thorvg/thorvg/issues/1479
WebGPU is a Render Hardware Interface built on top of the various APIs provided by the driver/OS depending on your platform. WebGPU exposes an API for performing operations, such as rendering and computation, on a Graphics Processing Unit.
WebGPU official documentation:
https://www.w3.org/TR/webgpu/
The new engine type introduced:
`tvg::CanvasEngine::Wg`
The new canvas type introduced:
`tvg::WgCanvas`
Usage example:
// init glfw
glfwInit();
// create a windowed mode window and its opengl context
glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);
GLFWwindow* window = glfwCreateWindow(800, 800, "WebGPU base app", nullptr, nullptr);
// get window size
int width{}, height{};
glfwGetWindowSize(window, &width, &height);
// init engine webgpu …
=> wg_engine: introduce webgpu canvas

src/loaders/jpg/tvgJpgd.cpp
Fixes #1705
Hello @hermet, I found the culprit. Could you please take a look?
Reverts e3a21e39a0211f2, this should be just `pSrc[0]*4` and keep the negative values. Thanks!
=> loader/jpg: Fix a regression bug.

src/renderer/tvgInitializer.cpp
Initialize both renderers to allow `init(SW | GL);`
refer to https://github.com/thorvg/thorvg/pull/1690#issuecomment-1759634391
=> renderer/initializer: Support for initializing SW and GL engines together

src/bindings/capi/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp
[issues 1710: CAPI](https://github.com/thorvg/thorvg/issues/1710) Missing blend functions in capi bindings
Introduced setter and getter for composite methods of the paint object:
`TVG_API Tvg_Result tvg_paint_set_composite_method(Tvg_Paint* paint, Tvg_Paint* target, Tvg_Composite_Method method);`
`TVG_API Tvg_Result tvg_paint_get_composite_method(const Tvg_Paint* paint, const Tvg_Paint** target, Tvg_Composite_Method* method);`
=> capi: introduce missing blend functions in capi bindings

src/renderer/gl_engine/tvgGlRenderPass.cpp
../src/renderer/gl_engine/tvgGlRenderPass.cpp:37:29: warning: macro expands to multiple statements [-Wmultistatement-macros]
37 |     if (mColorTex) GL_CHECK(glDeleteTextures(1, &mColorTex));
=> gl_engine: fix a compiler warning.

src/renderer/sw_engine/tvgSwRasterC.h
alpha value has been missed by mistake,
a regression by c50d2fd
Issue: https://github.com/thorvg/thorvg/issues/1716
=> sw_engine raster: fixed a default alpha blending bug.

src/renderer/tvgWgCanvas.cpp, src/renderer/wg_engine/meson.build, src/renderer/wg_engine/tvgWgCommon.h, src/renderer/wg_engine/tvgWgPipelineBase.cpp, src/renderer/wg_engine/tvgWgPipelineBase.h, src/renderer/wg_engine/tvgWgPipelineEmpty.cpp, src/renderer/wg_engine/tvgWgPipelineEmpty.h, src/renderer/wg_engine/tvgWgPipelineSolid.cpp, src/renderer/wg_engine/tvgWgPipelineSolid.h, src/renderer/wg_engine/tvgWgRenderData.cpp, src/renderer/wg_engine/tvgWgRenderData.h, src/renderer/wg_engine/tvgWgRenderer.cpp, src/renderer/wg_engine/tvgWgRenderer.h, src/renderer/wg_engine/tvgWgShaderSrc.cpp, src/renderer/wg_engine/tvgWgShaderSrc.h
[issues 1479: Shape](https://github.com/thorvg/thorvg/issues/1479)
In order to build you need third party libraries. Before you start please read this: [LearnWebGPU](https://eliemichel.github.io/LearnWebGPU/getting-started/hello-webgpu.html)
Usage example:
// init glfw
glfwInit();
// create a windowed mode window and its opengl context
glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);
GLFWwindow* window = glfwCreateWindow(800, 800, "WebGPU base app", nullptr, nullptr);
// get window size
int width{}, height{};
glfwGetWindowSize(window, &width, &height);
// init engine webgpu
tvg::Initializer::init(tvg::CanvasEngine::Wg, 0);
// create wg canvas
auto canvasWg = tvg::WgCanvas::gen();
canvas_wg->target(glfwGetWin32Window(window), width, height);
// prepare a shape (Rectangle + Rectangle + Circle …
=> wg_engine: introduce ability to draw multiple solid color filled shapes.

src/renderer/sw_engine/tvgSwRaster.cpp
Unified common logic for scaled image raster operations, Avoid on-spot pixel computation as possible.
Tested on local machine (single thread)
Lottie: 0.057s -> 0.053s (-0.004s)
=> sw_engine/raster: optimized the scaled image rasterization

inc/thorvg.h, src/bindings/capi/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp, src/bindings/wasm/tvgWasm.cpp, src/examples/Animation.cpp, src/examples/Capi.cpp, src/examples/Lottie.cpp, src/loaders/lottie/tvgLottieBuilder.cpp, src/loaders/lottie/tvgLottieBuilder.h, src/loaders/lottie/tvgLottieLoader.cpp, src/loaders/lottie/tvgLottieLoader.h, src/loaders/lottie/tvgLottieModel.cpp, src/loaders/lottie/tvgLottieModel.h, src/loaders/lottie/tvgLottieParser.cpp, src/loaders/lottie/tvgLottieProperty.h, src/renderer/tvgAnimation.cpp, src/renderer/tvgFrameModule.h, test/capi/capiAnimation.cpp, test/testAnimation.cpp
replace the frame count unit from the int32_t to float since animations could smoothly interpolate key-frames.
This notificably improve the animation smoothness in Lottie
Beta API changes:
Result Animation::frame(uint32_t no) -> Result Animation::frame(float no) 
uint32_t Animation::curFrame() const -> float Animation::curFrame() const 
uint32_t Animation::totalFrame() const -> float Animation::totalFrame() const
=> animation/lottie: updated the frame count unit.

src/renderer/tvgPaint.cpp, src/renderer/tvgPaint.h, src/renderer/tvgPicture.cpp, src/renderer/tvgRender.cpp, src/renderer/tvgRender.h, src/renderer/tvgScene.cpp, src/renderer/tvgScene.h, src/renderer/tvgShape.cpp
Get rid of the polymorphism function table,
use the switch directly instead.
We profiled, both binary & performance is better than before.
Tested on a local machine (single thread):
- Lottie: 2ms improved
- Binary: -0.5kb
=> renderer: revise the internal paints structure.

inc/thorvg.h, src/bindings/capi/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp, src/examples/Capi.cpp, src/loaders/lottie/tvgLottieBuilder.cpp, src/loaders/svg/tvgSvgSceneBuilder.cpp, src/renderer/tvgShape.cpp, src/savers/tvg/tvgTvgSaver.cpp, test/capi/capiShape.cpp, test/testShape.cpp
This change just allows users to use the offset of the stroke dash. Actually feature enhacement has been introduced by 478e45f9f3d330aea65e839b58ba05f4be3a02a8.
@APIs:
uint32_t Shape::strokeDash(const float** dashPattern) -> uint32_t Shape::strokeDash(const float** dashPattern, float* offset = nullptr)
Result Shape::strokeDash(const float* dashPattern, uint32_t cnt) -> Result Shape::strokeDash(const float* dashPattern, uint32_t cnt, float offset = 0.0f)
Tvg_Result tvg_shape_set_stroke_dash(Tvg_Paint* paint, const float* dashPattern, uint32_t cnt) -> Tvg_Result tvg_shape_set_stroke_dash(Tvg_Paint* paint, const float* dashPattern, uint32_t cnt, float offset)
Tvg_Result tvg_shape_get_stroke_dash(const Tvg_Paint* paint, const float** dashPattern, uint32_t* cnt) -> Tvg_Result …
=> common: stroke dash offset support with new apis.

inc/thorvg.h, src/bindings/wasm/tvgWasm.cpp
The Animation::frame() method has been modified.
It will now return InsufficientCondition,
if the frame value is the same as the previous one.
In addition to this change, we have also updated its usage accordingly.
=> wasm: fix a regression bug.

src/renderer/tvgScene.h, src/renderer/tvgShape.h
these member values can be accesssed without update() call.
=> renderer/scene: ++safety

src/examples/all.sh
We can now call `examples/all.sh` on the mac os.
Added condition to detect OS and it replaces find command so the mac doesn't cause error.
=> examples: Support mac os to execute all

src/loaders/external_png/tvgPngLoader.cpp
../src/loaders/external_png/tvgPngLoader.cpp(110): warning C4244: '=': conversion from 'float' to 'uint32_t', possible loss of data
../src/loaders/external_png/tvgPngLoader.cpp(111): warning C4244: '=': conversion from 'float' to 'uint32_t', possible loss of data
../src/loaders/external_png/tvgPngLoader.cpp(112): warning C4244: '=': conversion from 'float' to 'uint32_t', possible loss of data
=> loaders/png: fixed data conversion warnings on Windows

src/renderer/gl_engine/tvgGlGpuBuffer.cpp, src/renderer/gl_engine/tvgGlGpuBuffer.h
This PR fix a potential memory out of bounds error in GLGpuBuffer
If buffer data is larger than memory alignment, need to make sure there is enough memory in current stage buffer
=> gl_engine: fix memory out of bounds error in GlGpuBuffer

docs/Doxyfile, inc/thorvg.h, src/bindings/capi/thorvg_capi.h
Fixed all warnings on building doxygen, wrong annotations are replaced from both `thorvg.h` and `thorvg_capi.h`.
Also I found unnecessary configs from `Doxyfile` and I commented it out.
@issue: #1754 
now it's clean without any warnings!
=> docs: Remove all warnings from doxygen

src/loaders/lottie/tvgLottieLoader.cpp, src/savers/gif/gif.h, src/savers/gif/tvgGifSaver.cpp
this fixes the memory sanitizer report:
../src/savers/gif/gif.h:315:31: runtime error: index 255 out of bounds for type 'unsigned char [255]'
../src/savers/gif/gif.h:113:54: runtime error: index 255 out of bounds for type 'unsigned char [255]'
Issue: https://github.com/thorvg/thorvg/issues/1758
=> saver/gif: stabilizing++

inc/thorvg.h, src/bindings/capi/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp, src/examples/Blending.cpp, src/examples/Duplicate.cpp, src/examples/InvLumaMasking.cpp, src/examples/InvMasking.cpp, src/examples/LumaMasking.cpp, src/examples/Masking.cpp, src/examples/MaskingMethods.cpp, src/examples/PictureRaw.cpp, src/examples/Texmap.cpp, src/examples/TvgSaver.cpp, src/loaders/raw/tvgRawLoader.cpp, src/loaders/raw/tvgRawLoader.h, src/loaders/tvg/tvgTvgBinInterpreter.cpp, src/renderer/tvgLoadModule.h, src/renderer/tvgLoader.cpp, src/renderer/tvgLoader.h, src/renderer/tvgPicture.cpp, src/renderer/tvgPicture.h, test/capi/capiPicture.cpp, test/testPicture.cpp, test/testSavers.cpp, test/testSwEngine.cpp
[issues 1479: picture raw loader to support premultiplied](https://github.com/thorvg/thorvg/issues/1764)
api changes:
Result Picture::load(uint32_t* data, uint32_t w, uint32_t h, bool copy);
Result Picture::load(uint32_t* data, uint32_t w, uint32_t h, bool premultiplied, bool copy);
capi changes
TVG_API Tvg_Result tvg_picture_load_raw(Tvg_Paint* paint, uint32_t *data, uint32_t w, uint32_t h, bool copy);
TVG_API Tvg_Result tvg_picture_load_raw(Tvg_Paint* paint, uint32_t *data, uint32_t w, uint32_t h, bool premultiplied, bool copy);
=> picture: added ability to support premultiplied for picture raw loader

src/loaders/lottie/tvgLottieLoader.cpp
The animation couldn't be triggered on a single thread. Regression bug introduced by 29b5bc372de91cc9ef62b02d6c3117a4e24a7ff0
=> lottie/builder: Fix a broken animation

.github/workflows/build_macos.yml
Github action recently hits an error, it's about meson downloading bug via brew. Meson has a dependency `python` and python installation is failed randomly with this log.
So I added few commands before downloading meson.
```sh
find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete
sudo rm -rf /Library/Frameworks/Python.framework/
brew install --force python3 && brew unlink python3 && brew unlink python3 && brew link --overwrite python3
```
It prevents python installation bug due to duplicated sym link.
=> infra: fix macos build crash

src/loaders/lottie/tvgLottieParser.cpp
Currently, it assumes "ty":"gr" for the related shapes children, which can be skipped since the children will be in the "it" scope.
Some Lottie data is missing the "ty":"gr" field,
and ThorVG couldn't display the content properly.
It can ignore it with the context understanding.
=> lottie/parser: Fix the shapes parsing logic.

src/renderer/wg_engine/tvgWgPipelineImage.cpp, src/renderer/wg_engine/tvgWgPipelineImage.h, src/renderer/wg_engine/tvgWgRenderData.cpp, src/renderer/wg_engine/tvgWgRenderData.h, src/renderer/wg_engine/tvgWgRenderer.cpp, src/renderer/wg_engine/tvgWgRenderer.h, src/renderer/wg_engine/tvgWgShaderSrc.cpp
[issues 1479: pictures](https://github.com/thorvg/thorvg/issues/1479)
Exampe of usage:
```
auto picture = tvg::Picture::gen();
picture->load("images/test.png");
picture->translate(0, 0);
picture->size(100, 100);
picture->opacity(255);
canvas->push(std::move(picture));
```
=> wg_engine: introduced images drawing support for webgpu renderer

src/examples/Blending.cpp, src/examples/Duplicate.cpp, src/examples/InvLumaMasking.cpp, src/examples/InvMasking.cpp, src/examples/LumaMasking.cpp, src/examples/Masking.cpp, src/examples/MaskingMethods.cpp, src/examples/PictureJpg.cpp, src/examples/PicturePng.cpp, src/examples/PictureRaw.cpp, src/examples/PictureWebp.cpp, src/examples/Texmap.cpp, src/examples/TvgSaver.cpp
Loading of binary data operations must be performed in binary mode rather than text. 
The issue appears on windows platform, especially for PNG loading
=> examples: fixed manual loading of binary data (jpg, png, raw ect)

src/renderer/sw_engine/tvgSwRenderer.cpp, src/savers/gif/tvgGifSaver.cpp
Basic shapes were trimmed entirely when they were outside of the canvas, even if they had a big enough stroke to be partially on the canvas.
This fixes the issue.
Issue: https://github.com/thorvg/thorvg/issues/1785
=> sw_engine: fixed a bug where strokes were not showing.

src/loaders/lottie/tvgLottieBuilder.cpp
There is a buggy workaround code that rewinds the stroke scaling.
Issue: https://github.com/thorvg/thorvg/issues/1730
=> lottie/builder: hotfix, invalid stroking scaling.

src/loaders/lottie/tvgLottieBuilder.cpp, src/loaders/lottie/tvgLottieModel.cpp, src/loaders/lottie/tvgLottieModel.h
There are some matting masking bugs observed,
Reverted the commit. We will revisit it later.
commit https://github.com/thorvg/thorvg/commit/d37c5002623a44d0d16581f6cbeee91c928fb535
Author: Hermet Park <hermet@lottiefiles.com>
Date:   Wed Oct 25 18:55:05 2023 +0900
lottie: introduced static layer cache.
lottie builder doesn't need to rebuild the layer object
if it has no any animation frame data.
That case, we can cache the layer scene in order to reuse it.
Tested on local machine (single thread):
- Lottie: appx. 2ms enhanced.
- Binary: +204
=> Lottie/builder: Fix a regression bug related to matte masking.

src/loaders/lottie/tvgLottieBuilder.cpp
There was likely a mistake in the rotation value set; there was no reason to multiply it by 2.
Issue: https://github.com/thorvg/thorvg/issues/1773
=> lottie/builder: corrected polystar rotation.

inc/thorvg.h, src/bindings/capi/thorvg_capi.h, src/bindings/capi/tvgCapi.cpp, src/loaders/external_jpg/tvgJpgLoader.cpp, src/loaders/external_jpg/tvgJpgLoader.h, src/loaders/external_png/tvgPngLoader.cpp, src/loaders/external_png/tvgPngLoader.h, src/loaders/external_webp/tvgWebpLoader.cpp, src/loaders/external_webp/tvgWebpLoader.h, src/loaders/jpg/tvgJpgLoader.cpp, src/loaders/jpg/tvgJpgLoader.h, src/loaders/lottie/tvgLottieLoader.cpp, src/loaders/lottie/tvgLottieLoader.h, src/loaders/lottie/tvgLottieParser.cpp, src/loaders/png/tvgPngLoader.cpp, src/loaders/png/tvgPngLoader.h, src/loaders/svg/tvgSvgLoader.cpp, src/loaders/svg/tvgSvgLoader.h, src/loaders/tvg/tvgTvgLoader.cpp, src/loaders/tvg/tvgTvgLoader.h, src/renderer/tvgLoadModule.h, src/renderer/tvgLoader.cpp, src/renderer/tvgLoader.h, src/renderer/tvgPicture.cpp, src/renderer/tvgPicture.h
tvgLottie wasn't able to load external image when loading through memory (not file), added new parameter `resourcePath`(optional, default = `""`).
API:
Result Picture::load(const char* data, uint32_t size, const string& mimeType, bool copy)
-> Result Picture::load(const char* data, uint32_t size, const string& mimeType, bool copy, const string& resourcePath)
New parameter:
- `resourcePath`: absolute directory path where resource directory is included.
Example:
Animation and asset directory are located in `/home/anims` and lottie has assets like
```json
"assets": [
{
"id": "image_0",
"w": 200,
"h": 300,
"u": "images/",
"p": "img_0.png",
"e": 0
}
]
```
The parameter `resourcePath` should be `/home/anims` then tvgLottieLoader will load external image `/home/anims/images/img_0.png`
Usage: …
=> lottie/loader: Support external image with memory animation

src/common/tvgInlist.h, src/loaders/external_jpg/tvgJpgLoader.cpp, src/loaders/external_jpg/tvgJpgLoader.h, src/loaders/external_png/tvgPngLoader.cpp, src/loaders/external_png/tvgPngLoader.h, src/loaders/external_webp/tvgWebpLoader.cpp, src/loaders/external_webp/tvgWebpLoader.h, src/loaders/jpg/tvgJpgLoader.cpp, src/loaders/jpg/tvgJpgLoader.h, src/loaders/lottie/tvgLottieLoader.cpp, src/loaders/lottie/tvgLottieLoader.h, src/loaders/png/tvgPngLoader.cpp, src/loaders/png/tvgPngLoader.h, src/loaders/raw/tvgRawLoader.cpp, src/loaders/raw/tvgRawLoader.h, src/loaders/svg/tvgSvgLoader.cpp, src/loaders/tvg/tvgTvgLoader.cpp, src/loaders/tvg/tvgTvgLoader.h, src/renderer/tvgAnimation.cpp, src/renderer/tvgFrameModule.h, src/renderer/tvgLoadModule.h, src/renderer/tvgLoader.cpp, src/renderer/tvgLoader.h, src/renderer/tvgPicture.cpp, src/renderer/tvgPicture.h
The loader cache is applied to conserve memory.
If the input data is already present in loaders,
the loader cache will promptly return the active loader.
This results in a lot of memory savings for the duplicated resources.
binary diff: -400 bytes
=> Loaders: Introduced a loader cache.

src/loaders/lottie/tvgLottieBuilder.cpp, src/loaders/lottie/tvgLottieModel.cpp, src/loaders/lottie/tvgLottieModel.h
This ia a buggy,
We will revisit this optimization with a perfect solution.
=> lottie/builder: revert the clipper cache.

src/renderer/gl_engine/tvgGlRenderPass.h, src/renderer/gl_engine/tvgGlRenderer.cpp, src/renderer/gl_engine/tvgGlRenderer.h, src/renderer/gl_engine/tvgGlShaderSrc.cpp, src/renderer/gl_engine/tvgGlShaderSrc.h
This PR implement the ComposeMethods in GL backends.
> In some cases, the rendering may be incorrect, and off-screen rendering needs to be optimized. 
https://github.com/thorvg/thorvg/issues/1687
=> gl_engine: support advance compose method

src/renderer/tvgPaint.h
[Issues 1811: Compiler shadowing warning](https://github.com/thorvg/thorvg/issues/1811)
thorvg: Godot CI compilation issue fixed
=> thorvg: Godot CI compilation issue fixed

src/loaders/lottie/tvgLottieParser.cpp
Found crash point:
`tvgLottieBuilder.cpp` line: 957
```cpp
if (strcmp(layer->refId, (*asset)->name)) continue;
```
LottieObject* `*asset` references NULL in some case, and added condition to check whether asset is null.
```cpp
if (*asset == nullptr || strcmp(layer->refId, (*asset)->name)) continue;
```
Crashed file here, and now works well with this patch:
> [1313.json](https://github.com/thorvg/thorvg/files/13594350/1313.json)
> [1577.json](https://github.com/thorvg/thorvg/files/13594351/1577.json)
> [2121.json](https://github.com/thorvg/thorvg/files/13594352/2121.json)
> [2472.json](https://github.com/thorvg/thorvg/files/13594356/2472.json)
> [7924.json](https://github.com/thorvg/thorvg/files/13594358/7924.json)
> [8906.json](https://github.com/thorvg/thorvg/files/13594359/8906.json)
> …
=> lottie/builder: fix crash by null reference
