src/renderer/tvgShape.cpp

The magic number kappa (0.552284), which is associated with the bezier curve, has been introduced. This formula is supposed to be applied to the rounded corners of the rectangle to ensure consistent drawing results.
Issue: https://github.com/thorvg/thorvg/issues/1824

renderer/shape: Apply the magic number kappa to achieve rounded corners.

---

src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h

This PR changed the GL fbo creation logical to save much more runtime memory while keep the rendering result correct.
For the same example: **MaskingMethods**
After this changes, only need create 3 times:

gl_engine: optimize framebuffer creation and save some runtime memory

---

src/renderer/gl_engine/tvgGlRenderTask.cpp
src/renderer/gl_engine/tvgGlRenderer.cpp

This PR fix some example not fully rendered.
Root Cause:
The scissor value may chaned by sub render task, and need to reset to surface size when root layer blit to screen.

gl_engine: fix wrong scissor value cause content not fully rendered

---

src/renderer/wg_engine/meson.build
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

For further development of features, we need to create off-screen buffers that will allow us to implement functionality related to composition and blending, as well as for loading data to system memory from the framebuffer. Separating the framebuffer into a separate entity allows you to create several instances of them, switch between them, and blend them according to given rules.
For current time we have only a single render target instance, that have a handle to drawing into surface surface, like a native window. 
New approach allows:
- offscreen rendering
- render pass handling
- switching between render targets
- ability to render images, strokes and shapes into independent render targets

wg_engine: refactor render targets handling

---

src/loaders/svg/tvgSvgPath.cpp
src/loaders/svg/tvgSvgPath.h
src/loaders/svg/tvgSvgSceneBuilder.cpp

Push the path data into a given shape directly.
This will skip unnecessary memory copies.
https://github.com/thorvg/thorvg/issues/1848

loader/svg: optimize the path conversion.

---

src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h
src/renderer/wg_engine/tvgWgShaderTypes.cpp
src/renderer/wg_engine/tvgWgShaderTypes.h

[issues 1479: Opacity](#1479)
Usage example:
// prepare a shape (Rectangle + Rectangle + Circle + Circle) with opacity
shape1->appendRect(0, 0, 200, 200);                //x, y, w, h
shape1->appendRect(100, 100, 300, 300, 100, 100);  //x, y, w, h, rx, ry
shape1->appendCircle(400, 400, 100, 100);          //cx, cy, radiusW, radiusH
shape1->appendCircle(400, 500, 170, 100);          //cx, cy, radiusW, radiusH
shape1->fill(255, 255, 0);                         //r, g, b
shape1->opacity(128)                               //opacity
canvas->push(std::move(shape1));

wg_engine: Added shape opacity value usage

---

src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgGeometry.cpp
src/renderer/wg_engine/tvgWgGeometry.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h
src/renderer/wg_engine/tvgWgRenderer.cpp

Before the current changes, all surfaces were painted using a full-screen overlay, no matter how large the object was rendered. This approach is redundant and required reorganization. At the moment, all objects are rendered using an overlay equal to the box of the object itself, which reduces the cost of filling the surface. 
Also surfaces and images were divided into different entities, which reduces the pressure on memory. 
Also geometry data for rendering and geometry data for calculations in system memory were logically separated.

wg_engine: shape bbox based rendering (optimization)

---

src/renderer/gl_engine/tvgGlCommon.h
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlShaderSrc.cpp

This PR enhance the gradient render in GL backend:
* change the color and stop size to 16 in shader and buffer block
* calculate transform when upload gradient info to gpu pipeline
| lineargrad1.svg | radialgrad1.svg |
| ---------------| ----------------|
|  <img src="https://github.com/thorvg/thorvg/assets/26308154/87ecba98-4b81-4112-9df3-34a38de23fe3" width="200" /> |  <img src="https://github.com/thorvg/thorvg/assets/26308154/ff88cd52-2313-451f-92ba-c80ee7f72cd2" width="200" /> |

gl_engine: fix svg gradient position not correct

---

src/loaders/svg/tvgSvgSceneBuilder.cpp

A regression bug is occured.
clipper is also required to be transformed with loader->resize()...
This reverts commit e62a8668e79852cbe4e74cc83c982fd298a01b73.

Revert "svg: removed an unnecessary nested scene."

---

src/loaders/external_jpg/tvgJpgLoader.cpp
src/loaders/external_jpg/tvgJpgLoader.h
src/loaders/external_png/tvgPngLoader.cpp
src/loaders/external_png/tvgPngLoader.h
src/loaders/external_webp/tvgWebpLoader.cpp
src/loaders/external_webp/tvgWebpLoader.h
src/loaders/jpg/tvgJpgLoader.cpp
src/loaders/jpg/tvgJpgLoader.h
src/loaders/png/tvgPngLoader.cpp
src/loaders/png/tvgPngLoader.h
src/loaders/raw/tvgRawLoader.cpp
src/loaders/raw/tvgRawLoader.h
src/renderer/tvgLoadModule.h
src/renderer/tvgPicture.cpp

Removed internal unique_ptr usage for a more compact size.

renderer/loader: code refactoring.

---

src/loaders/external_jpg/tvgJpgLoader.cpp
src/loaders/external_jpg/tvgJpgLoader.h
src/loaders/external_png/tvgPngLoader.cpp
src/loaders/external_png/tvgPngLoader.h
src/loaders/external_webp/tvgWebpLoader.cpp
src/loaders/external_webp/tvgWebpLoader.h
src/loaders/jpg/tvgJpgLoader.cpp
src/loaders/jpg/tvgJpgLoader.h
src/loaders/png/tvgPngLoader.cpp
src/loaders/png/tvgPngLoader.h
src/loaders/raw/tvgRawLoader.cpp
src/loaders/raw/tvgRawLoader.h
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwRaster.cpp
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/tvgLoadModule.h
src/renderer/tvgPicture.h
src/renderer/tvgRender.h
src/renderer/wg_engine/tvgWgRenderer.h

Introduced a dedicated mutex for each surface instance to ensure safe sharing between the loader, renderer, and engine.
This enhancement allows for secure modification and access to bitmap data, addressing potential concurrency issues.
Multiple Picture instances can now safely share a single loader instance, optimizing performance.
This change builds upon the previous Loader Cache improvements: ff6ea4b6c4564fd6c7c1d8bdde951dc0165e4034

renderer: enhanced shared surface handling with mutex implementation

---

src/loaders/svg/tvgXmlParser.cpp

Single or double quotation marks that occur before
closing the quotation mark are ignored.
related issue: https://github.com/thorvg/thorvg/issues/1892

loader/svg: Skip check for quotes inside quotes

---

src/renderer/sw_engine/tvgSwMemPool.cpp
src/renderer/sw_engine/tvgSwRasterTexmap.h

Hi,
While I was trying to build ThorVG for an STM32 MCU I found that in `tvgSwCommon.h` `mpoolInit` has `uint32_t` parameter while in `tvgSwCommon.cpp` it's `unsigned`. The difference caused link error on a 32 bit MCU.

fix the prototype of mpoolInit

---

src/loaders/lottie/tvgLottieModel.h

enable exceeding the range of normalized values in time remapping.
the issue came from a misunderstanding of the lottie spec.
issue: https://github.com/thorvg/thorvg/issues/1809

lottie: Corrected the Time Remapping Range

---

src/renderer/tvgShape.cpp

the bug was introduced in 9bf8bb018d9e17f64af09a55ee39a1d1a2dc9a2e.
Migrated the circle commands to the rectangle, which is currently necessary. Retained the previous circle commands for backward compatibility.

renderer/shape: fixed a regression bug

---

src/tools/svg2png/svg2png.cpp

buffer clearing is mandatory for the thorvg now.
issue: https://github.com/thorvg/thorvg/issues/1909

svg2png: clear the target buffer before the drawing.

---

meson.build
meson_options.txt
src/common/meson.build
src/common/tvgLock.h
src/meson.build
src/renderer/sw_engine/tvgSwRaster.cpp
src/renderer/tvgLoader.cpp
src/renderer/tvgRender.h
src/renderer/tvgTaskScheduler.cpp
src/renderer/tvgTaskScheduler.h
wasm_build.sh

Some systems such as micro-processor might not support the thread feature on the system.
Enhance the portability by compiling the thorvg with toggling the threading depepdency through the build option.
For this, thorvg newly introduced the internal Key/ScopedLock abstraction for transparent thread-locking dependnecy.
To turn off the thread feature, please use the next build option:
$meson setup build -Dthreads=false ...
Note that the thread feature is enabled in default.
Turning off the thread feature could reduce the binary size by 7kb.
issue: https://github.com/thorvg/thorvg/issues/1900

common: STM32 portability enhancement

---

src/renderer/sw_engine/tvgSwShape.cpp

Basically, sw_engine uses a desinated memory pool, this reservation is not so effective.

sw_engine: removed redundant logic.

---

src/renderer/wg_engine/tvgWgBindGroups.cpp
src/renderer/wg_engine/tvgWgBindGroups.h
src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp

[issues 1479: opacity](#1479)
Supported opacity value for scene
Usage example:
//Create a Scene
scene->opacity(100);
//Prepare Circle
shape1->appendCircle(400, 400, 250, 250);
shape1->fill(255, 255, 0);
shape1->opacity(100);
scene->push(std::move(shape1));
//Round rectangle
auto shape2 = tvg::Shape::gen();
shape2->appendRect(450, 100, 200, 200, 50, 50);
shape2->fill(0, 255, 0);
shape2->strokeWidth(10);
shape2->strokeFill(255, 255, 255);
scene->push(std::move(shape2));
canvas->push(std::move(scene));

wg_engine: introduced scene opacity

---

src/renderer/gl_engine/tvgGlRenderPass.cpp
src/renderer/gl_engine/tvgGlRenderPass.h
src/renderer/gl_engine/tvgGlRenderTask.cpp

This PR add stencil attachment in GLRenderTarget.
Plans to use stencil to test support for path clipping and complex path rendering when the tessellation algorithm cannot handle it.

gl_engine: append stencil attachment in GLRenderTarget

---

src/renderer/sw_engine/tvgSwRenderer.cpp

The compositor memory is likely to be reused in the next frame. To enhance performance, it is advisable to retain this memory by default.
We may consider introducing a cache policy interface in the Initializer. This would allow users to manage the Canvas memory more effectively.
Anyhow, this improves the Lottie example performance by 10%

sw_engine: retain the compositor cache memory

---

src/renderer/sw_engine/tvgSwRenderer.cpp

invalidate cached compositors when target size is changed. compositors must be re-initialized with a new size.
regression bug by ca3c1fc1b9bc1a74b5430f3eab1952727f1762b1

sw_engine: fix a regression bug

---

src/loaders/svg/tvgSvgLoader.cpp

I haven't figured out how to test this yet, and I don't know if changes are needed in more places. But this should be all the basic logic needed.
Fixes #1927

svg_loader: Add missing implementation of skewX and skewY in transform-list

---

src/renderer/sw_engine/tvgSwShape.cpp

Omit the dash line when its length falls below a minimal threshold. This threshold is set to less than 0.0001 times the pixel size.

sw_engine: Rectified dash line drawing issue.

---

src/loaders/svg/tvgSvgPath.cpp

The three specifications below apply.
Specification: https://www.w3.org/TR/SVG/paths.html#ArcOutOfRangeParameters
- If the endpoint (x, y) of the segment is identical to the current point (e.g., the endpoint of the previous segment),
then this is equivalent to omitting the elliptical arc segment entirely.
- If either rx or ry is 0, then this arc is treated
as a straight line segment(a "lineto") joining the endpoints.
- If either rx or ry have negative signs, these are dropped; the absolute value is used instead.
related issue : https://github.com/thorvg/thorvg/issues/1937

loader/svg: Apply specification of out-of-range elliptical arc parameters

---

src/renderer/sw_engine/tvgSwShape.cpp

This update fixes an issue where duplicated overlapping curves/lines, when introduced as a single line.
That case overlapping command operation is take account for the trim path's path-building process.
We now skip such cases to ensure the trim path functions correctly.
issue: https://github.com/thorvg/thorvg/issues/1939

sw_engine: Address a corner case in trim path handling

---

src/loaders/lottie/tvgLottieBuilder.cpp

retry image loading with the given candidates,
even if the suggested format is mismatched.

lottie: compatibility++

---

src/examples/DirectUpdate.cpp

Properly guide a sample usage to guarantee the sync call.

examples: updated DirectUpdate sample

---

src/renderer/gl_engine/tvgGlGeometry.cpp
src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/gl_engine/tvgGlTessellator.h

This PR made the following changes:
* merge vertices that are close enough before tessellation
* append return branch in tessellation to prevent dead loop caused by floating point precision
Current state:
With these changes, svg_example now runs successfully but renders incorrectly in some cases.

gl_engine: enhance the tessellation algorithm

---

src/renderer/sw_engine/tvgSwRaster.cpp
src/renderer/tvgScene.h

Previously, the logic was set to halt rendering when any part of the paints, particularly bitmap-based images, failed to render.
This update modifies the behavior to continue drawing the scene, allowing for the successful rendering of other elements.
issue: https://github.com/thorvg/thorvg/issues/1951

renderer: ensure canvas rendering continues despite invalid scene parts

---

src/renderer/sw_engine/tvgSwRaster.cpp

Adjusted the sampling position basis by -0.5 pixel to enhance edge line interpolation quality.
This change addresses an issue with the image up-scaling process, resulting in clearer and more accurate visuals.
issue: https://github.com/thorvg/thorvg/issues/1949

sw_engine: Improve image up-scaler quality

---

src/renderer/tvgCanvas.h
test/testSwCanvasBase.cpp

Allow direct updates to the paint object without prior validation. The verification process is deemed inefficient;
users are expected to ensure the paint is updated using a canvas that contains it.
This might break the backward compatibility.

renderer/canvas: Optimize logic by removing paint verification.

---

.github/workflows/build_windows.yml

Version 0.58 find missing libraries and causes an error. (ex: libwebp 1.0).
There is no need to fix the current version, so always use the latest version.

infra/window: Remove version fix of meson

---

src/renderer/gl_engine/tvgGlGeometry.cpp
src/renderer/gl_engine/tvgGlGeometry.h
src/renderer/gl_engine/tvgGlRenderTask.cpp
src/renderer/gl_engine/tvgGlRenderTask.h
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/gl_engine/tvgGlShaderSrc.cpp
src/renderer/gl_engine/tvgGlShaderSrc.h
src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/gl_engine/tvgGlTessellator.h

This PR contains the following changes:
* add new render task to do stencil and cover rendering which is a fallback rendering method to handle cases that trianglation tessellation failed
* add a new tessellator to generate stencil and cover vertex mesh
**After using this fallback method, more cases can be rendered successfully:**
----

gl_engine: add stencil and cover render task

---

src/loaders/svg/tvgSvgLoader.cpp

empty id is invalid. Therefore, set it to null and make it is not used.
issue: https://github.com/thorvg/thorvg/issues/1977

loader/svg: Fix empty id to null

---

src/renderer/wg_engine/meson.build

[issues 1991: Basic steps to compile for linux (wg_beta, examples)](https://github.com/thorvg/thorvg/issues/1991)
meson.build file fixed

wg_engine: meson script fixed

---

src/renderer/sw_engine/tvgSwStroke.cpp

In the case of non-uniform scaling for
thick strokes, artifacts were visible.
The calculations took into account the angle
resulting from the already transformed points,
whereas the untransformed points should have
been considered - the transformation is taken
into account in the next step.
@issue: https://github.com/thorvg/thorvg/issues/1915
before:
after:

sw_engine: fixing stroke outline

---

src/common/tvgBezier.cpp
src/common/tvgBezier.h
src/loaders/lottie/tvgLottieProperty.h
src/renderer/sw_engine/tvgSwShape.cpp

Dashed curves require greater precision in calculating their lengths. Otherwise, it results in visual
discrepancies compared to the expected outcomes.
issue: https://github.com/thorvg/thorvg/issues/1686
before:
after:

sw_engine: Increasing accuracy for dashed curves

---

src/loaders/lottie/tvgLottieProperty.h

this is useful for slot & expression type casting.

lottie: introduced LottieProperty base class

---

src/renderer/gl_engine/tvgGlRenderPass.cpp
src/renderer/gl_engine/tvgGlTessellator.h

../src/renderer/gl_engine/tvgGlRenderPass.cpp:35:34: warning: macro expands to multiple statements [-Wmultistatement-macros]
35 |     if (mColorTex != 0) GL_CHECK(glDeleteTextures(1, &mColorTex));
|                                  ^~~~~~~~~~~~~~~~
../src/renderer/gl_engine/tvgGlCommon.h:33:9: note: in definition of macro ‘GL_CHECK’
33 |         x; \
|         ^

gl_engine: fix a compile warnings, errors.

---

src/loaders/svg/tvgSvgLoader.cpp

Improve parenthesis checking and space checking.
- There must be only one pair of parentheses.
- There cannot be spaces(and ') between id strings.

svg: Improve valid check for url(#id)

---

src/loaders/lottie/tvgLottieModel.h

strlen() was used in tvgLottieModel.h without the inclusion of cstring. This patch fixes this

Lottie loader: fix compilation on windows

---

src/examples/AnimateMasking.cpp
src/examples/Animation.cpp
src/examples/DirectUpdate.cpp

Ensure synchronous calls are made after updating the canvases.

examples: ++threading stability.

---

src/renderer/tvgShape.cpp

According to the SVG standard, drawing a circle/ellipse should start at the '3 o'clock' position and proceed in a clock-wise direction. Until now, this point was set at '12 o'clock'.
The differences in the outcome were visible for dashed strokes.
issue: https://github.com/thorvg/thorvg/issues/1686
before:
after:

common: Changing the circle/ellipse starting point

---

src/renderer/tvgShape.cpp

According to the SVG standard, drawing a rectangle starts at (x+rx, y) point. Till now it was (x+w, y+ry). The difference was visible only for dashed strokes.

common: Changing the rounded rect starting point

---

src/renderer/sw_engine/tvgSwMath.cpp

stroke line drawing has been broken at a certain case, this reverts a part of change from the old optimization:
d81f5d29fb66f8d56e6197ca35dc375befc535e9
note that this change wouldn't affect any performance.
issue: https://github.com/thorvg/thorvg/issues/2015

sw_engine: fix a regression bug.

---

src/renderer/gl_engine/tvgGlGeometry.cpp

Since we choose multisample antialiasing, use stencil then cover to render polygon can get better performance.
Also the code is much easier to understand.

gl_engine: use stencil and cover tessellator by default

---

src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h

[issues 1479: antialiasing](#1479)
Anti-aliasing implementation
Implements antialiasing as a post process on compute shaders and original render target with scale of **x2** (hardcoded, can be changed as a constant)
Can be modified to setup as an external setting

wg_engine: antialiasing

---

src/bindings/capi/tvgCapi.cpp

Currently, the Lottie Animation API is not working due to the missing header.

capi: added missing lottie header

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/renderer/tvgLoadModule.h
src/renderer/tvgLoader.cpp

The previous loader cache mechanism encountered a problem when the user changed the content of the cached data.
In such cases, a new request would not be processed because the renderer would use the previously cached content.
So far, the TVG cache mechanism utilizes a pointer hash key for the fastest hashing mechanism available.
One limitation is that it assumes the address is unique for the data.
To resolve this, we modified the caching policy.
Now, the renderer will not cache copied data;
it will only cache the given data when it is deemed shareable.
issue: https://github.com/thorvg/thorvg/issues/2020

renderer/loader: revamping the caching mechanism.

---

src/renderer/gl_engine/tvgGlGeometry.cpp
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlShaderSrc.cpp
src/renderer/gl_engine/tvgGlTessellator.cpp

Since we choose MSAA, no need to calculate edge alpha during fragment stage. So this commit removed the alpha attribute and related code:
* Remove the alpha attribute in vertex data.
* Change position type from `vec3` to `vec2` in all shader code.
* Remove alhpa multiplication in all fragment shaders

gl_engine: remove unused alpha attribute

---

src/bindings/capi/thorvg_capi.h
src/loaders/lottie/thorvg_lottie.h
src/loaders/lottie/tvgLottieAnimation.cpp

In case the given JSON is invalid, it's more closed to `Result::InvalidArguments`.

lottie/api: specify clear result for override API

---

src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderTypes.cpp
src/renderer/wg_engine/tvgWgShaderTypes.h

[issues 1479: LinearGradient, RadialGradient](#1479)
Introduced fill spreads for linear and radial fills: Pad, Reflect, Repeat
Pad:
Reflect:
Repeat:

wg_engine: fill spread

---

AUTHORS
src/examples/resources/radial_gradient_focal_outside_circle.svg
src/renderer/sw_engine/tvgSwFill.cpp

sw_engine: radial gradient
https://github.com/thorvg/thorvg/issues/2014
Radial gradient results in a corrupted image when the focal point is outside the circle on Apple Silicon. This happens because some compilers use FMA to optimize the a = dr² - dx² - dy² calculation, which cause loss of precision.
We use compiler specific float contraction control pragmas to avoid this when they exist, and revert to manual de-optimization in other cases.

sw_engine: fix radial gradient when focal point is outside circle on Apple Silicon

---

src/loaders/png/tvgPngLoader.cpp
src/renderer/tvgRender.h

this is a regresion bug by 886b6b365b6c91e9b60c89970f44be4c38de12f3

png: corrected a wrong premultiplied option.

---

src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieParser.h

Previously, slot overriding only works in single sid, the others are ignored.
This patch enables slot overriding for all sids within a single slot.
Issue: #2045 
```json
{"ball_color":{"p":{"a":0,"k":[0.1,1,0.5,1]}},"background_color":{"p":{"a":0,"k":[1,1,1,1]}}}
```
**[Before]** `background_color` not working
**[After]** all overridden

lottie/slot: Support overriding plural sids

---

src/renderer/gl_engine/tvgGlRenderPass.cpp
src/renderer/gl_engine/tvgGlRenderPass.h
src/renderer/gl_engine/tvgGlRenderTask.cpp
src/renderer/gl_engine/tvgGlRenderTask.h

This PR contans the following changes and switch to using MSAA in all GLRenderTarget:
* use GLRenderBuffer in color and stencil attachment, also use x4 sample count by default.
* add msaa resolve logical at the end of a ComposeTask, so the normal color texture can get the final rendering result.

gl_engine: enable msaa resolve in GLRenderPass

---

src/bindings/capi/thorvg_capi.h

APIs:
- Tvg_Colorspace::TVG_COLORSPACE_ABGR8888S
- Tvg_Colorspace::TVG_COLORSPACE_ARGB8888S

capi: Add two additional ColorSpace options to align with C++ APIs.

---

src/loaders/webp/utils/bit_reader.cpp
src/loaders/webp/utils/bit_reader_inl.h
src/loaders/webp/utils/utils.h

The google's libwebp source uses aligned memory access.
This patch is that applies the two commits below to our static lib code.
refer to:
[Remove WEBP_FORCE_ALIGNED and use memcpy() instead]
https://github.com/webmproject/libwebp/commit/3884972e3f9ae887e0c16ca342851eff3ae67485
[bit_reader.c: s/VP8L_USE_UNALIGNED_LOAD/VP8L_USE_FAST_LOAD/]
https://github.com/webmproject/libwebp/commit/ac49e4e4dc05d6dcd4083aaa41965713e42c1c35
source :
https://chromium.googlesource.com/webm/libwebp/+/refs/heads/main/src/utils/bit_reader_inl_utils.h#80
related issue: https://github.com/thorvg/thorvg/issues/2006

loader/webp: Remove WEBP_FORCE_ALIGNED and use memcpy() instead

---

src/renderer/wg_engine/tvgWgGeometry.cpp
src/renderer/wg_engine/tvgWgGeometry.h
src/renderer/wg_engine/tvgWgRenderData.cpp

[issues 1479: FillRule](#1479)
Introduced fill rule winding
This rule makes sense only if path have some self intersections. In all other cases shapes are filled by even-odd behavor.

wg_engine: winding fill rule

---

src/renderer/tvgScene.h
src/renderer/tvgShape.h

This commit addresses an issue where paints lost their composition context when drawings occurred without any updates.
Now, paints will consistently retain the composition context, ensuring accurate rendering.
Issue: https://github.com/thorvg/thorvg/issues/2058

renderer: ensure paints retain composition context

---

src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieParser.cpp

When json file is invalid in the parser,
the LottieComposition object is not released and the parse() returns false.
To prevent memory leaks, free the memory before returning false.
related issue : https://github.com/thorvg/thorvg/issues/2070

lottie: Prevent memory leak when file is invalid

---

src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp

[issues 1479: strokes](#1479)
Introduced order setting
auto star = tvg::Shape::gen();
star->fill(80, 80, 80);
star->moveTo(599, 34);
star->lineTo(653, 143);
star->lineTo(774, 160);
star->lineTo(687, 244);
star->lineTo(707, 365);
star->lineTo(599, 309);
star->lineTo(497, 365);
star->lineTo(512, 245);
star->lineTo(426, 161);
star->lineTo(546, 143);
star->close();
star->strokeWidth(10);
star->strokeJoin(tvg::StrokeJoin::Round);
star->strokeFill(255, 255, 255);
star->order(true); // stroke first
if (canvas->push(std::move(star)) != tvg::Result::Success) return;
result example:
star->order(**true**); // _left shape_
star->order(**false**); // _right shape_

wg_engine: stroke first

---

src/loaders/svg/tvgSvgPath.cpp

The if-check to skip-rule when drawing an arc path is already checked in line 476.
In addition, since the float type equal check is performed in the range of 1/256,
unintentional skiped may occur. Therefore, remove duplicate code. https://www.w3.org/TR/SVG2/paths.html#ArcOutOfRangeParameters
test file:
SVG_FILE_147893
SVG_FILE_147939
related issue: https://github.com/thorvg/thorvg/issues/1255

loader/svg: Remove duplicate if-check in pathAppendArcTo

---

src/examples/Lottie.cpp

lottie/extensions will be only accessed by LottieExtension

examples/lottie: do not scan samples recursively.

---

src/renderer/gl_engine/tvgGlCommon.h
src/renderer/gl_engine/tvgGlGeometry.cpp
src/renderer/gl_engine/tvgGlGeometry.h
src/renderer/gl_engine/tvgGlRenderTask.cpp
src/renderer/gl_engine/tvgGlRenderTask.h
src/renderer/gl_engine/tvgGlRenderer.cpp

This PR enhance the GlStencilCoverTask:
* Support rendering Gradient in path Stroke mode
* Fix GlStencilCoverTask not support even-odd fill rule
* Make GlStencilCoverTask can discard overlapped area during stroke rendering
The GradientStroke case is almost correct:

gl_engine: make stencil task support other advance logical

---

src/loaders/lottie/tvgLottieParser.cpp

When image data fails to load or image parsing fails,
the id is leaked without being assigned to the name.
To prevent that, free id value when obj is nullptr.
related issue: https://github.com/thorvg/thorvg/issues/2072
BrokenLottie.7z/test3_IDX_130_RAND_18289244608080059871.json BrokenLottie.7z/test3_IDX_131_RAND_7772102071213376276.json BrokenLottie.7z/test3_IDX_132_RAND_3072617087893397532.json BrokenLottie.7z/test3_IDX_134_RAND_17738488813555566674.json BrokenLottie.7z/test3_IDX_137_RAND_13903188963759129023.json BrokenLottie.7z/test3_IDX_138_RAND_1645404078965858130.json

loader/lottie: Prevent leak memory when image load fails

---

src/loaders/ttf/tvgTtfLoader.cpp
src/loaders/ttf/tvgTtfLoader.h

use the preprocessor directives properly.

ttf: ++uwp portability

---

src/examples/resources/svg/consecutive_lines.svg
src/renderer/sw_engine/tvgSwShape.cpp

There are differences in behavior compared to the SVG spec, especially when consecutive line drawings occur without a moveTo command following a closePath command.
Actually, thorvg didn't care the behavior in that scenario, this update ensures the scenario is handled correctly to align with the SVG specification.
issue: https://github.com/thorvg/thorvg/issues/1487

sw_engine: rectify consecutive line drawings.

---

src/loaders/lottie/tvgLottieModel.h

Invalid gradient causes segmentation fault in population.
Added preventing logic. The function `populate` will not proceed and return 0 when `color.input` is nullptr.
related issue: #2072 
> Resolving crashes by segmentation fault from 123 files
- lottieslot_IDX_2_RAND_6332298139641021187.json
- lottieslot_IDX_47_RAND_13313713864635949061.json
- lottieslot_IDX_89_RAND_15775210715052235439.json
- lottieslot_IDX_126_RAND_16601351284790143166.json
- lottieslot_IDX_127_RAND_2435458778335924685.json
- lottieslot_IDX_198_RAND_12222704937178303596.json
- lottieslot_IDX_246_RAND_14265115990637144842.json
- lottieslot_IDX_252_RAND_16333113645329726009.json
- lottieslot_IDX_276_RAND_4643679359098999915.json
- lottieslot_IDX_334_RAND_4516773319034023871.json
- …

lottie: Fix crash when an invalid gradient is provided

---

src/loaders/lottie/tvgLottieParser.cpp

This change is better for stability. Returns `None` if the `mode` attribute cannot be parsed.
related issue: #2072
> Resolving crashes by segmentation fault for 3 files
- test9_IDX_135_RAND_12722319039069386985.json
- test9_IDX_207_RAND_6442145524277313594.json
- test9_IDX_743_RAND_6211786878291024908.json

lottie: Fix crash from invalid masking method

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp

removed unused static condition.
static was prepared for optimization,
but not used at all.
we will revisit this later when time permits.
binary size: -6kb

lottie: code refactoring.

---

src/loaders/lottie/tvgLottieParserHandler.h

D:\Projects\thorvg\src\loaders\lottie\tvgLottieParserHandler.h(52): warning C4083: expected ')'; found identifier 'effc' [44/46] Compiling C++ object src/thorvg-0.dll.p/loaders_lottie_tvgLottieParserHandler.cpp.obj D:\Projects\thorvg\src\loaders\lottie\tvgLottieParserHandler.h(52): warning C4083: expected ')'; found identifier 'effc' [45/46] Compiling C++ object src/thorvg-0.dll.p/loaders_lottie_tvgLottieParser.cpp.obj D:\Projects\thorvg\src\loaders\lottie\tvgLottieParserHandler.h(52): warning C4083: expected ')'; found identifier 'effc'
I'm not sure this option is really necessary.

portability: removed a compiler waring

---

src/common/tvgCompressor.cpp

Memory buffer-overflow is reported by ubsan.
In some cases, the b64decoder attempts to access `B64_INDEX` with negative integer index. Adding a condition to verify this scenario.
related issue: #2072 
> Resolving global-buffer-overflow by segmentation fault for 51 files
- test3_IDX_28_RAND_16261639712779502311.json
- test3_IDX_35_RAND_8309361089976797197.json
- test3_IDX_62_RAND_14264694530752380586.json
- test3_IDX_64_RAND_11732237327808738464.json
- test3_IDX_72_RAND_4598263687280085861.json
- test3_IDX_81_RAND_12171893598383239596.json
- test3_IDX_87_RAND_3126791548630821255.json
- test3_IDX_96_RAND_1894973443382169464.json
- test3_IDX_104_RAND_3070988726917405495.json
- test3_IDX_114_RAND_18058571645869157452.json
- test3_IDX_127_RAND_4221562738579431624.json
- …

lottie: Fix buffer-overflow in base64 decode

---

src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderTypes.h

[issues 1479: LottieExtensions](#1479)
LottieExtensions example supports
Supports multiple color stops for gradient fill (redial and linear)

wg_engine: Lottie extensions

---

src/loaders/lottie/tvgLottieModel.h

Invalid array access in `LottieGradient::populate`. Added preventing logic.
related issue: #2072 
> Resolving heap-buffer-overflow for 100 files
- lottieslot_IDX_19_RAND_12869611367480417304.json
- lottieslot_IDX_25_RAND_6847350414593490645.json
- lottieslot_IDX_44_RAND_15848512419441078021.json
- lottieslot_IDX_50_RAND_5807196878273210903.json
- lottieslot_IDX_55_RAND_9432165057333607863.json
- lottieslot_IDX_72_RAND_15114513152328341965.json
- lottieslot_IDX_95_RAND_17512533089551937727.json
- lottieslot_IDX_115_RAND_16109261102165821315.json
- lottieslot_IDX_118_RAND_15881926118350713257.json
- lottieslot_IDX_136_RAND_389829138177223098.json
- lottieslot_IDX_177_RAND_16025790448066370425.json
- lottieslot_IDX_257_RAND_16590272615132028700.json
- …

lottie: Fix heap-buffer-overflow in gradient populate

---

src/renderer/sw_engine/tvgSwShape.cpp

ensure that the number of contour/close data is properly paired.
issue: https://github.com/thorvg/thorvg/issues/2129

sw_engine/stroke: hotfix the memory access violation

---

src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

[issues 1479: lottie](#1479)
To optimize blend operations hardware pipeline blend stage are used for some blend methods:
```
BlendMethod::SrcOver
BlendMethod::Normal
BlendMethod::Add
BlendMethod::Multiply
BlendMethod::Darken
BlendMethod::Lighten
```
For other types compute shaders are used

wg_engine: blending optimization

---

src/loaders/svg/tvgXmlParser.cpp

If the key is not parsed and the '=' keyword is located next,
keep to parse the following syntax.
related issue:
https://github.com/thorvg/thorvg/issues/2116

loader/svg: Fix invalid syntax check

---

src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/gl_engine/tvgGlShaderSrc.cpp

This PR change all GL shader output *premultiplied alpha color*, also change the blending functor in gl_renderer
with this patch, the masking color is correct.

gl_engine: change all shader output premultiplied alpha color

---

inc/thorvg.h
src/renderer/gl_engine/tvgGlRenderer.cpp

GL might need to generate a default target FBO
when the given target ID indicates the main surface.
However, users may want to draw visuals directly onto the main surface.
This policy must be reviewed thoroughly.

gl_engine: hotfix for the main surface drawing issue.

---

src/renderer/wg_engine/tvgWgBindGroups.cpp
src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

[issues 1479: lottie](#1479)
Vertex, Index and uniform buffers now updates instead of recreate. Implemented pools form mesh objects and render shapes data
it increase performance in 30-40% in massive animations scenes

wg_engine: vertex, index and unifroms buffers, render objects caching

---

.github/workflows/regression.yml
.github/workflows/regression_check.py
test/regression/check_same_image_size.py
test/regression/settings_comparison.toml
test/regression/settings_crash_leak.toml

- previously svg2png crashes, timeouts and leaks have been ignored, but with new step now are now being caught - this depends partially on #2072 
- ~using github actions to create github comments instead curl(which did not work, I do not know why) - thanks to this, a comment will be created for each PR after the first passing of the CI, indicating whether or not changes in test suite have been detected in the PR, and on subsequent passes the same comment will be updated with newer information~
- re-enabling build with address/undefined sanitizer - looks that all strange freeze have been fixed
Not sure why, but comments not working(maybe will work after merging?) due error
```
/home/runner/work/_actions/peter-evans/create-or-update-comment/v4/dist/index.js:4695
const error = new …
```

Finding also crashes in regression finder

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/loaders/lottie/tvgLottieLoader.cpp

Currently, tvg ignores the frame value if the difference is less than 0.001. In most cases, updating the frames when the change is less than 1ms is just an unnecessary burden on the system.
Instead, this ensures that the perfect last frame is reached.
issue: https://github.com/thorvg/thorvg/issues/2147

lottie: rectify the frame updates.

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgXmlParser.cpp

If a Polygon's points array is odd, it is not a valid shape.

loader/svg: Skip to invalid polygon

---

src/loaders/svg/tvgSvgPath.cpp

If the command after `m` is not recognized, it must be recognized as `l` or `L`.
However, if it is not recognized after ending with `z`, all commands after it are ignored.
```
<svg width="100" version="1.0" xmlns="http://www.w3.org/2000/svg" height="100" xmlns:xlink="http://www.w3.org/1999/xlink">
<path style="stroke:#F00" d="m 20,20 0,50 50 0 -50 -50 z  70,70 0,50 50 0 -50 -50 z  "/>
</svg>
```

loader/svg: Ignore unrecognized commands following 'z'

---

src/renderer/sw_engine/tvgSwRasterNeon.h

I'm getting a compilation error when compiling on aarch64
```
w_engine_tvgSwRaster.cpp.o -MF src/libthorvg.so.0.13.99.p/renderer_sw_engine_tvgSwRaster.cpp.o.d -o src/libthorvg.so.0.13.99.p/renderer_sw_engine_tvgSwRaster.cpp.o -c ../src/renderer/sw_engine/tvgSwRaster.cpp
In file included from ../src/renderer/sw_engine/tvgSwRaster.cpp:238:
../src/renderer/sw_engine/tvgSwRasterNeon.h: In function ‘bool neonRasterTranslucentRle(SwSurface*, const SwRleData*, uint8_t, uint8_t, uint8_t, uint8_t)’:
../src/renderer/sw_engine/tvgSwRasterNeon.h:72:15: error: cast from ‘unsigned int*’ to ‘uint32_t’ {aka ‘unsigned int’} loses precision [-fpermissive]
72 |         if ((((uint32_t) dst) & 0x7) != 0) {
|               ^~~~~~~~~~~~~~
../src/renderer/sw_engine/tvgSwRasterNeon.h:85:32: warning: comparison …
```

sw_engine : type cast compile error

---

meson.build
meson_options.txt
src/meson.build

Note that this change renames the Meson option from 'vector' to 'simd',
separates the NEON types into 'neon-arm' and 'neon-aarch',
and designates the 'mfpu' option solely for 'neon-arm'.

infra: revise the vector build script

---

src/renderer/gl_engine/tvgGlRenderTask.cpp
src/renderer/gl_engine/tvgGlRenderTask.h
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/gl_engine/tvgGlShaderSrc.cpp
src/renderer/gl_engine/tvgGlShaderSrc.h

This PR replace the blit logical with normal texture rendering in the final color blit pass.
Since blit msaa framebuffer to another msaa framebuffer may generate GLError in some platforms. Use normal texture rendering to blit the final color buffer onto target framebuffer.

gl_engine: using normal texture rendering in final color blit

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoader.h

Because memcpy() is not guaranteed to copy null at the end of the data array,
it increase the size by 1 and add null.
This prevents invalid access of string functions in parser.

loader/svg: Add null to the end of data

---

src/bindings/capi/thorvg_capi.h

lottie/common: Fix typo in API documentation comment

---

src/loaders/lottie/tvgLottieLoader.cpp

ensure that the loading has been completed before overriding.

lottie: ++stability

---

src/renderer/gl_engine/tvgGlCommon.h
src/renderer/gl_engine/tvgGlGeometry.cpp
src/renderer/gl_engine/tvgGlRenderPass.cpp
src/renderer/gl_engine/tvgGlRenderPass.h
src/renderer/gl_engine/tvgGlRenderTask.cpp
src/renderer/gl_engine/tvgGlRenderTask.h
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h

This PR implement ClipPath in GLEngine by using depth test with the following changes:
* Append depth buffer attachment in tvgGlRenderPass
* using depth test if Shape has path clip

gl_engine: using depth buffer to support path clip

---

src/loaders/lottie/tvgLottieLoader.cpp

In any cases from parsing error, Marker APIs come runtime crash.
Added checking nullptr condition to avoid them.
issue: #2183

lottie/loader: Fix crash when parsing error

---

src/common/tvgStr.cpp

The string passed to the svg parser is not guaranteed to always be a valid string.
Certain strings may have numbers that cannot be converted.
Therefore, make sure to check whether the converted value is in the appropriate range before returning.
related issue: https://github.com/thorvg/thorvg/issues/2078#issuecomment-2037495121

loader/svg: Add check to the limits of result of StrToFloat

---

src/renderer/sw_engine/tvgSwShape.cpp

The error was visible when multiple shapes were
simultaneously trimmed. The length of a single
shape was zeroed out only in selected cases,
which caused accumulation that could lead to
incorrect extension of the variable determining
the maximum length.
@issue: https://github.com/thorvg/thorvg/issues/2173
Screenshot taken just before finishing the drawing of the windows on the building to the left - pay attention to the tree and the building on the right:
Screenshot taken just before starting to draw the left edge of the windows in the building on the left - pay attention to the door and the tree:

sw_engine: fix max length of trimmed strokes

---

src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgGeometry.cpp
src/renderer/wg_engine/tvgWgGeometry.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h
src/renderer/wg_engine/tvgWgRenderer.cpp

Optimizations:
- "on-the-fly" computing polyline segments lengths, total length and bboxes
- optimaze stroking algorithm by prevent vector normalizations
- tabulated sin and cos functions
- reducing system and graphics memory realocations
- prealocate triangle fans index buffers (less memory writes)
- using render meshes heaps to reduce webgpu instances re-creations
- using single instance of pilylines for standard operations such as trim and split
- "on-the-fly" strokes generations with dash pattern
- "on-the-fly" mesh objects generation in a process of path decoding
- merge strokes into single mesh by each shape

wg_engine: optimize with the internal triangulation algorithm and mesh rendering

---

examples/meson.build
meson.build
src/loaders/meson.build
src/savers/meson.build

Selecting a tool without choosing the required tools resulted in a usage error. Now, the activation of the appropriate saver/loader for a given tool is enforced.

build: enforcing saver/loader usage for given tool

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgXmlParser.cpp

[Revert "loader/svg: Skip to invalid polygon"](https://github.com/thorvg/thorvg/commit/c89dd9e2366a5f363507583131a2c042d209de55) 
This reverts commit https://github.com/thorvg/thorvg/commit/75e587a9a9b8becbedc6f1ccacd88da95be1ccb4.
If incorrect data for the points in a polygon is provided,
the element should still be rendered, but only up to the point
where the error occurs—using an even number of the points that
have been successfully loaded.
[svg_loader: correct polygon's points loading](https://github.com/thorvg/thorvg/commit/54f85d9a04ee1397d8b40b8ad63f76a4a62e200c) 
Only an even number of correctly read points defining
a polygon should be loaded and passed on for rendering.
Any remaining points should be ignored.

svg_loader: correct polygon's points loading 

---

src/loaders/svg/tvgSvgLoader.cpp

The display property was not copied along with other node properties. This caused incorrect rendering
of an object with display=none if accessed through a use tag.

svg_loader: copy display property

---

src/loaders/svg/tvgSvgLoader.cpp

The opacity value should be copied along
with other node properties.

svg_loader: fix opacity cloning

---

src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlShaderSrc.cpp
src/renderer/gl_engine/tvgGlTessellator.cpp

This PR fix the gradient effect not rendered correct:
* Fix error when handle GradientTransform calculation. And move the inv calculation into gradient vertex shader.
* Fix cubic tessellation not close the last point
----
----
I think now the SVG example is correct:

gl_engine: fix gradient rendering error

---

src/renderer/tvgShape.h

Using a mask (any type) with alpha set to less
than 255 through the fill(r, g, b, a) API resulted in incorrect compositions of fill and stroke.
Incorrect results were also observed for luma masks, as their alpha is calculated based on the other color channels.
@issue: https://github.com/thorvg/thorvg/issues/1653
modyfied InvLumaMasking.cpp example:
```
// rect
shape->appendRect(0, 0, 200, 200);
shape->fill(255, 0, 0);
shape->strokeWidth(50);
shape->strokeFill(255, 255, 0);
//Mask
mask->appendCircle(200, 200, 125, 125);
mask->fill(255, 50, 255);
//Nested Mask
auto nMask = tvg::Shape::gen();
nMask->appendCircle(220, 220, 125, 125);
nMask->fill(255, 50, 255);
mask->composite(std::move(nMask), tvg::CompositeMethod::InvLumaMask); …
```

common: fix composition while masking

---

src/loaders/svg/tvgSvgSceneBuilder.cpp

An empty link causes the wrong loader to be found and causes various problems.
related issue : https://github.com/thorvg/thorvg/issues/2078#issuecomment-2067726046

loader/svg: If link string is empty, not create picture object

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h

If any of the graphics nodes are not closed,
the graphics nodes between them are ignored.
related issue: https://github.com/thorvg/thorvg/issues/2210

loader/svg: Check current graphics node that not closed

---

src/bindings/capi/thorvg_capi.h
test/capi/capiAnimation.cpp

C API doesn't support default parameter, removed it.
Issue: #2228

bindings/capi: Fix incompatible parameter

---

meson.build
src/tools/lottie2gif/lottie2gif.cpp
src/tools/svg2png/svg2png.cpp
src/tools/svg2tvg/svg2tvg.cpp

the WIN32_LEAN_AND_MEAN definition will remove the unused features in windows.h that helps to improve the build-speed as well as fixing the issue.
Issue: https://github.com/thorvg/thorvg/issues/2225

infra: fix build failure using c++17 (or later) with MSVC.

---

src/renderer/gl_engine/tvgGlCommon.h
src/renderer/gl_engine/tvgGlGeometry.cpp
src/renderer/gl_engine/tvgGlGeometry.h
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/gl_engine/tvgGlTessellator.h

This PR optimize the tessellator's performance 
* restrict the scissor box of composite task
* do not tessellate stroke or fill geometry if there is no Fill or Stroke color
* use actually transformed curve to calculate polyline count when doing curve flatten
----
Before this patch the performance of Lottie example
After this patch the performance of Lottie example

gl_engine: optimize tessellation performance

---

src/loaders/lottie/tvgLottieExpressions.cpp

Stop handling if the interpreting result is invalid.

lottie/expressions: ++exceptional handling

---

src/loaders/svg/tvgSvgCssStyle.cpp

The paintOrder property set by the style was
not being copied. Now fixed.

svg_loader: paintOrder property properly copied

---

src/renderer/tvgShape.cpp

For sweep angles very close to a multiple of pi/2, an extra cubic curve segment was added, which was
populated with NaN values due to finite precision limits.

common: fix a precision issue in appendArc api

---

meson.build
meson_options.txt
src/loaders/lottie/jerryscript/jerry-core/ecma/operations/ecma-iterator-object.cpp
src/loaders/lottie/tvgLottieExpressions.cpp
test/testAnimation.cpp
test/testLottie.cpp

this commit introduces an additional build options:
- lottie expressions: this advanced feature in Lottie can significantly increase binary size. Users now have the option to enable or disable it based on their requirements.
Note that, this change introduces one config definitions:
- THORVG_LOTTIE_EXPRESSIONS_SUPPORT

lottie: enable the expressions feature in default

---

src/loaders/svg/tvgSvgCssStyle.cpp
src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h
src/loaders/svg/tvgSvgSceneBuilder.cpp

The display property, like any other node's style property, should be part of a node style. This ensures its correct copying and inheritance.
For the 'symbol' node, which is not rendered unless it is used within a 'use' node, the display property can also be applied. Because of that it cannot be utilized during scene construction to determine whether the symbol is being defined or used within a 'use' context.
before:
after:
sample:
```
<svg viewBox="0 0 80 20" xmlns="http://www.w3.org/2000/svg">
<symbol id="myDot" width="10" height="10" viewBox="0 0 2 2" display="true">
<circle cx="1" cy="1" r="1" />
</symbol>
<path
d="M0,10 h80 M10,0 v20 M25,0 v20 M40,0 v20 M55,0 v20 M70,0 v20"
fill="none"
stroke="pink" />
<use href="#myDot" x="5" y="5" style="opacity:1.0" />
<use href="#myDot" x="20" …
```

svg_loader: move the display property to the style

---

src/common/tvgArray.h

do not try memory copy if the size is 0.

common/array: ++safety

---

examples/Common.h

When WIDTH and HEIGHT values change,
the default size of the window also changes.

example: Sync setting size and window default size

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieProperty.h

Text Tracking value("tr") is parsed and never used. Calculate text spacing size via the tracking offset.
I checked Lottie spec docs [here](https://lottiefiles.github.io/lottie-docs/text/#text-document) for "tr" attribute. However it doesn't seem clear to explain them.
I referred original logic on [lottie-web](https://github.com/airbnb/lottie-web/blob/master/build/player/lottie_canvas.js#L10710) to calculate `trackingOffset` value.
Issue: #2223 
[Before]
[After]

lottie/text: Support text tracking

---

src/loaders/lottie/tvgLottieModel.cpp

Free the children data properly,
rarely observerd this, only when a layer is hidden.

lottie: fixed a memory leak

---

README.md
src/renderer/gl_engine/meson.build

GLES v3 was introduced many years ago;
we are now dropping support for GLES v2.
issue: https://github.com/thorvg/thorvg/issues/2269

gl_engine: updated GLES minimum requirement from v2 to v3

---

src/loaders/lottie/tvgLottieModel.h

When resetting back to animated property, system causes an UAF because frames have been freed.
Mark frames in nullptr at the case, so it doesn't use frame data after freed.
Issue: #2255 
**Current, when back to animated property.**
**Seems resetting well now.**

lottie/slot: Fix slot resetting bug

---

test/capi/capiAnimation.cpp
test/testAnimation.cpp

The precision margin for the comparison
has been set to 0.01f instead of 004004.

test: fix margin value

---

src/renderer/wg_engine/tvgWgRenderer.h

Use the override specifier so that
a compiler could warn any human mistake.

wg_engine: code refactoring

---

src/renderer/gl_engine/meson.build

let's keep this for a while until our minimum requirement is clear.

infra/gl_enigne: fallback use gles v2 if the system doesn't have v3.

---

src/loaders/lottie/tvgLottieBuilder.cpp

Fix access issue when iterating over children
in case of an empty container.
@Issue: https://github.com/thorvg/thorvg/issues/2283

lottie: fix access violation while updating

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp

Added support for skew transformation by
a specified angle around a specified axis.
after:
expected:
[skewed_stars.json](https://github.com/thorvg/thorvg/files/15314637/skewed_stars.json)

lottie: implement skew transformation

---

src/loaders/lottie/tvgLottieExpressions.h

After introducing roundness support, the build
process did not ensure proper compilation
for the case without expression support.

lottie: fix build error without extras

---

src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h
src/renderer/wg_engine/tvgWgRenderer.cpp

https://github.com/thorvg/thorvg/issues/1479
EvenOdd fill rule reorganized: using global bbox of whole path for fill.

wg_engine: Text support

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/renderer/tvgGlCanvas.cpp
src/renderer/tvgSwCanvas.cpp
src/renderer/tvgWgCanvas.cpp

Reset the viewport context when the target buffer is reset. This improves usability because the viewport is highly dependent on the target buffer.

renderer/canvas: tweak the viewport behavior.

---

src/loaders/lottie/tvgLottieBuilder.cpp

In case the shapes could be merged, matrix
multiplication was not stored in any variable,
resulting in one of the transformations not
being applied.
before:
after:
[fix3.json](https://github.com/thorvg/thorvg/files/15376969/fix3.json)

lottie: matrix multiplication fix

---

web/src/lottie-player.ts

Previously, the Intersection Observer doesn't filter hidden animations when page just loaded.
Ensure that the only visible animations to be played. Hidden resources will be frozen in the initial load.
Related Issue: https://github.com/thorvg/thorvg.web/issues/5

web: Reduce initial playing resources

---

src/loaders/svg/tvgXmlParser.h

The appearance of xml entities was handled
by the svg parser, but they may also be present
in the embedded data. Thus, while decoding base64, these elements must be removed.
@Issue: https://github.com/thorvg/thorvg/issues/2273
before:
after:

common: fix data parsing

---

src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp

[issues 1479: Fill Rule](#1479)
In this solution we dont need to find silhouette, that is not a cheep operation (decreasing performance in 2 times)
For winding, you can select separate operations for front and back faces (increment for front, decrement for back) After rendering the fan, the value in the stencil buffer will be the winding number. You can fill the appropriate portion by rendering a screen-sized quad with stencil testing enabled and the stencil function set according to which winding rule you wish to use.
For even-odd, you don't need to distinguish front and back faces; you can just use INVERT as the operation.

wg_engine: fill rule winding optimization

---

src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/lottie/tvgLottieLoader.h
src/renderer/tvgPicture.cpp

the Lottie scene should be updated when the slot overriding is updated. Previously, it only depended on the frame update.
issue: https://github.com/thorvg/thorvg/issues/2303

lottie: fixed a missing slot overriding update.

---

src/bindings/capi/tvgCapi.cpp

fix: 🐛 missing binding for tvg_canvas_set_viewport c api

---

AUTHORS
src/bindings/capi/thorvg_capi.h

Fix warning during build with lvgl https://github.com/lvgl/lvgl/pull/6081/
```
error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
```

capi: fix compile warning

---

src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/gl_engine/tvgGlTessellator.h

Add new function `strokeSquare` and `strokeRound` to handle StrokeCap during Path tessellation
----
After this commit, I think the **Stroke** case is correct.

gl_engine: Support StrokeCap in GlTessellator

---

src/loaders/lottie/tvgLottieBuilder.cpp

In the case of a transformation (denoted as T1)
appearing after the repeater, but at the same
level of nesting, the objects to which the repeater is applied should not consider T1. However,
the transformation of the repeater itself should
take T1 into account.
example 20874.json from lottie zip files:
before:
after:

lottie: repeater transformation fix

---

src/bindings/wasm/tvgWasmLottieAnimation.cpp

wasm binding for viewport API in web.
see: #2276

wasm: Support viewport API

---

src/loaders/lottie/tvgLottieBuilder.cpp

A regression bug by a recent change:
1ee79a6c2afafb6b16b14abc969b60c1dbc7a065

lottie: hotfix memory leaks by a regression

---

src/loaders/svg/tvgSvgLoader.cpp

This broke x86_32 GCC build on Linux and Windows with this error:
```
hirdparty/thorvg/src/loaders/svg/tvgSvgLoader.cpp: In function 'bool _toColor(const char*, uint8_t*, uint8_t*, uint8_t*, char**)':
thirdparty/thorvg/src/loaders/svg/tvgSvgLoader.cpp:716:42: error: cannot convert 'float_t*' {aka 'long double*'} to 'float*'
716 |         if (_parseNumber(&content, &hue, &th) && hue) {
|                                          ^~~
|                                          |
|                                          float_t* {aka long double*}
thirdparty/thorvg/src/loaders/svg/tvgSvgLoader.cpp:106:73: note:   initializing argument 3 of 'bool _parseNumber(const char**, const char**, float*)'
106 | static bool _parseNumber(const char** content, const char** end, float* number)
| …
```

loader/svg: Fix unintended use of `float_t` type

---

src/renderer/sw_engine/tvgSwShape.cpp

Fixing the problem with handling a specific
case where the length of the remaining line
to be drawn and the dash line length were
exactly the same.
before:
after:
no dash:
```
shape1->moveTo(100, 100);
shape1->lineTo(400, 100);
shape1->lineTo(400, 400);
shape1->lineTo(100, 400);
shape1->lineTo(100, 700);
shape1->lineTo(400, 700);
shape1->lineTo(400, 750);
shape1->strokeFill(255, 0, 0);
shape1->strokeWidth(10);
float dashPattern1[3] = {300, 600, 300};
shape1->strokeDash(dashPattern1, 3);
if (canvas->push(std::move(shape1)) != tvg::Result::Success) return;
```

sw_engine: fix dashing

---

src/loaders/lottie/tvgLottieParser.cpp

Shape's property 'direction' should be parsed
together with other properties specific for
the shape. This solves the issue with direction-
it wasn't working.

lottie: parsing obj property inside this obj

---

src/renderer/gl_engine/tvgGlGeometry.cpp
src/renderer/gl_engine/tvgGlRenderer.cpp

This PR fix the GlRenderer not take GradientStroke into consider when prepare Geometry vertices.
-----
After this fix, the gradient_stroke.svg can be rendered

gl_engine: fix GradientStroke ignored by tessellator

---

src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgShaderSrc.cpp

In a case of usage stencil buffer only we need to turn off an color target writes. In other case color buffer fill be filled by unxepcted color if fragment shader did not return any value. It happens in a case on OpenGL realization of webgpu, that used in linux
Befire:
After:

wg_engine: fix color buffer corruption with wgpu-opengl wrapper (linux)

---

src/renderer/gl_engine/tvgGlShaderSrc.cpp

This PR: Fix when gradient position is same as some starting or ending point of a gradient stop, the output color is blank
---- 
After this patch:

gl_engine: fix gradient color interpretation error

---

examples/Capi.cpp
examples/StrokeTrim.cpp
examples/meson.build
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/renderer/sw_engine/tvgSwShape.cpp
src/renderer/tvgRender.h
src/renderer/tvgShape.cpp
src/renderer/tvgShape.h
test/capi/capiShape.cpp
test/testShape.cpp

New api sets/gets the trim of the stroke
along the defined path segment, allowing
control over which part of the stroke is
visible.
@Issue: https://github.com/thorvg/thorvg/issues/2190

common: strokeTrim api

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/renderer/tvgShape.cpp
src/renderer/tvgShape.h

The functions setting stroke's features always
returned a true. Returnig a boolen was a remnant
from a previous implementation. Since now they
never return false, they can be void functions.
The APIs description has been corrected.

common: clarification of returned types

---

src/loaders/lottie/tvgLottieBuilder.cpp

When lottie has similar font names, it incorrectly matches fonts due to a logic bug.
This error causes an infinite loop when searching for glyphs. (The program hangs out)
[text-grouping-line.json](https://github.com/user-attachments/files/15546077/text-grouping-line.json)
Breaks from font iteration(at `_attachFont`) only when composition's font and text font are exactly matched, keep looping otherwise.

lottie: Fix invalid font match

---

src/renderer/sw_engine/tvgSwShape.cpp

For the 'simultaneous' trimming option, the maximum stroke length from all subpaths was determined and used to scale the trim of each subpath. As a result, if the subpaths had different lengths, this scaling was incorrect.
Now, the length is determined separately for each
subpath and is used to scale the trimming of its stroke.
@Issue: https://github.com/thorvg/thorvg/issues/2335
before:
after:
expected:
[trim_sim.json](https://github.com/user-attachments/files/15519501/trim_sim.json)

sw_engine: fix trimming

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/renderer/tvgShape.cpp
test/capi/capiShape.cpp
test/testShape.cpp

NonSupport indicates unsupported options due to disabled features or lack of system support. InvalidArgument indicates the case such as incorrect parameter values.

api: corrected return type.

---

src/renderer/sw_engine/tvgSwRle.cpp

the arranged value is examined with the local test, improved the speed twice for a corner-case - extreamly huge size shape.
test resource: [notification.json](https://github.com/user-attachments/files/15605543/notification.json)

sw_engine: Fine-tuning RLE performance.

---

test/capi/capiShape.cpp
test/testShape.cpp

warning C4305: 'argument': truncation from 'double' to 'float'

test: resolve compiler warnings on msvc.

---

src/renderer/sw_engine/tvgSwShape.cpp

When checking the fastTrack condition,
it's necessary to exclude the outlines
with a Bezier curve (Move-Cubic-Line,
Move-Cubic-Close, Move-Line-Cubic).
@Issue: https://github.com/thorvg/thorvg/issues/2379
sample:
```
shape1->moveTo(15,15);
shape1->lineTo(1, 15);
shape1->cubicTo(1, 1 , 15, 1 ,15 ,15);
shape1->fill(255, 255, 255, 200);
shape1->strokeWidth(0.6);
shape1->strokeFill(255, 0, 0);
shape1->scale(10);
canvas->push(std::move(shape1));
shape1 = tvg::Shape::gen();
shape1->moveTo(1,30);
shape1->cubicTo(1, 16 , 15, 16 ,15 ,30);
shape1->close();
shape1->fill(255, 255, 255, 200);
shape1->strokeWidth(0.6);
shape1->strokeFill(255, 0, 0);
shape1->scale(10);
canvas->push(std::move(shape1));
```
before:
after:

sw_engine: fix fastTrack condition

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h
src/loaders/svg/tvgSvgSceneBuilder.cpp

The text node is handled, but default values
of the font-family and font-size as used in
the user's system are not.
For now font has to be loaded by the user.
@Issue: https://github.com/thorvg/thorvg/issues/2350

svg_loader: handle text node

---

src/renderer/gl_engine/tvgGlGeometry.cpp
src/renderer/gl_engine/tvgGlRenderPass.cpp
src/renderer/gl_engine/tvgGlRenderPass.h
src/renderer/gl_engine/tvgGlRenderTask.cpp
src/renderer/gl_engine/tvgGlRenderTask.h
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/gl_engine/tvgGlShaderSrc.cpp
src/renderer/gl_engine/tvgGlTessellator.cpp

This PR fix some composite rendering error with the following changes:
* Optimize clip logical, change to use GL_GRATER and keep incrace depth value, so no need to do depth clear after every clip draw.
* Correct geometry bounding box calculation, and make sure the bounds is larger than all vertices
* Limit drawing area for off-screen RenderPass with correct scissor box
------
Before this commit:
------
After this commit, the bounds is correct:
The geometry is correct at SceneBlending example (The color is not , since GL backend has not implement advance blending, I plan to do this in next few weeks):

gl_engine: fix clip path and bounds not correct

---

examples/Text.cpp
inc/thorvg.h
src/loaders/ttf/tvgTtfLoader.cpp
src/loaders/ttf/tvgTtfLoader.h
src/renderer/tvgLoader.cpp
src/renderer/tvgLoader.h
src/renderer/tvgText.cpp

Adding support for reading from memory is
necessary to enable embedded ttf support,
e.g. in svg files.

ttf_loader: support loading from memory

---

src/renderer/sw_engine/tvgSwRenderer.cpp

enable fill anti-aliasing when the stroke is trimming.

sw_engine: fix a missing anti-aliasing

---

src/bindings/capi/tvgCapi.cpp

There was a typo in the name (tvg_canvas_est_viewport), which made it seem like it was missing. The correctly named API has already been added, so this one can be removed.

capi: remove the incorrectly named API

---

src/renderer/wg_engine/tvgWgGeometry.cpp
src/renderer/wg_engine/tvgWgRenderData.cpp

Ignoring rezo-width strokes, single point strokes (as in sw renderer)
Fix visual artifacts in case of mitter joints.

wg_engine: fix strokes failers and visual atrifacts

---

src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h

Fix wrong application of fill rule in a cases of terminated path (.close()/.moveTo())
IF avoid visual artifacts
Before/After:

wg_engine: fix fill rule usage

---

examples/Text.cpp
inc/thorvg.h
src/renderer/tvgLoader.cpp
src/renderer/tvgText.cpp
test/testText.cpp

issues caught during testing:
- wrong returned value while unloading
- lack of support for unprovided mimetype
- missing file.close in Text example

test for text loading from memory + issues caught during testing

---

src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderer.cpp

Skip shapes rendering, if opacity is 0 and if fill color for shape and strokes also equal to 0 This behavior is used in sw renderer and fix visual artifacts in referenced animations. Also this rule fix composition results in case of AlphaMask and InvAlphaMask methods
Before/After:

wg_engine: skip shapes with zero opacity values

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieParser.cpp

Assigning numbers 1 or 2 to a bool always
resulted in true. Now fixed and repeated
shapes are drawn in the proper order.
before:
after:
AE:
sample:
[abowe.json](https://github.com/user-attachments/files/15888508/abowe.json)
[below.json](https://github.com/user-attachments/files/15888510/below.json)

lottie: fix repeater order

---

src/renderer/tvgLoader.cpp
test/testSavers.cpp

In the absence of support for the TTF loader
crashes occurred. Fixed.

common: add missing ifdef

---

src/renderer/sw_engine/tvgSwRasterAvx.h
src/renderer/sw_engine/tvgSwRasterNeon.h

recte/rle 8 bit rasterizer has been broken,
make it work safely with c raster version.
issue: https://github.com/thorvg/thorvg/issues/2146

sw_engine: hotfix avx/neon 8 bit rasterizer.

---

src/renderer/sw_engine/tvgSwRasterTexmap.h

prevent the out of range anti-aliasing frames.
issue: https://github.com/thorvg/thorvg/issues/2401

sw_engine: ++exception handling

---

src/renderer/wg_engine/tvgWgGeometry.cpp
src/renderer/wg_engine/tvgWgGeometry.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderer.cpp

Fix computation of segments count for cubic curves. 
Using screen coordinates of base points, instead of world coordinates.
Before/After

wg_engine: fix incorrect geomatry

---

examples/Example.h

Add SDL_WINDOW_RESIZABLE to the sdl window property and call canvas->update() in the resize event.
Afterwards, if the canvas needs to be expanded by the window size by passing the size as an argument to the update(canvas,elapsed) interface, it can be processed individually.

examples: Support window resizable

---

src/renderer/sw_engine/tvgSwStroke.cpp

Since the value was casted to int the results
were different than expected.
before:
after:
sample:
```
<svg viewBox="0 -20 108 100">
<path
stroke="red"
stroke-width="4"
transform="scale(2)"
fill="none"
stroke-linejoin="miter"
stroke-miterlimit="7"
id="p1"
d="M 16 20 L 21 5 l 0 50  " />
<path
stroke="blue"
opacity="0.4"
stroke-width="4"
transform="scale(2)"
fill="none"
stroke-linejoin="miter"
stroke-miterlimit="6.9"
id="p1"
d="M 16 20 L 21 5 l 0 50  " />
</svg>```

sw_engine: fix stroke miterlimit precision

---

examples/DirectUpdate.cpp

The update might affect areas outside of the
default window. Update the sample to handle window resizing.

example: clear buffer properly.

---

examples/Example.h
src/renderer/gl_engine/meson.build
src/renderer/gl_engine/tvgGlCommon.h
src/renderer/gl_engine/tvgGlRenderTask.cpp
src/renderer/gl_engine/tvgGlShader.cpp

This PR make the GL backend can be compile and running when link with OpenGL on MacOS. Since GLES is only available in iOS.
BTW:
The Windows platform may have the same problem.

gl_engine: Fix compile error if only has OpenGL library on MacOS

---

src/renderer/tvgCanvas.h

If target() is called again after update()(or without update()) is called and the size of the buffer changes, a crash may occur.
Therefore, check the refresh variable and do draw after update().
issue: https://github.com/thorvg/thorvg/issues/2444

renderer/canvas: Check refresh before draw

---

README.md
examples/Example.h
examples/meson.build
meson.build
src/renderer/gl_engine/meson.build
src/renderer/gl_engine/tvgGlCommon.h
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlShader.cpp

- guarantee minimum version requirement
- removed glesv2 dependency
- corrected gl ver dependency
- removed sdl practices
issue: https://github.com/thorvg/thorvg/issues/2282

gl_engine: revise the gl portability

---

src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h

This PR Fix some rendering error after Example window resize.
When canvas size changed, need to clear cached GLRenderTarget and GLCompose.

gl_engine: Fix compose render not correct after canvas resize

---

src/renderer/gl_engine/tvgGlRenderTask.cpp
src/renderer/gl_engine/tvgGlRenderTask.h
src/renderer/gl_engine/tvgGlRenderer.cpp

This PR Fix memory leak cuased ClipTask and empty render task
#2461

gl_engine: Fix memory leak caused by no deleted GlRenderTask

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h

That basic information is addressed in the Results section.
We can only add information that pertains to a specific scenario.

doc: removed useless information for easier maintainence

---

src/renderer/gl_engine/tvgGlRenderer.cpp

This PR fix the wrong return value caused some example not working
This can fix : #2465 
Also , the `Performance` and `Viewport` example is being rendered correct.

gl_engine: correct the return value of render function

---

src/renderer/wg_engine/tvgWgGeometry.cpp
src/renderer/wg_engine/tvgWgGeometry.h

Change the appliense of stroke mitter corresponding to SVG spec.
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-miterlimit
See **StrokeMiterlimit** and **Stroke** examples
Before/After

wg_engine: fix stroke miterlimit

---

src/renderer/wg_engine/tvgWgRenderData.cpp

Texture must be fully uploaded into GPU memory before we can use or destroy it. This change force texture data to update.
See PicturePng, PictureJpg examples for texture usage

wg_engine: force texture data writing on GPU side

---

examples/Example.h

Fix SDL2 headers include path to use them in more standard way and release IDE warnings
Tested on linux and macos

examples: fix sdl2 headers include path

---

src/renderer/tvgCanvas.h

This reverts commit 60212747b54c73e97ab93a15bfc5ff9362408c02.
this triggered duplicated updates,
it came up with many thread sanitizer problems.
issue: https://github.com/thorvg/thorvg/issues/2462

Revert "renderer/canvas: Check refresh before draw"

---

src/loaders/lottie/tvgLottieLoader.cpp

make it sync call before accessing the composition data from marker and segments.
issue: https://github.com/thorvg/thorvg/issues/2462

lottie: fix a data-race problem

---

src/renderer/wg_engine/tvgWgGeometry.cpp
src/renderer/wg_engine/tvgWgGeometry.h

Shapes were incorrectly closed in certain cases -
the decision to close a shape or not should be based on path commands rather than the number of points and their distances from each other.
before:
after - expected result is that the second triangle is not closed:
sample:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 500" >
<path d="M 20 20 h 300 l -150 200 l -150 -200 Z" stroke="blue" stroke-width="30" fill="none" stroke-linejoin="round" opacity="0.5"/>
<path d="M 20 270 h 300 l -150 200 l -150 -200" stroke="red" stroke-width="30" fill="none" stroke-linejoin="round" opacity="0.5"/>
</svg>
```

wg_engine: fix line joins

---

test/capi/capiSavers.cpp

warning C4305: 'argument': truncation from 'double' to 'float'

test/capi: --compiler warning on MSVC

---

src/renderer/gl_engine/tvgGlGeometry.h
src/renderer/tvgRender.h

A minor syntactic adjustment to two instances of `operator==` and one instance of `operator!=`, both to the end of ensuring these locally-scoped functions are properly identified as `const`. In the majority of cases, this shouldn't have any impact; however, this change makes these operators play nice in `c++20` contexts.

renderer: Ensure `const` equality operators

---

src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/tvgShape.h

For shapes with a stroke that has opacity, anti-aliasing should be applied to a fill.
The use of a transparent gradient stroke will also be handled correctly.
before:
after:
sample:
```
shape->appendRect(100, 100, 600, 600, 250, 250);
shape->fill(0, 255, 0);
shape->strokeWidth(100);
shape->strokeFill(255, 255, 255, 100);
canvas->push(std::move(shape));
```

sw_engine: fix aa

---

.github/workflows/build_android.yml
.github/workflows/build_ios.yml
.github/workflows/build_macos.yml
.github/workflows/build_ubuntu.yml
.github/workflows/build_windows.yml
.github/workflows/memcheck_asan.sh
.github/workflows/memcheck_valgrind.sh
.github/workflows/regression.yml

My GitHub organizations are configured [not to include `write` permissions for workflows by default](https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#configuring-the-default-github_token-permissions) (this is considered a best practice, but was set up as opt-in for existing orgs because it would otherwise break existing workflows). This means that the **valgrind**/**asan** test steps in the `build_ubuntu.yml` workflow triggered errors and weren't able to report.
As it happens, currently those two reporting things were trying to submit empty comments, which seems undesirable. So I'm proposing limiting them to only run when they have something to say.
Beyond that, best practices dictate that each workflow …

Improve permissions handling in workflows

---

src/renderer/gl_engine/tvgGlGeometry.h
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlTessellator.h

This PR can improve the hairline rendering : #2509

gl_engine: support simple hairline stroke rendering

---

src/renderer/wg_engine/tvgWgBindGroups.cpp
src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h

See Blending, SceneBlending, Opacity examples
Full review of blending support.
Support Solid color, Gradient fill and Image blending workflows
See [Blend Mechanics](https://github.com/thorvg/thorvg/wiki/WebGPU-Raster-Engine-Development#blendcomposition-mechanics)
sw/before/after

wg_engine: fix blend methods support

---

src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h

The `dispose()` method can be called on a worker thread. GL resources are released on `sync()`, ensuring guaranteed thread safety.
issue: https://github.com/thorvg/thorvg/issues/2517

gl_engine: ++thread safety

---

src/renderer/gl_engine/tvgGlRenderer.cpp

Fix memory leak when nothing need to be draw in renderImage
issue: #2522

gl_engine: fix memory leak when rendering image

---

src/renderer/gl_engine/meson.build

macOS has officially deprecated OpenGL.
shutdown the warnings to avoid be side-tracked.

gl_engine: --deprecated warnings on macOS

---

src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

Store desposed object in MT-safe list and then despose objects in sync stage

wg_engine: fix safe disposing of render data in MT environment

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/renderer/tvgPaint.cpp
src/renderer/tvgPaint.h
src/renderer/tvgRender.cpp
src/renderer/tvgRender.h
test/testPaint.cpp

This corrects the return value to Result::InsufficientCondition when a custom transform is applied.
Additionally, unnecessary x and y member fields have been removed.

renderer: Rectified the paint transforms.

---

src/renderer/tvgPicture.h
src/renderer/tvgShape.h

The flag could be missed when the image is copied with a surface.

Renderer: rectified a missing image update flag

---

src/renderer/gl_engine/tvgGlRenderer.cpp

If there are both gradient colors and solid colors the gradient color is used first for rendering.
Now the example `Duplicate` is correct:

gl_engine: make sure solid color not overwrite gradient fill

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieParser.h

The width and height of the image must
be specified in the Lottie file and must
be taken into account during rendering.
solves 11493.json:
before:
after:
also solves 11636.json

lottie: add support for image size

---

src/common/tvgLines.cpp

In the function calculating the tangent to a cubic bezier at a given t, the atan was calculated using dx over dy, instead of dy over dx. The error was visible during the animation using auto-orient = true.
file | before | after|
-----|--|------|
5949.json |<img width="300" alt="Zrzut ekranu 2024-07-9 o 01 04 19" src="https://github.com/thorvg/thorvg/assets/67589014/bbfcb620-aa68-4389-b0d7-28cd29de9f86">|<img width="300" alt="Zrzut ekranu 2024-07-9 o 01 04 35" src="https://github.com/thorvg/thorvg/assets/67589014/9b2a6f68-2614-436f-a1a7-5710586f8dcf">|
16787.json|<img width="300" alt="Zrzut ekranu 2024-07-9 o 01 16 34" src="https://github.com/thorvg/thorvg/assets/67589014/8038510b-ab0d-40de-88ac-4ddea3a10892">|<img width="300" alt="Zrzut ekranu 2024-07-8 o 20 14 39" …

common: fix bezAngleAt function

---

src/renderer/sw_engine/tvgSwRaster.cpp

```
auto bg = tvg::Shape::gen();
bg->appendRect(0, 0, 400, 400);
bg->fill(255, 255, 255);
canvas->push(std::move(bg));
shape->appendRect(0, 0, 400, 400);
shape->fill(0, 0, 255, 100);
mask->appendCircle(200, 200, 125, 125);
mask->fill(255, 255, 255);
shape->composite(std::move(mask), tvg::CompositeMethod::AlphaMask);
canvas->push(std::move(shape));
```
before:
after:

sw_engine: fix masked translucent rect

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp

Issue: #2178 (Partial support of Text Range Selector)
New supported properties of this patch:
I referred to [lottie-web](https://github.com/airbnb/lottie-web/blob/master/build/player/lottie_canvas_worker.js#L11470) for the offset calculating logic.
- Percent  ([range_selector_text_style_fill_color_percent.json](https://github.com/user-attachments/files/15912127/range_selector_text_style_fill_color_percent.json))
- Index ([range_selector_text_style_fill_color_index.json](https://github.com/user-attachments/files/15912136/range_selector_text_style_fill_color_index.json))
- Fill Color ([range_selector_text_style_fill_color_blue.json](https://github.com/user-attachments/files/15912144/range_selector_text_style_fill_color_blue.json))
- Fill Opacity (_lottie-web not working_, …

lottie/text: Support text range selector (Phase 1)

---

src/loaders/lottie/tvgLottieBuilder.cpp

Internal matrix can be null.
This update prevents such cases by using a safer API.

lottie: ++memory access stability

---

src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

[issues 1479: Viewport](#1479)
Supports viewport settings and rectangular clip path.
Native webgpu scissors cliping are used as a way to clip viewport
sw/webgpu

wg_engine: Viewport support

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp

- retain reusable precomp clipper shapes during animation.
- retain resuable layer solid paint during animation.

lottie: ++ scene composing optimization

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieParser.cpp

lottie: support 'direction' in ellipses
partially solves 16699.json (without https://github.com/thorvg/thorvg/pull/2330 won't work since direction property is given before the type property))
before:
after:

lottie: support 'direction' in ellipses

---

src/loaders/lottie/meson.build
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieRenderPooler.h

LottieRenderPooler is designed to manages rendering instances(paints) efficiently through a simple pooling mechanism to resuse among the animations
This replaces the previous individusal paints implemenations among solidfill, precomp vierport and pictures,
also fix a potential paints corruption problems.

lottie: introduced LottieRenderPooler

---

src/renderer/wg_engine/tvgWgBindGroups.cpp
src/renderer/wg_engine/tvgWgBindGroups.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h

[issues 1479: ClipPath](#1479)
Introduce ClipPath composition support.
Clip path composition is an only composition type who doesn't ignore blend method. 
Clip path is a combination of composition approach and blend approach using compute shader.

wg_engine: Introduce ClipPath composition support

---

src/renderer/wg_engine/tvgWgShaderSrc.cpp

[Fill spread](https://github.com/thorvg/thorvg/issues/2435) example
Fixed range selector edged cases
before:
after:

wg_engine: fix fill spread artifacts

---

src/renderer/wg_engine/tvgWgGeometry.cpp

[GradientStroke](https://github.com/thorvg/thorvg/issues/2435) example
More accurate coefitient computation
Before:
After:

wg_engine: fix cubic generation artifacts (GradientStroke example)

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h

More precisely, culling the render objects by
determining if the group has no renderable objects.
Additionally, check opacity to quickly return
in the rendering process.

lottie: ++optimization with object culling

---

src/loaders/svg/tvgSvgLoader.cpp

../src/loaders/svg/tvgSvgLoader.cpp: In function ‘bool _toColor(const char*, uint8_t*, uint8_t*, uint8_t*, char**)’: ../src/loaders/svg/tvgSvgLoader.cpp:108:17: warning: ‘hue’ may be used uninitialized [-Wmaybe-uninitialized]
108 |     const char* _end = end ? *end : nullptr;
|                 ^~~~
../src/loaders/svg/tvgSvgLoader.cpp:713:31: note: ‘hue’ was declared here
713 |         const char *content, *hue, *saturation, *brightness;
|                               ^~~
../src/loaders/svg/tvgSvgLoader.cpp:108:17: warning: ‘saturation’ may be used uninitialized [-Wmaybe-uninitialized]
108 |     const char* _end = end ? *end : nullptr;
|                 ^~~~
../src/loaders/svg/tvgSvgLoader.cpp:713:37: note: ‘saturation’ was declared here
713 |         const char *content, *hue, …

svg: resolve compiler warnings.

---

src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwFill.cpp
src/renderer/sw_engine/tvgSwRaster.cpp

The restriction of the 'length' of a linear gradient
to values greater than FLT_EPSILON was causing rendering
issues in cases where it was a valid gradient with well
defined dx and dy values.
@issue: https://github.com/thorvg/thorvg/issues/2582

sw_engine: fix linear grad issue

---

inc/thorvg.h
src/renderer/tvgAnimation.cpp

A zero-range segment can be useful for a stopped motion. There is no need to prohibit these values.

renderer/animation: rectified the segment value exception

---

src/renderer/sw_engine/tvgSwFill.cpp

In the Taylor series expansion, there was a missing division by 2! in the term with the second derivative.
@Issue: https://github.com/thorvg/thorvg/issues/2530
sample:
```
<svg
viewBox="0 0 100 100"
xmlns="http://www.w3.org/2000/svg"
xmlns:xlink="http://www.w3.org/1999/xlink">
<defs>
<radialGradient id="myGradient" spreadMethod="reflect"
gradientUnits="userSpaceOnUse"
r="10" cx="50" cy="50">
<stop offset="0.0" stop-color="#000000" />
<stop offset="1.0" stop-color="#FFFFFF" />
</defs>
<rect width="100" height="100" x="0" y="0" fill="url(#myGradient)" />
</svg>
```
before:
after:

sw_engine: fix radial coefficients calculations

---

src/loaders/ttf/tvgTtfLoader.cpp
src/loaders/ttf/tvgTtfReader.cpp
src/loaders/ttf/tvgTtfReader.h
test/testText.cpp

Adds the ability to load some composite glyphs and prevents an error when a composite glyph is used.
Implementation based on ttf glyf table documentation: https://learn.microsoft.com/en-us/typography/opentype/spec/glyf
There are still some missing features like scaling, parent glyph point based positioning etc. I think this is a topic for future work. Howerever, it looks like implemented features are enough for utf-8 latin subset in major fonts.
solves issue: #2599

ttf_loader: Basic support for composite glyphs loading

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/renderer/sw_engine/tvgSwShape.cpp
src/renderer/tvgRender.h
src/renderer/tvgShape.h

For pairs of start/end values like -0.5 and 0.5
(also -0.4 and 0.6, etc), the entire stroke should be drawn, but instead, nothing is drawn.
```
shape1->appendCircle(245, 125, 50, 120);
shape1->appendCircle(245, 365, 50, 120);
shape1->appendCircle(125, 245, 120, 50);
shape1->appendCircle(365, 245, 120, 50);
shape1->fill(0, 50, 155, 100);
shape1->strokeFill(0, 0, 255);
shape1->strokeJoin(tvg::StrokeJoin::Round);
shape1->strokeCap(tvg::StrokeCap::Round);
shape1->strokeWidth(12);
shape1->strokeTrim(-0.4f, 0.6f, false);
auto shape2 = tvg::cast<tvg::Shape>(shape1->duplicate());
shape2->translate(300, 300);
shape2->fill(0, 155, 50, 100);
shape2->strokeFill(0, 255, 0);
shape2->strokeTrim(-0.4f, 0.6f, true);
canvas->push(std::move(shape1)); …
```

common: fix trimming

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwFill.cpp
src/renderer/sw_engine/tvgSwRaster.cpp
src/renderer/sw_engine/tvgSwRenderer.cpp

For a linear gradient defined by identical start and end
points, and for a radial gradient with a radius of 0,
the rendered shape should have the color of the last
specified color stop.
The documentation has been updated accordingly.
@Issue: https://github.com/thorvg/thorvg/issues/2582
note:
for start=end svg standard defines that the last stop color should be used to fill the shape. for lottie files tested in skottie and AE - both seems to use the same def as svg

sw_engine: handle grad edge cases 

---

src/loaders/lottie/tvgLottieBuilder.cpp

apply expressions to separate x/y transform coordinates.

lottie/expressions: add missing expressions property updates

---

src/common/tvgLock.h
src/renderer/tvgTaskScheduler.h

This reverts #2385, which was merged on 2024-06-10 as a workaround for broken GitHub Actions runner images (see https://github.com/actions/runner-images/issues/10004). GitHub Actions was fixed a few days later, so the workaround is no longer necessary, and should be reverted to avoid problems with the upcoming release of VS 2022 17.12.
This workaround macro `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` should have been defined on the command line (i.e. somewhere in thorvg's `meson.build`). Defining workaround macros in source files is fragile, because library headers could be dragged in before the workaround macros are defined, and upcoming changes to MSVC's STL will reveal this problem and emit compiler errors. (I work on MSVC's STL, and this was found by our …

Revert `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` workaround

---

examples/MaskingMethods.cpp
inc/thorvg.h
src/loaders/lottie/tvgLottieParser.cpp
src/renderer/sw_engine/tvgSwRaster.cpp
src/renderer/tvgRender.h

This is only introduced for software rasterizer.
issue: https://github.com/thorvg/thorvg/issues/2608
- examples/MaskingMethods
- Lottie Lighten
[lighten.json](https://github.com/user-attachments/files/16510008/lighten.json)
- Lottie Darken
[darken.json](https://github.com/user-attachments/files/16510009/darken.json)

Lighten/Darken Masking Enhancement

---

src/renderer/tvgPaint.cpp
src/renderer/tvgText.h

Text fill is broken by 43c87b4eb5cef0fbaa3a4ab8084790b5b5c19735

renderer: rectified the bounds() behavior

---

meson.build

In case of modern systems, size is not a big problem, so we turn the optimization option to default
for better performance.
FPS: ~20% enhanced
Size: ~25% increased
Note that this doesn't affect to the web player.

infra: switch the optimization option to level 3

---

src/common/tvgMath.cpp

The epsilon value currently used for the precision of Beziers calculations is sufficient for comparing curve lengths. However, for the parameter t, which ranges from 0 to 1, an accuracy of 1% can introduce errors.
The solution is to increase the precision for the t parameter while keeping the rest of the calculations at the previously used epsilon value.
@Issue: https://github.com/thorvg/thorvg/issues/2619

common: increase precision for bezier calculations

---

src/common/tvgArray.h
src/common/tvgInlist.h
src/common/tvgMath.cpp
src/common/tvgMath.h

common: add missing consts
Adding const was necessary to allow calling
the functions on constant objects.
common: fix arg name
For Bezier curves, we typically use 't' as a parameter
within the 0-1 range, while 'at' is used for the parameter
scaled by the curve's length. In one of the functions,
an incorrect name was used, which could be confusing.
No logical changes.

common: add missing consts & fix arg name

---

src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h

[issues 2608: light/dark mask](#2608)
* CompositeMethod::LightMask
* CompositeMethod::DarkMask
darken.json
lighten.json

wg_engine: light/dark mask mode support

---

src/bindings/wasm/tvgWasmLottieAnimation.cpp

The canvas syncs before changing a target buffer.
issue: https://github.com/thorvg/thorvg/issues/2580

wasm: thorvg canvas resize problem.

---

src/loaders/lottie/tvgLottieBuilder.cpp

For rounded rectangles the roundness value should
be determined using to the formula:
r = max(min(size.x/2, r), min(size.y/2, r))
rather than the previous method:
r = min(size.x/2, size.y/2, r)
sample:
[roundedRect.json](https://github.com/user-attachments/files/16564597/roundedRect.json)
before:
after:

lottie: handle edge case for rounded rect

---

src/renderer/wg_engine/tvgWgBindGroups.cpp
src/renderer/wg_engine/tvgWgBindGroups.h
src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h
src/renderer/wg_engine/tvgWgShaderTypes.cpp
src/renderer/wg_engine/tvgWgShaderTypes.h

* used precalculated gradient texture instead of per-pixel gradient map computation
* used HW wrap samples for fill spread setting
* used single shader module for composition instead of signle module per composition type
* used single shader module for blending for each of fill type (solid, gradient, image) instaed of signle module per blend type
* much easier to add new composition and blend equations
* get rided std::string uasge
* shaders code is more readable
Verified on windows/linux/macos/emsdk
Samples to verify:
* Blending
* MaskingMethods
* LinearGradient
* RadialGradient

wg_engine: shaders refactoring

---

src/loaders/lottie/tvgLottieBuilder.cpp

Added prioritization of rectangle roundness over
rounded corners, in line with AE results.
[rectRound0_RCornerS.json](https://github.com/user-attachments/files/16592171/rectRound0_RCornerS.json)
[rectRound1_RCornerS.json](https://github.com/user-attachments/files/16592172/rectRound1_RCornerS.json)
[rectRoundS_RCorner0.json](https://github.com/user-attachments/files/16592173/rectRoundS_RCorner0.json)
[rectRoundS_RCorner1.json](https://github.com/user-attachments/files/16592174/rectRoundS_RCorner1.json)

lottie: prioritization of roundness in rectangles

---

src/loaders/lottie/tvgLottieLoader.cpp

In certain cases, the user might want to set mapped memory directly. This update ensures that a null terminator is appended to the string data.
Co-Authored-By: Mira Grudzinska <mira@lottiefiles.com>
Issue: https://github.com/thorvg/thorvg/issues/2642

lottie: ensure a null terminator at the end of the copied data

---

inc/meson.build
src/meson.build

A pkgconfig file is already provided, which enables using `thorvg` once it is installed. However, this file is not, and cannot be, available at setup time if using `thorvg` as a subproject.
In such cases, Meson provides the `override_dependency` mechanism for a subproject to tell its parent how to use it. 
This would be necessary for #1723, for example.

build: Override dependency for use as subproject

---

examples/meson.build
meson.build
src/bindings/meson.build
src/bindings/wasm/meson.build
src/loaders/meson.build
src/meson.build
test/meson.build
tools/meson.build

If a Meson option is typed as `boolean`, the `get_option` returns a boolean, and comparing it with `true` is redundant. Meson also errors if you try to compare across types, so it couldn't _not_ be a boolean.
Also, Meson is not C, so no need for parentheses around `if` conditions.

build: Remove redundant comparisons

---

src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgCompositor.h
src/renderer/wg_engine/tvgWgGeometry.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h

wg_engine: aabb based masking optimization
* used fragment shaders for mask applience instead of compute shaders
* less render targets swithing
* aabb based mask application. Masks computes only on the area with shapes, but not full screen
* shape aabb based on transformed shape bbox
Ready for direct mask application (part 3)
Samples to verify:
* Masking
* MaskingMethods

wg_engine: composition and blend optimization - PART 2

---

src/renderer/sw_engine/tvgSwRasterTexmap.h

The y range initialization was missing a check to ensure that the height is a positive value. This could lead to an attempt to call malloc with a negative argument, which cast to an unsigned value, caused a crash.

sw_engine: fix TexmapPolygon rastering

---

src/loaders/lottie/tvgLottieBuilder.cpp

The occurrence of a 'carriage return' (13) or 'end of text' (3) caused the skipping of the next character check, immediately searching for it in the list of available characters. If the next character was also 13 or 3, it led to incorrect interpretation; however, if it was the last character in the sequence, a crash occurred.
modified sample (line 108: ```"t": "START\r\rSTART",```:
[text.json](https://github.com/user-attachments/files/16674490/text.json)
before (missing one \r):
after:
for line 108: ```"t": "START\r",``` crashed occured before this change

lottie: fix text update

---

src/common/tvgMath.h
src/loaders/lottie/meson.build
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieBuilder.h
src/loaders/lottie/tvgLottieExpressions.h
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieModifier.cpp
src/loaders/lottie/tvgLottieModifier.h
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieParser.h
src/loaders/lottie/tvgLottieProperty.h

Due to the lack of an analytical solution for Bezier
curves offsetting, a simple and computationally cheap
approximation has been implemented. The algorithm shifts
the segments connecting control points and determines
new points based on their intersections.
@issue: https://github.com/thorvg/thorvg/issues/2230
(shapes with the same color should look the same, they have different directions)
[samples.zip](https://github.com/user-attachments/files/16631126/samples.zip)

lottie: add partial offsetPath support

---

src/renderer/gl_engine/tvgGlGeometry.h
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlTessellator.cpp

This PR fix the stroke miter not working as expect and contains the following changes:
* correct the stroke width and color calculation with scaling
* fix the miter limit calculation to make bevel join fallback correct
issue: https://github.com/thorvg/thorvg/issues/2435

gl_engine: fix mistake in the calculation of stroke miter limit

---

src/loaders/lottie/tvgLottieExpressions.cpp
src/loaders/lottie/tvgLottieProperty.h

Prevent expression processing if a property fails to parse.
This is a hotfix to address expression-related crashes.

lottie/expressions: Improve safety

---

src/renderer/wg_engine/tvgWgBindGroups.cpp
src/renderer/wg_engine/tvgWgBindGroups.h
src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgCompositor.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h

Masking workflows optimized:
* used hardware blending stage for scene blending
* used AABB for scene blending
* reduced number of offfscreen buffers coping
* reduced number of render pass switching
* used render pipelines abilities to convert offscreen pixel format to screen pixel format
* removed unused shaders
+15% performance boost in avarage in animations with masks
masking.json animation:
before - 200 fps, after - 235 fps

wg_engine: masking optimization - PART 3

---

src/loaders/lottie/tvgLottieModel.cpp

To avoid editing the trim path values provided
by the user, the logic for their interpretation
was moved from the API to the renderer (7c87d8e).
This caused an issue in the lottie animations when the trim path is applied more than once. Now fixed.
@issue: https://github.com/thorvg/thorvg/issues/2670
before:
after:
sample:
[11483_part.json](https://github.com/user-attachments/files/16770250/11483_part.json)

lottie: fix trim path regression

---

src/loaders/lottie/tvgLottieBuilder.cpp

The bug caused the trim path to not be applied
when it appeared in a group between different
shapes.
before:
after:
sample:
[trim.json](https://github.com/user-attachments/files/16770152/trim.json)

lottie: fix trim

---

src/loaders/svg/tvgSvgLoader.cpp

The range of saturation and brightness values is 0 ~ 100% and range of hue is 0 ~ 360.
If a value greater than 100% is loaded, it will be modified to be 100%.
issue: https://github.com/thorvg/thorvg/issues/2678

svg_loader: Adjust hsl values out of range

---

src/loaders/lottie/tvgLottieExpressions.cpp

Stabilized $bm_sum(), by allowing the different dimensional arguments.
issue: https://github.com/thorvg/thorvg/issues/2664

lottie/expressions: hotfix a crash

---

src/common/tvgMath.cpp
src/common/tvgMath.h

An uint8_t version of the lerp function
is introduced to handle cases where
the interpolation factor t exceeds 1, which
previously caused overflow issues due to casting.
[sample.json](https://github.com/user-attachments/files/16715605/sample.json)
before:
after:

common: uint8_t version of the lerp

---

src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwRaster.cpp
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/sw_engine/tvgSwRenderer.h
src/renderer/tvgPaint.cpp
src/renderer/tvgPicture.cpp
src/renderer/tvgRender.h
src/renderer/tvgScene.h
src/renderer/tvgShape.h
src/renderer/tvgText.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

Blending anti-aliased parts has been rectified
before:
after:

++ blendings

---

src/renderer/sw_engine/tvgSwShape.cpp

The limit on leftovers was too small, which became noticeable for animations with trimming - currently implemented with the dashing alg.
The limit has been increased.
before (stuttering in animation smoothness):
after:
sample:
[acc.json](https://github.com/user-attachments/files/16797662/acc.json)

sw_engine: increased accuracy in dashing

---

src/common/tvgMath.cpp
src/common/tvgMath.h
src/loaders/lottie/tvgLottieModel.cpp

According to the definition of trim path elements,
the begin and end values are specified as percentages
in the range of 0-100% (this is also confirmed by AE,
where it's not possible to exceed this range).
Added clamping to align with specs.
before:
after:
sample:
[part.json](https://github.com/user-attachments/files/16788631/part.json)

lottie: handle trim path edge cases

---

src/loaders/ttf/tvgTtfLoader.cpp
src/loaders/ttf/tvgTtfReader.cpp

Whitespace is processed as valid glyph without an outline.
If for any reason an invalid glyph is found in text, it will now be skipped when rendering (instead of increasing offset by last valid glyph advance).
Closes #2687

loader/ttf: Spaces and invalid glyphs rendering fix

---

src/common/tvgMath.cpp
src/common/tvgMath.h

A numerically motivated limit on the matrix determinant set at 1e-6 was not sufficient. The limit has been increased.
before:
after:
sample:
[icons.svg.zip](https://github.com/user-attachments/files/16851194/icons.svg.zip)

common: precision increase while matrix inversion

---

src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwRaster.cpp
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/sw_engine/tvgSwRenderer.h
src/renderer/tvgPicture.cpp
src/renderer/tvgRender.h
src/renderer/tvgShape.h
src/renderer/tvgText.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

Corrected the alpha interpolation order during blending. This also corrected the hard mix blending result in the guitar sample.
before:
after:

sw_engine: rectified the blending operations.

---

src/renderer/tvgText.h

Allow the canvas to pass through
even if text elements are not properly supported.
issue: https://github.com/thorvg/thorvg/issues/2715

renderer: ++reliability in text drawing

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp

Issue: #2178 
Compute line spacing based on the text range selector, applying the maximum spacing value for each line.
---
[line-spacing-10px-sample.json](https://github.com/user-attachments/files/16925626/line-spacing-10px-sample.json)

lottie/text: Support line spacing

---

src/loaders/lottie/tvgLottieExpressions.cpp

added missing velocityAtTime() for float types.
issue: https://github.com/thorvg/thorvg/issues/2724

lottie: ++expressions coverage

---

src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/tvgShape.h

prevent a nullptr memory access
regression by f5337015e971d24379d2ee664895503ab8945e13
issue: https://github.com/godotengine/godot/issues/97078

renderer: hotfix a crash

---

src/renderer/wg_engine/tvgWgGeometry.cpp

Vertex ordering during line join needed adjustment. Vertices were forming two partialy overlapping triangles instead of a rectangle. The issue was rarely visible since the resulting rectangle often overlapped significantly with other rectangles.
before:
after:
sample:
```
shape->moveTo(-2, -40);
shape->lineTo(34.641, 20);
shape->lineTo(-34.641, 20);
shape->lineTo(0, -40);
shape->close();
shape->strokeFill(255, 0, 0, 150);
shape->strokeWidth(20);
shape->strokeCap(tvg::StrokeCap::Butt);
shape->strokeJoin(tvg::StrokeJoin::Bevel);
```

wg_engine: fix vertices while line joining

---

src/loaders/lottie/tvgLottieParser.cpp

If randomize is not enabled, "rn" prop falls into skip()
---
[36644.json](https://github.com/user-attachments/files/17054054/36644.json)
It won't be rendered after latest text range patch.

lottie/text: hotfix for parsing text range issue

---

examples/Clipping.cpp
examples/PictureRaw.cpp
examples/TvgSaver.cpp
examples/meson.build
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/svg/tvgSvgSceneBuilder.cpp
src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/sw_engine/tvgSwRle.cpp
src/renderer/tvgPaint.cpp
src/renderer/tvgPaint.h
test/capi/capiPaint.cpp
test/testPaint.cpp
test/testSwEngine.cpp

Separate clip function from the Composite() clipping and composition can be used together.
This helps avoid the introduction of nested scenes  when composition and clipping overlap.
Deprecated:
```
enum class CompositeMethod::ClipPath
enum Tvg_Composite_Method::TVG_COMPOSITE_METHOD_CLIP_PATH
```
Experimental API:
```
- Result Paint::clip(std::unique_ptr<Paint> clipper)
- Tvg_Result tvg_paint_set_clip(Tvg_Paint* paint, Tvg_Paint* clipper)
```
Issue: https://github.com/thorvg/thorvg/issues/1496

Introduced Paint::clip() API

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.h

Improving text render compatibility by fixing wrong Text Range.
When lottie doesn't have `end` prop in the range, system must ignore condition regarding to `end`.
The original logic unintentionally swaps `start` and `end` prop, because `end` is the zero in this case. Then the text range animation behaves the opposite.
---
This fixes 5 animations below. It might work for the others which look opposite in animation and run by text range selector.
- [27329.json](https://github.com/user-attachments/files/17039125/27329.json)
- [18580.json](https://github.com/user-attachments/files/17039136/18580.json)
- [17939.json](https://github.com/user-attachments/files/17039138/17939.json)
- [36644.json](https://github.com/user-attachments/files/17039139/36644.json)
- …

lottie/text: Fix incorrect text range without end condition

---

src/renderer/wg_engine/tvgWgGeometry.cpp
src/renderer/wg_engine/tvgWgGeometry.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h

Fixed visual arifacts:
* angular circles
* extra triangles
* wrongly closed polylines
Animations to verify:
* 5344-honey-sack-hud.json
* birth_stone_logo.json
* insta_camera.json
* polystar.json
* starstrips.json
see: https://github.com/thorvg/thorvg/issues/2685

wg_engine: fix strokes triangulation artifacts

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h

When stroke-width unit is percentage, loader refer to the normalized diagonal of viewport.
+) Add Width type so as not to affect existing types.
https://svgwg.org/svg2-draft/painting.html#StrokeWidth
https://svgwg.org/svg2-draft/coords.html#Units
example)
```
<svg width="100" height="50" xmlns="http://www.w3.org/2000/svg">
<rect x="15" y="15" width="70" height="20" fill="none" stroke="#F00" stroke-width="10%"/>
<rect x="15" y="15" width="70" height="20" fill="none" stroke="#00F" stroke-opacity=".3" stroke-width="10"/>
</svg>
```
related issue: https://github.com/thorvg/thorvg/issues/2131

svg_loader: Fix calculation when stroke-width unit is percentage

---

src/bindings/wasm/tvgWasmLottieAnimation.cpp

Updated the WebGPU engine API to align with the latest interface.
Static/Single instance, adapter and device to support multiple canvases on the browser.
Moved the WGPU request part to `initWGInstance` helper function. This must only be called once, even when multiple players are involved.
Issue: #2695

wasm: Handle WebGPU part for integration

---

src/loaders/svg/tvgSvgLoader.cpp

regarding https://github.com/thorvg/thorvg/pull/2750#issuecomment-2364333927 by @MewPurPur 
before:
after:
sample:
```
<svg width="1600" height="600" xmlns="http://www.w3.org/2000/svg">
<rect x="10%" y="100" width="40%" height="400" fill="none" stroke="#00f" stroke-width="10%" />
<circle cx="20%" cy="250" r="10%" opacity="0.5" />
</svg>
```

svg_loader: fix circle radius if in percentages

---

src/loaders/jpg/tvgJpgd.cpp

../src/loaders/jpg/tvgJpgd.cpp:867:36: warning: ‘*&P.DCT_Upsample::Matrix44::v[0][0]’ may be used uninitialized [-Wmaybe-uninitialized]
https://github.com/thorvg/thorvg/issues/2639

loader/jpg: --compiler warnings

---

src/renderer/wg_engine/tvgWgGeometry.h
src/renderer/wg_engine/tvgWgRenderData.cpp

[wg_engine: fix stroke trimming](https://github.com/thorvg/thorvg/commit/8e907fc62d4eccb97d4c0c07f4125e8d41dc337c) 
Fix cases when begin < 0 - this require handling the stroke
in two parts: begin - 0 and 0 - end.
Improve trimming for simultaneous=true.
[wg_engine: prevent adding duplicate points while trimming](https://github.com/thorvg/thorvg/commit/6edf12830df606db865ad75802c3d4ff3d743801) 
In cases where the distance between points is 0, further
processing of the points results in division by zero.
To avoid this check, we ensure that duplicate points are
not added during trimming.
1) SIMUL = TRUE:
before (sw vs wg):
after:
2) SIMUL = FALSE:
before (sw vs wg):
after:
sample:
```
auto sim = false;
shape1->appendRect(10, 10, 100, 100); …
```

wg_engine: fix stroke trimming

---

src/renderer/sw_engine/tvgSwRaster.cpp

8bit translucent gradient rle were missing AA. Fixed.
sample: 
[mask_op_99_rle.json](https://github.com/user-attachments/files/17156436/mask_op_99_rle.json)
before (see corners):
after:

sw_engine: fix translucent grad rastering

---

src/renderer/tvgPaint.cpp

Fast track was applied for clippers even if they
were also clipped. As a result their clips were
omitted.
@Issue: https://github.com/thorvg/thorvg/issues/2777
before:
after:
sample:
```
//correct
{
auto rect1 = tvg::Shape::gen();
rect1->appendRect(0,0,800,800);
rect1->fill(0,0,255);
shape1->moveTo(65, 15);
shape1->lineTo(165, 15);
shape1->lineTo(165, 115);
shape1->lineTo(65, 115);
shape1->lineTo(65, 15);
shape1->close();
shape1->fill(255, 0, 0);
auto bbox1 = tvg::Shape::gen();
bbox1->appendRect(70, 20, 20, 100);
shape1->composite(std::move(bbox1), tvg::CompositeMethod::ClipPath);
rect1->composite(std::move(shape1), tvg::CompositeMethod::ClipPath);
canvas->push(std::move(rect1));
}
//not correct
{
float shift = 100;
auto rect1 = tvg::Shape::gen(); …
```

renderer: fix clipped clippers

---

examples/MultiCanvas.cpp

adjusted the size according to the offsets.

examples: fixed an incorrect buffer size.

---

src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgCompositor.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h

wg_engine needs to refactor to remove the enum value usage before proceeding with its removal.
Please, see TODO in tvgWgPipelines.h/cpp
see https://github.com/thorvg/thorvg/issues/2783

wg_engine: CompositeMethod::ClipPath will be replaced with the Scene::clip()

---

src/loaders/lottie/tvgLottieParser.cpp

Mem leak was observed in a case the end values
(deprecated feature) were provided for the gradient.
@Issue: https://github.com/thorvg/thorvg/issues/2667

lottie: fix mem leak

---

src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/gl_engine/tvgGlShaderSrc.cpp
src/renderer/gl_engine/tvgGlShaderSrc.h

Add new shader to support darken and lighten mask method.
---------
Now the MaskingMethod example is correct:

gl_engine: implement darken and lighten mask method

---

src/loaders/lottie/tvgLottieModel.cpp

When populating the gradient, the color/alpha should be assigned the first possible value from the provided ones, rather than the default value of 255.
this problem is preset in https://github.com/thorvg/thorvg/issues/2765 in 23.json file, but this is not the main issue.
before:
after (same as skottie, lottie web SVG; lottie web canvas seems not to use alpha):
sample:
[fixPopulate.json](https://github.com/user-attachments/files/17189552/fixPopulate.json)

lottie: fix gradient populating

---

src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h

the color stop number should be retained during
the population of frames
issue: https://github.com/thorvg/thorvg/issues/2765

lottie: fixed a corrupted colorstop population

---

examples/ImageRotation.cpp

M_PI was not declared error solved

examples: fix mingw build error

---

src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwMath.cpp
src/renderer/sw_engine/tvgSwStroke.cpp

During the stroke's outline calculation, the function handling small cubics set all angles to zero. When the cubic was small but not zero, this resulted in incorrect outlines. Now such curves are ignored.
Co-Authored-By: Hermet Park <hermet@lottiefiles.com>
Issue: https://github.com/thorvg/thorvg/issues/2776
Issue: https://github.com/thorvg/thorvg/issues/2712

sw_engine: ignore small cubics

---

.github/workflows/memcheck_valgrind.sh

Previously, if "definitely lost:" was included, it was always decided an error.
Therefore, I modified it to recognize the size and number of errors.
https://github.com/thorvg/thorvg/issues/2817

infra: Improve valgrind result analysis syntax

---

src/renderer/wg_engine/tvgWgShaderSrc.cpp

fixed incorrect opacity applience for scene blending
See guitar.json
Before/After

wg_engine: fix custom scene blending with opacity

---

cross/wasm32_wg.txt

Current WG Engine requires a minimum stack size of 1024KB to function properly.
---
STACK_SIZE must be increased for WG Engine's requirements.
As a result, less than 1024KB doesn't work with WebGPU, increased to minimal size.

wasm: increase stack size for WebGPU

---

src/renderer/wg_engine/tvgWgGeometry.h

fixed crash with shape have too big path.
update vertex array sizes
see PictureSvg example:

wg_engine: fix long path decoding crash

---

cross/wasm32_wg.txt

Patch #2826 increased the stack size to 4MB

wasm: increase stack size

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieModifier.h
src/loaders/lottie/tvgLottieParser.cpp

Implemented the mask attribute 'x' - expand mask.
Enforced rounded lines join according to tests in AE.
@Issue: https://github.com/thorvg/thorvg/issues/2832
sample: 
[expansion.json](https://github.com/user-attachments/files/17304492/expansion.json)

lottie: add support for mask expansion

---

examples/Blending.cpp
examples/Duplicate.cpp
examples/InvLumaMasking.cpp
examples/InvMasking.cpp
examples/LumaMasking.cpp
examples/Masking.cpp
examples/MaskingMethods.cpp
examples/PictureRaw.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/loaders/raw/tvgRawLoader.cpp
src/loaders/raw/tvgRawLoader.h
src/renderer/tvgLoader.cpp
src/renderer/tvgLoader.h
src/renderer/tvgPicture.cpp
src/renderer/tvgPicture.h
test/capi/capiPicture.cpp
test/testPicture.cpp
test/testSwEngine.cpp

Use ColorSpace to support various types of raw bitmaps.
API Modifications:
- Result Picture::load(uint32_t* data, uint32_t w, uint32_t h, bool premultiplied, bool copy = false) -> Result Picture::load(uint32_t* data, uint32_t w, uint32_t h, ColorSpace cs, bool copy = false)
- Tvg_Result tvg_picture_load_raw(Tvg_Paint* paint, uint32_t *data, uint32_t w, uint32_t h, bool premultiplied, bool copy) -> Tvg_Result tvg_picture_load_raw(Tvg_Paint* paint, uint32_t *data, uint32_t w, uint32_t h, Tvg_Colorspace cs, bool copy)

api: polish the thorvg API usages

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h

- enum class PathCommand -> enum class PathCommand : uint8_t
- enum class Result::Unknown (6) -> enum class Result::Unknown = 255
- typedef enum Tvg_Path_Command -> typedef uint8_t Tvg_Path_Command
- TVG_RESULT_UNKNOWN (6) -> TVG_RESULT_UNKNOWN = 255

api: path data size reduction (to 1 byte)

---

src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/gl_engine/tvgGlTessellator.h

Implement the path trim claculation, and handle the strokeTrim before doing Path stroke.
issue: https://github.com/thorvg/thorvg/issues/2435

gl_engine: implement path trim in tvgGlTessellator

---

src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgGeometry.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderer.cpp

see https://github.com/thorvg/thorvg/issues/2843
fixed zero points path hendling
created a single shared instance of stoke generator in heap, instead of stack. No performace impact in this case

wg_engine: fix aabb for empty shapes and long paths

---

src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/lottie/tvgLottieLoader.h

there is no need to retain the data,
as the Lottie source is not reusable
and is affected by the parsing mechanism.
issue: https://github.com/thorvg/thorvg/issues/2647

lottie: release memory immediately after loading is complete.

---

src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgCompositor.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h

Apply custom blending using fragment shaders instead of compute shaders
This reduces the number of context switches (from 4 to 2) when using a custom blend
Also removes artifacts on surface boundaries when using analiasing (will be added in part 2).

wg_engine: MSAA support, part 1 - move blending to fragment shaders

---

src/loaders/lottie/tvgLottieParser.cpp

The color input will contain at least colorStops.count * 4 elements (not including alpha). Since the alpha offset values don't have to much colorStops, estimation is used.

lottie: correct the array reserved size

---

src/renderer/sw_engine/tvgSwRaster.cpp

Since the source buffer is 32 bits, not 8 bits,
both alpha and inverse alpha need to be calculated.

sw_engine: fix _rasterDirectImage

---

src/common/tvgMath.h
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModifier.cpp
src/loaders/lottie/tvgLottieModifier.h
src/loaders/lottie/tvgLottieProperty.h

According to tests in AE, the offset direction should not depend on the direction of the shape. A positive offset value expands the shape, while a negative value contracts it. Fixed.
note: 
Comparing the results with Lottie-web was misleading.

lottie: offset does not depend on shape direction

---

src/renderer/gl_engine/tvgGlShaderSrc.cpp

Change the shader to ignore the alpha from masking color.
related issue: #2879

gl_engine: ignore masking alpha when calculate inv luma masking

---

src/renderer/sw_engine/tvgSwFill.cpp

properly filtering alpha channel of the 8bits linear gradient masking drawing.
issue: https://github.com/thorvg/thorvg/issues/2204

sw_engine: fixed linear gradient filling masking.

---

src/renderer/tvgLoader.cpp

Do not allow data sharing among same svg instances. This should be addressed properly.

renderer: hotfix a broken svg file sharing

---

src/renderer/wg_engine/tvgWgGeometry.h

Use tvg pi constant instead of cmath. better mingw compiler support on windows

wg_engine: use tvg math constants

---

src/loaders/svg/tvgXmlParser.cpp

runtime error: applying non-zero offset 1 to null pointer Observed for Bespoke-leather-belt-2016012857.svg

svg: prevent runtime error

---

src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgCompositor.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h

Full review of clipping workflow.
Before we are used separate render target for each clip path and compute shader to find clip path intersections with AND logic.
Now we are using depth buffer and transactions from depth to stencil and back to get AND logic intersections,
Compute shaders, layouts and pipelines was removed
Result:
Few clippathes on the single frame, frog_vr.json (Before/After)
Massive clippathes on the single frame, 5317-fireworkds.json (Before/After)

wg_engine: clippath optimization

---

src/renderer/wg_engine/tvgWgShaderSrc.cpp

Pre-multiplied color on alpha chanel applied
See starburst.json
Issue https://github.com/thorvg/thorvg/issues/2685
Before:
After:

wg_engine: fixed image and scene normal blend

---

src/renderer/gl_engine/tvgGlGeometry.cpp
src/renderer/gl_engine/tvgGlGpuBuffer.cpp
src/renderer/gl_engine/tvgGlGpuBuffer.h
src/renderer/gl_engine/tvgGlRenderer.cpp

WebGL has a strict rule that does not allow the same GLBuffer to be bound to both ARRAY_BUFFER and ELEMENT_ARRAY_BUFFER at the same time. (https://registry.khronos.org/webgl/specs/latest/1.0/#5.14.5)
To support WebGL in the future, a separate GLBuffer is used to store index data.
prepare for #2837

gl_engine: seperate the index buffer from vertex buffer

---

src/renderer/wg_engine/tvgWgGeometry.h

Fixed cases, if path have equals neighbors points on the path. 
F.e,
```
shape->moveTo(100, 200);
shape->lineTo(100, 200);
```
https://github.com/thorvg/thorvg/issues/2685
See text.json
before:
after:

wg_engine: fix artifacts with zero length segmants on path

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/renderer/tvgPaint.h

Since the translate API was used while text updating, the subsequent range selector transformations gets overwritten when updating the shape (scale and rotate, adding another translation will persist). This caused unexpected results. Fixed by using the transform API when additional transformations are needed.
before:
after:
sample:
[textRS.json](https://github.com/user-attachments/files/17463027/textRS.json)

lottie: fix rotation in text range selector

---

src/loaders/lottie/tvgLottieBuilder.cpp

Scaling the entire scene caused unintended scaling of the translation in the text range selector.
before: 
after:
sample:
[size30.json](https://github.com/user-attachments/files/17551634/size30.json)
[size50.json](https://github.com/user-attachments/files/17551636/size50.json)

lottie: fix text range selector translation

---

src/renderer/wg_engine/tvgWgShaderTypes.cpp

In case if gradient offsets are equal the last color are used instead of first
f.e
```
//Gradient Color Stops
tvg::Fill::ColorStop colorStops[3];
colorStops[0] = {0, 0, 0, 0, 255};
colorStops[1] = {0, 128, 128, 128, 255};
colorStops[2] = {1, 255, 255, 255, 255};
```
(128, 128, 128) will be used instaed of (0, 0, 0)
See _rg1024_Ufo_in_metalic_style.svg_
https://github.com/thorvg/thorvg/issues/2592
Reference:
Before:
After:

wg_engine: fix equals gradient offsets

---

src/renderer/wg_engine/tvgWgGeometry.h
src/renderer/wg_engine/tvgWgRenderData.cpp

Tesseletion factor now depends on scale matix of the shape
See _vnu.svg_
https://github.com/thorvg/thorvg/issues/2592
Before:
After:

wg_engine: fix cubic splines and circles tesselation quality

---

src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/sw_engine/tvgSwShape.cpp

Shape's bbox represents only fill's render region. Render region of fill and stroke is stored in SwTask. This was visible while rendering shapes with a stroke - fill was to big.
@Issue: https://github.com/thorvg/thorvg/issues/2908
before - fill drawn under the whole stroke
after - fill drawn under half of the stroke - as expected
sample:
```
<svg viewBox="0 0 800 800" xmlns="http://www.w3.org/2000/svg">
<rect fill="red" stroke="white" stroke-width="100" stroke-opacity="0.5" x="300" y="0" width="200" height="600"/>
</svg>
```

sw_engine: fix render fill region

---

src/renderer/wg_engine/tvgWgGeometry.h

Introduced dash offset param for stroke dashes
Issue https://github.com/thorvg/thorvg/issues/2592
see _patch.svg_ 
Before:
After:
Reference (edge svg):

wg_engine: implement dash offset

---

src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
tools/lottie2gif/lottie2gif.cpp
tools/svg2png/svg2png.cpp

New APIs:
- Tvg_Canvas* tvg_glcanvas_create(void)
- Tvg_Result tvg_glcanvas_set_target(Tvg_Canvas* canvas, int32_t id, uint32_t w, uint32_t h)
- Tvg_Canvas* tvg_wgcanvas_create(void)
- Tvg_Result tvg_wgcanvas_set_target(Tvg_Canvas* canvas, void* instance, void* surface, uint32_t w, uint32_t h, void* device)
issue: https://github.com/thorvg/thorvg/issues/2855

capi: support gl/wg canvases

---

examples/StrokeMiterlimit.cpp
inc/thorvg.h
src/bindings/wasm/tvgWasmLottieAnimation.cpp
src/common/tvgStr.cpp
src/common/tvgStr.h
src/loaders/svg/tvgSvgSceneBuilder.cpp
src/renderer/tvgCommon.h
src/renderer/tvgLoader.cpp
src/renderer/tvgLoader.h
src/renderer/tvgPicture.cpp
src/renderer/tvgPicture.h
src/renderer/tvgSaver.cpp
src/renderer/tvgText.cpp
tools/lottie2gif/lottie2gif.cpp

replaced std::string with char* in API parameters.
- Result Picture::load(const std::string& path) -> Result Picture::load(const char* filename)
- Result Picture::load(const char* data, uint32_t size, const std::string& mimeType, const std::string& rpath = "", bool copy = false) -> Result Picture::load(const char* data, uint32_t size, const char* mimeType, const char* rpath = "", bool copy = false)
- Result Text::load(const std::string& path) -> Result Text::load(const char* filename)
- Result Text::load(const char* name, const char* data, uint32_t size, const std::string& mimeType = "ttf", bool copy = false) -> Result Text::load(const char* name, const char* data, uint32_t size, const char* mimeType = "ttf", bool copy = false)
- Result Text::unload(const std::string& …

api: revise the apis for v1.0

---

src/renderer/gl_engine/tvgGlGpuBuffer.cpp
src/renderer/gl_engine/tvgGlGpuBuffer.h
src/renderer/gl_engine/tvgGlRenderer.cpp

This PR fix a low-level error in GL backend :(
The CPU buffer cache in the IndexBuffer object needs to be cleared, otherwise it will cause memory leaks and reduce performance per frame

gl_engine: Fix memory leak in the IndexBuffer object

---

src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderTypes.cpp
src/renderer/wg_engine/tvgWgShaderTypes.h

Implemented gradien focal points
Issue https://github.com/thorvg/thorvg/issues/2728 
Issue https://github.com/thorvg/thorvg/issues/2936
See https://skia.org/docs/dev/design/conical/
The implementetion provide general solution for the equation, solved by t
```
Setting Up the Equations
Interpolated Center:
Ct = (1-t) * C0 + t * C1
Interpolated Radius:
rt = (1-t) * r0 + t * r1
Distance from Ct to Pt:
|Pt - Ct| = rt
```
No any impact on performance
Before/After:
Before/After:

wg_engine: support gradient focal point

---

src/renderer/gl_engine/tvgGlCommon.h
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlShaderSrc.cpp

This PR support the new RadialGradient API.
The mathematical calculation comes from https://skia.org/docs/dev/design/conical/
related issue: #2907 #2728 #2936
Now the gradient parts is rendering correct:

gl_engine: Support new radial gradient data struct and calculation

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h

Change in the algorithm for selecting characters included in the range selector. This is the first step towards adding support for maxAmount, smoothness, and easing.
Smoothness and maxAmount added.
@Issue: https://github.com/thorvg/thorvg/issues/2178
AE vs this pr (not sync)
[smoothness.json](https://github.com/user-attachments/files/17581496/smoothness.json)

lottie: text range selector++

---

examples/Capi.cpp
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
test/capi/capiLinearGradient.cpp
test/capi/capiRadialGradient.cpp

API Removal:
- Tvg_Result tvg_shape_set_stroke_linear_gradient(Tvg_Paint* paint, Tvg_Gradient* grad)
- Tvg_Result tvg_shape_set_stroke_radial_gradient(Tvg_Paint* paint, Tvg_Gradient* grad)
- Tvg_Result tvg_shape_set_shape_linear_gradient(Tvg_Paint* paint, Tvg_Gradient* grad)
- Tvg_Result tvg_shape_set_shape_radial_gradient(Tvg_Paint* paint, Tvg_Gradient* grad)
API Addition:
- Tvg_Result tvg_shape_set_stroke_gradient(Tvg_Paint* paint, Tvg_Gradient* grad)
- Tvg_Result tvg_shape_set_shape_gradient(Tvg_Paint* paint, Tvg_Gradient* grad)

capi: unified the separate linear and gradient fill APIs

---

src/renderer/gl_engine/tvgGlRenderer.cpp

This PR fix the Lottie example becoming slower with each frame
It is caused by the clip tasks with the GlShape.
The clips need to be cleared every time when shape update. Otherwise, the increasing number of clips will hurt the performance.

gl_engine: Fix repeated clip drawing causes performance degradation

---

src/loaders/lottie/tvgLottieBuilder.cpp

sample for opacity:
[opacity2.json](https://github.com/user-attachments/files/17701801/opacity2.json)
tvg:
AE:
sample for fill opacity:
[fillOp1.json](https://github.com/user-attachments/files/17701866/fillOp1.json)
tvg:
AE:

lottie: text range opacity ++

---

examples/meson.build
test/meson.build

Fixed conflict with ThorVG and Cocoa framework (required for webgpu on macos): Point is **ambiguous** type in a case of macos usage.
Conflics appears only in case of **examples + test + wg** compilation:
`meson setup builddir -Dexamples=true -Dtests=true -Dengines="wg"`
Tests must be compiled before examples, where Cocoa are included
Also fixed **try** issue by adding compilations flags to support exceptions in a case of macos usage
Issue https://github.com/thorvg/thorvg/issues/2938
_Alternatively_ we can do not change order of the compilation, but change variable declarations in testShape.cpp from Point to tvg::Point, that also removes ambiguous, f.e.
`const tvg::Point* pts2;`
but not
`const Point* pts2;`

wg_engine: fix test build scripts and ambiguous declarations for macos

---

src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h

Use anisotropy filter for gradient fills
Not performance impact
Issue https://github.com/thorvg/thorvg/issues/2931
Before/After

wg_engine: fix radial fill anti-aliased drawing

---

src/bindings/wasm/tvgWasmLottieAnimation.cpp

Removed data copy for gif saving.
Binding function `save` has changed:
- bool save(string data, string mimetype)

wasm: Enhance gif saving without data copy

---

src/loaders/lottie/tvgLottieParser.cpp

"conversion from 'float' to 'int8_t', possible loss of data"

infra: prevent warning on windows

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp

Reverted commit db800c8d4500cd379238c4ec1c9f6c59e70fe908, which introduced another regression that omitted support for multiple image asset references.
Updated the data of active images in the pooler
within the override() function to resolve the issue.

lottie: Fixed a regression bug

---

examples/Example.h

Free the canvas in the reverse order of their creation.

example: ++gl, wgpu safety

---

src/loaders/lottie/tvgLottieExpressions.cpp

'end' used instead of 'offset'

lottie: fix bug in expressions

---

src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

We must to dispose all paints before the context will be destroyed to prevent wegpu handles leak, including Shapes and Pictures by using objects pools as global object registers
see: PicturePng, PictureJpg
PicturePng sanitizer report: Before

wg_engine: fix resources disposing on context destroy

---

examples/Example.h
examples/MultiCanvas.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/bindings/wasm/tvgWasmLottieAnimation.cpp
src/renderer/tvgWgCanvas.cpp

- Result WgCanvas::target(void* device, void* instance, void* target, uint32_t w, uint32_t h, int type = 0) -> Result WgCanvas::target(void* device, void* instance, void* target, uint32_t w, uint32_t h, ColorSpace cs, int type = 0)
- Tvg_Result tvg_wgcanvas_set_target(Tvg_Canvas* canvas, void* device, void* instance, void* target, uint32_t w, uint32_t h, int type) -> Tvg_Result tvg_wgcanvas_set_target(Tvg_Canvas* canvas, void* device, void* instance, void* target, uint32_t w, uint32_t h, Tvg_Colorspace cs, int type)

renderer: reserved colorspace option in target api

---

cross/wasm32_gl.txt
src/bindings/wasm/tvgWasmLottieAnimation.cpp
src/renderer/gl_engine/meson.build
src/renderer/gl_engine/tvgGlCommon.h
wasm_build.sh

This PR support cross compile the GL backend code into WASM. The code needs WebGL 2.0 API so, the compile flags contains `MAX_WEBGL_VERSION` and `FULL_ES3` Also add binding code to initialize the WebGL context and GLCanvas.
With this PR, the wasm binary contains WebGL backend rendering, the rest of the work will need to be supported by the thorvg.web project.
issue: #2837

gl_engine: support cross compile GL backend into WASM

---

src/renderer/gl_engine/tvgGlCommon.h
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlTessellator.cpp

This PR fix the wrong matrix scale factor value caused the stroke alpha to be zero when the matrix contains rotation.
issue: #2997
------
Some case is correct.
1. abstract_circle.json
2. anubis.json
3. kote.json
4. swinging.json

gl_engine: correct the stroke alpha calculation

---

src/bindings/wasm/tvgWasmLottieAnimation.cpp

Added missing parameter for `GlCanvas->target`

wasm: fix build error

---

src/renderer/wg_engine/tvgWgBindGroups.cpp
src/renderer/wg_engine/tvgWgBindGroups.h
src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgCompositor.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

The main reason of refactoring is to separate bind group sets and pipelines, and change owning of pipelines to compositor
It will be helpfull for resizing (intermidiate changes)
Should not impact to performance and web player
see: Svg example

wg_engine: separate pipelines ans bind group layouts (refactoring)

---

src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgShaderSrc.cpp

Apply texture color space on texture creation, instead of shader side
Make final color equation same for all blend types
see: PicturePng, PictureJpg examples

wg_engine: apply texture formats on creation (refactoring)

---

src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgShaderTypes.cpp
src/renderer/wg_engine/tvgWgShaderTypes.h

Use universal vec4f type for blend settings and color to pass data as shader parameter
see: Blending examples

wg_engine: simplify shader types (refactoring)

---

src/renderer/gl_engine/tvgGlGeometry.cpp

This PR fix some rendering error in **Lottie** example. 
related issue: #2799 
--------
* a_mountain.json
* balloons_with_string.json
* water_filling.json
* card_hover.json

gl_engine: Fix the wrong bounds cause composition not correct

---

meson.build
meson_options.txt
src/loaders/external_jpg/tvgJpgLoader.cpp
src/loaders/external_png/tvgPngLoader.cpp
src/loaders/external_webp/tvgWebpLoader.cpp
src/loaders/jpg/tvgJpgLoader.cpp
src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/png/tvgPngLoader.cpp
src/loaders/svg/tvgSvgLoader.cpp
src/loaders/ttf/tvgTtfLoader.cpp
src/loaders/webp/tvgWebpLoader.cpp
src/renderer/tvgLoader.cpp
src/renderer/tvgPicture.cpp
src/renderer/tvgText.cpp

certain systems, may not support file I/O operations. ThorVG should provide users with an option to configure builds according to their requirements.
This ensures that file I/O calls are avoided,
preventing potential crashes.
Please use the meson '-Dfile=true/false' option for this.
issue: https://github.com/thorvg/thorvg/issues/3008

renderer: make the file io configurable.

---

src/bindings/capi/thorvg_capi.h

- Standardized usage of "\" and "@" across the documentation.
- Aligned formatting with C++ Doxygen style guidelines.

capi: maintain consistency in Doxygen formatting

---

AUTHORS
src/renderer/sw_engine/tvgSwRle.cpp

Since longjmp is not yet fully supported on Wasm (emscripten uses JS to make the jumps and requires slow jumps), but also because longjmp is hard to reason about, this patch replaces it with return values. The logic stays exactly the same.

sw_engine: replaced longjmp with returns

---

src/bindings/capi/thorvg_capi.h

C does not support default arguments. For thorvg_capi.h to maintain C compatibility, default arguments must be omitted.

capi: removed default argument from C API.

---

src/bindings/wasm/tvgWasmLottieAnimation.cpp

Use <emscripten/html5_webgpu.h> for browser-specific WebGPU support.

wasm: switch to Emscripten-specific WebGPU header

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieCommon.h
src/loaders/lottie/tvgLottieParser.cpp

before:
after:
AE:
sample:
[CAPS_COMPARISON.json](https://github.com/user-attachments/files/17985153/CAPS_COMPARISON.json)

lottie: add caps support

---

cross/wasm32.txt
cross/wasm32_wg.txt

Reduce stack size to 2MB for optimized memory usage
_Originally posted by @SergeyLebedkin  in https://github.com/thorvg/thorvg/pull/3034#discussion_r1875840029_

wasm: reduce WebGPU stack size

---

src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgCompositor.h
src/renderer/wg_engine/tvgWgRenderer.cpp

In case of resizing recreate only render targets, but not all compositor handles.
Must be verified in web player

wg_engine: improve resizing mechanics

---

src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/gl_engine/tvgGlTessellator.h

This PR rewrite the PathTrim code and fixed almost all the issue caused by PathTrim inside GL backend.
related issue: #2799 
-------
The following cases is correct with this Patch.
* birth_stone_logo
* fly_in_beaker
* frog_vr
* cat_loader
* happy_holidays
* holdanimation
* isometric
* skullboy
* threads
* lolo
* seawalk
* expressions/10151
* expressions/world_locations
* expressions/jolly_walker // This animation is rendered same as Software raster, but I am not sure it is correct
Please check if I am wrong

gl_engine: Fix calculation error in path triming

---

src/bindings/wasm/tvgWasmLottieAnimation.cpp

Following ThorVG API changes (#1372), updated the canvas handling:
- Replaced Canvas::clear() calls with Canvas::remove()

wasm: update canvas API usage from clear() to remove()

---

examples/meson.build

meson.source_root -> meson.project_source_root()
meson.build_root -> meson.project_build_root()

infra: --meson deprecated usages

---

src/renderer/sw_engine/tvgSwFill.cpp

Added a term that was omitted during one of the refactorings.
before:
after:
sample:
```
auto fill = tvg::RadialGradient::gen();
fill->radial(200, 200, 200, 200, 200, 0);
colorStops[0] = {0, 255, 255, 255, 0};
colorStops[1] = {1, 0, 0, 0, 255};
fill->colorStops(colorStops, 2);
shape1->appendRect(0, 0, 400, 400);
shape1->fill(255,0,0);
mask->appendRect(0, 0, 200, 200);
mask->fill(fill);
auto add = tvg::Shape::gen();
add->appendCircle(200, 100, 50, 50);
add->fill(255, 255, 255, 125);
mask->mask(add, tvg::MaskMethod::Subtract);
shape1->mask(mask, tvg::MaskMethod::Alpha);
```

sw_engine: fix grad calculations

---

cross/wasm32.txt
cross/wasm32_wg.txt
src/bindings/wasm/tvgWasmLottieAnimation.cpp

The binary size recently increased due to the ASYNCIFY option, which was required for WebGPU initialization. 
To prevent unnecessary binary size growth, ThorVG will no longer depend on asynchronous processes such as `emscripten_sleep` (ASYNCIFY or JSPI).
As a result, the combined WASM binary size has been significantly reduced to less than 1MB.
Size comparison: 1559KB → 998KB (-36%)

wasm: remove ASYNCIFY to reduce binary size

---

src/renderer/gl_engine/tvgGlRenderer.cpp

This PR fix the color not correct when rendering gradient color in GL backend.
the following issue can be fixed with this patch: #3032, #3030
-----

gl_engine: Fix gradient color not correct when shape has opacity

---

examples/SceneEffects.cpp
inc/thorvg.h
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieParser.h
src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwPostEffect.cpp
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/tvgRender.h
src/renderer/tvgScene.h

The Trintone effect maps the scene's shadows, midtones, and highlights
to three specific colors, allowing for more complex and artistic color grading.
Applied Trintone Formula:
```
if (L < 0.5) Result = (1 - 2L) * Shadow + 2L * Midtone
else Result = (1 - 2(L - 0.5)) * Midtone + (2(L - 0.5)) * Highlight
Where the L is Luminance.
```
https://github.com/user-attachments/assets/cd08810a-4bd0-44ca-8599-c42648d5f7ca
https://github.com/user-attachments/assets/ecdd36c5-d1f8-493c-96c0-87720a9b470c
issue: https://github.com/thorvg/thorvg/issues/2718

Support Trintone Effect

---

src/loaders/lottie/tvgLottieBuilder.cpp

dropshadow opacity range seems 0 ~ 256.
make it sure in 0 ~ 255.

lottie: ++exception handling

---

src/renderer/tvgRender.h

The dash offset value was not copied while
'=' opetator was applied.
@Issue: https://github.com/thorvg/thorvg/issues/1643 (part of the problem)
before:
after:

sw_engine: fix dash offset

---

src/loaders/lottie/tvgLottieLoader.cpp

Resolved an issue where parsing failed due to mismatch between file size obtained via `ftell` and the actual bytes read by `fread`. This occurred because newline translation (`\r\n` to `\n`) in text mode altered the byte count, leading to incorrect assumptions about the data size.

portability: fix file size check on Windows

---

src/renderer/tvgPaint.h

This issue only valid on the main branch, not in the released package.
regression by 1806b329718589a36b606cac5760e41dacb586f6
issue: https://github.com/thorvg/thorvg/issues/3070

renderer: fixed a memory leak

---

inc/thorvg.h
src/renderer/tvgAccessor.cpp

remove the restriction of targeting only Picture.
now, any kind of paints can be adaptable here.

API: enable users to use an accessor to traverse Scene

---

src/loaders/lottie/tvgLottieBuilder.cpp

The scene tree should be arranged prior to appending the masking. This was caused by 838785d75a79f0dbdb12273b4406b3f650855bbf

lottie: Fixed a regression in masking logic

---

src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/gl_engine/tvgGlTessellator.h

As part of this request, I updated ```tvgGlTessellator.cpp``` and ```tvgGlTessellator.h``` to ensure they do not terminate prematurely for paths with a step of 0 or exceptionally small values when a valid ```stroke-width``` is present.
In my opinion, the optimal approach was to separate vertex generation into dedicated methods: ```strokeRoundPoint``` and ```strokeSquarePoint```. My update supports two different ```stroke-cap``` styles. I have also tested it with various files (JSON, SVG) as well as a small example application similar to the one included in the previous pull request (https://github.com/thorvg/thorvg/pull/3066).
Issues: https://github.com/thorvg/thorvg/issues/3065

gl_engine: Fix for rendering short paths

---

src/renderer/sw_engine/tvgSwRenderer.cpp

A shape with both fill and stroke, where clipping left only a fragment of one (either fill or stroke), was not rendered at all. Now fixed.
sample (modified Clipping.cpp):
```
auto star1 = tvg::Shape::gen();
compose(star1); 
star1->fill(255, 255, 0);
star1->strokeFill(255 ,0, 0);
star1->strokeWidth(10);
auto clip1 = tvg::Shape::gen();
clip1->appendCircle(200, 230, 110, 110);
auto scene1 = tvg::Scene::gen();
scene1->push(star1);
scene1->clip(clip1);
auto clip2 = tvg::Shape::gen();
clip2->appendCircle(200, 230, 80, 50);
auto scene2 = tvg::Scene::gen();
scene2->push(scene1);
scene2->clip((clip2));
canvas->push(scene2);
```

sw_engine: fix clipping

---

src/loaders/lottie/tvgLottieLoader.cpp

After resizing animation, base clipper for viewport(of root scene) didn't change. This causes issue that animation always clipped by initial psize.
This also brings v1 regression issue after `Result Picture::size(float w, float h)` function called:
Issue: #3039 
_psize is 500 by 500, and resized to 700 by 700_
**[v1.0-pre]**
Even if resized to bigger, animations shows in initial size(500 x 500)
**[v1.0-pre + this patch]**

lottie: fix viewport clipping issue when resize

---

src/renderer/gl_engine/tvgGlRenderTarget.cpp
src/renderer/gl_engine/tvgGlRenderTarget.h
src/renderer/gl_engine/tvgGlRenderer.cpp

There is a potential memory leaks when GlCanvas change target to a new framebuffer all change size after https://github.com/thorvg/thorvg/commit/ccf5a8158fc7d02679a3dd0d3b6c6ed718385386
Because GlRenderTarget contains framebuffer and render target objects, these GPU resources need to be released before reusing the structure and calling init with the new size.

gl_engine: fix fbo and texture leak

---

src/loaders/svg/tvgSvgSceneBuilder.cpp

If a clip was defined by a use node pointing
to a basic shape subject to transformation, and
the use node itself was translated, the order
of applying these transformations was incorrect.
sample:
```
<svg id="svg1" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
<defs>
<circle id="m1" cx="30" cy="50" r="30" transform="matrix(1 0.44 1 1 0 10)"/>
</defs>
<clipPath id="clip">
<use href="#m1" x="10" y="12"/>
</clipPath>
<rect x="0" y="0" width="100" height="100"  fill="red" clip-path="url(#clip)"
fill-opacity="0.5"/>
<use href="#m1" x="10" y="12" fill="blue" opacity="0.4"/>
<rect x="47" y="52" width="20" height="20"  fill="red"
fill-opacity="0.5"/>
</svg>
```
before:
after:

svg_loader: fix transformation order

---

src/renderer/sw_engine/tvgSwRle.cpp

Remove unused version of SUBPIXELS().

sw_engine: prevent warning

---

src/loaders/lottie/tvgLottieBuilder.cpp

After the stroke clipper is introduced, using clipping
requires ensuring that clipping is based on fill rather
than on stroke. Fixed now.
regression by: 324bff30d15b3be66144a681a5ffa813b7592143

lottie: enforce fill clipper over stroke clipper

---

src/loaders/webp/dsp/dec.cpp

warning: writing 4 bytes into a region of size 0 [-Wstringop-overflow=]

webp: --compiler warning

---

src/renderer/sw_engine/tvgSwRenderer.cpp

This fixes a wrong compositor access
during the rasterization
issue: https://github.com/orgs/thorvg/discussions/3109

sw_engine: assign the stride omitted

---

examples/Capi.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/loaders/svg/tvgSvgSceneBuilder.cpp
src/renderer/tvgPaint.cpp
src/renderer/tvgShape.cpp
test/testShape.cpp

Unify the Path commands & pts getters.
C++ API modiciation:
- uint32_t Shape::pathCommands(const PathCommand** cmds) const
- uint32_t Shape::pathCoords(const PathCommand** cmds) const -> Result Shape::path(const PathCommand** cmds, uint32_t* cmdsCnt, const Point** pts, uint32_t* ptsCnt)
C API modification:
- Tvg_Result tvg_shape_get_path_coords(const Tvg_Paint* paint, const Tvg_Point** pts, uint32_t* cnt)
- Tvg_Result tvg_shape_get_path_commands(const Tvg_Paint* paint, const Tvg_Path_Commands** cmds, uint32_t* cnt) -> Tvg_Result tvg_shape_get_path(const Tvg_Paint* paint, const Tvg_Path_Command** cmds, uint32_t* cmdsCnt, const Tvg_Point** pts, uint32_t* ptsCnt)

api: path api revision for v1.0

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieData.h
src/loaders/lottie/tvgLottieParser.cpp

The text stroke's 'of' property determines whether the stroke appears above (true) or below (false)
the fill.
Previously, it was incorrectly used to decide whether the stroke would render.
@Issue: https://github.com/thorvg/thorvg/issues/3126
before:
after:
samples:
[fill_over_stroke_orange.json](https://github.com/user-attachments/files/18409831/fill_over_stroke_orange.json)
[stroke_over_fill_blue.json](https://github.com/user-attachments/files/18409833/stroke_over_fill_blue.json)

lottie: fix text stroke's 'of' property

---

src/renderer/sw_engine/tvgSwRasterTexmap.h

Fix heap buffer overflow in texture mapping rasterizer by adding proper bounds checking for texture coordinates. This prevents accessing memory outside of the allocated image buffer during texture sampling and interpolation.
---
**Situation:**
At the ` _rasterPolygonImageSegment`, `vv` value gets `-1` then crahses.
**Sample file:** 
[Lottie Runtime Crash Issue 3102.json](https://github.com/user-attachments/files/18373071/Lottie.Runtime.Crash.Issue.3102.json)
**Crash Point:**
Drawing `image_0`
**Fixes**
Added a defense logic for preventing the values get negative value, but this need to be reviewed properly.
Issues: #3102

sw_engine: Fix buffer overflow in texture mapping rasterizer

---

src/loaders/lottie/tvgLottieExpressions.cpp

Prevent segfault in case of the omitted name json data

lottie/expressions: ++safety

---

src/renderer/sw_engine/tvgSwStroke.cpp

The value of the variable 'i' was not modified
after the refactor, resulting in a reference to
an incorrect array element.
from svg samples:
before:
after:

sw_engine: fix bug introduced in 07e73a9

---

src/renderer/wg_engine/meson.build

- Add platform check to exclude webgpu_native in meson.build
- Avoid requiring -Dbindings=wasm_beta for Emscripten builds

chore(build): exclude webgpu_native for emscripten build

---

examples/Interaction.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/loaders/lottie/tvgLottieAnimation.cpp
src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/lottie/tvgLottieLoader.h
src/renderer/tvgAnimation.cpp
src/renderer/tvgFrameModule.h
test/testAnimation.cpp

Changed the unit of the segment from a normalized value to frame numbers, ensuring alignment with other frame control interfaces.
Note that This change may break backward compatibility.

api: revised the animation segment specification

---

src/renderer/wg_engine/tvgWgGeometry.h

Some SVG files fails during stoke dashing on windows.
Fixed

wg_engine: fix segmentation fault on windows with SVG examples

---

src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieParser.h

Unify the common parts of the parsing logic
by applying a strategy pattern,
allowing the behavior to vary based on the effect type.
This helps to reduce the size and improved the parsing safety.

lottie: revise the effect parsing logic

---

src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/sw_engine/tvgSwRenderer.h
src/renderer/tvgRender.h
src/renderer/tvgScene.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

to correctly delete RenderData from effects it must be disposed in the renderer 
a new method has been added to the RenderMethod interface
https://github.com/thorvg/thorvg/issues/3054

engine: introduce scene effect dispose render method

---

src/loaders/lottie/tvgLottieExpressions.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieProperty.h

Point/Position is too ambuguous to classify,
Renamed them to LottieScalar and LottieVector,
and unify the duplicate logic among them.

lottie: clean up code for maintenance

---

src/renderer/tvgPaint.cpp

Replaced ceil and direct casts with nearbyint to improve viewport size calculation. This ensures consistent approach with the fastTrack case in sw_engine.
@Issue: https://github.com/thorvg/thorvg/issues/3148

common: more accurate clipped viewport rounding

---

src/renderer/gl_engine/tvgGlShaderSrc.cpp
src/renderer/sw_engine/tvgSwCommon.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp

samples:
[blurColorBurn.json](https://github.com/user-attachments/files/18572504/blurColorBurn.json)
[blurColorDodge.json](https://github.com/user-attachments/files/18572505/blurColorDodge.json)
before:
after:
AE:
note: skottie results are as from AE, lottie-web are a bit different

wg_engine/sw_engine: fix color burn/dodge edge cases

---

src/renderer/tvgTrimPath.cpp

The idea of introducing epsilon during trimming was to eliminate the occurrence of short segments whose length would be zero when higher computational accuracy was used. By mistake, during the refactor of 8ed4c2f302aa54f15b8f2ca2a09f95c143e3c2e1, one of the conditions was lost. Fixed.
@Issue: https://github.com/thorvg/thorvg/issues/3053

common: add missing condition while trimming

---

src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/tvgSwCanvas.cpp
src/renderer/tvgWgCanvas.cpp
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

Considered global engine initialization and termination. Engines could be used among multiple worker threads.

sw/gl/wg: ++threads safety

---

src/loaders/lottie/tvgLottieModel.cpp
src/renderer/tvgShape.h
src/renderer/tvgTrimPath.cpp

Trimming that passes through the curve's start point (like -0.1:0.1) requires passing through the curve twice. The points obtained from both passes must be joined - visible when dashing
Cases for simultaneous = true have been handled.
@Issue: https://github.com/thorvg/thorvg/issues/3192
sample:
```
if (!canvas) return false;
float dashPattern[2] = {80, 20};
shape1->appendCircle(200, 200, 150, 150);
shape1->fill(55, 0, 255, 100);
shape1->strokeFill(0, 0, 255, 200);
shape1->strokeJoin(tvg::StrokeJoin::Bevel);
shape1->strokeCap(tvg::StrokeCap::Butt);
shape1->strokeWidth(22);
shape1->strokeTrim(-0.25, 0.25, true);
shape1->strokeDash(dashPattern, 2, 40);
```
before:
after:
note:
now includes also https://github.com/thorvg/thorvg/pull/3198

renderer: handle trimming cases passing through 0.0 point

---

examples/Capi.cpp
examples/StrokeTrim.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/svg/tvgSvgSceneBuilder.cpp
src/renderer/tvgShape.cpp
src/renderer/tvgShape.h
test/testShape.cpp

The path direction of shapes is now functional for path trimming. Replace the main logic with Lottie's by default
to align the spec, migrate the original logic to svg loader side.
This revision helps to reduce the binary size by 2–3 KB for lottie loader.
API Modifications:
- Result Shape::appendRect(float x, float y, float w, float h, float rx = 0, float ry = 0) 
-> Result Shape::appendRect(float x, float y, float w, float h, float rx = 0, float ry = 0, bool cw = true)
- Result Shape::appendCircle(float cx, float cy, float rx, float ry)
-> Result Shape::appendCircle(float cx, float cy, float rx, float ry, bool cw = true)
- TVG_API Tvg_Result tvg_shape_append_circle(Tvg_Paint* paint, float cx, float cy, float rx, float ry)
-> TVG_API Tvg_Result tvg_shape_append_circle(Tvg_Paint* paint, …

renderer: revise the Shape rect/circle features

---

src/renderer/tvgTrimPath.cpp

Bug introduced as part of a7e7bbc.
After recalculating begin and end to the 0-1 range, an extra check was added to handle cases when begin is very close to end. However, this was a bad approach since, even for very close values, their relationship remains important. What should have been done in the mentioned commit is properly handling  the case begin == end, which was incorrectly treated as trimming from begin to end. Instead, it should be handled as trimming from begin to 1.0 and from 0.0 to end.
@Issue: https://github.com/thorvg/thorvg/issues/3204
note:
This extra check for whether `begin - end < epsilon` was added because [18859.json](https://github.com/user-attachments/files/18758198/18859.json) was flickering. However, it was not the correct fix - now it's properly handled.

renderer: fix trimmed stroke blinking

---

src/loaders/lottie/jerryscript/jerry-core/ecma/base/ecma-helpers-conversion.cpp
src/loaders/lottie/jerryscript/jerry-core/ecma/base/ecma-helpers-number.cpp
src/loaders/lottie/jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-math.cpp
src/loaders/lottie/jerryscript/jerry-core/ecma/operations/ecma-typedarray-object.cpp

warning: implicit conversion increases floating-point precision

jerryscript: fix warnings on masOS (intel)

---

src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h
src/renderer/wg_engine/tvgWgShaderTypes.cpp
src/renderer/wg_engine/tvgWgShaderTypes.h

wg_engine: optimize gaussian blur effect for webgpu renderer
+10-15% FPS expected on hi resolutions
Single shader instance used for vertical and horizontal blur
Local workgroup memory used for caching texture data for local threads group
Threads configuration changed from 2d to 1d topology
before:
after:

webgpu_gaussian_optimization

---

src/renderer/wg_engine/tvgWgGeometry.h

For an odd number of dash/gap segments, the offset was handled incorrectly because the non-doubled count of dashes and gaps was used.
Additionally, in ddcbbf7, an error was introduced by overlooking the fact that the offset can shift the dash pattern in such a way that the first segment of the dashed line becomes a gap.
samples:
[s.svg.zip](https://github.com/user-attachments/files/18787916/s.svg.zip)
[837.json](https://github.com/user-attachments/files/18787902/837.1.json)

wg_engine: fix dash offset behavior

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieParser.h

Only parsing and font loading is added.
The text update while building the scene
will be handled in a separate commit.
@Issue: https://github.com/thorvg/thorvg/issues/3184
ThorVG
lottie-web

lottie: parsing embedded fonts data

---

src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/sw_engine/tvgSwShape.cpp

In cases where the fill was changed while the stroke existed but remained unchanged, the stroke would disappear because it was being reset during the shape preparing (shapeReset). Fixed by disabling the reset of stroke rle from shape reseting.
Also the shape should be prepared not only when the RenderUpdateFlag is set to Color, but also when it is set to Gradient.
@Issue: https://github.com/thorvg/thorvg/issues/3237
before:
after:
sample (changed FillRule.cpp)
[FillRule.cpp.zip](https://github.com/user-attachments/files/18817350/FillRule.cpp.zip)

sw_engine: fix update issue

---

cross/wasm32.txt
cross/wasm32_gl.txt
cross/wasm32_sw.txt
cross/wasm32_wg.txt
wasm_build.sh

- Changed optimization flags to -Oz, reducing the binary size by 120KB.
- Applied wasm-opt convergence as a post-process to ensure the minimum possible size with the given optimization flag.

wasm: optimize binary size

---

cross/wasm32.txt
cross/wasm32_wg.txt
src/renderer/wg_engine/meson.build
src/renderer/wg_engine/tvgWgGeometry.cpp
src/renderer/wg_engine/tvgWgGeometry.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

Manage the global buffer memory for vertex and indexed vertex buffers, increase the memory size incrementally twice by default and reduce the default buffer size, which is not suitable for typical scenarios.
This could reduce the a bit stack memory usage and improve the portability across systems where has the stack memory limitation and potentially gaining performance enhancement by avoiding brutal stack memory usage at the many function calls.
added the internal functions:
- WgVertexBuffer* mpoolReqVertexBuffer(float scale = 1.0f);
- WgIndexedVertexBuffer* mpoolReqIndexedVertexBuffer(float scale = 1.0f);
- void mpoolRetVertexBuffer(WgVertexBuffer* buffer);
- void mpoolRetIndexedVertexBuffer(WgIndexedVertexBuffer* buffer);
issue: https://github.com/thorvg/thorvg/issues/3159

wg_engine: introduced global vertexbuffer mempool / ++thread safety

---

src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/gl_engine/tvgGlTessellator.h

Offset is correctly applied to dashed strokes,
properly shifting the dash pattern.
@issue: https://github.com/thorvg/thorvg/issues/3217
@issue: https://github.com/thorvg/thorvg/issues/3223
@issue: https://github.com/thorvg/thorvg/issues/3191
CONTAINS https://github.com/thorvg/thorvg/pull/3228
before:
after:

gl_engine: add offset support in dashed strokes

---

src/renderer/wg_engine/tvgWgGeometry.cpp

regresion by ac08a9d6e716cc76b773eb35ba2badb1f3eebffc
issue: https://github.com/thorvg/thorvg/issues/3241

wg_engine: fix a memory violation by a mistake

---

src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/wg_engine/tvgWgGeometry.h

The sw_engine, when determining the outline, converts floats to ints by multiplying them x64, resulting in a comparison precision of 1/64 = 0.015625.
Both gl_engine and wg_engine operate on floats. Before adding a closing point to a shape, they performed a comparison to check if the point differed from the starting point:
- wg: with a precision of 1e-3 (using length2, i.e., eps = 1e-6
- gl: used direct == comparison. Now, consistency has been ensured by introducing a comparison precision of 1/64 in both wg_engine and gl_engine.
@Issue: https://github.com/thorvg/thorvg/issues/2799
@Issue: https://github.com/thorvg/thorvg/issues/3235
samples to test: polystar.json, starstrips.json
before:
after:
after all engine look the same:
sample:
```
float a = 0.0f; …
```

wg/gl_engine: standardize shapes closing precision

---

src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderer.cpp

The stroke was not updated because the update function handled flags related to color/gradient only for the fill, not for the stroke.
before:
after:
sample:
```
auto x = 0.0f, y = 0.0f;
// fill + no stroke -> fill + stroke
{
//fast track
{
x += 100; y += 0;
shape->appendRect(10, 10, 50, 50);
shape->fill(0, 255, 0);
shape->translate(x, y);
canvas->push(shape);
shape->strokeFill(0, 0, 255);
shape->strokeWidth(10);
canvas->update();
}
//rle
{
x += 100; y += 0;
shape->appendRect(10, 10, 50, 50, 1, 1);
shape->fill(0, 255, 0);
shape->translate(x, y);
canvas->push(shape);
shape->strokeFill(0, 0, 255);
shape->strokeWidth(10);
canvas->update();
}
}
// grad + no stroke -> grad + stroke
{
//fast track
{
x = 0.0f; y += 100;
auto fill = …
```

wg_engine: fix stroke update

---

src/renderer/sw_engine/tvgSwRaster.cpp

Before the C++ compiler couldn't decide the template of std::min (that happen if `int` type is not an `int32_t`), so explicitly changing all types to int32_t fixes this.

sw_engine: fix internal types of rasterXYFlip

---

src/renderer/tvgCommon.h

fix a error call of ambiguous overloaded ‘free(void*&)’

common: ++portablity

---

src/loaders/lottie/tvgLottieExpressions.cpp

A JavaScript code line may return undefined, but this should not be treated as an error.
For example, consider the following two lines of code:
- `var $bm_rt = 30` (Statement) → result: `undefined`
- `$bm_rt = 30` (Expression) → result: `30`
Both lines execute the same operation, but the JavaScript interpreter (REPL JS) evaluates them differently.
Therefore, an evaluation result of undefined should not be blocked, as it does not indicate a failed code execution.
---
We can simply proof this in browser console.
As a result, single line expressions like `var $bm_rt = time * 360` doesn't work.
[sample.json](https://github.com/user-attachments/files/18887080/sample.json)

lottie/expressions: Fix incorrect evaluation result check condition

---

examples/Capi.cpp
examples/StrokeTrim.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/loaders/lottie/tvgLottieBuilder.cpp
src/renderer/gl_engine/tvgGlGeometry.cpp
src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/gl_engine/tvgGlTessellator.h
src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/sw_engine/tvgSwShape.cpp
src/renderer/tvgRender.h
src/renderer/tvgShape.cpp
src/renderer/tvgShape.h
src/renderer/wg_engine/tvgWgRenderData.cpp
test/testShape.cpp

support added for all engines
@issue: https://github.com/thorvg/thorvg/issues/3118 
before:
after:
sample:
```
float dashPattern1[2] = {20, 10};
//Dashed stroke + fill
shape1->appendCircle(120, 120, 75, 75);
shape1->appendRect(200, 50, 150, 150);
shape1->fill(0, 50, 155, 100);
shape1->strokeFill(0, 0, 255);
shape1->strokeJoin(tvg::StrokeJoin::Round);
shape1->strokeCap(tvg::StrokeCap::Round);
shape1->strokeDash(dashPattern1, 2);
shape1->strokeWidth(12);
shape1->trimpath(0.2f, 0.8f, false);
//Dashed stroke only
shape1 = tvg::Shape::gen();
shape1->appendCircle(120, 120, 75, 75);
shape1->appendRect(200, 50, 150, 150);
shape1->strokeFill(0, 0, 255);
shape1->strokeJoin(tvg::StrokeJoin::Round);
shape1->strokeCap(tvg::StrokeCap::Round); …
```

trimming fill & stroke

---

src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/wg_engine/tvgWgGeometry.h

The differences resulted from discrepancies between the engines in applying equality or inequality signs and in using different precision levels when determining the dash remainder when transitioning to a new path command.
@Issue: https://github.com/thorvg/thorvg/issues/3265

gl/wg_engine: fix differences in dashing among engines

---

examples/all.sh

Usage:
all.sh [engine name] [interval]
Example:
$./all.sh gl 3

examples: allow the engine name from the test script

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieBuilder.h

don't do rendering further when the inverse mattes has
a fully translucent. This could improve rendering performance
in that case.

lottie: more precise culling for inverse mattes

---

src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/gl_engine/tvgGlTessellator.h

While dashing, changing the path command each time caused a new 'move to' command to be added, even when dash segments across different path commands should have been connected.
@Issue: https://github.com/thorvg/thorvg/issues/3231
before:
after:

gl_engine: fix line join while dashing

---

src/loaders/ttf/tvgTtfReader.cpp

It might happen that the first point doesn't belong to the contour - such cases were observed as artifacts till now.
@Issue: https://github.com/thorvg/thorvg/issues/3268
before:
after:
sample:
```
shape->appendRect(0, 0, w, h);
shape->fill(75, 75, 75);
canvas->push(shape);
if (!tvgexam::verify(tvg::Text::load(EXAMPLE_DIR"/font/output.ttf"))) return false;
auto text4 = tvg::Text::gen();
text4->font("output", 195);
text4->text("qwerty");
text4->fill(255, 0, 255);
text4->translate(0, 210);
canvas->push(text4);
text4 = tvg::Text::gen();
text4->font("output", 195);
text4->text("uiop");
text4->fill(255, 0, 0);
text4->translate(0, 510);
canvas->push(text4);
text4 = tvg::Text::gen();
text4->font("output", 95);
text4->text("QWERTYUIOP");
text4->fill(255, 0, 255); …
```

ttf_loader: handling contours starting with OFF_CURVE

---

src/bindings/wasm/tvgWasmLottieAnimation.cpp

1. return null canvas when engine is not avaiable.
2. remove the ifdef for unnecessary taret calls.

wasm: refine the logic for clarity

---

examples/Lottie.cpp
examples/LottieExpressions.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/wasm/tvgWasmLottieAnimation.cpp
src/loaders/lottie/tvgLottieLoader.cpp
src/renderer/tvgCommon.h
src/renderer/tvgLoader.cpp

Add support for the .lot extension to recognize Lottie animation files, as this introduces an additional extension for Lottie.
issue: #3248

common: Support .lot extension

---

src/renderer/sw_engine/tvgSwRle.cpp

Generating the outline may return false, e.g., if the shape is completely trimmed. If such a shape was used as a clip, an attempt to generate 'rle' will still be made. In such a case, a crash will occur because the outline is nullptr.
```
shape1->appendCircle(400, 400, 350, 350);
shape1->fill(0, 50, 155);
shape1->strokeFill(0, 0, 255);
shape1->strokeWidth(12);
auto clip = tvg::Shape::gen();
clip->appendRect(0, 0, 400, 400, 50, 50);
clip->trimpath(0.5, 0.5, true);
shape1->clip((clip));
```
```
../src/renderer/sw_engine/tvgSwRle.cpp:694:5: runtime error: member access within null pointer of type 'SwOutline'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../src/renderer/sw_engine/tvgSwRle.cpp:694:5 in …
```

sw_engine: hanndle empty clips

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieBuilder.h
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h

implemented an aggressive culling strategy to eliminate unnecessary renderings if the rendering visuals were hidden by other overlaid opaque fills or strokes
this pretty improves the performance for those scenarios when rendering sequences are fragmented by fills/strokes.
performance could be potentially improved ~7% in such cases.

lottie: optimize rendering performance

---

src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgCompositor.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderTypes.cpp
src/renderer/wg_engine/tvgWgShaderTypes.h

wg_engine: introduce tiny and triton effect for webgpu renderer

---

src/renderer/wg_engine/tvgWgPipelines.cpp

Issue: https://github.com/thorvg/thorvg/issues/3292
fixed by releasing newly created or refactored pipelines and shaders

wg_engine: fix memory leak sanitizer report (fill effect)

---

src/common/tvgStr.cpp
src/common/tvgStr.h
src/loaders/lottie/tvgLottieInterpolator.cpp
src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieParserHandler.cpp
src/loaders/lottie/tvgLottieProperty.h
src/loaders/svg/tvgSvgCssStyle.cpp
src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgXmlParser.cpp
src/renderer/tvgCommon.h
src/renderer/tvgLoader.cpp
src/renderer/tvgText.h
src/savers/gif/tvgGifSaver.cpp

tvg expects the coherent memory allocator usage,
while strdup() is out of the control. so replaced it.

common: replace the strdup() with strDuplicate()

---

src/common/tvgMath.cpp
src/common/tvgMath.h
src/renderer/tvgRender.cpp
src/renderer/tvgRender.h
src/renderer/tvgShape.h

previously, the bounding box calculation was simply determined by comparing all the points, which led to incorrect sizing due to Bezier control points.
Now, it accurately computes the curve boundary,
properly addressing this issue.
before -> after:

renderer: improved the paint bounding box accuracy

---

src/loaders/lottie/tvgLottieBuilder.cpp

issue: #3266
Embedded font rendering was recently introduced but lacked support for text justification.  This adds the necessary justification logic to ensure proper alignment.
| Before | After |
|--------|-------|
| ![Before](https://github.com/user-attachments/assets/e2537bb5-fd2b-4371-9266-da2f0307f2f8) | ![After](https://github.com/user-attachments/assets/929bea2f-bfc8-46bf-91da-caa1a6833337) |
| ![Before](https://github.com/user-attachments/assets/57bd0756-8c2a-425c-b13b-1fa2d0db0ae0) | ![After](https://github.com/user-attachments/assets/55b8b194-5104-4c66-bb5d-d766ce036454) |

lottie/text: fix justification in embedded font rendering

---

src/renderer/gl_engine/tvgGlRenderer.cpp

See Clipping example
Issue: https://github.com/thorvg/thorvg/issues/3063
sw/gl/wg

gl_engine: introduce the stroke clipper

---

examples/BoundingBox.cpp
examples/LottieTweening.cpp
examples/meson.build
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/svg/tvgSvgSceneBuilder.cpp
src/renderer/tvgPaint.cpp
src/renderer/tvgPaint.h
src/renderer/tvgPicture.h
src/renderer/tvgScene.h
src/renderer/tvgShape.h
src/renderer/tvgText.h
src/savers/gif/tvgGifSaver.cpp
test/testPaint.cpp

C++ API Modificaiton:
- Result Paint::bounds(float* x, float* y, float* w, float* h, bool transform = false) const
-> Result Paint::bounds(float* x, float* y, float* w, float* h) const
C++ API Addition:
- Result Paint::bounds(Point* pt4) const
C API Modification:
- Tvg_Result tvg_paint_get_bounds(const Tvg_Paint* paint, float* x, float* y, float* w, float* h, bool transformed);
-> Tvg_Result tvg_paint_get_aabb(const Tvg_Paint* paint, float* x, float* y, float* w, float* h);
C API Addition:
- Tvg_Result tvg_paint_get_obb(const Tvg_Paint* paint, Tvg_Point* pt4);
issue: https://github.com/thorvg/thorvg/issues/3290

api: object oriented bounding box support

---

src/renderer/tvgPaint.cpp

For rectangular stroke clipping, clipping was happening in the fastTrack mode, resulting in regular clipping instead of stroke clipping.
1. first commit:
before:
after:
sample:
```
auto rect = tvg::Shape::gen();
rect->appendRect(0, 0, 800, 800);
rect->fill(255, 0, 0);
mask->appendRect(10, 10, 780, 780);
mask->fill(255, 255, 255);
rect->mask(mask, tvg::MaskMethod::Alpha);
auto clipRect = tvg::Shape::gen();
clipRect->appendRect(100, 100, 600, 600, 100, 100);
//clipRect->strokeWidth(60);
auto clip = tvg::Shape::gen();
clip->appendRect(100, 100, 600, 600, 100, 100);
clipRect->clip(clip);
rect->clip(clipRect);
canvas->push(rect);
```
2. second commit:
before:
after:
sample:
```
auto rect = tvg::Shape::gen();
rect->appendRect(0, 0, 800, 800);
rect->fill(255, 0, …
```

renderer: fix rectangular stroke clipping

---

src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h

_Originally issued by @mgrudzinska in https://github.com/thorvg/thorvg/pull/3269#discussion_r1974502080_
---
At second overriding for same sid(Lottie Slot), current property(applied from first override) is no longer memory-managed, is just replaced with new value, then system loses pointer.
Thus, if the LottieSlot has already been overridden and doesn't need to back-up for Slot resetting, `release()` should be called before next overriding.
---

lottie/slot: fix potential memory leak when overriding twice

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieExpressions.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieProperty.h
src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgSceneBuilder.cpp
src/renderer/gl_engine/tvgGlGeometry.cpp
src/renderer/gl_engine/tvgGlRenderPass.cpp
src/renderer/wg_engine/tvgWgShaderTypes.cpp

Ensures that the project compiles and all tests pass as expected if set to c++20. This was in the form of explicit qualifiers for `identity` and `lerp`, both of which are part of the standard namespace starting in c++20. The former failed compilation outright when unqualified, while the latter silently prioritized `std::lerp` instead.

common: support c++20 builds

---

src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieProperty.h

In member function ‘constexpr LottieGenericProperty<LottieScalarFrame<float>, float>& LottieGenericProperty<LottieScalarFrame<float>, float>::ope>    inlined from ‘LottieFloat& LottieStroke::dashValue()’ at ../src/loaders/lottie/tvgLottieModel.h:60:104,
inlined from ‘void LottieParser::parseStrokeDash(LottieStroke*)’ at ../src/loaders/lottie/tvgLottieParser.cpp:623:82:
../src/loaders/lottie/tvgLottieProperty.h:297:8: warning: ‘<anonymous>.LottieGenericProperty<LottieScalarFrame<float>, float>::value’ may be used>  297 | struct LottieGenericProperty : LottieProperty
|        ^~~~~~~~~~~~~~~~~~~~~
../src/loaders/lottie/tvgLottieModel.h: In member function ‘void LottieParser::parseStrokeDash(LottieStroke*)’:
../src/loaders/lottie/tvgLottieModel.h:60:104: note: ‘<anonymous>’ declared here
60 …

lottie: --compiler warnings

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieParser.h

Added support for cases without text grouping and range selector.
@Issue: https://github.com/thorvg/thorvg/issues/2888
[tvg.json](https://github.com/user-attachments/files/18877521/tvg.json)
[follow_path.json](https://github.com/user-attachments/files/18680823/follow_path.json)

lottie: add support for text follow path

---

src/renderer/tvgTaskScheduler.cpp
src/renderer/tvgTaskScheduler.h
src/savers/gif/tvgGifSaver.cpp

removed the direct thread inclusion
when those thread features are disabled

renderer: ++wasm build portability

---

src/loaders/lottie/tvgLottieProperty.h

When the datas are copied with deep copy, memory issue caused (SEGV on unknown address) due to these reasons:
1. `mimeType` is nullptr when it's not embedded(base64) data
2. datas(b64Data, mimeType) should not be clear, it's used for next slot copy in same pair.
---
Test sample:
[slotsample3.json](https://github.com/user-attachments/files/19277100/slotsample3.json)

lottie/slot: fix image deep copy logic

---

src/renderer/wg_engine/tvgWgCommon.cpp

The Emscripten header was previously used because the WebGPU initialization logic was in WgContext::initialize.
Now, initialization occurs at the binding/application level.

wg_engine: remove unnecessary header

---

src/renderer/wg_engine/tvgWgRenderData.cpp

We must to update bbox even in case, if chape did not have any geometry
issue: https://github.com/thorvg/thorvg/issues/3289

wg_engine: crash for empty clips fix

---

src/common/tvgArray.h

Replaces `Array(){}` with `Array() = default;`
The previous constructor was causing issues with WebGPU support, because it created a user-defined constructor, which changes how the object is treated during global initialization in WebAssembly. The empty constructor was likely causing the interpreter to set up unnecessary stack frames or function calls during global initialization, leading to an index out-of-bounds error when trying to use the Array.
By using `= default`, we tell the compiler "don't generate any actual constructor code" - it can just set up the memory directly without function calls or stack frames, which works better with WebAssembly's initialization model.

array: use default constructor

---

src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/sw_engine/tvgSwShape.cpp
src/renderer/tvgRender.h
src/renderer/tvgShape.h

introduced a threshold for the minimum dash size
to prevent excessive fragmentation.
issue: https://github.com/thorvg/thorvg/issues/3332

renderer: safety++

---

src/common/tvgStr.cpp
src/common/tvgStr.h
src/loaders/lottie/jerryscript/jerry-core/api/jerryscript.cpp
src/loaders/lottie/jerryscript/jerry-core/include/jerryscript-core.h
src/loaders/lottie/tvgLottieExpressions.cpp
src/loaders/lottie/tvgLottieExpressions.h
src/loaders/lottie/tvgLottieProperty.h

- Handle text value of text document.
- Expand `add()` for string concatenation.
issue: #3303

lottie/expressions: text document support

---

src/bindings/capi/thorvg_capi.h

The correct name is `tvg_accessor_set`, not `tvg_accessor_set_paint`.

capi: fix name mismatch

---

src/bindings/wasm/tvgWasmLottieAnimation.cpp

Fixed a build error that occurred when the WebGPU feature was disabled due to a missing feature check condition. The issue affected building with the software and OpenGL only backends.
issue: #3356

wasm: fix build error when WebGPU is disabled (SW/GL only)

---

src/loaders/lottie/tvgLottieExpressions.cpp
src/loaders/lottie/tvgLottieProperty.h

usage) temporalWiggle(freq, amp, octaves=1, amp_mult=.5, t=time)
Samples the property at a wiggled time. The freq value is the frequency in wiggles per second, amp is the amplitude in units of the property to which it is applied, octaves is the number of octaves of noise to add together, amp_mult is the amount that amp is multiplied by for each octave, and t is the base start time. For this function to be meaningful, the property it samples must be animated, because the function alters only the time of sampling, not the value.
Note: need to verify this with a practical samples.
issue: https://github.com/thorvg/thorvg/issues/1640

lottie/expressions: add temporalWiggle() support

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/loaders/lottie/tvgLottieParser.cpp

For both enums, values 1 and 2 correspond to the same thing in ThorVG and in the Lottie file format. However, in ThorVG, StrokeCap::Square and StrokeJoin::Bevel correspond to 0, whereas in the Lottie file format, they correspond to value 3.

lottie: fix stroke cap/join values

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp

| Text Style | Text Doc |
|------------|--------|
| ![CleanShot 2025-04-03 at 15 39 51@2x](https://github.com/user-attachments/assets/14e909e3-c3ba-4e2d-94f3-b239cde74f1c) | ![CleanShot 2025-04-03 at 15 38 49@2x](https://github.com/user-attachments/assets/601a8206-5aa3-4cba-9138-7139bf446d8a) |
Duplicated text document properties (fill color, stroke color, and stroke width) to the text range.  
If these properties are not defined in the range selector, ThorVG incorrectly overrides them with default values.  
The correct behavior is to preserve the original values. The added flags address this issue.
---
| lottie-web | ThorVG (Before) | ThorVG (Patched) |
|------------|------------------|-------------------|
| ![CleanShot 2025-04-03 at 15 42 …

lottie/text: added range selector flags

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieBuilder.h

This reverts commit 7ef3352efa5852037c0441db4b055b791958bec3.
For mattes of type 'InvAlpha' or 'InvLuma', the matted layer can still be visible regardless of the matte's opacity (unlike 'Alpha' and 'Luma' masks, which cut out the entire layer when opacity = 0). The previously introduced optimization incorrectly assumed that with opacity = 255, the image would not be visible.
@Issue: https://github.com/thorvg/thorvg/issues/3375
@Issue: https://github.com/thorvg/thorvg/issues/3380
@Issue: https://github.com/thorvg/thorvg/issues/3381
@Issue: https://github.com/thorvg/thorvg/issues/3382
sample:
[matte_anim.json](https://github.com/user-attachments/files/19622977/matte_anim.json)
before:
after:
AE:

lottie: revert "lottie: more precise culling for inverse mattes"

---

src/renderer/gl_engine/tvgGlCommon.h
src/renderer/gl_engine/tvgGlRenderTask.cpp
src/renderer/gl_engine/tvgGlRenderTask.h
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/gl_engine/tvgGlShaderSrc.cpp
src/renderer/gl_engine/tvgGlShaderSrc.h

Full support of fill, tint, tritone with all effects parameters

gl_engine: Introduce fill, tint, tritone effects for opengl renderer

---

src/loaders/lottie/tvgLottieModel.cpp

[lottie: fix mask length in follow path](https://github.com/thorvg/thorvg/commit/6a39276e91b0866fee89044c49deba513bc24e55) 
Each time the 'updateText' was called, the mask
path (if the follow path existed) was appended
to the previous one, causing it to grow infinitely.
A 'clear' call on the existing path was missing.
[lottie: fix crash on follow path](https://github.com/thorvg/thorvg/commit/7f296f9bc0ab3ea06751d0757526f7fdbf260991) 
It could happen that the searched text position
(distance from the start pointt) on the follow path
was exactly equal to the path length. In such a case,
the cmds pointer pointed to the last element, and in
the next iteration, this caused a crash.
Test:
[sample](https://github.com/user-attachments/files/19671764/follow_rect.json) to test crash (on mac intel, …

lottie: follow path fixes

---

src/renderer/tvgScene.h

- If you rotate a scene that contains a path, the AABB is incorrect.
- The AABB of the scene is "wrapped" around the OBB for the child path, instead of being wrapped around the AABB for the child path.
Now after these changes:

common: fix incorrect aabb of scenes

---

src/loaders/lottie/tvgLottieModel.h

Prevents a crash when the font family in the text document does not match any font in the provided font list.
sample:
[text.json](https://github.com/user-attachments/files/19691540/text.json)

lottie: safety++

---

src/loaders/ttf/tvgTtfLoader.cpp

If wrong utf8 sequence if given as an input, decoding return nullptr and it has to be handled correctly.
test:
crash occurred when unicode was passed in expressions - can be also recreated with this incorrect utf8 sequence:
```
auto text12 = tvg::Text::gen();
text12->font("SentyCloud", 50);
text12->fill(255, 25, 25);
text12->text("\xF8\x88\x80\x80\x80");
text12->translate(0, 525);
canvas->push(text12);
```

ttf: prevent crash while converting utf8 to unicode

---

src/renderer/tvgPaint.h

Prevents field accessing on `nullptr`.
Resolve: #3404

renderer: Added null check in Paint::Impl:clip

---

src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/tvgPaint.cpp
src/renderer/tvgPaint.h
src/renderer/tvgRender.h

ThorVG did not consider updates to the clipping path when a paint object was modified after being added to the scene.
This fix ensures that any updates to clipping are correctly reflected during rendering.
issue: https://github.com/thorvg/thorvg/issues/3403

renderer: fixed a clippging update isssue

---

src/renderer/tvgShape.h

Flag was missing in the appendRect().
sample:
```
shape1->appendRect(10, 10, 100, 100);
shape1->fill(0, 0, 255);
shape1->appendRect(210, 10, 100, 100);
canvas->update(shape1);
```
before:
after:

renderer: add missing RenderUpdateFlag

---

src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/wg_engine/tvgWgShaderTypes.cpp

|before|after|
|-|-|
|<img width="400" alt="bbb" src="https://github.com/user-attachments/assets/8eca5934-0119-41af-83e4-2fbd7823435e" />|<img width="400" alt="bbb" src="https://github.com/user-attachments/assets/c3118ffd-b01c-4fc0-ab4b-5750bafa59cd" />|
|<img width="400" alt="bbb" src="https://github.com/user-attachments/assets/7430f5b5-91a3-4ff3-946e-4b7f96adaa41"/>|<img width="400" alt="bbb" src="https://github.com/user-attachments/assets/ee32dd40-3c7f-4cc1-9384-30b565082f4a"/>|

wg_engine/gl_engine: fix drop shadow blended color 

---

inc/thorvg.h
src/loaders/lottie/tvgLottieBuilder.cpp
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/sw_engine/tvgSwFill.cpp
src/renderer/tvgCommon.h
src/renderer/tvgFill.cpp
src/renderer/tvgFill.h
src/renderer/tvgPaint.cpp
src/renderer/tvgPaint.h
src/renderer/tvgPicture.cpp
src/renderer/tvgPicture.h
src/renderer/tvgRender.h
src/renderer/tvgScene.cpp
src/renderer/tvgScene.h
src/renderer/tvgShape.cpp
src/renderer/tvgShape.h
src/renderer/tvgText.cpp
src/renderer/tvgText.h

The following is a redesign that extends the class internally.
The main goal is to preserve the characteristics of the pImpl idiom for data encapsulation, while simultaneously reducing the memory allocation overhead typically associated with pImpl.
The stragegy is here:
Rather than alloc the impl memory inside of the thorvg engine, impl extends the API classes in order to consolidate the memory.
size has been decreased by -4kb with optimization=s
issue: https://github.com/thorvg/thorvg/issues/3214

renderer: revise the pImpl design with a better efficiency

---

src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwRle.cpp

basically, sw engine aims for 32bits, it reduces
the bundle size by 1kb.
Need to carefully see any side effect in practice.

sw_engine: --size reduction

---

examples/Capi.cpp
examples/Example.h
examples/MultiCanvas.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/sw_engine/tvgSwPostEffect.cpp
src/renderer/sw_engine/tvgSwRaster.cpp
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/sw_engine/tvgSwRenderer.h
src/renderer/tvgCommon.h
src/renderer/tvgGlCanvas.cpp
src/renderer/tvgInitializer.cpp
src/renderer/tvgSwCanvas.cpp
src/renderer/tvgWgCanvas.cpp
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h
test/testAccessor.cpp
test/testInitializer.cpp
test/testPicture.cpp
test/testScene.cpp
tools/lottie2gif/lottie2gif.cpp
tools/svg2png/svg2png.cpp

Simplified parameters and ensured proper backend engine initialization by using reference checking through canvas instances.
C++ API Modification:
- Result Initializer::init(uint32_t threads, CanvasEngine engine) -> Result Initializer::init(uint32_t threads)
- Result Initializer::term(CanvasEngine engine) -> Result Initializer::term()
C API Modification:
- Tvg_Result tvg_engine_init(Tvg_Engine engine_method, unsigned threads) -> Tvg_Result tvg_engine_init(unsigned threads);
- Tvg_Result tvg_engine_term(Tvg_Engine engine_method) ->  Tvg_Result tvg_engine_term()

api: revise engine initialization and termination

---

src/bindings/wasm/tvgWasmLottieAnimation.cpp
src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgRenderer.cpp

Only minor changes required
preservation support of emsdk
Performance with [v22.1.0.5](https://github.com/gfx-rs/wgpu-native/releases/tag/v22.1.0.5)
```
Windows Lottie wg
v19: 140 ms
v22: 124 ms (+10%)
```
issue: https://github.com/thorvg/thorvg/issues/2909
_note_ issue https://github.com/thorvg/thorvg/issues/3331 are still there

wg_engine: sync up to update the engine work to webgpu_native v22

---

src/loaders/lottie/tvgLottieParser.cpp

The incorrect line join used for OffsetPath was caused by changes to the StrokeJoin enum values in commit 34d731fa94bbc5b1b70415eea37b78acdb6405de. During those changes, the line join value for OffsetPath was mistakenly not updated.

lottie: fix stroke join for offset path

---

src/renderer/sw_engine/tvgSwRaster.cpp

Improves the color accuracy of rasterized images by skipping the pre-multiply step when the alpha is fully opaque or fully transparent.
fixes: #3429

sw_engine: ++raster color accuracy

---

examples/Example.h

SDL + software engine doesn't need the vsync?
Observed the rendering performance is noticeably unstable on Intel Arc chipsets with certain window sizes (ie 800x800) when VSync is enabled on software-rendered windows.
This might be a workaround, or it could be an issue with the driver or SDL.
Either way, the SDL + software engine doesn't need VSync.

example: disable vsync of sw window for stability.

---

examples/CustomTransform.cpp
examples/DirectUpdate.cpp
examples/GradientTransform.cpp
examples/ImageRotation.cpp
examples/Retaining.cpp
examples/SceneTransform.cpp
examples/Transform.cpp
examples/Update.cpp

just changed the size to another one for better showcase since 800x800 is not preferred by intel arc chipset. animations look stutter.

examples: changed animatable window size.

---

src/loaders/lottie/tvgLottieBuilder.cpp

\u0003 (\3) can be used as delimiter. Now handled correctly.

lottie: add missing delimiter

---

examples/Example.h
src/renderer/gl_engine/meson.build
src/renderer/gl_engine/tvgGl.cpp
src/renderer/gl_engine/tvgGl.h
src/renderer/gl_engine/tvgGlCommon.h
src/renderer/gl_engine/tvgGlRenderTask.cpp
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlTessellator.cpp

no any 3rd-party libs, such as glfw or glad did not used support windows, linux, macos and emsdk
only the actually used set of functions are loaded
Co-Authored-By: Sergii Liebodkin <sergii@lottiefiles.com>
Co-Authored-BY: Hermet Park <hermet@lottiefiles.com>
issue: https://github.com/thorvg/thorvg/issues/2453

gl_engine: dynamic load gl functions

---

src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp

The "s" key does not have to appear at the beginning of the position block. Previously, such cases would result in a parsing error — now they are handled correctly.

lottie: enhance parsing of position's SeparateCoords

---

src/loaders/lottie/tvgLottieBuilder.cpp

Added missing factor.
before:
after:
AE:
sample:
[polygon_rounded.json](https://github.com/user-attachments/files/20196622/polygon_rounded.json)

lottie: fix points calculation for rounded polygon

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.h

Use local font by default and fall back if no glyphs exist.

lottie: removed undesired embedded option.

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h

If stop is declared immediately after Gradient is closed, the stop is registered in latestGradient.
Change latestGradient to a Stack and add a stop only to the last added gradient.
When that gradient is closed, no more stops should be registered for that gradient.
And gradients do not allow nested declarations, so only the earliest declared Gradient is valid.
related issue: https://github.com/thorvg/thorvg/issues/3469

svg_loader: Fix <stop> being registered in closed latestGradient

---

src/renderer/sw_engine/tvgSwRle.cpp

In some clipping cases, the memory allocated for storing spans was too small. As a result, the entire clipped area might not have been rendered.
This has been resolved by adding an experimental factor to increase the size of allocated memory.
@issue: https://github.com/thorvg/thorvg/issues/3461
after:
before:
after:
sample:
```
auto rect1 = tvg::Shape::gen();
rect1->appendRect(100,100,10,100,1,1);
rect1->appendRect(112,100,10,100,1,1);
rect1->appendRect(124,100,10,100,1,1);
rect1->appendRect(136,100,10,100,1,1);
rect1->appendRect(148,100,10,100,1,1);
rect1->appendRect(160,100,10,100,1,1);
rect1->appendRect(172,100,10,100,1,1);
rect1->appendRect(184,100,10,100,1,1);
rect1->fill(255, 0, 0, 80);
auto rect2 = static_cast<tvg::Shape*>(rect1->duplicate());
rect2->fill(255, 0, 0, 255); …
```

sw_engine: fix too small memory alloc for spans

---

src/renderer/gl_engine/tvgGlRenderTarget.cpp
src/renderer/gl_engine/tvgGlRenderTarget.h
src/renderer/gl_engine/tvgGlRenderer.cpp

We must to remove offscreen render buffers during removing render target
https://github.com/thorvg/thorvg/issues/3210

gl_engine: fix memory leak on target resize

---

src/loaders/lottie/tvgLottieBuilder.cpp

A precomposition layer is clipped to its viewport. If the same layer also had a mask that was optimized using clipping, this clip was unintentionally overridden by the viewport clipping. This conflict is now fixed.
before:
after (same as in AE, lottie web):
sample:
[test.json](https://github.com/user-attachments/files/20357644/test.json)

lottie: fix precomposition with masking

---

src/renderer/gl_engine/tvgGlRenderer.cpp

gl_engine: fix compilation warning with RenderRegion data type

---

src/renderer/wg_engine/meson.build
src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgCompositor.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h
src/renderer/wg_engine/tvgWgRenderTask.cpp
src/renderer/wg_engine/tvgWgRenderTask.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

Implemented task-based rendering and geometry stage buffers:
1. Get information about current frame objects
2. Accumulate geometry data into a stage buffer during frame rendering
3. Flush it to the GPU in single call
4. Run rendering process in post render stage
https://github.com/thorvg/thorvg/issues/3489
https://github.com/thorvg/thorvg/issues/3455
Lottie example performance:
```
main:    83 ms
staging: 67 ms
~25% boost
```
thorvg-wasm.wasm (linux, emsdk)
```
staging: 929864 bytes
main:    927727 bytes
```
1. Current Implementation: Per-Shape GPU Buffer Management
In the existing rendering pipeline, each geometric shape undergoes a distinct process of tessellation and subsequent GPU buffer allocation. Upon each geometry update, the tessellator processes the shape's path data, generating …

wg_engine: geometry stage buffers implementation

---

cross/ios_arm64.txt

Use meson's official cpu_family name 'aarch64' instead of 'arm64' for ios build.
Both aarch64 and arm64 technically refer to the same architecture. The standard CPU naming convention uses `aarch64`, but within the iOS ecosystem (including the Xcode toolchain), Apple employs its own naming convention, `arm64`.
Therefore, the naming of a configuration file such as `ios_arm64` is not incorrect in itself. However, meson recognizes only certain officially registered architectures, and since `arm64` is not among them, this can lead to issues when meson build is used.
For these reasons, I suggest using the `aarch64` cpu naming instead of `arm64` in meson related configuration lines while keeping the filename as is (ios_arm64).

infra(ios): Set cpu family to aarch64 for meson compatibility

---

src/renderer/gl_engine/tvgGlRenderTask.cpp
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h

The clear flag specified in Canvas::draw is ignored when set to false, since GlRenderer::mClearBuffer is never explicitly reset to false.
This commit ensures that mClearBuffer is reset to its default (false) after being used, so that the clear operation behaves correctly per draw.
- Note: GlComposeTask: always clear since the bound framebuffer is selfFbo
- `GlComposeTask::run`: `GL_CHECK(glBindFramebuffer(GL_FRAMEBUFFER, getSelfFbo()));`
-  `GlBlitTask::run`: `GL_CHECK(glBindFramebuffer(GL_FRAMEBUFFER, getTargetFbo()));`
- Issue: #1779
- History: 
- https://github.com/thorvg/thorvg/commit/548962f5f8868429b9ebf5ce6fb9005dcb9a606a#diff-9e1e59292fa7b422d5ff866d9b48e16bdd61ab18bed965fa9d1a6b809bca7ee0R110
- https://github.com/thorvg/thorvg/commit/cc2fa23359b9c07c13cb6cedf11298386d80517c#diff-9 …

gl_engine: fix always-true clear flag

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieBuilder.h

preserve the target opacity by multiplying,
do not overwrite it.

lottie: fixed a repeater opacity logic

---

src/renderer/wg_engine/tvgWgBindGroups.cpp
src/renderer/wg_engine/tvgWgBindGroups.h
src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgCompositor.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderTypes.cpp
src/renderer/wg_engine/tvgWgShaderTypes.h

Introduced stage buffer for uniforms to reduce number of memory shafles from cpu to gpu memory
**Refactor: Unified Uniform Buffer for Improved Performance**
This pull request introduces a stage buffer for uniforms, significantly reducing memory transfers calls between the CPU and GPU.
**Problem**
Previously, each shape managed its transformation settings, opacity, colors, and gradients in separate data structures. This necessitated the creation of individual uniform buffers on the GPU, leading to a high volume of data transfers calls from system memory to video memory.
**Solution**
Now, all shape-related data (fills and strokes settings) are consolidated into a single, shared data structure. During rendering, this data is accumulated on demand into a single buffer, which can then be …

wg_engine: uniform stage buffers implementation

---

src/loaders/lottie/tvgLottieModifier.cpp

One point was skipped during the creation of the offset corner. The error was not visible because the point lies on the line, but it will become apparent if further modifiers are applied to the object (not supported now).
samples not supported now (#3378 used to render the sample):
before this change:
after this change:
AE:
sample:
[pucker_rect_op_miter4.json](https://github.com/user-attachments/files/20716506/pucker_rect_op_miter4.json)

lottie: fix offset with miter join

---

examples/ImageScaling.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/renderer/tvgCanvas.cpp
src/renderer/tvgCanvas.h
src/renderer/tvgPicture.h
src/renderer/tvgScene.h
test/testPaint.cpp

Removed the paint parameter previously used to forcibly update a single paint.
This behavior was unsafe in ThorVG, as a single paint object may be connected to others through the scene graph.
Now, the canvas engine is responsible for properly updating all damaged paints as needed, allowing the user to simply call update() in any case.
API Modifications:
C++ API:
Modified: Result Canvas::update(Paint* paint) -> Result Canvas::update()
CAPI:
Removed: tvg_canvas_update_paint()
Issue: https://github.com/thorvg/thorvg/issues/3116

api: revise the canvas update() API

---

src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgCompositor.cpp

After introducing staged buffers and tesk-based rendering removed the need for forced flush of each texture data into gpu.
General approach used for all data types.
Can increase performance on discrete GPUs.
```
Lottie wg (GF3060Ti)
main: 45
PR: 40
```

wg_engine: avoid forced texture flushes

---

src/renderer/sw_engine/tvgSwRasterAvx.h
src/renderer/sw_engine/tvgSwRasterNeon.h

The span was incremented both in the for loop instruction (ARRAY_FOREACH) and inside the loop body. Fixed.
@Issue: https://github.com/thorvg/thorvg/issues/3547
before:
after:

avx/neon: remove double increment of the value

---

src/renderer/sw_engine/tvgSwFill.cpp

This approach should be introduced in d8ebd8b4f517a013479bfbebbcdd3523ca3173ee. Using FLOAT_EPSILON is not sufficient due to numerical precision, since it's later inverted, and its very small value leads to significant errors during inversion.

sw_engine: fix focal point clamping

---

src/meson.build

On Windows, you need to consistently set `__declspec` on symbols. This is handled automatically in `thorvg.h` for shared libraries, and left out entirely for static libraries by the `TVG_STATIC` define.
When building as a subproject with static libraries, it is thus useful to export `TVG_STATIC` to the parent project, or else `thorvg.h` will attempt to set `__declspec` for a shared library (when the parent project uses it), and linkage will fail.

build: Export TVG_STATIC to parent projects

---

examples/SceneEffects.cpp
inc/thorvg.h
src/renderer/tvgScene.cpp
src/renderer/tvgScene.h

- corrected data type (float -> double)
- guarantee to call va_end()
- docs / samples revision
- include cstdarg as an essential header

common: chores wrt scene effect

---

examples/Capi.cpp
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp

```
+ Tvg_Result tvg_scene_reset_effects(Tvg_Paint* scene)
+ Tvg_Result tvg_scene_push_effect_gaussian_blur(Tvg_Paint* scene, double sigma, int direction, int border, int quality)
+ Tvg_Result tvg_scene_push_effect_drop_shadow(Tvg_Paint* scene, int r, int g, int b, int a, double angle, double distance, double sigma, int quality)
+ Tvg_Result tvg_scene_push_effect_fill(Tvg_Paint* scene, int r, int g, int b, int a)
+ Tvg_Result tvg_scene_push_effect_tint(Tvg_Paint* scene, int black_r, int black_g, int black_b, int white_r, int white_g, int white_b, double intensity)
+ Tvg_Result tvg_scene_push_effect_tritone(Tvg_Paint* scene, int shadow_r, int shadow_g, int shadow_b, int midtone_r, int midtone_g, int midtone_b, int highlight_r, int highlight_g, int highlight_b)
```
issue: …

capi: add scene effects

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/renderer/gl_engine/tvgGlCommon.h
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlShaderSrc.cpp

there are several reports about poor quality,
arranged the value to the medium level.
before -> after:

arrange the blur effect

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/renderer/gl_engine/tvgGlShaderSrc.cpp
src/renderer/sw_engine/tvgSwPostEffect.cpp
src/renderer/sw_engine/tvgSwRaster.cpp
src/renderer/wg_engine/tvgWgShaderSrc.cpp

- corrected the reversed black/white intensity multiplication.
- made a minor adjustment to the luma equation.
- updated and aligned the API documentation accordingly.
before- > after:

engines: corrected wrong tint effects

---

examples/SceneEffects.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp
src/renderer/gl_engine/tvgGlCommon.h
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlShaderSrc.cpp
src/renderer/sw_engine/tvgSwPostEffect.cpp
src/renderer/tvgRender.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderTypes.cpp

- introduced a blending factor to control the mix between the original color and the tritone effect.
- improved Lottie compliance with this enhancement.
- implemented the spec by all engines
CAPI:
* Tvg_Result tvg_scene_push_effect_tritone(Tvg_Paint* scene, int shadow_r, int shadow_g, int shadow_b, int midtone_r, int midtone_g, int midtone_b, int highlight_r, int highlight_g, int highlight_b); -> TVG_API Tvg_Result tvg_scene_push_effect_tritone(Tvg_Paint* scene, int shadow_r, int shadow_g, int shadow_b, int midtone_r, int midtone_g, int midtone_b, int highlight_r, int highlight_g, int highlight_b, int blend);

common: added blending factor to tritone post-effect

---

src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwPostEffect.cpp
src/renderer/sw_engine/tvgSwRenderer.cpp

removed the direct rendering optimization of the dropshadow, because it's a buggy.

sw_engine: dropshadow stability++

---

examples/FillRule.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/svg/tvgSvgSceneBuilder.cpp
src/renderer/tvgShape.cpp
src/renderer/tvgText.h
test/testShape.cpp

Clarify the FillRule usage by associating it
explicitly with color/gradient fills.
C++ API
* Result Shape::fill(FillRule r) -> Result Shape::fillRule(FillRule r)

api: rename shape fill rule API for clarity

---

src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwPostEffect.cpp
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/tvgCommon.h

- shadow rendering was skipped when the blur value was 0. it now correctly renders shadows without blur.
- this also fixes the distance offset scalability.
issue: https://github.com/thorvg/thorvg/issues/3602

sw_engine: improved the dropshadow effect support

---

CONTRIBUTING.md

When running the following command:
```bash
$ meson . build -Dtests=true -Dloaders="all" -Dsavers="all" -Dbindings="capi" -Dtools="all" -Dlog=true
```
the following warning message is displayed:
`WARNING: Running the setup command as 'meson [options]' instead of 'meson setup [options]' is ambiguous and deprecated.` 
To remove this warning, `meson setup [options]` should be used.

docs: update test setup command to use `meson setup [options]`

---

src/renderer/wg_engine/tvgWgCompositor.cpp

This pull request includes minor typo corrections in comments within the `src/renderer/wg_engine/tvgWgCompositor.cpp` file. Specifically, the word "neccessary" was corrected to "necessary" in two functions.

wg_engine: Fixed typo in comment

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h

Previously, only single-level <use> references were supported. If a <use> node pointed to another element that itself contained a <use> node, the reference wasn’t resolved.
This has been fixed by replacing the array of postponed elements with a list. The list is traversed, and nodes aren’t cloned while they or any of their children remain unresolved. In such cases, the target element also gets added to the list, enabling recursive resolution of nested href references.
@Issue: https://github.com/thorvg/thorvg/issues/3615
samples:
[Archiwum.zip](https://github.com/user-attachments/files/21222689/Archiwum.zip)
before:
after:

svg: fix nested use nodes

---

src/renderer/gl_engine/tvgGlGeometry.cpp
src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/gl_engine/tvgGlTessellator.h
src/renderer/tvgRender.cpp
src/renderer/tvgRender.h

Move stroke dasher to the common code space to create an abillity to use it on the cross API renderers (wg and gl). 
Stroke dasher is a path-to-path operation, same as path trim, so can be placed to the common space.
Now RenderShape can generate dashed path by himself.
Dashing mechanics fully hiden from the user but can be used in gl and wg renderers.
issue: https://github.com/thorvg/thorvg/issues/3557

renderer: refactored to share gl stroke dasher among engines

---

src/common/tvgMath.h
src/loaders/lottie/tvgLottieModifier.cpp
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/svg/tvgSvgPath.cpp
src/loaders/svg/tvgSvgPath.h
src/loaders/svg/tvgSvgSceneBuilder.cpp
src/loaders/ttf/tvgTtfReader.cpp
src/renderer/tvgRender.h
src/renderer/tvgShape.cpp
src/renderer/tvgShape.h

- Use RenderPath common interfaces instead of
direct array manipulations.
- Replace multiple scalar operations with Point utility
operations where applicable.

common: clean code++

---

examples/Blending.cpp
inc/thorvg.h
src/common/tvgColor.cpp
src/loaders/svg/tvgSvgLoader.cpp
src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwRaster.cpp
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/tvgPaint.cpp

- Hue: Creates a result color with the luminance and saturation of the base color and the hue of the blend color.
- Color: Creates a result color with the luminance of the base color and the hue and saturation of the blend color. This preserves the gray levels in the image and is useful for coloring monochrome images and for tinting color images.
- Luminosity: reates a result color with the hue and saturation of the base color and the luminance of the blend color. This mode creates the inverse effect of Color mode.
- Saturation: Saturation: Creates a result color with the luminance and hue of the base color and the saturation of the blend color. Painting with this mode in an area with no (0) saturation (gray) causes no change.
- HardMix: Adds the bottom & top. If the resulting sum for a …

sw_engine: support hue, color, luminosity, hardmix blends

---

src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.cpp

Set the scene to use Composition mode so that it generates a pre-composition image, and then normal blend with destination.
wg and gl are already craetes intermediate buffers in a case of custom blend or composition. so only what we need to do is reinterpret the composition blend as a normal blend
```
auto bg = tvg::Shape::gen();
bg->appendRect(0, 0, 1000, 1000);
bg->fill(50, 50, 50);
canvas->push(bg);
scene->blend(tvg::BlendMethod::Composition);
shape->appendRect(100, 100, 200, 200);
shape->fill(255, 0, 0);
shape->blend(tvg::BlendMethod::Add);
scene->push(shape);
canvas->push(scene);
```
https://github.com/thorvg/thorvg/pull/3621

wg/gl: add composition blend mode

---

src/loaders/lottie/tvgLottieModel.cpp

| Previous                                                                                      | Patched                                                                                      |
|-----------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------|
| ![CleanShot 2025-07-25 at 00 01 33](https://github.com/user-attachments/assets/2ae4cb16-6abc-4443-ae5a-1e0f17fc5c35) | ![CleanShot 2025-07-25 at 00 00 33](https://github.com/user-attachments/assets/c9c1a0db-e7ea-434e-baae-3df1d80b3a8e) |
Issue file: [smile.json](https://github.com/user-attachments/files/21413769/smile.json)
Fix logic bug in LottieLayer::remap() where timeRemap calculation could exceed frame …

lottie: fix timeRemap frame boundary handling

---

CONTRIBUTORS
src/savers/gif/tvgGifSaver.cpp
test/testSavers.cpp

https://github.com/thorvg/thorvg/issues/3671#issuecomment-3143892584
1
The test failure in test/testSavers.cpp was due to an incorrect ref count of `bg`. 
Added unref in `GifSaver::run` to resolve it.
2
Added brace-format usage for Initializer

savers/gif: Unref bg after push to fix ref count

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/renderer/tvgPaint.cpp
src/renderer/tvgPaint.h
test/testPaint.cpp

This is useful for selectively excluding paint objects during rendering.
Please note that, an invisible object is not considered inactive—it may still participate in internal update processing if its properties are updated, but it will not be taken into account for the final drawing output. To completely deactivate a paint object, remove it from the canvas.
C++ API
+ Result Paint::visible(bool on)
+ bool Paint::visible()
C API:
+ Tvg_Result tvg_paint_set_visible(Tvg_Paint* paint, bool visible)
+ bool tvg_paint_get_visible(const Tvg_Paint* paint)

renderer: added an API to set the visibility of the Paint object.

---

src/renderer/wg_engine/tvgWgShaderSrc.cpp

fixed observable border clamping for gauss filter in webgpu
https://github.com/thorvg/thorvg/issues/3677

wg_engine: fix gauss border clamping

---

src/renderer/gl_engine/tvgGlEffect.cpp
src/renderer/gl_engine/tvgGlShaderSrc.cpp

fixed observable border clamping for gauss filter in opengl
by design, the gl renderer creates temporary off-screen buffers for rendering scenes, 
including for applying effects. the size of the off-screen buffer depends on the scene bbox 
and it is offset relative to the screen to the beginning of the bbox. 
in this case, the off-screen buffer may extend beyond the screen boundaries, 
but the scene will only be rendered in the area of intersection of the screen and the buffer itself. in
this case, we do not have enough data to apply the gaussian filter, 
since the source of data for it may be neighboring pixels that were initially cut off 
and are not in the area of intersection of the screen viewport and the off-screen buffer. 
we can cut off such pixels when calculating the gaussian …

gl_engine: fix gauss border clamping

---

src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgShaderSrc.cpp

Introduced HSL blending support for webgpu: Hue, Saturation, Color, Luminosity
Supported for all blending targets: solid, gradient, image, scene
sw/wg

wg_engine: hsl blending support

---

examples/Retaining.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/renderer/tvgCanvas.cpp
src/renderer/tvgCanvas.h
test/testSwCanvas.cpp

This update adjusts the ThorVG canvas specification to
allow more flexible and efficient usage patterns.
Key changes include:
a. push behavior:
calling canvas push no longer triggers an automatic update
on the paint object.  This avoids redundant updates in common
scenarios where the user explicitly calls canvas update afterwards.
b. implicit update on draw:
if canvas draw is called without a prior canvas update,
an implicit update will be performed. This ensures compatibility
with the updated push behavior and prevents missing updates.
c. relaxed success conditions
the functions canvas update, sync, draw are now more tolerant
of empty or idle canvas states. If no paint objects are present,
they will return success instead of failure.
Note: These changes may break backward compatibility …

canvas api revision

---

src/common/tvgMath.cpp
src/common/tvgMath.h
src/renderer/tvgRender.cpp

introduced a bounds() calculation with 4 points
without creating a Bezier instance, for better efficiency.

common: introduce global Bezier bounds

---

src/renderer/tvgRender.cpp

Fix incorrect merge direction that
broke x-axis ordering in line-sweeping.
issue: https://github.com/thorvg/thorvg/issues/3696

renderer: stabilizing partial rendering++

---

src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/sw_engine/tvgSwShape.cpp

removed additional bbox for shape.
renderBox is enough to use.

sw_engine: neat & clean data++

---

cross/wasm32.txt
cross/wasm32_gl.txt
cross/wasm32_sw.txt
cross/wasm32_wg.txt

Add --closure=1 to all wasm cross files (default/sw/gl/wg) to minimize JS glue code size and improve DCE.
This optimization also helps contain bundle size growth as player modules diversify and multiple glue files are introduced.
---
Glue code size is reduced by -55% without WASM size increasement.
---
**Common Test:**
**Module bundler compatibility:**
**Framework compatibility**

wasm: enable closure optimization for JS glue

---

examples/BoundingBox.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/common/tvgMath.h
src/loaders/svg/tvgSvgSceneBuilder.cpp
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwMath.cpp
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/sw_engine/tvgSwRenderer.h
src/renderer/sw_engine/tvgSwShape.cpp
src/renderer/tvgPaint.cpp
src/renderer/tvgPaint.h
src/renderer/tvgPicture.h
src/renderer/tvgRender.cpp
src/renderer/tvgRender.h
src/renderer/tvgScene.h
src/renderer/tvgShape.h
src/renderer/tvgText.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h
src/savers/gif/tvgGifSaver.cpp
test/testPaint.cpp

- Refactored to use bounding box information provided by the rendering engine
to ensure accurate AABB/OBB support, including stroke visuals.
Note that this requires paints to be properly pushed into the canvas,
and may affect API behavior.
- Updated Lottie/SVG loaders to use internal AABB functions,
which now exclude stroke bounds. The previous implementation
was also inaccurate in this regard.
- Adjusted example & tests accordingly.
Note:
- GL and WG render engines do not yet support these updates.
- This change may break backward compatibility in existing applications.
Before:
After:

revise the engine based bbox support

---

src/renderer/gl_engine/tvgGlRenderTask.cpp

Fixed broken blending visuals.
We must to turn off depth testing during custom scene blending
https://github.com/thorvg/thorvg/issues/3722

gl_engine: fix broken blending visual

---

src/renderer/sw_engine/tvgSwRaster.cpp

Apply one single INTERPOATE() instead of multiple ALPHA_BLENDS() while it's compatible

sw_engine: fine-tune image composition

---

src/renderer/gl_engine/tvgGlRenderTask.cpp
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlShaderSrc.cpp
src/renderer/gl_engine/tvgGlShaderSrc.h

Align intermediate fbo with source buffer instead of destination buffer. 
Align text coordinates for reading source and intermediate fbos.
https://github.com/thorvg/thorvg/issues/3722

gl engine: fix broken blending visual (sub-scenes alignment)

---

examples/LottieExtension.cpp
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/loaders/lottie/thorvg_lottie.h
src/loaders/lottie/tvgLottieAnimation.cpp
src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/lottie/tvgLottieLoader.h
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieParser.h
test/testLottie.cpp

Introduce Slot APIs for efficient slot data reuse
New APIs:
- uint32_t LottieAnimation::gen(const char* slot)
- Result LottieAnimation::apply(uint32_t id)
- Result LottieAnimation::del(uint32_t id)
Removed API:
- Result override(const char* slot)
issue: #2591 
---
```cpp
const char* slotJson = R"({ /* Slot Data */  })";
auto slotId = animation->gen(slotJson); // retrieve slotId
```
```cpp
animation->apply(slotId);
```
```cpp
animation->apply(0); // Animation resets to default
```
```cpp
auto slotId = animation->gen(slotJson);
animation->apply(slotId);
animation->apply(0);
// Apply slot data using slotId, without duplicated parsing
animation->apply(slotId);
```
```cpp
animation->del(slotId); // Also applied slot will be reset
```

lottie/slot: Introduce reusable Slot API

---

examples/Capi.cpp
examples/Text.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/renderer/tvgShape.cpp
src/renderer/tvgText.cpp
src/renderer/tvgText.h
test/testText.cpp

Introduce outline support for text rendering.
The outline feature applies a stroke around text glyphs, allowing improved readability and visual emphasis.
C++:
+ Result Text::outline(float width, uint8_t r, uint8_t g, uint8_t b)
CAPI:
+ Tvg_Result tvg_text_set_outline(Tvg_Paint* paint, float width, uint8_t r, uint8_t g, uint8_t b)
CAPI:
Text:
issue: https://github.com/thorvg/thorvg/issues/3397

text: add outline style support

---

src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.cpp

generated geometry of strokes is taken into account in the calculation of aabb pre-calculated strokes mesh geometry is used and transformation is applied
https://github.com/thorvg/thorvg/issues/3725

wg/gl: support stroke bounding box

---

test/testPaint.cpp

#3643
src/renderer/sw_engine (45.8% -> 46.0%)

test/sw_engine: Add coverage for `shapeStrokeBBox` in tvgSwShape.cpp

---

examples/Example.h

example: fix compilation errors on win/mingw

---

examples/Animation.cpp
examples/ImageRotation.cpp
examples/ImageScaling.cpp
examples/Lottie.cpp
examples/LottieExpressions.cpp
examples/LottieInteraction.cpp
examples/LottieTweening.cpp
examples/MultiCanvas.cpp
examples/PictureSvg.cpp
examples/Svg.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/bindings/wasm/tvgWasmLottieAnimation.cpp
src/renderer/tvgPicture.cpp
src/renderer/tvgPicture.h

This method defines the origin point of the Picture using normalized coordinates. Unlike a typical pivot point used only for transformations, this origin affects both the transformation behavior and the actual rendering position of the Picture.
C++ API
+ Result Picture::origin(float x, float y)
+ Result Picture::origin(float* x, float* y)
CAPI
+ Tvg_Result tvg_picture_set_origin(Tvg_Paint* picture, float x, float y)
+ Tvg_Result tvg_picture_get_origin(Tvg_Paint* picture, float* x, float* y)
issue: https://github.com/thorvg/thorvg/issues/1506

api: added Picture::origin() support for user covenience

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/renderer/tvgPicture.cpp
src/renderer/tvgPicture.h

explicitly state that user data is not modifiable, this also keeps the api consistency.
C++ API
* Result Picture::load(uint32_t* data, uint32_t w, uint32_t h, ColorSpace cs, bool copy = false) -> Result Picture::load(const uint32_t* data, uint32_t w, uint32_t h, ColorSpace cs, bool copy = false)
C API
* Tvg_Result tvg_picture_load_raw(Tvg_Paint* picture, uint32_t *data, uint32_t w, uint32_t h, Tvg_Colorspace cs, bool copy) -> Tvg_Result tvg_picture_load_raw(Tvg_Paint* picture, const uint32_t *data, uint32_t w, uint32_t h, Tvg_Colorspace cs, bool copy)

api: add missing const qualifier to user data parameter

---

src/bindings/wasm/tvgWasmLottieAnimation.cpp

This patch removes the unused `rpath` parameter from the load() function.
This simplifies the WASM binding while keeping the API aligned with current usage in thorvg.web.
For context, my initial intent was to handle default parameters via overload, but since rpath is not used, I simplified the API as requested.

wasm: remove unused rpath parameter from load()

---

examples/Capi.cpp
examples/Example.h
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/bindings/wasm/tvgWasmLottieAnimation.cpp
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/sw_engine/tvgSwRenderer.h
src/renderer/tvgRender.h
src/renderer/tvgSwCanvas.cpp

C++ API
+ enum EngineOption [None, Default, SmartRender]
* SwCanvas* SwCanvas::gen() -> SwCanvas* SwCanvas::gen(EngineOption op = EngineOption::Default)
C API
+ enum [TVG_ENGINE_OPTION_NONE, TVG_ENGINE_OPTION_DEFAULT, TVG_ENGINE_OPTION_SMART_RENDER]
* Tvg_Canvas* tvg_swcanvas_create() -> Tvg_Canvas* tvg_swcanvas_create(Tvg_Engine_Option op)
Note: SmartRender is still an experimental feature and may not be fully matured. For product stability, use EngineOption::None. (SmartRender is applied by default.)

api: introduced EngineOption to specify engine behavior

---

src/loaders/lottie/tvgLottieProperty.h

populated and count fields were not properly initialized during frames-based deep copy operations.
issue: https://github.com/thorvg/thorvg/issues/3766

lottie/slot: fix colorstop memory access crash with animated value

---

src/renderer/sw_engine/tvgSwPostEffect.cpp

properly arrange the memory offset in case of shifting
issue: https://github.com/thorvg/thorvg/issues/3764

sw_engine: hotfix memory violation of dropshadow

---

src/renderer/tvgCanvas.cpp

This update refines the management of the canvas context during initialization and operation. By improving context handling, it resolves a potential issue where the target method might not function correctly in certain cases.
related: #3763

renderer: revise canvas context handling in target method

---

src/loaders/jpg/tvgJpgLoader.cpp
src/loaders/jpg/tvgJpgd.cpp
src/loaders/jpg/tvgJpgd.h

- skip colospace conversion if the canvas and image source is matched.
- removed unused logic.

loader/jpg: fine tune optimization++

---

src/loaders/lottie/tvgLottieBuilder.cpp

aligned the AE implementation to apply the matte
only to the immediate target, avoiding matte chaining.

Lottie: Fixed track matte behavior.

---

src/renderer/sw_engine/tvgSwPostEffect.cpp

Don't try dropshadow filter if the zero-size sigma size is given. extends zero means no-filter application.

sw_engine: corrected wrong condition

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieBuilder.h
src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/lottie/tvgLottieLoader.h
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h
src/renderer/tvgLoadModule.h
src/renderer/tvgPicture.cpp
src/renderer/tvgPicture.h

This PR implements an asset resolver callback mechanism for Lottie animations. It enables applications to provide custom image loading logic with the following benefits:
- Eliminates unnecessary base64 encoding/decoding steps for dotLottie use cases
- Provides flexible image asset handling for users who want to resolve assets in their own way
```cpp
auto animation = tvg::LottieAnimation::gen();
char* data = "hello, world";
// ...
animation->resolve([](tvg::Paint* p, const char* src, void* user_data) {
ifstream file(TEST_DIR"/test.webp", ios::in | ios::binary);
auto size = sizeof(uint32_t) * (1000*1000);
auto data = (char*)malloc(size);
file.read(data, size);
file.close();
auto ret = static_cast<tvg::Picture*>(p)->load(data, size, "webp", nullptr, true);
return ret == Result::Success;
}, …
```

lottie: support asset resolver callback

---

examples/TextLineWrap.cpp
examples/meson.build
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/loaders/ttf/tvgTtfLoader.cpp
src/loaders/ttf/tvgTtfLoader.h
src/loaders/ttf/tvgTtfReader.cpp
src/loaders/ttf/tvgTtfReader.h
src/renderer/tvgLoadModule.h
src/renderer/tvgText.cpp
src/renderer/tvgText.h

Text linewrap method controls how the text is laid out
when it exceeds the available space. The wrapping mode
determines whether text is truncated, wrapped by character
or word,or adjusted automatically. An ellipsis mode is
also available for truncation with "..."
C++ API
+ enum TextWrap [None, Character, Word, Smart, Ellipsis, Hyphenation]
+ Result Text::wrap(TextWrap mode)
C API
+ enum Tvg_Text_Wrap [TVG_TEXT_WRAP_NONE, TVG_TEXT_WRAP_CHARACTER, TVG_TEXT_WRAP_SMART ...]
+ Tvg_Result tvg_text_wrap_mode(Tvg_Paint text, Tvg_Text_Wrap mode)
issue: https://github.com/thorvg/thorvg/issues/3397

text: support linewrap feature

---

src/loaders/lottie/tvgLottieBuilder.cpp

revised the logic to align with the lottie practices.
issue: https://github.com/thorvg/thorvg/issues/2690

lottie: fixes the trim path multiplication

---

src/loaders/lottie/tvgLottieLoader.cpp

Skip parser when the target slot ID is not found in the animation. Previously, parser would fail to continue when encountering slot overrides that don't exist in the animation, causing parsing to halt.
file: [sample.json](https://github.com/user-attachments/files/22648896/sample.json)
| Before | After |
|--------|-------|
| <img width="2052" height="1888" alt="Before" src="https://github.com/user-attachments/assets/e5f6f81f-dffa-417a-9e95-a736763810e8" /> | <img width="2050" height="1886" alt="After" src="https://github.com/user-attachments/assets/10a44a40-5328-4d53-acbd-c1c3ee829747" /> |

lottie/slot: fixed slot parsing for non-existent slots

---

src/renderer/gl_engine/tvgGlShaderSrc.cpp

for some reason, the browser's shader compiler is more sensitive to certain different types of operations, as well as to punctuation in the source code. provided fixes:
- Incompatibility between int and float types
- Removed unnecessary semicolons
- Constants (e.g., 0 or 1) are now explicitly converted to floats (0.0 or 1.0)

webgl: fix shader compilation errors

---

cross/wasm32.txt
cross/wasm32_wg.txt
examples/Example.h
examples/MultiCanvas.cpp
src/bindings/wasm/tvgWasmLottieAnimation.cpp
src/renderer/wg_engine/tvgWgBindGroups.cpp
src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderer.cpp

A migration to a new, more modern version has been introduced.
The transition from version 22 to version 24/25, which have new headers that are incompatible with the previous version, has been completed.
Emscripten cross files for compiling for the new header version have also been updated.
Used **_'--use-port=emdawnwebgpu'_** flag for compilation and linking
no changes in performance or memory consumption are expected
you can find latest (v25) webgpu library files there:
https://github.com/gfx-rs/wgpu-native/releases
how to setup it, see there:
https://github.com/thorvg/thorvg/wiki/WebGPU-Engine-Development
https://github.com/thorvg/thorvg/issues/3422
https://github.com/thorvg/thorvg/issues/3835

wg_engine: update webgpu lib to v25

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/lottie/tvgLottieLoader.h
test/testAnimation.cpp

Separate the build and update processes to allow more flexible control between threaded and non-threaded parsing sequences. This change helps support proper asset resolver injection timing.
issue: https://github.com/thorvg/thorvg/issues/3851

lottie: separate build and update logic for better flexibility

---

src/loaders/jpg/tvgJpgd.cpp

jpeg_decoder takes ownership of fileStream and frees it, so deleting it again caused a double free.
- issue: #3872
```cpp
void jpeg_decoder::decode_init(jpeg_decoder_stream *pStream)
{
init(pStream);
locate_sof_marker();
}
void jpeg_decoder::init(jpeg_decoder_stream *pStream)
{
m_pMem_blocks = nullptr;
m_error_code = JPGD_SUCCESS;
m_ready_flag = false;
m_image_x_size = m_image_y_size = 0;
m_pStream = pStream;
m_progressive_flag = false
```
```cpp
void jpeg_decoder::free_all_blocks()
{
delete(m_pStream);
m_pStream = nullptr;
```

loader/jpg: fix double free
