src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h

revise code for simple & better readibility.

svg_loader: code refactoring

---

src/bindings/capi/tvgCapi.cpp

Added checks to capi bindings to avoid crash when API is used with invalid parameters.

bindings/capi: Check invalid parameters in capi.

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoader.h

merge loader class with task to simplfy code.

svg_loader: refactoring code.

---

inc/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
test/testCapi.c

Changes:
- add shape's path getter for C binding
- add test for this getter in testCapi.c
- change tvg_shape_linear_gradient_set and tvg_shape_linear_gradient_set to new api

bindings/capi: Added path getters + test in testCapi.c

---

inc/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
test/testCapi.c

put missing const parameter and correct set/get naming.
attention, these two apis are changed!
tvg_gradient_color_stops() => tvg_gradient_set_color_stops()
tvg_gradient_spread() = tvg_gradient_set_spread()

capi: correct interfaces.

---

src/lib/tvgShape.cpp
src/lib/tvgShapeImpl.h

revise duplicate() method for clean & neat code.

common path: code refactoring.

---

README.md

ReadMe: Add description for svg2png

---

inc/thorvg.h
src/lib/tvgCanvas.cpp
src/lib/tvgCanvasImpl.h
src/lib/tvgCommon.h
src/lib/tvgFill.cpp
src/lib/tvgGlCanvas.cpp
src/lib/tvgLinearGradient.cpp
src/lib/tvgPaint.cpp
src/lib/tvgPicture.cpp
src/lib/tvgPictureImpl.h
src/lib/tvgRadialGradient.cpp
src/lib/tvgScene.cpp
src/lib/tvgSceneImpl.h
src/lib/tvgShape.cpp
src/lib/tvgShapeImpl.h
src/lib/tvgSwCanvas.cpp

removed unique_ptr usages from pImpl pattern.
that increased binary size.
2204082 -> 2045672

common: binary optimization.

---

inc/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/examples/testCapi.cpp

added gradient's color_stops and spread getter for Capi binding
add test code in testCapi.c

bindings/capi: Added gradient getter

---

src/lib/tvgBezier.cpp

bezAt() function needed to be fixed.
Also the convergence in the while loop was sped up and
the break condition was changed.
These fixes the problem of plotting dashed strokes in circles and arcs.

Bezier curve:  improvement of the curve splitting algorithm

---

.travis.yml

enable examples and svg2png tool

Travis-CI: Add build options

---

src/examples/Stacking.cpp
src/examples/meson.build

- Description : This example shows how to restack paints node.
- Tests or Samples (if any) : examples/Stacking.cpp

examples: add stacking example

---

README.md
src/lib/tvgPictureImpl.h
src/loaders/svg/tvgSvgPath.cpp
src/loaders/svg/tvgSvgSceneBuilder.cpp
src/meson.build
src/wasm/meson.build
src/wasm/thorvgwasm.cpp
test/wasm_test.html
wasm_build.sh
wasm_cross.txt

Support Emscripten wasm build for thorvg viewer

thorvg viewer: introduce thorvg viewer

---

test/wasm_test.html

Update index.html according to updated wasm interface.
Missed chance to update index.html during review.

wasm test: update sample index.html

---

inc/thorvg.h
src/examples/FillRule.cpp
src/examples/meson.build

one shape shows Winding, the other one shows EvenOdd.

examples FillRule: added shape::fillRule() example

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgPath.cpp

svg_loader SvgLoader: Fix wrong indentation

---

src/lib/tvgCanvasImpl.h
src/lib/tvgFill.h
src/lib/tvgPaint.h
src/lib/tvgSceneImpl.h
src/lib/tvgShapeImpl.h
src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgPath.cpp

Correct missing or incorrect spaces according to coding convention.

common lib/loaders: Fix missing space for coding convention

---

src/loaders/svg/tvgSvgLoader.cpp

svg_loader SvgLoader: Fixed a typo

---

src/lib/tvgLoaderMgr.cpp
src/lib/tvgLoaderMgr.h

keep clean & neat thorvg coding style.

common LoaderMgr: code refactoring

---

src/lib/sw_engine/tvgSwCommon.h
src/lib/sw_engine/tvgSwMemPool.cpp
src/lib/sw_engine/tvgSwShape.cpp
src/lib/sw_engine/tvgSwStroke.cpp

This is a subsequential trial of 1b8188ee676eae5c690b1b88bb823b6ad126bb78
for opimizing memory alloc count.
In this time, it concentrates on stroke outline.
@Issues: 75

sw_engine mempool: performance optimization.

---

src/lib/sw_engine/tvgSwCommon.h
src/lib/sw_engine/tvgSwRle.cpp
src/lib/sw_engine/tvgSwShape.cpp
src/lib/sw_engine/tvgSwStroke.cpp

Tis is a subsequential trial of 1b8188ee676eae5c690b1b88bb823b6ad126bb78
for opimizing memory alloc count.
In this time, it concentrates on rle span.
@Issues: 75

sw_engine rle: performance optimization.

---

src/lib/tvgShape.cpp
src/lib/tvgShapeImpl.h

All shapes will have path data,
avoid unnecesary dynamic memory allocation internally.
@Issues: 75

common shape: memory optimization

---

src/lib/sw_engine/tvgSwRenderer.cpp
src/lib/tvgTaskScheduler.cpp
src/lib/tvgTaskScheduler.h
src/loaders/svg/tvgSvgLoader.cpp

replaced future/promise with mutex since they use a lot of memory allocation number.
plus, binary size is reduced from 2094896 -> 1746864

common taskScheduler: thread sync optmization

---

inc/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp

Capi binding for raw picture->load(data,...) was added

Capi: Picture Raw binding

---

inc/thorvg.h
src/examples/MultiCanvas.cpp
src/examples/Stress.cpp
src/examples/Svg2.cpp
src/lib/tvgPictureImpl.h

this implementation handles the center-aligned scale.
Also removed viewbox usage since we have size() method.

common picture: revise resize method.

---

src/loaders/svg/tvgSvgSceneBuilder.cpp

Scene's opacity() propagates opacity value inside.
Therefore, unnecessary opacity calculation.

svg_loader SceneBuilder: No propagate opacity to child

---

src/examples/Opacity.cpp
src/lib/sw_engine/tvgSwRenderer.cpp
src/lib/sw_engine/tvgSwRenderer.h

Unify Shape+Stroke composition with CompositeCtx which is added for Scene Composition
This fixes clipping issue as well.
@Issues: 164

sw_engine renderer: code refactoring.

---

code_format
tools/codestyle/README
tools/codestyle/c++_clang_formatter.sh
tools/codestyle/code_formatter.sh
tools/codestyle/cpplint_tizen_160919.py
tools/codestyle/cpplint_tizen_dir.sh

Tool allows auto formatting of code according to Google coding standard
for easier control and fixing formatting issues.
Based on tool already used on Tizen.org repo:
https://review.tizen.org/gerrit/gitweb?p=platform/core/api/webapi-plugins.git;a=tree;f=tools/codestyle;h=8a8bd7adfcfe7ed144e8937fda00ae4e3793c33a;hb=refs/heads/tizen

[Tools] Automatic code format tool added

---

src/examples/Opacity.cpp

The circle of Opacity example is not smooth.
So fix it.
https://github.com/Samsung/thorvg/issues/176
./src/exsamples/Opacity

examples Opacity: Add close method

---

src/loaders/svg/tvgSvgLoader.cpp

fix mistake

---

src/loaders/raw/tvgRawLoader.h
src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgSceneBuilder.cpp

Commits
svg_loader SvgLoader: Prevent array overflow
raw_loader RawLoader: Add initialize
svg_loader SvgLoader: Add memory allocation failed check

loader Loader: Refactoring for code safety

---

inc/thorvg.h
src/examples/Masking.cpp
src/lib/gl_engine/tvgGlCommon.h
src/lib/gl_engine/tvgGlRenderer.cpp
src/lib/gl_engine/tvgGlRenderer.h
src/lib/sw_engine/tvgSwRenderer.cpp
src/lib/sw_engine/tvgSwRenderer.h
src/lib/tvgCanvasImpl.h
src/lib/tvgPaint.h
src/lib/tvgPicture.cpp
src/lib/tvgPictureImpl.h
src/lib/tvgRender.h
src/lib/tvgSceneImpl.h
src/lib/tvgShapeImpl.h

Splited out ClipPath routine from other pixel compositions'
since yet it's unlikely compatible...

common composite: code refactoring.

---

src/lib/sw_engine/tvgSwRenderer.cpp

recover a broken shape+stroking opacity that introduced in ealier refactoring...

sw_engine renderer: fix a regression bug.

---

inc/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp

Added Shape->bounds Capi binding

Capi: Shape bounds binding

---

AUTHORS
src/examples/Transform.cpp
src/examples/Update.cpp
src/lib/gl_engine/tvgGlGeometry.cpp
src/lib/gl_engine/tvgGlGeometry.h
src/lib/gl_engine/tvgGlPropertyInterface.cpp

gl_engine: fix coding convention.

---

src/examples/ClipPath.cpp
src/examples/Masking.cpp
src/lib/gl_engine/tvgGlRenderer.cpp
src/lib/gl_engine/tvgGlRenderer.h
src/lib/sw_engine/tvgSwCommon.h
src/lib/sw_engine/tvgSwRaster.cpp
src/lib/sw_engine/tvgSwRenderer.cpp
src/lib/sw_engine/tvgSwRenderer.h
src/lib/tvgCanvasImpl.h
src/lib/tvgPaint.h
src/lib/tvgPictureImpl.h
src/lib/tvgRender.h
src/lib/tvgSceneImpl.h
src/lib/tvgShapeImpl.h

We re-implement the masking feature with image composition method.
This patch is working only for single shape but settle up coming extensions.

common sw_engine: revise the masking implementation.

---

src/lib/sw_engine/tvgSwRenderer.cpp

if shape rendering is failed, all the prepared data must be reset
because those are invalid.
@Issues: 180

sw_engine renderer: fix invalid rle issue.

---

src/lib/sw_engine/tvgSwCommon.h
src/lib/sw_engine/tvgSwRaster.cpp

added a routine that draw non-transformed translucent image.
composition images will use this routine to draw faster.
Also added optimization point comments in raster image.

sw_engine: optimize raster image.

---

src/examples/Masking.cpp
src/lib/sw_engine/tvgSwRaster.cpp

composition alpha masking supports scene/paints targets.
@Examples: Masking
@Issues: 31

sw_engine composition: enhance image masking

---

src/lib/tvgPaint.h

composition target also copied in duplication.
added missing part.

common paint: duplicate composition target.

---

inc/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp

Capi: Composite Method binding

---

inc/thorvg.h
src/examples/InvMasking.cpp
src/examples/meson.build
src/lib/sw_engine/tvgSwRaster.cpp
src/lib/tvgPaint.h

sw_engine composition: invert alpha masking

---

src/lib/sw_engine/tvgSwShape.cpp

Added stroke's RLE reset in shape reset function.

shape: Fixed reset api.

---

.github/workflows/actions_cpplint.yml
.github/workflows/cpp_lint_check.sh

Add a bot that checks the coding style using cpplint
and reports the result as a review comment.
This feature refers to the repository where cpplint
and docker settings with github-action.
This action works whenever a PR is created and updated.
In cpplint, only the violation of ThorVG's coding style is reported
as a warning using several options.
whitespace/parens
whitespace/indent
whitespace/end_of_line
whitespace/blank_line
The bot will review all of the contents of all files in the current commit file list,
However, in the future, we will improve Bot to only review the changes.
[code change example]
[bot's review]
[No problem case]

infra coding_style: Add coding style check bot

---

src/lib/gl_engine/tvgGlGeometry.cpp
src/lib/gl_engine/tvgGlGeometry.h
src/lib/tvgCanvasImpl.h
src/lib/tvgPaint.h
src/lib/tvgPictureImpl.h
src/loaders/svg/tvgXmlParser.cpp

Combine if condition with the same return value.
Remove empty space
Remove tab

common: Clean up code

---

.github/workflows/actions.yml
test/meson.build

This is a build checker using the github action.
When a pull request occurs this action does a basic build,
example build, build with test.
- Screenshot :

infra CI: Introduce new build test with github action

---

src/examples/StrokeGradient.cpp
src/examples/meson.build

Example showing a gradient usage for a stroke.
example for #191

example StrokeGradient

---

src/lib/sw_engine/tvgSwRenderer.cpp

sw_engine Renderer: Fix build problem caused by merge conflict.

---

src/lib/tvgSceneImpl.h

Pre-condition is broken when this commit come - b60a773d12ef5ab558e95066b2deecea8d859e8c
Both condition should be identitcal so that comp logic is perfectly performed.

scene: fix a composition regression bug.

---

src/examples/Duplicate.cpp

Duplication of the Picture with a raw image is added

example: Duplicate.cpp modified

---

src/loaders/svg/tvgSvgSceneBuilder.cpp

If the boundary of scene created through the scenebuilder is larger than the viewbox,
scene(SVG's root) should be clipped to the size of the viewbox.
So, if scene need a clip, add a parent root and add clippath composition to that root.
#277, #290 
[Test SVG]
```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 552 240" width="400" height="200" version="1.1">
<circle  opacity="0.9" fill="#2c9691" fill-rule="nonzero"  cx="100" cy="100" r="300" />
</svg>
```
[before]
[result]

loader SvgSceneBuilder: Add root node to clipping viewBox.

---

src/lib/gl_engine/tvgGlRenderer.cpp
src/lib/gl_engine/tvgGlRenderer.h
src/lib/sw_engine/tvgSwRenderer.cpp
src/lib/sw_engine/tvgSwRenderer.h
src/lib/tvgPaint.h
src/lib/tvgPictureImpl.h
src/lib/tvgRender.h
src/lib/tvgSceneImpl.h
src/lib/tvgShapeImpl.h

Introduce RenderRegion structure for region data
to simplify the methods paratemers.
also depends on the NRVO for the return data.

common engines: code refactoring

---

src/lib/sw_engine/tvgSwCommon.h
src/lib/sw_engine/tvgSwImage.cpp
src/lib/sw_engine/tvgSwMath.cpp
src/lib/sw_engine/tvgSwRenderer.cpp
src/lib/sw_engine/tvgSwRle.cpp
src/lib/sw_engine/tvgSwShape.cpp

1. unified clip & bounding box in rle processing
2. unified outline boundingbox functions between shape & image.

sw_engine: code refactoring

---

src/examples/GradientMasking.cpp
src/examples/meson.build
src/lib/sw_engine/tvgSwRaster.cpp

@Issues: 243
After adding gradients to rectangle, mask wasnt visible as it should, described in #243, also some problems with invert masking + gradients was found here is fix also for that.
After fix:

gradients: paint linerar gradients properly with mask composition method

---

src/lib/sw_engine/tvgSwRaster.cpp

Masking and Inverse masking are for now rastered properly only for the linear
gradients without the opacity.
The if statement is pulled outside the for loop in order to improve the performance.
Please be aware that antialiasing still needs to be applied, as well as translucent gradients and radial gradients.
- Screen Shots :

sw_engine: fixing linear gradient rastering for shapes with composition

---

meson.build
meson_options.txt
src/lib/tvgLoaderMgr.cpp
src/lib/tvgLoaderMgr.h
src/loaders/meson.build
src/loaders/png/meson.build
src/loaders/png/tvgPngLoader.cpp
src/loaders/png/tvgPngLoader.h
src/meson.build

- Description : Added loading png images using libpng. To enable this feature, change the `png` option in `meson_options` to **true**.
- Sample: #285

png_loader: Added libpng based png loading

---

src/lib/tvgLoaderMgr.cpp

Print info if file format is not supported.

loader loaderMgr: add a useful debug message.

---

src/lib/sw_engine/tvgSwRaster.cpp

ialpha variable is removed in functions in which it was used only once
unnecessary memory allocation is removed as well

sw_engine: unnecessary memory allocation and variables has been removed

---

src/loaders/png/tvgPngLoader.cpp
src/loaders/png/tvgPngLoader.h

Seperate behaviors open/read/close,
free/close pngimage properly,
add copyright for files.
There still left one optimization point by applying Task.

loader png: code refactoring

---

src/lib/tvgPaint.cpp
src/lib/tvgPaint.h
src/lib/tvgSceneImpl.h
src/lib/tvgShape.cpp

remove inlining to reduce size by 22kb.

binary optimization

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h
src/loaders/svg/tvgSvgSceneBuilder.cpp

++ clean code.
Remove any unwilling code.

loaders svg: code refactoring

---

src/loaders/svg/tvgSvgSceneBuilder.cpp

Current loader could return invalid shapes -default, from _appendShape()-
by a certain interpretation result,
Though it's a wrong or exception case, we can prevent worse case by avoiding it.

loaders svg: prevent composition setting if the result shape is invalid.

---

src/loaders/svg/tvgSvgSceneBuilder.cpp

composition target missed transform of its source.
That brings incorrect composition area.
This fixes it.

loader svg: fix composition(mask/clip) issue.

---

src/loaders/svg/tvgSvgLoader.cpp

keep it clean & neat within tvg coding convention.

loaders svg: code refactoring.

---

src/loaders/svg/tvgSvgLoader.cpp

prevent buffer overflow just in case.

loaders svg: ++safety

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h
src/loaders/svg/tvgSvgPath.cpp

strtof's behavior is changed by system locale.
https://linux.die.net/man/3/strtof
Because of this, strtof(10.0000) returns 0.0 in some locales.
When a given value string is locale-independent, strtof has to be
replaced to custom function.

loader SvgLoader: add locale-independent strtof function

---

inc/thorvg.h

The descriptions have been changed and new ones added.
There are still few apis for which descriptions are missing.
- Issue Tickets (if any) : #27

doc common: adding the documentation for the C++ APIs

---

.github/workflows/actions.yml
.github/workflows/actions_cpplint.yml
.github/workflows/cpp_lint_check.sh

infra Actions: If no coding style error, no comment

---

inc/thorvg.h

doc common: change of the return value in the composite API

---

inc/thorvg.h
inc/thorvg_capi.h

group ThorVG C++ APIs
group ThorVGCapi C APIs
https://github.com/Samsung/thorvg/issues/27

doc common: Add grouping of C++ api and C api

---

inc/thorvg_capi.h

Groupping like below
```
C APIs
- Initializer
- Canvas
- SwCanvas
- Paint
- Shape
- Gradient
- Picture
- Scene
```
https://github.com/Samsung/thorvg/issues/27

doc common: Revise c api doc

---

inc/thorvg.h
inc/thorvg_capi.h

doc: polish up api documentation.

---

inc/thorvg_capi.h

- #define are moved to the corresponding \defgroup. I'm not sure whether it is more clear. I've done this because enums were already moved
- ThorVG changed to TVG (it was changed in thorvg.h as well)
- both, NULL and nullptr, are used in the file - is it ok?

docs: thorvg_capi

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h
src/loaders/svg/tvgXmlParser.cpp
src/loaders/svg/tvgXmlParser.h

Change tag name "Doc" to "Svg"
Fix "Mask" tag name.
Add element to skip output (title)
Add attribute to skip output (id, data-name, version, overflow=visible, xmlns*, xml:space)

log SvgLoader: Enhance log message

---

src/lib/sw_engine/tvgSwRaster.cpp

The translucent rastering function is splitted into 3 other (instead of if/else).
An additional function is introducted to decide which one of the 3 should be called.
These refactoring is done to preserve the convention used for all other rastering functs.
Please be aware, that I moved some parts of the code and close them in functions. There are no other important changes (I changed the name buf to buffer and I moved ++span next to ++i in for loop).
I'd like to do exactly the same changes for linear grad rect and radial grad.

sw_engine: refactoring the linear gradient rle rastering function

---

inc/thorvg.h
src/lib/tvgPaint.cpp
src/lib/tvgPaint.h

I need this API in the saver module.

common: added API to get the transformation matrix of the object

---

meson.build
meson_options.txt
test/catch.hpp
test/meson.build
test/testInitializer.cpp
test/testMain.cpp

Catch2 is a multi-paradigm test framework for C++.
It is primarily distributed as a single header file,
very easy and simple to adopt this to thorvg project.
This patch introduces catch2 infrastsructure and one prototype as a sample.
You can refer "testInitializer.cpp", how to add unit test! (nothing else)
Also, enable Unit-tests with meson option when you change any thorvg code.
$meson build -Dtests=true.
launch tvgUnitTest in the build result then verify 100% coverage
before submitting any patches.
For your information, you can check test option by this command:
$tvgUnitTest -h

tests: introduce catch2 unit tests infrastructure.

---

src/lib/meson.build
src/lib/tvgTvgHelper.h

tvgTvgHelper.h is a base file used for .tvg saver/loader module

TVG Loader/Saver module: tvg helper file

---

src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp

Added 'tvg_picture_load_data' capi.

capi: picture load data

---

meson.build
src/lib/tvgLoaderMgr.cpp

regression by - 15b56a66de8fb5872afc4bda4986cae6967ddb56

fix build break.

---

src/loaders/tvg/tvgTvgLoadParser.cpp
src/loaders/tvg/tvgTvgLoadParser.h
src/loaders/tvg/tvgTvgLoader.cpp

TVG format verification was added on TvgLoader:open()

tvg_loader: added tvg format verification

---

test/capi/capiInitializer.cpp
test/capi/capiPaint.cpp
test/capi/capiShape.cpp
test/capi/capiSwCanvas.cpp

tset capi: code refactoring.

---

.github/workflows/actions.yml

infra CI: Fix test flag of test build

---

.github/workflows/actions.yml
test/meson.build

Users can download the unit test result list from PR-> Checks -> Build Test -> Artifacts.

infra CI: Upload unit test result to artifact

---

test/meson.build
test/testScene.cpp

- Creation
- Push
- Reserve
- Clear

test Scene: Add tvg::Scene unit tests

---

src/loaders/tvg/tvgTvgLoadParser.cpp

keep it neaat & clean code for readibility and maintenence.

tvg_loader: code refactoring.

---

src/bin/svg2png/svg2png.cpp

previous code didn't take care of multi-threading.
This revise code to avoid changing canvas buffer during multi-tasking.

svg2png: revise code to fix memory violation.

---

src/bin/svg2png/svg2png.cpp

Modify the code to fit coding style

svg2png: Clean up code

---

README.md

Use spellcheck

---

src/lib/sw_engine/tvgSwRenderer.cpp

tvg sw_engine tries to skip composition as far as its doable,
it tries composition only if the translucent shape with stroking is there.
There has been a condition bug that composition is applied unnecessarily
even if stroking is disabled. This resulted in broken blending
at gradient filling since it applied alpha values multiple times.
Issues:
https://github.com/Samsung/thorvg/issues/445

sw_engine renderer: fix a broken composition bug

---

.github/workflows/actions.yml

infra: ++ strict build test

---

src/lib/sw_engine/tvgSwCommon.h

runtime error: load of value 190, which is not a valid value for type 'bool'
@Issue: https://github.com/Samsung/thorvg/issues/544

sw_engine: --sanitizer errors

---

inc/thorvg.h
src/lib/tvgShape.cpp
src/lib/tvgShapeImpl.h

user may need to reset stroke dash to off,
now stroke api allows it.

common shape: allow to reset stroke dash.

---

inc/thorvg.h
src/lib/tvgLoaderMgr.cpp
src/lib/tvgLoaderMgr.h
src/lib/tvgPictureImpl.h

Fixed load() to return InvalidArgument if the file path is invalid.

common picture: ++exception case.

---

src/loaders/png/tvgPngLoader.cpp
src/loaders/png/tvgPngLoader.h

Added PngLoader::open(const char* data, uint32_t size, bool copy)
Changed variables visibility to private

png_loader: added open from memory

---

test/capi/capiScene.cpp
test/capi/meson.build

issue: https://github.com/Samsung/thorvg/issues/45

tests capi: Add capi Scene TC

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h
src/loaders/svg/tvgSvgSceneBuilder.cpp

optimize memory usage & fix memory leak at gradient.

svg_loader: optimize memory usage.

---

src/loaders/jpg/tvgJpgLoader.cpp
src/loaders/jpg/tvgJpgLoader.h

keep it clean and neat code add some TODO comments for the future tasks.
This also fixes potential data memory leaks.

jpg_loader: code refactoring

---

src/loaders/svg/tvgSvgUtil.cpp

svg_loader SvgUtil: Move nullcheck to before use

---

src/examples/images/logo_test.svg

Manually created svg with edited logo.svg that test most of the svg tags
and attributes

example: logo_test.svg

---

test/testPicture.cpp

Added rendering jpg and png files to increase UTC code coverage

test: render jpg and png files

---

test/capi/capiPaint.cpp
test/capi/capiShape.cpp
test/capi/capiSwCanvas.cpp

Added tests for tvg_canvas_reserve, tvg_canvas_update_paint, tvg_paint_duplicate, tvg_paint_set_composite_method, tvg_shape_cubic_to, tvg_shape_close

test capi: added missing canvas, paint and shape tests

---

src/loaders/jpg/tvgJpgLoader.cpp
src/loaders/jpg/tvgJpgLoader.h

jpg header decompression on open()

jpg_loader: decompress header on opening

---

src/lib/sw_engine/tvgSwRenderer.cpp

For filled and stroked shapes with a gradient, the opacity
was applied during the composition and during the ctable update.
To prevent this, in case the composition occurred, ctable
is updated with the opacity = 255.
before:
after:
code:
```
shape->appendRect(0, 0, 800, 800, 0, 0);
shape->fill(255, 0, 0, 255);
if (canvas->push(move(shape)) != tvg::Result::Success) return;
colorStops[0] = {0, 0, 0, 255, 255};
colorStops[1] = {1, 0, 0, 255, 255};
shape1->appendRect(410, 0, 180, 180, 10, 10);
auto fill = tvg::LinearGradient::gen();
fill->linear(0, 0, 800, 800);
fill->colorStops(colorStops, 2);
shape1->fill(move(fill));
shape1->opacity(100);
shape1->stroke(10);
fill = …
```

sw_engine: preventing the double application of the opacity

---

src/lib/sw_engine/tvgSwRenderer.cpp

+ trivial changes while reading the code.

sw_engine renderer: code refactoring

---

src/lib/sw_engine/tvgSwFill.cpp
src/lib/sw_engine/tvgSwRaster.cpp
src/lib/tvgCommon.h
src/lib/tvgLinearGradient.cpp
src/lib/tvgPicture.cpp
src/lib/tvgRadialGradient.cpp
src/lib/tvgSaverImpl.h
src/lib/tvgScene.cpp
src/lib/tvgSceneImpl.h
src/lib/tvgShape.cpp

common: code refactoring

---

src/examples/Tvg.cpp

tvg_saver: example

---

src/loaders/tvg/tvgTvgLoadParser.cpp

tvg format: code refactoring #7

---

src/lib/tvgBinaryDesc.h
src/lib/tvgSaverImpl.h
src/loaders/tvg/tvgTvgLoadParser.cpp

revise format of the macro names, no logical changes.

tvg format: code refactoring #9

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h
src/loaders/svg/tvgSvgSceneBuilder.cpp

`node->style->comp` changed to `node->style->clipPath` and `node->style->mask`.

svg_loader: allow both clipPath and mask together

---

inc/thorvg.h

3 api candidates has been verified since it's tagged in beta,
we confirm that they are useful for tvg usages.
* Modified: 
removed composite() getter api

apis: promote beta apis to the official ones.

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h
src/loaders/svg/tvgXmlParser.cpp
src/loaders/svg/tvgXmlParser.h

clean up about logging before replacing it with TVGLOG()

svg_loader: code refactoring.

---

meson.build
meson_options.txt
src/lib/sw_engine/tvgSwCommon.h
src/meson.build

Changes:
- Added 'neon' vector option in build system
- Introduced neon version of rasterRGBA32 API, which improves speed of the function on ARM cpu's around ~35% (measured on 800x800 array of uint32_t)

sw_engine common: Added neon version of rasterRGBA32 API.

---

src/lib/tvgLoader.cpp

common loader: use RawLoader class immediately.

---

src/lib/tvgLoader.cpp

revise the mimetype load method to keep it clean & neat.

tvg loader: code refactoring

---

src/lib/tvgShape.cpp

common Shape: Fix check to invalid argument

---

src/lib/sw_engine/tvgSwRasterNeon.h

Neon operations should be performed on memory aligned to 8 bytes.
This commit fixes this issue and increase stability of neon rasterizer.

sw_common neon: Fix issue with unaligned memory.

---

meson.build
src/meson.build

neon/avx can't be resided in together,
we replace it with a string variable.

infra: simplify vector meson option.

---

inc/thorvg.h

Added description according to api behavior change

doc: Enhance appendPath docs

---

src/lib/sw_engine/tvgSwRasterNeon.h

sw_engine neon: refactoring

---

test/testSwEngine.cpp

test SwEngine: _rasterTranslucentRect added into the tests

---

src/lib/sw_engine/tvgSwRasterAvx.h

The aligned and not aligned memory parts handled separately.
This gives around 10% of the performance increase (tested on i7-8700 CPU)

sw_engine avx: the not aligned memory separated in the rasterRGBA32 func

---

src/wasm/thorvgwasm.cpp

Changed function `bool update(int width, int height, bool force)`;

wasm: add force parameter for update() function

---

src/wasm/thorvgwasm.cpp

defaultData is no more needed for the viewer

wasm: remove default data

---

src/wasm/thorvgwasm.cpp

Improved bounds calculation in case a rotation is applied

wasm: improved bounds calculation

---

src/lib/sw_engine/tvgSwRasterNeon.h

This PR fixes build issues observed when ThorVG is crosscompiled for ARM with vectorization option enabled

sw_engine: Fixed build errors.

---

src/savers/tvg/tvgTvgSaver.cpp
src/savers/tvg/tvgTvgSaver.h

removed the duplicated given child transform code,
no logical changes actually.

tvg_saver: code refactoring

---

src/lib/tvgShape.cpp

visible on windows using clang

common: preventing possible compiler warnings

---

src/lib/sw_engine/tvgSwFill.cpp
src/lib/sw_engine/tvgSwStroke.cpp
src/lib/tvgBezier.cpp
src/lib/tvgShape.cpp
src/loaders/svg/tvgSvgPath.cpp
src/loaders/svg/tvgSvgSceneBuilder.cpp
src/savers/tvg/tvgTvgSaver.cpp

msvc warings regarding conversion int->float are still present

common: preventing msvc compiler warnings

---

src/meson.build

connected with issue #813 - this problem will come up after solving the one with VS

infra: excluding pthread lib dependency on windows os

---

src/lib/sw_engine/tvgSwRasterAvx.h

__m256i_u is an internal gcc/clang type, which can not be used by msvc.
To ensure the portability of the lib a proper intrinsic is used.
The question, whether the aligned and unaligned memory should be handled separately (like in #753) is still open. 
present in #813

sw_engine avx: removing not portable variable type

---

test/capi/capiPicture.cpp

Added lines for testing tvg_picture_get_viewbox function in test/capi/capiPicture.cpp

test: added test for tvg_picture_get_viewbox function

---

README.md

Added links to the thorvg website and the docs in the repo.
Relates to #856

Readme: Add links to documentation 

---

.github/workflows/build_win.yml
meson.build
src/lib/tvgInitializer.cpp

Add build test for normal build
https://github.com/Samsung/thorvg/issues/600

infra: Add window build test in CI

---

meson.build
meson_options.txt
src/loaders/meson.build

just for developer convenience (including me)
ex) $meson . build -Dloaders="all" ...

infra: add all option to enable all loader formats.

---

test/testPicture.cpp

test Picture: Fix array release

---

src/meson.build

apply two more compiler options to reduce binary size.
Saved about 7kb.

optimize binary size.

---

src/wasm/thorvgwasm.cpp

Wasm needs ABGR STRAIGHT buffer.
As there is a problem using ABGR for loaders, it is better to use ARGB8888.
This patch makes wasm using ARGB8888 and relocate pixels and unmultiply after sync().

WASM: Use ARGB8888. Convert into ABGR and unmultiply after sync()

---

src/lib/gl_engine/tvgGlProgram.cpp
src/lib/gl_engine/tvgGlShader.cpp
src/lib/sw_engine/tvgSwCommon.h
src/lib/sw_engine/tvgSwMemPool.cpp
src/lib/tvgFill.cpp
src/lib/tvgFill.h
src/lib/tvgShapeImpl.h

replaced new/delete with malloc/free
saved 936 bytes

binary size optimization

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h

Clips and masks require to implement some additional variables,
so the new struct has been introduced. Implementation of the usage
of these additional variables will be the subject of a separate
commit.

svg_loader: SvgCompositeNode introduced

---

src/loaders/svg/tvgSvgSceneBuilder.cpp

Since the mask color is important, the mask can not be saved
as a shape. To preserve the color information, each shape
is saved separately and pushed into the final scene.
NOTE:
the presented results are drawn after pr #620 is applied
before:
after:
code:
```
<svg viewBox="-10 -10 120 120">
<mask id="myMask">
<rect x="0" y="0" width="100" height="100" fill="white" />
<path d="M10,35 A20,20,0,0,1,50,35 A20,20,0,0,1,90,35 Q90,65,50,95 Q10,65,10,35 Z" fill="black" />
</mask>
<polygon points="-10,110 110,110 110,-10" fill="orange" />
<circle cx="50" cy="50" r="50" mask="url(#myMask)" />
</svg>
```
------------------------
before:
after:
code:
```
<svg viewBox="-10 -10 120 120">
<mask id="myMask">
<g fill="red">
<rect x="0" y="0" width="50" height="20" />
<g fill="white">
<rect x="50" y="0" …
```

svg_loader: mask node loaded as a scene

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h
src/loaders/svg/tvgSvgSceneBuilder.cpp
src/loaders/svg/tvgXmlParser.cpp

removed the std::string usages.
saved 17kb.

svg_loader: reduce binary size

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h

svg_loader: reduce binary size.

---

src/lib/tvgArray.h

properly handle if the realloc() is failed.
@Isssue: https://github.com/Samsung/thorvg/issues/995

common array: + exception handling.

---

src/lib/tvgSaver.cpp

fix the memory leak in the corner case
detected by tvg test suites
@Issue: https://github.com/Samsung/thorvg/issues/995

common: ++exception handling.

---

src/lib/tvgPaint.cpp
test/capi/capiPaint.cpp

delete dangling object properly in the corner case.
@Issue: https://github.com/Samsung/thorvg/issues/995

common paint: fix a memory leak.

---

src/lib/sw_engine/tvgSwRenderer.cpp

Tasks can be disposed while the renderer referencing it.
Now, we can delete the tasks with lazy approach by introducing some tags.
@Issue: https://github.com/Samsung/thorvg/issues/995

sw_engine renderer: fix the invalid memory access in the corner case.

---

src/lib/sw_engine/tvgSwCommon.h
src/lib/sw_engine/tvgSwRaster.cpp

The function pointers used to pass the proper blending method - mask
or inverse mask.

sw_engine: unification of mask and inv mask functions

---

src/lib/sw_engine/tvgSwCommon.h
src/lib/sw_engine/tvgSwRaster.cpp

renamed internal variables, no logical changes.

sw_engine raster: code refactoring

---

src/lib/sw_engine/tvgSwRaster.cpp

Rastering functions for masked images that are not rectangular
(clipped) were implemented.

sw_engine: missing implementations added

---

src/lib/tvgPaint.cpp
src/lib/tvgPaint.h

renamed internal variable. no logical changes.

common paint: code refactoring

---

.github/workflows/actions.yml
.github/workflows/build_win.yml

This test works after the patch is merged into the master branch.
issue: https://github.com/Samsung/thorvg/issues/1032

infra: Add build test after patch merged

---

README.md

This badge is updated when a patch is pushed to the master branch.

README: Update Badge

---

src/loaders/png/tvgLodePng.cpp

decoding color channels rgba -> bgra
@Issue: https://github.com/Samsung/thorvg/issues/1007

png_loader: correct colorspace

---

src/loaders/svg/tvgSvgLoader.cpp

svg_loader: memory properly released

---

src/loaders/svg/tvgSvgLoader.cpp

svg_loader: mem properly freed

---

src/lib/sw_engine/tvgSwCommon.h
src/lib/sw_engine/tvgSwRaster.cpp
src/lib/sw_engine/tvgSwRenderer.cpp

we are considering the larger space of the image buffer,
in this case stride info is necessary.

sw_engine image: introduce the stride property for the image.

---

src/lib/sw_engine/tvgSwCommon.h
src/lib/sw_engine/tvgSwImage.cpp
src/lib/sw_engine/tvgSwMath.cpp
src/lib/sw_engine/tvgSwRenderer.cpp
src/lib/tvgMath.h

Applied the fast-track routine for axis-aligned images.
This helps to remove outline generation if no clips.

sw_engine image: optimized image rendering.

---

src/lib/sw_engine/tvgSwImage.cpp
src/lib/sw_engine/tvgSwMath.cpp
src/lib/tvgMath.h
src/lib/tvgPaint.cpp

cover the four cases: 0, 90, 180, 270 degrees...

common paint: improve rotation condition precision

---

src/lib/sw_engine/tvgSwFill.cpp
src/lib/sw_engine/tvgSwRaster.cpp
src/lib/tvgMath.h
src/lib/tvgPaint.cpp
src/lib/tvgRender.cpp
src/lib/tvgShape.cpp
src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgSceneBuilder.cpp
src/savers/tvg/tvgTvgSaver.cpp

introduced mathZero(), mathEqual() for floating variables.

common math: code refactoring

---

src/lib/sw_engine/tvgSwRasterNeon.h

keep the internal function name consistency.

sw_engine neon: code refactoring.

---

.github/workflows/actions.yml

0.45 -> latest. For b_sanitize option. (0.45 version is not supported).

infra: Use latest meson version

---

src/lib/sw_engine/tvgSwRaster.cpp

these solid images shouldn't apply the alpha blending...

sw_engine raster: optimize the image raster

---

src/lib/tvgShapeImpl.h

common shape: fix memory access violation

---

src/lib/sw_engine/tvgSwCommon.h
src/lib/sw_engine/tvgSwImage.cpp
src/lib/sw_engine/tvgSwRaster.cpp

sw_engine image: code refactoring

---

src/loaders/svg/tvgSvgLoader.cpp

svg_loader: Add nullptr check.

---

.github/workflows/cpp_lint_check.sh

In order to avoid duplication of the already created comment,
already created results will be deleted.

infra stylebot: Delete existing comments

---

src/lib/sw_engine/tvgSwRaster.cpp

separate internal functions per context
and keep the coding convention.

sw_engine image: refactoring before further development.

---

src/lib/sw_engine/tvgSwRaster.cpp

implement composition by translucent / opaque.

sw_engine image: complete sequeqnce of the direct rgb image drawing.

---

src/lib/sw_engine/tvgSwRaster.cpp

implement composition by translucent / opaque.

sw_engine image: complete sequeqnce of the scaled rgb image drawing.

---

src/lib/sw_engine/tvgSwRasterTexmap.h

Unrolled the blending stages by applying macro magics.
I know this is a bit bad for code readibility
but good for the performance and the optimal LOC.

sw_engine texmap: code refactoring.

---

src/lib/sw_engine/tvgSwRaster.cpp

+ blending stages using macro magics.
I know this is a bit bad for code readibility but good for the maintanence

sw_engine raster: code refactoring.

---

src/lib/sw_engine/meson.build
src/lib/sw_engine/tvgSwRasterTexmap.h
src/lib/sw_engine/tvgSwRasterTexmapInternal.h

Wrong inline function with C-preprocessing doesn't work at all...
Correct them with including the separate files instead.

sw_engine raster: fix the texmap regression bug.

---

src/lib/sw_engine/tvgSwRasterTexmapInternal.h

remove exceptional handling for the performance.

sw_engine texmap: remove unnecessary conditions.

---

src/lib/sw_engine/tvgSwRaster.cpp

Gave up the optimization this logic.
It brings too many digressed code, not good for maintenance...

 sw_engine raster: fix the regression bug of the image simple scaling rendering

---

src/examples/all.sh
src/examples/meson.build

This patch will save your time to check example.
./all.sh [interval time between examples, default is 1 second]

example: add script to execute all

---

src/examples/LumaMasking.cpp
src/examples/meson.build

Added an example ColorMasking.cpp that tests CompositeMethod::ColorMask
Merge after https://github.com/Samsung/thorvg/pull/620

example: added LumaMasking.cpp

---

src/loaders/svg/tvgSvgLoader.cpp

prevent a crash with an exceptional handling.
@Issue: https://github.com/Samsung/thorvg/issues/1131

svg_loader: ++robustness

---

src/loaders/svg/tvgSvgLoader.cpp

_svgLoaderParerXmlClose -> _svgLoaderParserXmlClose

svg_loader: typo fixed

---

src/loaders/svg/tvgSvgSceneBuilder.cpp

For masks with colors other than white the ColorMask should be used
instead of the AlphaMask. For the perf reasons the ColorMask is not used
when it's not necessary.
issue #619
it builds after #620 is merged

svg_loader: LumaMask used

---

src/loaders/svg/tvgXmlParser.cpp

The weekest condition should be checked as the last one.
Otherwise CDATA marker was never found.

svg_loader: changed the order of if conditions

---

.github/workflows/actions.yml

libefl-dev -> libefl-all-dev
ubuntu 19 -> 20
meson user install -> root install

infra: Fix ubuntu version and meson install

---

src/lib/sw_engine/tvgSwImage.cpp

sw_engine: float casted on the unsigned int type

---

src/loaders/jpg/tvgJpgd.cpp

fix the invalid negative shift operations.
@Issue: https://github.com/Samsung/thorvg/issues/1172

jpeg_loader: resolve the asan bug report.

---

src/loaders/svg/tvgSvgLoader.cpp

svg_loader: clearing the parser stop flags

---

src/bin/svg2png/svg2png.cpp

Add a message according to the returned Result type.

svg2png: Add more error message types

---

src/bin/svg2png/svg2png.cpp
src/bin/svg2tvg/svg2tvg.cpp

Windows: use _fullpath() instead of fullpath().

---

src/examples/Texmap.cpp
src/examples/meson.build

added texture mapping example.
@Issues: https://github.com/Samsung/thorvg/issues/1241

examples: Added Texmap

---

inc/thorvg.h
src/examples/Accessor.cpp
src/lib/tvgAccessor.cpp

It can pass user data to the callback function.
https://github.com/Samsung/thorvg/issues/1275

common Accessor: Add access API using std::function

---

README.md

Thorvg can be installed with vcpkg
I added it to the readme.

docs : Add vcpkg Installation Document

---

src/examples/TvgSaver.cpp

extracted functions for a better readiabilty.

examples TvgSaver: code refactoring.

---

src/lib/tvgPicture.cpp
src/lib/tvgPictureImpl.h
test/testPicture.cpp

invalid arguments won't be allowed.
@Issue: https://github.com/Samsung/thorvg/issues/1241

common picture: +exception handling.

---

src/examples/MultiCanvas.cpp
src/examples/Svg.cpp
src/examples/Tvg.cpp

Reference to the 'count' was ambiguous (var name / std::count).

examples: fixing building errors on macOS

---

src/examples/ImageScaleDown.cpp
src/examples/ImageScaleUp.cpp

ImageScaleUp/ImageScaleDown fixed.

examples: fixing the crash for disabled loaders

---

src/loaders/svg/tvgSvgLoader.cpp

svg_loader: fixing name

---

inc/thorvg.h
src/lib/gl_engine/tvgGlRenderer.cpp
src/lib/gl_engine/tvgGlRenderer.h
src/lib/sw_engine/tvgSwRenderer.cpp
src/lib/sw_engine/tvgSwRenderer.h
src/lib/tvgPaint.cpp
src/lib/tvgPaint.h
src/lib/tvgPictureImpl.h
src/lib/tvgRender.h
src/lib/tvgSceneImpl.h
src/lib/tvgShapeImpl.h

Keep small size & neat apis.
The main focus is to reduce the paint size and remove an api at the out of user demand.

clipper refactoring

---

.gitignore
src/lib/gl_engine/tvgGlCommon.h
src/lib/gl_engine/tvgGlGeometry.cpp
src/lib/gl_engine/tvgGlGeometry.h
src/lib/gl_engine/tvgGlRenderer.cpp
src/lib/gl_engine/tvgGlRenderer.h
src/lib/sw_engine/tvgSwCommon.h
src/lib/sw_engine/tvgSwRenderer.cpp
src/lib/sw_engine/tvgSwRenderer.h
src/lib/sw_engine/tvgSwShape.cpp
src/lib/sw_engine/tvgSwStroke.cpp
src/lib/tvgRender.h
src/lib/tvgShape.cpp
src/lib/tvgShapeImpl.h

re-design the shape data structure so that render backends are able to access them directly.
To achieve this, migrate shape/stroke/path
from the canvas interface to the render interface.

common shape: code refactoring & data optimization.

---

src/lib/sw_engine/tvgSwRasterTexmap.h

Prevent any potential crash.
@Issues: https://github.com/thorvg/thorvg/issues/1327

sw_engine - ++safety

---

test/capi/capiPicture.cpp

test capi: ++coverage

---

meson.build
meson_options.txt
src/savers/meson.build

ex) meson . build -Dsavers="all", ...

infra - add 'all' option for savers.

---

src/lib/tvgCommon.h

Introducing colors for different log types,
file name and line number added (for warnings
and errors only).

common: log msg modified

---

.github/workflows/codeql.yml

Setup a bot script to run codeql.
It discovers vulnerabilities across a thorvg codebase.
https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/viewing-code-scanning-logs

infra github: apply codeql

---

.github/workflows/actions.yml
.github/workflows/build_win.yml
.github/workflows/memcheck_asan.sh

Specify the build option "all" for the future expansion.

infra github: updated script

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h

Till now only the grad stops were inherited. Now all
grad attribs are.
Inheritance from different grad type is not supported.
@issue: https://github.com/thorvg/thorvg/issues/1209

svg_loader: gradient inheritance implemented 

---

src/examples/SceneClipper.cpp
src/examples/meson.build
src/lib/gl_engine/tvgGlRenderer.cpp
src/lib/gl_engine/tvgGlRenderer.h
src/lib/sw_engine/tvgSwCommon.h
src/lib/sw_engine/tvgSwRenderer.cpp
src/lib/sw_engine/tvgSwRenderer.h
src/lib/sw_engine/tvgSwRle.cpp
src/lib/tvgRender.h
src/lib/tvgSceneImpl.h

https://github.com/thorvg/thorvg/issues/524

Support Scene ClipPath

---

inc/thorvg.h
src/lib/sw_engine/tvgSwRenderer.cpp
src/lib/tvgRender.h
src/lib/tvgShape.cpp
src/lib/tvgShapeImpl.h
src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h
src/loaders/svg/tvgSvgSceneBuilder.cpp

@issue: https://github.com/thorvg/thorvg/issues/1340

svg_loader: paint-order attrib handled 

---

src/bin/svg2tvg/svg2tvg.cpp

Complete the Windows port build that is currently missing.
@Issue: https://github.com/thorvg/thorvg/issues/882

tools svg2tvg: ++Windows port

---

src/bin/svg2png/svg2png.cpp
src/lib/sw_engine/tvgSwStroke.cpp
src/loaders/jpg/tvgJpgLoader.cpp
src/loaders/png/tvgPngLoader.cpp
src/loaders/raw/tvgRawLoader.cpp

@Issue: https://github.com/thorvg/thorvg/issues/1381

Make it silent MSVC's trivial compilation warnings.

---

inc/thorvg.h
src/bin/meson.build
src/bin/svg2png/meson.build
src/bin/svg2tvg/meson.build
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/examples/Svg2.cpp
src/examples/meson.build
src/meson.build
test/capi/meson.build
test/meson.build
test/testPaint.cpp
test/testPicture.cpp

Issue: https://github.com/thorvg/thorvg/issues/1234

infra: specify TVG_API for both static/dynamic linking.

---

src/lib/sw_engine/tvgSwMemPool.cpp
src/lib/sw_engine/tvgSwRle.cpp
src/lib/tvgTaskScheduler.cpp
src/lib/tvgTaskScheduler.h

@Issue: https://github.com/thorvg/thorvg/issues/1370

Fix crash issue.

---

src/lib/tvgInitializer.cpp
src/loaders/svg/tvgSvgCssStyle.cpp
src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h
src/loaders/svg/tvgSvgSceneBuilder.cpp

Get rid of excessive type casting.

code refactoring

---

src/lib/sw_engine/tvgSwRaster.cpp

the value should be updated properly.

sw_engine: fix a logical wrong.

---

.github/workflows/regression.yml
.github/workflows/regression_check.sh
test/regression/check_same_image_size.py
test/regression/settings.toml

CI contains 3 parts:
- Testing for regressions - testing valid files if differs between master branch and PR
- Testing for differences in currently broken files
- Testing if png files are created in reproducible way(in size)
Output is collected and everything is added into comment into PR if anything is changed.
Differences from first and last step are critical, so CI will fail if found any regression.
In second step, there is no method to say if changes are good or bad, so that is why it never fails.

infra: Improved regression finder

---

src/lib/sw_engine/tvgSwRenderer.cpp
src/lib/tvgTaskScheduler.h

fully recovered from the scene clipping multi-tasksing.
@Issue: https://github.com/thorvg/thorvg/issues/1430

sw_engine: fix the dead lock issue.

---

inc/thorvg.h
test/capi/capiPaint.cpp
test/testPaint.cpp

- enum class CompositeMethod::LumaMask
- Result Picture::load(uint32_t* data, uint32_t w, uint32_t h, bool copy)

apis: Let's promote the beta APIs to official ones.

---

meson.build
meson_options.txt
src/lib/gl_engine/tvgGlRenderer.cpp
src/lib/meson.build

gl engine doesn't work. it's totally broken.

fix gl engine

---

src/examples/Performance.cpp
src/lib/tvgPicture.cpp
src/lib/tvgPictureImpl.h
src/lib/tvgSceneImpl.h

Issue: https://github.com/thorvg/thorvg/issues/1423

fix composition bugs

---

inc/thorvg.h
src/examples/Masking.cpp
src/examples/Svg.cpp
src/lib/sw_engine/tvgSwRenderer.cpp
src/lib/tvgPictureImpl.h
src/lib/tvgSceneImpl.h
src/lib/tvgShape.cpp
src/lib/tvgShapeImpl.h

Issue: https://github.com/thorvg/thorvg/issues/209
Result:

fix stroking composition

---

inc/thorvg.h
src/examples/InvLumaMasking.cpp
src/examples/meson.build
src/lib/sw_engine/tvgSwCommon.h
src/lib/sw_engine/tvgSwRaster.cpp
src/lib/sw_engine/tvgSwRasterTexmap.h
src/lib/sw_engine/tvgSwRasterTexmapInternal.h
src/lib/tvgRender.h
test/testPaint.cpp
test/testSwEngine.cpp

Issue: https://github.com/thorvg/thorvg/issues/404
InvLumaMask:
LumaMask:

Support Inverse Luma Mask

---

.github/workflows/regression.yml

CI: Fix ubuntu-latest apt-get install ... 404 Not Found.

---

src/lib/sw_engine/tvgSwCommon.h
src/lib/sw_engine/tvgSwFill.cpp
src/lib/sw_engine/tvgSwRaster.cpp
src/lib/sw_engine/tvgSwRasterAvx.h
src/lib/sw_engine/tvgSwRasterC.h
src/lib/sw_engine/tvgSwRasterNeon.h
src/lib/sw_engine/tvgSwRasterTexmapInternal.h

Still trying to simplifying raster code so that thorvg could introduce the a bunch of masking method code nicely.

Raster code refactoring

---

inc/thorvg.h

@Issue: https://github.com/thorvg/thorvg/issues/1372

doc: ++Colorspace description

---

src/lib/tvgBinaryDesc.h
src/loaders/tvg/tvgTvgBinInterpreter.cpp
src/savers/tvg/tvgTvgSaver.cpp

The issue was introduced by b214fd23bc4df3a42d41d31ab1c49d6c65151fb4

tvg: recover the broken compatibility.

---

src/lib/tvgBinaryDesc.h
src/loaders/tvg/tvgTvgBinInterpreter.cpp
src/savers/tvg/tvgTvgSaver.cpp

implement the miterlimit property that was introduced by 44a750ee5db79008388ae18c853e54365130cdba
Issue: https://github.com/thorvg/thorvg/issues/1490

tvg: support stroke miterlimit property.

---

src/lib/gl_engine/tvgGlRenderer.cpp
src/lib/gl_engine/tvgGlRenderer.h
src/lib/sw_engine/tvgSwCommon.h
src/lib/sw_engine/tvgSwFill.cpp
src/lib/sw_engine/tvgSwRaster.cpp
src/lib/sw_engine/tvgSwRasterTexmap.h
src/lib/sw_engine/tvgSwRenderer.cpp
src/lib/sw_engine/tvgSwRenderer.h
src/lib/sw_engine/tvgSwShape.cpp
src/lib/tvgCanvasImpl.h
src/lib/tvgPaint.cpp
src/lib/tvgPaint.h
src/lib/tvgPictureImpl.h
src/lib/tvgRender.h
src/lib/tvgSceneImpl.h
src/lib/tvgShapeImpl.h

Standardized the opacity data type to use 1 byte
across all instances to maintain consistency and reduce scattered usage.

common engines: optimizing data packing for compactness.

---

src/lib/tvgArray.h
src/savers/tvg/tvgTvgSaver.cpp

add last() which indicates the last element pointer.

common array: ++enhance the usability.

---

src/lib/tvgArray.h
src/savers/tvg/tvgTvgSaver.cpp

Implement a pair of access methods: last() and first().

common array: revise the interface.

---

src/lib/sw_engine/tvgSwRasterAvx.h

Hi 
this patch is a fix #1513.
Thank You
Vincenzo

Avx raster refactoring due to an internal change to support blending methods

---

.gitattributes
.gitignore

Issue: https://github.com/thorvg/thorvg/issues/1519

infra: updated git setting.

---

src/lib/tvgBezier.cpp
src/lib/tvgBezier.h

A utility for common use of the Bezier curve.

common bezier: Add a function that returns the position.

---

src/lib/tvgBezier.cpp

revert issued code from def6393d82102e1a95d2890c0373f5ee0937ca54.

common bezier: fix a regression bug.

---

src/lib/sw_engine/tvgSwRaster.cpp

Warning: comparison of integer expressions of different signedness
@Issue: https://github.com/thorvg/thorvg/issues/1526

sw_engine: fix compiler warning

---

src/lib/tvgLoadModule.h
src/lib/tvgPictureImpl.h
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieBuilder.h
src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/lottie/tvgLottieLoader.h
src/loaders/lottie/tvgLottieModel.h

this breaks 0 frame lottie rendering, now it's fixed.

loader lottie: ++enhancements

---

src/examples/Blending.cpp
src/lib/sw_engine/tvgSwRasterC.h
src/lib/sw_engine/tvgSwRasterTexmap.h
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieProperty.h

Preparing 0.10 release, checked the sanitizer reports.

fix memory violations

---

CONTRIBUTING.md

https://github.com/thorvg/thorvg/issues/1554

common: Update image path(CONTRIBUTING.md)

---

src/examples/Stress.cpp

use canvas::paints() instead of a local list.

example stress: revise the sample.

---

src/utils/tvgLzw.cpp

utils: code clean up

---

src/utils/tvgArray.h

This PR does the following things:
* Add a new method in tvg::Array to support sort with custom comparer
The tessellation code in #1531 use tvg::Array as much as possible, and the algorithm need to sort Point , Edge.
So I add the sort method in tvg::Array. This is a new method so there will be no impact on existing code.

utils: add sort method in tvgArray

---

src/loaders/svg/tvgSvgSceneBuilder.cpp

Added support for the objectBoundingBox value of
the clipPathUnits and for the userSpaceOnUse value
of the maskContentUnits.
@issue: https://github.com/thorvg/thorvg/issues/429

svg_loader: support other units for mask and clip 

---

src/lib/sw_engine/tvgSwCommon.h
src/lib/sw_engine/tvgSwShape.cpp

The latest offset feature has a missing starting point of the cubic bezier. This fix addresses the issue.

sw_engine: fix dash offset bug.

---

src/common/tvgArray.h
src/loaders/lottie/tvgLottieProperty.h
src/loaders/svg/tvgSvgCssStyle.cpp
src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgPath.cpp
src/loaders/svg/tvgSvgSceneBuilder.cpp
src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/sw_engine/tvgSwImage.cpp
src/renderer/sw_engine/tvgSwRle.cpp
src/renderer/sw_engine/tvgSwShape.cpp
src/renderer/sw_engine/tvgSwStroke.cpp

easy access to a specific data with a operator.

common/array: enhance the interface

---

src/renderer/sw_engine/tvgSwRenderer.cpp

Previously, a mechanism was introduced to skip antialiasing computations when shapes are invisible due to their stroking. However, this mechanism failed to account for the scale factor of the stroke; it only considered the current stroke width as a threshold.
Consequently, when the stroke width is scaled up to a value smaller than the threshold, the incorrect antialiasing approach is applied. This results in the appearance of jagged edges.
The implemented fix rectifies this problem and ensures that the antialiasing computation correctly takes into consideration both the visibility and the scale factor of the stroke width.

sw_engine: fixed a antialiasing issue.

---

src/bindings/wasm/tvgWasm.cpp

Do not try to update/render if nothing has been changed.

bindings/wasm: optimize the performance.

---

inc/thorvg.h

- Result Shape::strokeMiterlimit(float miterlimit)
- float Shape::strokeMiterlimit() const

apis: promote beta apis to official status

---

src/renderer/tvgTaskScheduler.cpp

This reverts commit 77de62068ccfc2e1480888c1173258c5c71d7750.
@Issue: https://github.com/thorvg/thorvg/issues/1623

Revert "renderer taskscheduler: code refactoring."

---

src/renderer/sw_engine/tvgSwRenderer.cpp

corrected a mistake caused by a dead brain.

sw_engine: fix a wrong compuation.

---

src/renderer/sw_engine/tvgSwCommon.h

Fixes #1661
I have not tested it, only converted the Godot patch to ThorVG main.

sw_engine: fix VS 2017 issues with Godot's NOMINMAX

---

src/renderer/sw_engine/tvgSwFill.cpp

This might be a workaround to correct the issue.
The threshold value comes from the mathematical inaccuracy.
@Issue:https://github.com/thorvg/thorvg/issues/1555

sw_engine fill: fixed radial fill focal issue.

---

src/loaders/lottie/tvgLottieModel.h

The omitted data must be generated with interpolation.
This change supplements that logic.

lottie/model: revise the colorstop poplulation logic.

---

src/loaders/tvg/tvgTvgBinInterpreter.cpp
src/renderer/tvgBinaryDesc.h
src/savers/tvg/tvgTvgSaver.cpp

properly support dash offset / radial gradient focal properites

update tvg binary support

---

src/renderer/sw_engine/tvgSwStroke.cpp

reverted changes that occurred this issue from d683d2e
Issue: https://github.com/thorvg/thorvg/issues/1670

sw_engine: fix a regression stroke bug

---

.github/workflows/build_ios.yml
.github/workflows/build_macos.yml
.github/workflows/build_ubuntu.yml
.github/workflows/build_windows.yml
ios_arm64_cross.txt
ios_x86_64_cross.txt

meson setup builddir --cross-file ./ios_cross.txt ...
ref: https://thiblahute.github.io/jpakkane.github.io/Cross-compilation.html

infra: added ios cross compile script.

---

src/renderer/gl_engine/tvgGlCommon.h
src/renderer/gl_engine/tvgGlGeometry.cpp
src/renderer/gl_engine/tvgGlGeometry.h
src/renderer/gl_engine/tvgGlProgram.cpp
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/gl_engine/tvgGlShaderSrc.cpp
src/renderer/gl_engine/tvgGlShaderSrc.h

* this PR implement the function `GlRenderer::renderImage`.
----
| normal | with RenderMesh |
| ----------| ------------------------|
|<img src="https://github.com/thorvg/thorvg/assets/26308154/b56a35a6-dcea-4861-810c-29f6b882c40a"  width="300"/> |<img src="https://github.com/thorvg/thorvg/assets/26308154/e3121ae3-54f3-4bfa-8475-d6797ddb91e2" width="300" /> |

gl_engine: support render image

---

src/loaders/lottie/tvgLottieBuilder.cpp

Revised the rendering logic of Lottie by creating a new rendering context using a queue when multiple strokes are requested.
Issue: https://github.com/thorvg/thorvg/issues/1642

Lottie: Fixed handling of multiple strokes in one layer.

---

.github/workflows/build_android.yml
.github/workflows/build_ios.yml
cross/android_aarch64.txt
cross/android_x86_64.txt
src/meson.build

* Android has no separated libpthread, it is included in libc

infra: add android CI build test with necessary cross build config.

---

src/loaders/lottie/tvgLottieBuilder.cpp

currently thorvg doesn't support full 3d transformation. orthogonal projection is mandatory.
Issue: https://github.com/thorvg/thorvg/issues/1698

lottie/builder: fix a regression bug.

---

README.md

**Summary:**
Enhanced the responsiveness of images in README files to ensure optimal display across various device sizes and orientations.
**Key Changes:**
Adjusted image styles for better aspect ratio maintenance and quality.
Verified compatibility and quality across multiple device types and sizes.
**Impact:**
Ensures a consistent and user-friendly visual experience in documentation across all devices.

Improve README Image Responsiveness

---

inc/thorvg.h
src/bindings/wasm/tvgWasm.cpp
src/examples/Animation.cpp
src/examples/Lottie.cpp
src/loaders/lottie/tvgLottieBuilder.cpp

Allow users to omit the default type casting for added convenience.

api: enhance the API usage.

---

src/renderer/wg_engine/meson.build
src/renderer/wg_engine/tvgWgPipelineLinear.cpp
src/renderer/wg_engine/tvgWgPipelineLinear.h
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp

[issues 1479: LinearGradient](thorvg#1479)
In order to build you need third party libraries. Before you start please read this: [LearnWebGPU](https://eliemichel.github.io/LearnWebGPU/getting-started/hello-webgpu.html)
Usage example:
// init glfw
glfwInit();
// create a windowed mode window and its opengl context
glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);
GLFWwindow* window = glfwCreateWindow(800, 800, "WebGPU base app", nullptr, nullptr);
// get window size
int width{}, height{};
glfwGetWindowSize(window, &width, &height);
// init engine webgpu
tvg::Initializer::init(tvg::CanvasEngine::Wg, 0);
// create wg canvas
auto canvasWg = tvg::WgCanvas::gen();
canvas_wg->target(glfwGetWin32Window(window), width, height);
// gradient color stops
colorStops[0] = …

wg_engine: Added ability to draw multiple linear gradient filled shapes

---

src/renderer/gl_engine/tvgGlRenderPass.cpp
src/renderer/gl_engine/tvgGlRenderPass.h
src/renderer/gl_engine/tvgGlRenderTask.cpp
src/renderer/gl_engine/tvgGlRenderTask.h
src/renderer/gl_engine/tvgGlRenderer.cpp

This PR changes all GlRenderTask from unique_ptr to raw-pointer

gl_engine: use raw pointer to pass and hold GlRenderTask

---

src/renderer/wg_engine/meson.build
src/renderer/wg_engine/tvgWgPipelineRadial.cpp
src/renderer/wg_engine/tvgWgPipelineRadial.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp

[issues 1479: RadialGradient](thorvg#1479)
In order to build you need third party libraries. Before you start please read this: [LearnWebGPU](https://eliemichel.github.io/LearnWebGPU/getting-started/hello-webgpu.html)
Usage example:
// init glfw
glfwInit();
// create a windowed mode window and its opengl context
glfwWindowHint(GLFW_CLIENT_API, GLFW_NO_API);
GLFWwindow* window = glfwCreateWindow(800, 800, "WebGPU base app", nullptr, nullptr);
// get window size
int width{}, height{};
glfwGetWindowSize(window, &width, &height);
// init engine webgpu
tvg::Initializer::init(tvg::CanvasEngine::Wg, 0);
// create wg canvas
auto canvasWg = tvg::WgCanvas::gen();
canvas_wg->target(glfwGetWin32Window(window), width, height);
// gradient color stops
colorStops[0] = …

wg_engine: Added ability to draw multiple radial gradient filled shapes

---

inc/thorvg.h
meson.build
meson_options.txt
src/examples/GifSaver.cpp
src/examples/meson.build
src/renderer/tvgCommon.h
src/renderer/tvgSaver.cpp
src/savers/gif/gif.h
src/savers/gif/meson.build
src/savers/gif/tvgGifSaver.cpp
src/savers/gif/tvgGifSaver.h
src/savers/meson.build
src/savers/tvg/tvgTvgSaver.cpp
src/savers/tvg/tvgTvgSaver.h

Add save() API that takes tvg::Animation as a parameter. This API uses gif.h to create each animation frame as a gif frame. Gif creation do not support threads because they must be added sequentially. Please see example/GifSaver.cpp
ex)
auto animation = tvg::Animation::gen();
auto picture = animation->picture();
picture->load(EXAMPLE_DIR"/walker.json");
auto saver = tvg::Saver::gen();
saver->save(std::move(animation), EXAMPLE_DIR"/test.gif"); saver->sync();
New API:
Result Saver::save(std::unique_ptr<Animation> animation, const std::string& path, uint32_t quality = 100, uint32_t fps = 0);
Issue: https://github.com/thorvg/thorvg/issues/1712

saver GifSaver: Introduce GifSaver for animation

---

meson.build
meson_options.txt
src/tools/lottie2gif/lottie2gif.cpp
src/tools/lottie2gif/meson.build
src/tools/meson.build

Usage:
lottie2gif [Lottie file] or [Lottie folder] [-r resolution] [-f fps]
Examples:
$ lottie2gif input.json
$ lottie2gif input.json -f 30
$ lottie2gif input.json -r 600x600 -f 30
$ lottie2gif lottiefolder
$ lottie2gif lottiefolder -r 600x600
$ lottie2gif lottiefolder -r 600x600 -f 30

tools/lottie2gif: introduce a new converter tool.

---

src/renderer/wg_engine/meson.build
src/renderer/wg_engine/tvgWgGeometry.cpp
src/renderer/wg_engine/tvgWgGeometry.h
src/renderer/wg_engine/tvgWgPipelineLinear.cpp
src/renderer/wg_engine/tvgWgPipelineRadial.cpp
src/renderer/wg_engine/tvgWgPipelineSolid.cpp
src/renderer/wg_engine/tvgWgPipelineStroke.cpp
src/renderer/wg_engine/tvgWgPipelineStroke.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp

Added ability to draw solid strokes
[issues 1479: Stroke, StrokeLine](https://github.com/thorvg/thorvg/issues/1479)
In order to build you need third party libraries. Before you start please read this: [LearnWebGPU](https://eliemichel.github.io/LearnWebGPU/getting-started/hello-webgpu.html)
Usage example:
//Test for Stroke Dash for Arc, Circle, Rect
shape->appendArc(70, 600, 160, 10, 30, true);
shape->appendCircle(70, 700, 20, 60);
shape->appendRect(130, 710, 100, 40);
shape->strokeFill(255, 0, 0);
shape->strokeWidth(5);
shape->strokeJoin(tvg::StrokeJoin::Round);
shape->strokeCap(tvg::StrokeCap::Round);
if (canvas->push(std::move(shape)) != tvg::Result::Success) return;

wg_engine: Added ability to draw solid strokes with dashes

---

src/bindings/capi/thorvg_capi.h

capi: udpated the doc.

---

src/loaders/raw/tvgRawLoader.h
src/renderer/tvgLoadModule.h

Move the raw image loading interface to the RawImageLoader. it is only valid for this component.

renderer/loader: code refactoring

---

src/loaders/lottie/tvgLottieParser.cpp

thorvg blending is quite buggy,
the feature needs a verification.

lottie/parser: ++ blending options

---

README.md
inc/thorvg.h
src/bindings/wasm/tvgWasm.cpp
src/examples/GifSaver.cpp
src/renderer/tvgSaveModule.h
src/renderer/tvgSaver.cpp
src/savers/gif/tvgGifSaver.cpp
src/savers/gif/tvgGifSaver.h
src/savers/tvg/tvgTvgSaver.cpp
src/savers/tvg/tvgTvgSaver.h
src/tools/lottie2gif/lottie2gif.cpp

https://github.com/thorvg/thorvg/issues/1769

Support Saver a background setting.

---

src/examples/ImageScaleDown.cpp
src/examples/ImageScaleUp.cpp
src/examples/Performance.cpp
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/tvgCanvas.h
test/capi/capiSwCanvas.cpp
test/testSwCanvasBase.cpp

Clear the buffer when canvas->clear() is called.
TODO: We need to add a color value parameter to clear it.

sw_engine: Clear buffer at the proper time.

---

src/renderer/gl_engine/tvgGlRenderer.cpp

update by 66305f3e6d0001ffca70e4337275900cdda8e5bb

gl_engine/renderer: skip sync if nothing should be done.

---

src/savers/gif/gif.h
src/savers/gif/tvgGifSaver.cpp
src/tools/lottie2gif/lottie2gif.cpp

support transparent gif

---

src/renderer/wg_engine/tvgWgPipelineImage.cpp
src/renderer/wg_engine/tvgWgPipelineImage.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgShaderSrc.cpp

[Issues 1479: pictures](https://github.com/thorvg/thorvg/issues/1479)
Formats supported:
ABGR8888
ARGB8888
ABGR8888S
ARGB8888S

webgpu: add support for textures color space formats

---

src/loaders/external_jpg/tvgJpgLoader.cpp
src/loaders/external_jpg/tvgJpgLoader.h
src/loaders/external_png/tvgPngLoader.cpp
src/loaders/external_png/tvgPngLoader.h
src/loaders/external_webp/tvgWebpLoader.cpp
src/loaders/external_webp/tvgWebpLoader.h
src/loaders/jpg/tvgJpgLoader.cpp
src/loaders/jpg/tvgJpgLoader.h
src/loaders/png/tvgPngLoader.cpp
src/loaders/png/tvgPngLoader.h
src/renderer/tvgCanvas.h
src/renderer/tvgPicture.cpp
src/renderer/tvgPicture.h
src/renderer/tvgScene.h
src/renderer/tvgShape.h

renderer: code refactoring.

---

src/loaders/jpg/tvgJpgd.cpp

loader/jpg: Fix warning

---

src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/lottie/tvgLottieLoader.h
src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoader.h
src/loaders/svg/tvgSvgSceneBuilder.cpp
src/loaders/svg/tvgSvgSceneBuilder.h
src/loaders/tvg/tvgTvgBinInterpreter.cpp
src/loaders/tvg/tvgTvgCommon.h
src/loaders/tvg/tvgTvgLoader.cpp
src/loaders/tvg/tvgTvgLoader.h
src/renderer/tvgLoadModule.h
src/renderer/tvgPicture.cpp

removed the internal unique_ptr usage to reduce the binary size(-553)

renderer/loader: optimization++

---

src/renderer/tvgTaskScheduler.cpp
src/renderer/tvgTaskScheduler.h

replace the stl with own lightweight data structures.

renderer/scheduler: --binary size by 2.2kb

---

src/common/tvgArray.h
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/tvgScene.h
src/savers/tvg/tvgTvgSaver.cpp

Use a default constructor with reservation.

common/array: code refactoring.

---

src/renderer/tvgPicture.cpp

reverted a wrong change from the previous code refactoring in 56433484726f7c1f165c35b27ac1625113234bc0

renderer/picture: fixed a regression

---

inc/thorvg.h

- applied ```@retval``` for those const values.
- applied ```@return``` for return value description.

doc: polish up the doxygen.

---

src/renderer/tvgPicture.h
src/renderer/tvgScene.h
src/renderer/tvgShape.h

renderer: minor optimization.

---

src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

New approach provide:
- webgpu instance, adaptor, device and default queue
- device capabilitieas info
- command buffer executor
- error handling

wg_engine: refactor context handles

---

src/renderer/sw_engine/tvgSwFill.cpp
src/renderer/sw_engine/tvgSwRaster.cpp

The condition is not valid,
Let it draw the fill as it's requested.
Issue: https://github.com/thorvg/thorvg/issues/1834

sw_engine/fill: fix a linear filling scaling issue.

---

inc/thorvg.h

New API:
- SwCanvas::Colorspace::ABGR8888S
- SwCanvas::ColorSpace::ARGB8888S

api: promote to official APIs.

---

src/loaders/lottie/tvgLottieLoader.cpp

Issue: https://github.com/thorvg/thorvg/issues/1874

lottie: resolve a thread sanitizer report.

---

src/loaders/svg/tvgSvgLoader.cpp

observed a memory leak at a corner case.

svg: ensure that all allocated memory.

---

src/examples/AnimateMasking.cpp
src/examples/Animation.cpp
src/examples/CustomTransform.cpp
src/examples/DirectUpdate.cpp
src/examples/ImageScaleDown.cpp
src/examples/ImageScaleUp.cpp
src/examples/Performance.cpp
src/examples/Retaining.cpp
src/examples/SceneTransform.cpp
src/examples/Transform.cpp
src/examples/Update.cpp

Guarantee the resource free at the termination.

examples: ++safety.

---

src/bindings/wasm/tvgWasmLottieAnimation.cpp
web/example/index.html
web/src/lottie-player.ts

Feature update for ThorVG Viewer's requirements.
- new loading feature - tvg, svg, jpg, png
- new exporting feature - tvg
Issue: #1871

web: importing/exporting feature update

---

src/bindings/wasm/tvgWasmLottieAnimation.cpp
web/example/index.html
web/src/lottie-player.ts

Updated features & props as ThorVG Viewer requirements
Added:
- `size` - `TVG.size()` wrapper
- `resize()` - method for dynamic resizing
- Support `save('png')`
Fixed:
- animation loading bug when <lottie-player> doesn't have `src` prop
- animation stop behavior -> cursor 0 frame when stopped

web: extra features & minor bug fixes

---

src/loaders/ttf/tvgTtfLoader.cpp

Ensured the data count is correctly multiplied by the data size.

ttf: Fixed an invalid unicode encoding.

---

src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/svg/tvgSvgLoader.cpp
src/loaders/tvg/tvgTvgLoader.cpp
src/loaders/tvg/tvgTvgLoader.h

Ensure scene data is freed when it's dangled in the loader.

loader: code refactoring

---

src/renderer/wg_engine/tvgWgBindGroups.cpp
src/renderer/wg_engine/tvgWgBindGroups.h
src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgGeometry.cpp
src/renderer/wg_engine/tvgWgGeometry.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h

[issues 1479: Masking](#1479)
Supported composition methods:
AlphaMask
InvAlphaMask
LumaMask
InvLumaMask
AddMask
SubtractMask
IntersectMask
DifferenceMask
Usage example:
//Solid Rectangle
shape->appendRect(0, 0, 400, 400);
shape->fill(0, 0, 255);
//Mask
mask->appendCircle(200, 200, 125, 125);
mask->fill(255, 255, 255);        //AlphaMask RGB channels are unused.
//Nested Mask
auto nMask = tvg::Shape::gen();
nMask->appendCircle(220, 220, 125, 125);
nMask->fill(255, 255, 255);       //AlphaMask RGB channels are unused.
mask->composite(std::move(nMask), tvg::CompositeMethod::AlphaMask);
shape->composite(std::move(mask), tvg::CompositeMethod::AlphaMask);
canvas->push(std::move(shape));
//Star
auto star = tvg::Shape::gen(); …

wg_engine: introduced composition ability

---

src/examples/Animation.cpp
src/examples/DirectUpdate.cpp
src/examples/Lottie.cpp
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieParser.h

lottie: enhance the feature support

---

src/examples/GifSaver.cpp

60fps takes a bit long time for our daily testing. Removed it for the speed.

examples/gif: revise the sample.

---

src/renderer/wg_engine/tvgWgBindGroups.cpp
src/renderer/wg_engine/tvgWgBindGroups.h
src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h

[issues 1479: blending](#1479)
Supported blend settings:
Normal
Add
Screen
Multiply
Overlay
Difference
Exclusion
SrcOver
Darken
Lighten
ColorDodge
ColorBurn
HardLight
SoftLight

wg_engine: introduced blending

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h

remove an unnecessary scene in the lottie render tree.

lottie: minor optimization.

---

src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/sw_engine/tvgSwRenderer.h
src/renderer/tvgCanvas.h
src/renderer/tvgPaint.cpp
src/renderer/tvgPaint.h
src/renderer/tvgPicture.cpp
src/renderer/tvgPicture.h
src/renderer/tvgRender.h
src/renderer/tvgScene.h
src/renderer/tvgShape.h
src/renderer/tvgText.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

Revise the logics to enhance the reliability.

paints retaining policy enhancement

---

src/loaders/lottie/tvgLottieProperty.h

lottie/parser: shutdown a compiler warning.

---

src/examples/PictureSvg.cpp
src/examples/meson.build

This is the simplest example using tvg::Picture's SVG loader.

examples/picture/svg: Add PictureSvg example

---

src/renderer/tvgCanvas.h

just figured out & fixed a side effect by this change: 9e690895242eb71a60ecafecff99b4defcc903d0

renderer/canvas: fix a regression error.

---

src/common/tvgLock.h

See the comment in  https://github.com/godotengine/godot/pull/88053#pullrequestreview-1867558507

Portability: Fix compiler shadowing warning

---

web/src/lottie-player.ts

Cleaned up code for improved consistency
**Issue**: #1882

web: code refactoring

---

src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgRenderData.cpp

[issues 1479: update](#1479)
gpu shapes vertex buffer reallocations optimization

wg_engine: animation optimizations (part 1)

---

src/loaders/webp/webp/types.h

this reduces the bin size around -1.5kb

loader/webp: do not expose webp apis.

---

src/common/tvgArray.h
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieProperty.h
src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgSceneBuilder.cpp
src/renderer/sw_engine/tvgSwMath.cpp
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/sw_engine/tvgSwRle.cpp
src/renderer/sw_engine/tvgSwStroke.cpp
src/renderer/tvgShape.h
src/renderer/tvgTaskScheduler.cpp

Make the array interface pair begin()/end() for consistency.

common/array: code refactoring

---

src/loaders/lottie/tvgLottieParser.cpp

Since the parser has become stable enough,
remove the exceptions and instead rely on parser error handling.

lottie/parser: clean up the exception handling mechanisms.

---

src/examples/PictureSvg.cpp

Adjust the image size and position to fit the window size.

examples/picture/svg: Adjust size ratio

---

src/common/tvgBezier.cpp
src/common/tvgBezier.h
src/loaders/lottie/tvgLottieProperty.h
src/renderer/sw_engine/tvgSwShape.cpp

Again, noticed this drops the performance appx. 10% 
Let's revisit this again.

Revert "sw_engine: Increasing accuracy for dashed curves"

---

src/loaders/lottie/tvgLottieBuilder.cpp

The lottie format defines the starting point for
drawing rectangles and ellipses differently than
the API available in the TVG. In the case of using dashes or trim paths, this leads to discrepancies. Therefore, when using the lottie builder, internal functions for appending rectangles and circles are utilized.
@issue: https://github.com/thorvg/thorvg/issues/1997

lottie: use internal append rect/ellipse func

---

src/renderer/tvgSaver.cpp

do not delete the given picture if the reference counting is more than 0.

saver: ++robustness

---

src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieParser.h

error: storing the address of local variable 'context' in '*this.LottieParser::context' [-Werror=dangling-pointer=]
1255 |     this->context = &context;
issue: https://github.com/thorvg/thorvg/issues/2051

lottie: fixed a compiler warning:

---

src/loaders/lottie/tvgLottieInterpolator.cpp

Fixed naming conflict in short names.
issue: #2062

lottie: Renamed function names with prefix

---

src/loaders/ttf/tvgTtfLoader.cpp

Enhances the portability of the TTF loader on UWP platforms by implementing an alternative file loading mechanism.
This is designed to support environments where the file mapping feature is not available, ensuring wider compatibility and reliability in file handling.
Issue: https://github.com/thorvg/thorvg/issues/1912

ttf: enhance UWP portability with alternative file loading

---

src/bindings/capi/thorvg_capi.h
src/loaders/lottie/thorvg_lottie.h
src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/lottie/tvgLottieLoader.h
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieParser.h
src/loaders/lottie/tvgLottieProperty.h
test/capi/capiLottie.cpp
test/testLottie.cpp

lottie: slot enhancement

---

src/loaders/lottie/tvgLottieModel.cpp
src/loaders/svg/tvgSvgLoader.cpp
src/renderer/sw_engine/tvgSwShape.cpp

[common] code clean up

---

src/renderer/wg_engine/tvgWgGeometry.cpp
src/renderer/wg_engine/tvgWgGeometry.h

[issues 1479: strokes](#1479)
Introduced stroke trim setting
left: (0.0, 0.95)
middle: (0.15, 1.0)
right: (0.15, 0.95)

wg_engine: stroke trim

---

src/loaders/lottie/tvgLottieModel.h

Slot overriding tries to set property via the `LottieObject`. It potentially causes unexpected changes.
Revised the `override` function. The purpose of this patch is to aim atomic property to be overriden.

lottie/slot: Fixed potential overriding bug

---

src/renderer/tvgPaint.cpp

Fixed a crash that occurred when a given clipper had no data. Properly handle this exceptional case to prevent the crash.
issue: https://github.com/thorvg/thorvg/issues/2083

renderer: Fix a crash issue related to the clipper

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h

These APIs have been thoroughly tested and verified.
New API:
- Result Animation::frame(float no)
- Picture* Animation::picture() const
- float Animation::curFrame() const
- float Animation::totalFrame() const
- float Animation::duration() const
- static Animation::std::unique_ptr<Animation> gen()
New CAPI:
- Tvg_Animation* tvg_animation_new()
- Tvg_Result tvg_animation_set_frame(Tvg_Animation* animation, float no)
- Tvg_Paint* tvg_animation_get_picture(Tvg_Animation* animation)
- Tvg_Result tvg_animation_get_frame(Tvg_Animation* animation, float* no)
- Tvg_Result tvg_animation_get_total_frame(Tvg_Animation* animation, float* cnt)
- Tvg_Result tvg_animation_get_duration(Tvg_Animation* animation, float* duration)
- Tvg_Result tvg_animation_del(Tvg_Animation* animation)
issue: …

api: Promote experimental Animation APIs to official status.

---

src/renderer/sw_engine/tvgSwShape.cpp

there has been a logical error that breaks the contour composition context. This fixes it.
issue: https://github.com/thorvg/thorvg/issues/2093

sw_engine: stabilize the contour composition logic.

---

src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgGeometry.cpp
src/renderer/wg_engine/tvgWgGeometry.h
src/renderer/wg_engine/tvgWgRenderData.cpp

[issues 1479](#1479)
- added ability to update buffers via memory mapping
- refactored winding fill rule computations

wg_engine: render buffers usage refactorings

---

src/loaders/svg/tvgSvgLoader.cpp

Inherit gradientUnits and recalculate each element
radial(cx, cy, r,...), linear(x1, y1, x2, y2).
related issue: https://github.com/thorvg/thorvg/issues/1255

loader/svg: Do recalc after gradient inheritance

---

src/loaders/svg/tvgSvgLoader.cpp

When finding the 'nodeFrom' referenced by `<use>`,
if it is the parent, it is not referenced.
https://www.w3.org/TR/SVG2/struct.html#UseElement
Specification:
If the referenced element is a (shadow-including) ancestor of the ‘use’ element,
then this is an invalid circular reference and the ‘use’ element is in error.
related issue: https://github.com/thorvg/thorvg/issues/2078 SVG_FILE_65171.svg
SVG_FILE_65172.svg

loader/svg: Check whether href id of use is parent or not

---

src/loaders/lottie/tvgLottieBuilder.cpp

The settings were incorrect;
'direction' and 'fillRule' do not have a relationship.

lottie: Removed redundant code.

---

README.md

https://github.com/thorvg/thorvg/issues/2081

README.MD: add instructions to install and update thorVG with MSYS2

---

src/renderer/sw_engine/tvgSwShape.cpp

fixed one more corner case problem, just observed. it's a side effect by 925009c4a526f0e9578e1213b752e4f270466928

sw_engine: hotfix a regression bug of line drawing.

---

src/loaders/svg/tvgSvgLoader.cpp

Support parsing of hsl(hue, saturation, brightness) color type and conversion to rgb color.

loader/svg: Support hsl color format

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h
src/renderer/sw_engine/tvgSwShape.cpp
src/renderer/tvgRender.h
src/renderer/tvgShape.h

issue: https://github.com/thorvg/thorvg/issues/2047

sw_engine: revised the trimpath dash line logic

---

src/loaders/svg/tvgSvgLoader.cpp

Checks whether the string that can be specified in Color is valid.
example)
```
style="stroke:asdasd"
```
related issue: https://github.com/thorvg/thorvg/issues/1255

loader/svg: Check invalid color

---

src/loaders/lottie/tvgLottieModel.h

revise the fix that occured a side effect by:
287e6d33d2c2fbd913c75cb0bc257a977c910b99

lottie: hotfix memory corruption.

---

src/loaders/lottie/tvgLottieLoader.cpp
src/renderer/tvgLoader.cpp

Currently, thorvg has no plan to support dotlottie format.

lottie: removed unused code.

---

.github/workflows/build_android.yml
cross/android_aarch64.txt
cross/android_x86_64.txt

Following the Android developer guide (https://developer.android.com/ndk/guides/other_build_systems), added HOST_TAG to the directory.

Modify txt file for cross-platform build setup

---

src/loaders/svg/tvgSvgLoader.cpp

svg: code refactoring

---

src/loaders/lottie/tvgLottieAnimation.cpp
src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/lottie/tvgLottieLoader.h
src/renderer/tvgFrameModule.h

lottie: code refactoring.

---

src/loaders/svg/tvgSvgUtil.cpp

related issue: https://github.com/thorvg/thorvg/issues/2156

loader/svg: Return actual decoded size

---

src/loaders/lottie/tvgLottieBuilder.cpp

When the Lottie Text Justify sets to center, text alignment should also be center.
[74_Text_Fonts.json](https://github.com/thorvg/thorvg/files/15090114/74_Text_Fonts.json)
**[Before]**
**[After]**

lottie: correct the multiline text alignment

---

README.md

Hi there,
Conan just added the Thorvg package. This PR adds some simple steps to install it.
Thanks in advance!

docs: Add Conan Installation steps

---

src/renderer/wg_engine/tvgWgBindGroups.cpp
src/renderer/wg_engine/tvgWgBindGroups.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h

[issues 1479: Masking, InvMasking, LumaMasking, InvLumaMasking](#1479)
Computes composition and blending using simgle pass istead of two full screen passes

wg_engine: blending and composition optimization

---

src/renderer/gl_engine/tvgGlRenderTask.cpp

Fix the stencil reference and compare function cause rendering not correct

gl_engine: fix stencil logical not correct

---

src/renderer/sw_engine/tvgSwRasterNeon.h

Improved the speed through neon processing

sw_engine : arm neonRasterGrayscale8 function to support aarch64

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h
src/loaders/svg/tvgSvgSceneBuilder.cpp

Unnecessary structure removed, typos corrected,
comment added, an unused function argument removed.

svg_loader: improved clarity, no logical changes

---

src/renderer/sw_engine/tvgSwRasterNeon.h

Improved the speed through neon processing.
Improvements Rate:
Lottie: (0.026321/0.026779) = +1.8%
Performance: (0.015411/0.015732) = +2.1%
issue: https://github.com/thorvg/thorvg/issues/30
[Lottie_aarch32.txt](https://github.com/thorvg/thorvg/files/15231339/Lottie_aarch32.txt)
[Lottie_aarch64.txt](https://github.com/thorvg/thorvg/files/15231340/Lottie_aarch64.txt)
[Performance_aarch32.txt](https://github.com/thorvg/thorvg/files/15231341/Performance_aarch32.txt)
[Performance_aarch64.txt](https://github.com/thorvg/thorvg/files/15231342/Performance_aarch64.txt)

sw_engine/neon: arm neonRasterPixel32 function to support aarch64

---

src/meson.build

- applying strict build options
- aligning options between gcc/clang compilers.

infra: update the compiler options

---

src/common/tvgLines.cpp

It will sacrifice precision that is not noticeable and instead try to improve performance.
Approximately 5% has beeen improved at Lottie example

common: tweaking bezier computation for perf.

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/lottie/tvgLottieProperty.h
test/testAnimation.cpp

issue: https://github.com/thorvg/thorvg/issues/2266

lottie: regression fix & improve the frame calculation.

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieProperty.h

- Separate the rounded corner logic from the updateStar since its logic has become too lengthy and complicated.
- Revise the path generation to eliminate duplicates.

lottie: keep the code clean and neat.

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h

- remove an unused return value.
- move bodies from header to implementation file.
- no logical changes.

lottie: code clean up

---

src/common/tvgMath.cpp
src/common/tvgMath.h
src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwRasterTexmap.h
src/renderer/tvgCommon.h
src/renderer/tvgPaint.cpp

issue: https://github.com/thorvg/thorvg/issues/2332

renderer: clipping optimization

---

src/renderer/wg_engine/meson.build
src/renderer/wg_engine/tvgWgCommon.h

see this as well: https://github.com/gfx-rs/wgpu-native/releases
issue: https://github.com/thorvg/thorvg/issues/1991

wg_engine: ++infra

---

src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h
src/renderer/wg_engine/tvgWgRenderer.cpp

In a case of compostions model view matrix did not apply samples count. Fixed

webgpu: fix model view matrix

---

src/renderer/sw_engine/tvgSwRasterTexmap.h

set the anti-aliasing frame info properly, in an exceptional case.
issue: https://github.com/thorvg/thorvg/issues/2391

sw_engine: fix a crash issue.

---

src/renderer/tvgGlCanvas.cpp
src/renderer/tvgSwCanvas.cpp
src/renderer/tvgWgCanvas.cpp

renderer/canvas: clean up code

---

src/renderer/wg_engine/tvgWgShaderSrc.cpp

Fix AlphaMask, InvAlphaMask, LumaMask and InvLumaMask math
Fix double apllience of opacity value

wg_engine: fix composition math

---

examples/FillSpread.cpp
examples/meson.build

@issue: https://github.com/thorvg/thorvg/issues/2124

examples: add FillSpread example

---

README.md
src/renderer/gl_engine/tvgGlCommon.h

there is no more EGL dependency in gl engine.

infra: --egl dependncy

---

src/loaders/lottie/jerryscript/jerry-core/jrt/jrt.h

issue: https://github.com/thorvg/thorvg/issues/2347

lottie: fix a compile error on MSC with clang.

---

meson.build
meson_options.txt
src/renderer/meson.build

The ThorVG OpenGL/ES engine has been stabilized and improved significantly. Now, as a graphics engine, its drawing features are quite functional. It is time to officially release the engine and maintain it in the release process.
Thanks @RuiwenTang for going above and beyond!
issue: https://github.com/thorvg/thorvg/issues/2435

infra: promote the GL engine to an official one.

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieParser.cpp

MaskMode=None is not properly addressed,
Prevent the crash from the use-case.
issue: https://github.com/thorvg/thorvg/issues/2426

lottie: hotfix for preventing a crash.

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h

C++
- GlCanvas::gen()
CAPI
- TVG_COMPOSITE_METHOD_INVERSE_LUMA_MASK

apis: promotes to official apis.

---

src/renderer/sw_engine/tvgSwRenderer.cpp

Synchronize the engine process precisely
before updating internal data.

sw_engine: ++thread safety

---

src/renderer/sw_engine/tvgSwFill.cpp

For gradients with fill spread set as repeat,
the lack of anti-aliasing between the last and
the first color caused noticeable jagged edges.
Interpolation was introduced between them,
visually improving the gradient quality.
| before | after |
|--|--|
|<img width="300" alt="Zrzut ekranu 2024-06-19 o 01 50 50" src="https://github.com/thorvg/thorvg/assets/67589014/ca5f0d4a-f87e-405f-852a-4f7743485e47">|<img width="300" alt="Zrzut ekranu 2024-06-19 o 01 48 28" src="https://github.com/thorvg/thorvg/assets/67589014/a2071f91-9f75-45b5-b969-d81b49182fa3">|
|<img width="300" alt="Zrzut ekranu 2024-06-19 o 01 51 06" src="https://github.com/thorvg/thorvg/assets/67589014/fd3ccf83-c918-45d7-8af1-00e3a3f57352">|<img width="300" alt="Zrzut ekranu 2024-06-19 o 01 48 16" …

sw_engine: improve grad quality

---

src/loaders/lottie/rapidjson/rapidjson.h
src/loaders/lottie/tvgLottieParserHandler.cpp

- Save binary size about 0.8kb
- issue: https://github.com/thorvg/thorvg/issues/2389

lottie: enhancement++

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/renderer/tvgCanvas.h

issue: https://github.com/thorvg/thorvg/issues/2494

api: ++description

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp
src/renderer/sw_engine/tvgSwRaster.cpp

Append the mask shape to the previous one, instead of composition, when it's able by the condition.
issue: https://github.com/thorvg/thorvg/issues/2426, https://github.com/thorvg/thorvg/issues/2428

lottie enhancement

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieProperty.h
src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/wg_engine/tvgWgRenderData.cpp

issue: https://github.com/thorvg/thorvg/issues/2512

common: Fix a compilation failure on VS 2017

---

src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

- apply thorvg compact coding style.
- separate private / public methods designated in sectors.

wg_engine: code refactoring

---

src/loaders/svg/tvgSvgLoader.cpp

loader->stack.pop() at line 3271 is called to remove the defs node added to the stack due to nested graphics elements.
However, it is called in an inappropriate situation and the loader's node tree is damaged. 
Fixes an error where the close tag is recognized as a `line` of the graphics tag when it is `linearGradient`.
ex)
```
<defs id="def">
<linearGradient x1="1" y1="2" x2="3" y2="4" id="l"/>
<rect x="10" y="10" width="10" height="10"  fill="blue" id="r2"/>
</defs>
```
related issue: https://github.com/thorvg/thorvg/issues/2518

svg_loader: Fix incorrect stack.pop() call in loader

---

src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/lottie/tvgLottieLoader.h

comp pointer is used for checking if the header is ready. It can be written in a worker thread and needs a critical section on the reader side.
This also potentally improve the thread efficiency from the segment() / marker() function calls.

lottie: ++thread safety.

---

src/renderer/gl_engine/tvgGlShaderSrc.cpp

This PR improve the gradient rendering quality: issue #2521

gl_engine: fix aliasing in gradient rendering

---

src/loaders/lottie/tvgLottieProperty.h

Adding support for auto-orient=true for frames <= first and >= last, as well as for positions specified without outer and inner tangent.
NOTE: tested together with #2540 
file|before|after|
--|--|--|
5949.json (very first frame)|<img width="669" alt="Zrzut ekranu 2024-07-9 o 01 47 09" src="https://github.com/thorvg/thorvg/assets/67589014/822dfb1a-855a-436e-a5df-de3f29cade0a">|<img width="727" alt="Zrzut ekranu 2024-07-9 o 01 35 39" src="https://github.com/thorvg/thorvg/assets/67589014/b1d7e8e6-1743-46ff-beaa-45714693c5e0">|
12458.json part1|<img width="607" alt="Zrzut ekranu 2024-07-9 o 01 48 41" src="https://github.com/thorvg/thorvg/assets/67589014/ffc872a6-8178-4fa5-b0a2-35e16a754319">|<img width="650" alt="Zrzut ekranu 2024-07-9 o 01 31 40 1" …

lottie: enhance support for ao: 1

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieProperty.h

- _draw() returns boolean whether merging shape is allowed or not.
- renamed some internal variables.

lottie: code refactoring

---

src/common/tvgLock.h
src/renderer/tvgRender.cpp
src/renderer/tvgRender.h

skip locking if the thread number is 0.

renderer: ++optimization

---

src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h

See folowing examples:
- Masking 
- InvMasking
- LumaMasking
- InvLumaMasking
- MaskingMethods
- GradientMasking
- AnimateMasking
sw/webgpu

wg_engine: fix masking methods support

---

src/common/tvgLines.cpp
src/common/tvgMath.cpp
src/common/tvgMath.h
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieProperty.h
src/loaders/svg/tvgSvgPath.cpp
src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/sw_engine/tvgSwMath.cpp

the custom atan2 algorithm by Remez.
see: https://en.wikipedia.org/wiki/Remez_algorithm
This improved the Lottie example by ~2ms.
Total atan2 performance time was reduced by 43%

common/math: introduced custom atan2()

---

src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieProperty.h
src/loaders/svg/tvgSvgLoader.cpp
src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/sw_engine/tvgSwImage.cpp
src/renderer/sw_engine/tvgSwMath.cpp
src/renderer/sw_engine/tvgSwRaster.cpp

nearbyint() is 2x faster than round() in our local test.

common: replace the round() with nearbyint()

---

src/loaders/lottie/tvgLottieBuilder.cpp

[4807.json](https://github.com/user-attachments/files/16177344/4807.json)
before:
after:

lottie: apply direction to rect

---

src/renderer/sw_engine/tvgSwRaster.cpp

[gray.json](https://github.com/user-attachments/files/16185669/gray.json)
before:
after:

sw_engine: grayscale image support++

---

examples/Example.h

Added handling for engine initialization failure.

examples: ++exception handling

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h
src/renderer/tvgPaint.cpp
src/renderer/tvgPaint.h
src/renderer/tvgPicture.h
src/renderer/tvgRender.h
src/renderer/tvgScene.h
src/renderer/tvgShape.h
src/renderer/tvgText.h

Apply LottieRenderPooler to path/rect/ellipse/polystar.
This enhances the animation performance: ~10%

lottie: ++scene rendering optimization

---

src/loaders/lottie/tvgLottieAnimation.cpp

lottie: remove useless condition check.

---

src/renderer/wg_engine/tvgWgBindGroups.cpp
src/renderer/wg_engine/tvgWgBindGroups.h
src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h

[issues 2410: emscripten support](https://github.com/thorvg/thorvg/issues/2410)
- Research and prototype the Emscripten build with WebGPU.
meson setup script:
`meson setup builddir -Ddefault_library=static -Dloaders=all -Dsavers="all" -Dbindings="wasm_beta" -Dengines="wg_beta" --cross-file ./cross/wasm_webgpu.txt`
tesing javascript:
```JS
<!DOCTYPE html>
<html>
<head>
<title>Emscripten</title>
<script src="../builddir/src/bindings/wasm/thorvg-wasm.js"></script>
</head>
<body>
<div>WebGPU web player</div>
<canvas id="canvasWebgpu" width="800" height="600">Hello</canvas>
<script>
let animator = null;
let totalFrames = 0.0;
let duration = 0.0;
async function render(timestamp) {
await animator.frame((timestamp / (duration * 1000) % 1) * totalFrames);
await animator.update();
await …
```

wg_engine: emscripten and browser support

---

src/loaders/lottie/tvgLottieBuilder.cpp

introduced an intermediate scene for embracing
the matte and maskings

lottie: support matte+masking combination

---

src/loaders/lottie/tvgLottieBuilder.cpp

The implementation of rounded polygons was
mistakenly omitted, now has been added.
@Issue: https://github.com/thorvg/thorvg/issues/2624
sample:
[roundedPolygonTest.json](https://github.com/user-attachments/files/16564953/roundedPolygonTest.json)
before (two triangles overlap):
after:
AE:

lottie: handle rounded polygons

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h
src/renderer/tvgPaint.cpp
src/renderer/tvgPaint.h
src/renderer/tvgShape.h

lottie: render pool optimization++

---

inc/thorvg.h

addressed supported raw data format.
issue: https://github.com/thorvg/thorvg/issues/2648

doc: ++enhancement in Picture::load()

---

examples/Capi.cpp

Added loading animation from a memory.

examples: capi example ++

---

src/bindings/wasm/tvgWasmLottieAnimation.cpp

Original patch from #2656 by @hermet 
- Added engine validating condition in constructor (As we talked [here](https://github.com/thorvg/thorvg/pull/2656#discussion_r1724426628))
- Enhanced destructor logic by adding explicit engine termination
---
Introduced the abstract EngineMethod to handle
different engines more effectively using polymorphism.

wasm: code refactoring

---

src/bindings/wasm/tvgWasmLottieAnimation.cpp

Found typo that crashes WASM build.

wasm: fix typo

---

src/loaders/ttf/tvgTtfLoader.cpp
src/loaders/ttf/tvgTtfLoader.h
src/renderer/tvgLoadModule.h
src/renderer/tvgText.h

previously italic style had been ignored
even if the font style changes.
issue: https://github.com/thorvg/thorvg/issues/2676

renderer/text: fix a missing text update

---

src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieParser.h

Note that, only dealt with a obivous case in practice.
issue: https://github.com/thorvg/thorvg/issues/2703

lottie/parser: ++ null value handling

---

src/loaders/lottie/tvgLottieBuilder.cpp

Issue: #2178 
Added support for Text Based of Text Range Selector, by processing further properties:
2. Character Excluding Spaces
3. Words
4. Lines
see: https://lottiefiles.github.io/lottie-docs/constants/#text-based
---
1. **Chars**
[text-based-chars.json](https://github.com/user-attachments/files/16914284/text-based-chars.json) (Unit: Index, Start: 0, End 1)
2. CharsExcludingSpaces
[text-based-excluding-space.json](https://github.com/user-attachments/files/16914285/text-based-excluding-space.json) (Unit: Index, Start: 0, End 2)
3. Words
[text-based-word.json](https://github.com/user-attachments/files/16914286/text-based-word.json)  (Unit: Index, Start: 0, End 3)
4. Lines
[text-based-line.json](https://github.com/user-attachments/files/16914287/text-based-line.json) (Unit: Index, Start: …

lottie/text: Support Text Based (Part of Phase 2)

---

src/renderer/wg_engine/tvgWgBindGroups.cpp
src/renderer/wg_engine/tvgWgBindGroups.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp

[issues 2620: wrong gradient transformation](#2620)
fill transformation matrix used

wg_engine: wrong gradient transformation fixed

---

src/loaders/lottie/tvgLottieLoader.cpp

set the dirName as the current location by default.
issue: https://github.com/thorvg/thorvg/issues/2733

lottie: fixed memory violation.

---

.github/labeler.yml
.github/workflows/pull_request_label.yml

Add a labeler that automatically creates labels when a pull request is created.
(You can edit the labeler by modifying ./.github/labeler.yml.)
https://github.com/thorvg/thorvg/issues/labels

infra: Add PR labeler

---

examples/Capi.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/loaders/lottie/thorvg_lottie.h
src/renderer/tvgPaint.cpp
src/renderer/tvgPicture.cpp
src/renderer/tvgScene.h
src/renderer/tvgShape.cpp
src/renderer/tvgShape.h
src/renderer/tvgText.h
test/capi/capiShape.cpp
test/capi/capiText.cpp
test/testPaint.cpp
test/testShape.cpp

**promoted offical c++ apis (v0.15)**
- enum class BlendMethod
- enum class CanvasEngine::Wg
- virtual Result Canvas::viewport(int32_t x, int32_t y, int32_t w, int32_t h);
- class Text
- Result Text::fill(uint8_t r, uint8_t g, uint8_t b)
- Result Text::fill(std::unique_ptr<Fill> f)
- static Result Text::unload(const std::string& path)
- static Result Text::load(const std::string& path)
- static Result Text::load(const char* name, const char* data, uint32_t size, const std::string& mimeType = "ttf", bool copy = false)
- static std::unique_ptr<Text> Text::gen()
- class WgCanvas
- static std::unique_ptr<WgCanvas> WgCanvas::gen()
- static const char* Initializer::version(uint32_t* major, uint32_t* minor, uint32_t* micro)
- class LottieAnimation
**promoted official c apis (v0.15)**
- …

api: clean up

---

src/renderer/wg_engine/tvgWgRenderData.cpp

Prevent crash for begin == end;

wg_engine: fix stroke trimming crash

---

src/renderer/sw_engine/tvgSwRaster.cpp

Rastering for 32bits dst buffer was implemented,
but 8bits dst were not supported.
@Issue: https://github.com/thorvg/thorvg/issues/2765
before (or crash):
after:
samples: 
[mask_op_99_rect.json](https://github.com/user-attachments/files/17156382/mask_op_99_rect.json)
[mask_op_100_rect.json](https://github.com/user-attachments/files/17156383/mask_op_100_rect.json)

sw_engine: add support for 8bits gradient rectangles

---

examples/MultiCanvas.cpp

This PR changed the MultiCanvas code to show how to render the content of GlCanvas to a given off-screen framebuffer.
#2746 
----

example: MultiCanvas show case with GL backend

---

src/loaders/lottie/tvgLottieBuilder.cpp

Use a clipper instead of masking when the condition is satisfied. Generally, clipping is cheaper than masking in fps & memory usage.
issue: https://github.com/thorvg/thorvg/issues/2647

lottie: optimization++

---

src/loaders/lottie/jerryscript/jerry-core/include/jerryscript-compiler.h

issue: https://github.com/thorvg/thorvg/issues/2764

lottie: portability++

---

src/loaders/lottie/tvgLottieParser.cpp

fixed a break in expressions/driving.json

lottie: hotfix layer effect parsing

---

src/renderer/sw_engine/tvgSwRle.cpp
src/renderer/sw_engine/tvgSwStroke.cpp

cut the Bezier curve based on the number of points and transform it into a straight line when it's very small.
issue: https://github.com/thorvg/thorvg/issues/2759

sw_engine: ++stability

---

src/common/tvgCompressor.cpp
test/testSwEngine.cpp

issue: https://github.com/thorvg/thorvg/issues/2794

renderer/compressor: corrected base64 decoded data size

---

src/meson.build

Apply the flag even if the sanitizer is toggled on.

infra: --shutdown the unkown-pragmas warning

---

src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderer.cpp

issue https://github.com/thorvg/thorvg/issues/2819
picture mesh data was not released

wg_engine: fix picture memory leak

---

meson.build

set dev mode for the next 1.0 release

release: bump up version v0.15

---

examples/Example.h
src/renderer/tvgWgCanvas.cpp
src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

issue: https://github.com/thorvg/thorvg/issues/2808

wg_engine: fixed resource leaks

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/renderer/tvgAccessor.cpp
src/renderer/tvgFill.cpp
src/renderer/tvgPaint.cpp
src/renderer/tvgPicture.cpp
src/renderer/tvgScene.cpp
src/renderer/tvgShape.cpp

api: remove deprecations

---

AUTHORS

SergeyLebedkin -> Sergii Liebodkin

common: fix autors name

---

wasm_build.sh

The build folder is now aligned with the thorvg.web build.

wasm: fix unified build folder structure

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/renderer/sw_engine/tvgSwMath.cpp
src/renderer/sw_engine/tvgSwPostEffect.cpp
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/sw_engine/tvgSwShape.cpp

Optimize the render region and fine-tune the Lottie effects for improved general performance.

post effect: optimization++

---

src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwMath.cpp
src/renderer/sw_engine/tvgSwRle.cpp

@Issue: https://github.com/thorvg/thorvg/issues/2651

sw_engine: split long lines to avoid overflow

---

wasm_build.sh

Fixed typo. It breaks build progress now.

wasm: update wasm build script

---

examples/Example.h
examples/MultiCanvas.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/tvgRender.h
src/renderer/tvgSwCanvas.cpp
src/renderer/wg_engine/tvgWgRenderer.cpp
src/savers/gif/tvgGifSaver.cpp
test/testAccessor.cpp
test/testPicture.cpp
test/testSwCanvas.cpp
test/testSwEngine.cpp
tools/svg2png/svg2png.cpp

- SwCanvas::Colorspace -> ColorSpace
API Addition:
- ColorSpace::Unknown

api: polish the thorvg API usages.

---

inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwRaster.cpp
src/renderer/tvgPaint.cpp
src/renderer/tvgPicture.cpp
src/renderer/tvgScene.h
src/renderer/tvgShape.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h

Note that this could break the tvg binaries.

api: removed redundant CompisiteMethod::ClipPath

---

inc/thorvg.h
src/loaders/svg/tvgSvgSceneBuilder.cpp
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/sw_engine/tvgSwFill.cpp
src/renderer/tvgFill.cpp
src/renderer/tvgFill.h
src/renderer/wg_engine/tvgWgRenderData.cpp

- refactored the Fill matrix to hold internal data statically.
- refactored for clean & neat the raster engine / svg loader logic.
- Matrix Fill::transform() const -> Matrix& Fill::transform() const

api: Fill Transform revision

---

src/common/tvgMath.h
src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/wg_engine/tvgWgGeometry.h

issue: https://github.com/thorvg/thorvg/issues/2313

wg_engine: merged math functions with common

---

src/loaders/lottie/tvgLottieModifier.cpp

For long Bezier curves compared to the offset value, the offsetting algorithm caused deformation. The problem became evident after adding mask extension, as the simple shapes defined there are based on Bezier curves rather than as shapes like a circle/rect/etc, which is the case for the offset. Now fixed.
before:
after:
sample:
[maskExpMax.json](https://github.com/user-attachments/files/17408137/maskExpMax.json)
[maskExpMin.json](https://github.com/user-attachments/files/17408138/maskExpMin.json)

lottie: fix offset

---

src/renderer/gl_engine/tvgGlRenderTask.h
src/renderer/gl_engine/tvgGlRenderer.cpp

- clean up code
- resolve some data casting compiler warnings

gl_engine: code refactoring

---

src/loaders/external_png/tvgPngLoader.cpp
src/loaders/png/tvgPngLoader.cpp
src/renderer/gl_engine/tvgGlShaderSrc.cpp

issue: https://github.com/thorvg/thorvg/pull/2880

png, gl_engine: fixed an wrong png colorspace.

---

src/loaders/svg/tvgSvgSceneBuilder.cpp

Apply scene when a clipper or masking was required.
This is a prerequisite task for migrating
the clip()/mask() features from Paint to Scene.
issue: https://github.com/thorvg/thorvg/issues/2831

svg: wrapping a paint with a scene

---

examples/Blending.cpp
examples/Capi.cpp
examples/FillSpread.cpp
examples/GradientStroke.cpp
examples/GradientTransform.cpp
examples/RadialGradient.cpp
examples/Text.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/renderer/tvgFill.cpp
src/renderer/wg_engine/tvgWgShaderTypes.cpp
test/capi/capiRadialGradient.cpp
test/capi/capiText.cpp
test/testFill.cpp
test/testSwEngine.cpp

@Issue: https://github.com/thorvg/thorvg/issues/2860

api: add focal parameters to the radial apis

---

src/renderer/tvgPaint.h

issue: https://github.com/godotengine/godot/pull/91580#issuecomment-2434596114

renderer: --shadow variable compiler warning

---

src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgCompositor.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgRenderTarget.cpp
src/renderer/wg_engine/tvgWgRenderTarget.h

Used native hardware MSAA x4
Full multisampling support including custom blend and compositions.
Must be verified on web and 4K resolution for performance issues
before/after
before/after

wg_engine: multisampling support

---

src/renderer/wg_engine/tvgWgGeometry.h

On a close path command creates a new object started form the closed point
This change handle cases like this:
```
shape->moveTo(10, 10);
shape->lineTo(510, 10);
shape->lineTo(510, 510);
shape->lineTo(10, 510);
shape->close();
shape->lineTo(510, 510);
```
See: _consecutive_lines.svg_
Issue https://github.com/thorvg/thorvg/issues/2592
Before:
After:

wg_engine: fix close command logic

---

src/renderer/sw_engine/tvgSwRenderer.cpp

issue: https://github.com/thorvg/thorvg/pull/2955

sw_engine: ++exceptional handling

---

examples/LottieExtension.cpp
src/loaders/lottie/tvgLottieParser.cpp

lottie/slot: Fix incorrect image slot schema

---

src/loaders/lottie/tvgLottieLoader.cpp

Keep trying overriding even if the given sid is invalid.
issue: https://github.com/thorvg/thorvg/issues/2969

lottie: ++slot overriding

---

src/loaders/svg/tvgSvgLoader.cpp

@Issue: https://github.com/thorvg/thorvg/issues/2960
sample:
```
<svg width="30" height="30" xmlns="http://www.w3.org/2000/svg">
<g color="#ff00ff">
<g color="#ff0000">
<g>
<linearGradient id="c" x2="1">
<stop stop-color="currentColor"/>
</g>
<linearGradient id="a" x2="1">
<stop stop-color="currentColor"/>
</g>
<linearGradient id="b" x2="1">
<stop stop-color="currentColor"/>
</g>
<circle r="4" fill="url(#a)" cx="11" cy="11"/>
<circle r="4" fill="url(#b)" cx="5" cy="5"/>
<circle r="4" fill="url(#c)" cx="17" cy="5"/>
</svg>
```
result:

svg_loader: handle currentColor inside gradient

---

examples/Example.h
examples/MultiCanvas.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/renderer/tvgGlCanvas.cpp

API modification:
- Result GlCanvas::target(int32_t id, uint32_t w, uint32_t h) 
-> Result GlCanvas::target(int32_t id, uint32_t w, uint32_t h, ColorSpace cs)
- Tvg_Result tvg_glcanvas_set_target(Tvg_Canvas* canvas, int32_t id, uint32_t w, uint32_t h)
-> Tvg_Result tvg_glcanvas_set_target(Tvg_Canvas* canvas, int32_t id, uint32_t w, uint32_t h, Tvg_Colorspace cs)

api: revise the gl target() api.

---

src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwRaster.cpp
src/renderer/sw_engine/tvgSwRasterAvx.h
src/renderer/sw_engine/tvgSwRasterC.h
src/renderer/sw_engine/tvgSwRasterNeon.h
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/tvgRender.h
src/renderer/tvgShape.cpp
src/renderer/tvgShape.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgShaderTypes.cpp
src/renderer/wg_engine/tvgWgShaderTypes.h

- introduced RenderColor
- internal name changes to avoid conflicts

renderer: code refactoring

---

src/loaders/lottie/tvgLottieModel.cpp

contains #2951
square was already supported
|shape|AE|TVG|
|------|--|----|
|[rampUp](https://github.com/user-attachments/files/17717191/rampUp.json)|<img width="600" alt="rampUp_AE" src="https://github.com/user-attachments/assets/65b9c7dc-ff96-4149-b0c3-2e69fb5cebcb">|<img width="600" alt="rampUp_tvg" src="https://github.com/user-attachments/assets/e396c19d-c4d4-49d3-8eba-33f6600832aa">|
|[rampDown](https://github.com/user-attachments/files/17717194/rampDown.json)|<img width="890" alt="rampDown_AE" src="https://github.com/user-attachments/assets/6685fece-d506-481d-8462-736853721fc3">|<img width="795" alt="rampDown_tvg" src="https://github.com/user-attachments/assets/0290959e-8f95-4563-a0ad-89575a7d4763">|
|[triangle](https://github.com/user-attachments/files/17717205/triangle.json)|<img …

lottie: shapes support in text range selector

---

examples/Example.h
examples/MultiCanvas.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/bindings/wasm/tvgWasmLottieAnimation.cpp
src/renderer/tvgWgCanvas.cpp
src/renderer/wg_engine/tvgWgBindGroups.cpp
src/renderer/wg_engine/tvgWgBindGroups.h
src/renderer/wg_engine/tvgWgCommon.cpp
src/renderer/wg_engine/tvgWgCommon.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

Added ability for canvas to render into external target texture, in addition to surface 
Issue https://github.com/thorvg/thorvg/issues/2745
See MultyCanvas example

wg_engine: multicanvas support

---

src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieParser.h

fixed a parsing failure that occurred
when a desired single value was presented as part of an array.
issue: https://github.com/thorvg/thorvg/issues/2975

lottie: ++parser stability

---

examples/Example.h
src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgCompositor.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

Added abillity to resize target (surface)
In case of resizing only render targets handles recreated 
Must be tested in web environment
Issue: https://github.com/thorvg/thorvg/issues/2985

wg_engine: support resizing

---

src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h

Pipeline creation workflow redesigned.
Make code more compact
No any public interfaces changed
See Clipping, Blendking, Masking examples

wg_engine: refactor pipeline creation

---

src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgShaderSrc.cpp

See SceneBlending example
Issue: https://github.com/thorvg/thorvg/issues/2998

wg_engine: Fixed scene blending equation and clear color rule

---

examples/Retaining.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/loaders/lottie/tvgLottieBuilder.cpp
src/renderer/tvgCanvas.cpp
src/renderer/tvgCanvas.h
src/renderer/tvgScene.cpp
src/renderer/tvgScene.h
src/renderer/tvgSwCanvas.cpp
test/testPaint.cpp
test/testScene.cpp

- Enhanced Scene management to provide users with more control.
- Scenes now support adding specific scenes at defined positions and removing them as needed.
- Ensure safe access to Canvas, Scene paints() by adding const specifiers.
- Removed virtual specifier for the canvas primitive apis.
- Introduced a nested scene in the canvas to remove logic duplication.
C++ API Modification:
- Result Scene::push(Paint* paint)
-> Result Scene::push(Paint* target, Paint* at = nullptr)
- Result Scene::clear(bool free = true)
-> Result Scene::remove(Paint* paint = nullptr)
- Result Canvas::push(Paint* paint)
-> Result Canvas::push(Paint* target, Paint* at = nullptr)
- list<Paint*>& Scene::paints()
-> const list<Paint*>& Scene::paints() const
- list<Paint*>& Canvas::paints()
-> const list<Paint*>& …

1.0 API Spec Revision

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/renderer/sw_engine/tvgSwPostEffect.cpp
src/renderer/tvgRender.h

Pre-convert the data type from float to uint8_t

common: refactored the scene effect tint

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieBuilder.h
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieParser.h
src/loaders/lottie/tvgLottieProperty.h

issue: https://github.com/thorvg/thorvg/issues/2718
https://github.com/user-attachments/assets/5c9d8c5a-6ff4-4a2c-b81f-98c7f90d01a3

lottie: support Stroke layer effect

---

examples/Example.h
examples/MultiCanvas.cpp
inc/thorvg.h
src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp
src/bindings/wasm/tvgWasmLottieAnimation.cpp
src/renderer/gl_engine/tvgGlCommon.h
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/sw_engine/tvgSwRenderer.h
src/renderer/tvgCanvas.h
src/renderer/tvgGlCanvas.cpp
src/renderer/tvgRender.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

gl_engine: revise target API for context managing

---

src/loaders/svg/tvgSvgSceneBuilder.cpp

Main purpose clippath is to cutout the
drawing region with a path. Otherwise
we need to use MaskMethod.

svg: remove styles from the clipPath

---

src/loaders/svg/tvgSvgSceneBuilder.cpp

Completely remove an element if the applied clip/mask is empty.
@Issue: https://github.com/thorvg/thorvg/issues/3089

svg: specs ++

---

examples/Blending.cpp
examples/MultiCanvas.cpp
examples/PictureSvg.cpp

Note that scene blending doesn't work properly

examples: revise the blending sample

---

src/common/tvgMath.h
src/loaders/lottie/tvgLottieModel.cpp
src/renderer/sw_engine/tvgSwCommon.h

issue: https://github.com/thorvg/thorvg/issues/3072

sw_engine: corrected the blending

---

src/renderer/wg_engine/tvgWgShaderSrc.cpp

issue: https://github.com/thorvg/thorvg/issues/3072

wg_engine: corrected ColorDodge, ColorBurn equation

---

src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h

Use reference insted of value for context passing

wg_engine: fix context handle passing by ref

---

src/renderer/sw_engine/tvgSwRasterTexmap.h

fixed a runtime error report of the sanitizer
at data casting.
issue: https://github.com/thorvg/thorvg/issues/3102

sw_engine: ++portability on macOS

---

examples/Accessor.cpp
inc/thorvg.h
src/bindings/capi/tvgCapi.cpp
src/renderer/tvgPaint.cpp
src/renderer/tvgShape.cpp
src/renderer/tvgShape.h
test/testAccessor.cpp
test/testShape.cpp

API modification:
- Shape::fillColor() -> Shape::fill()

api: renamed api for consistency

---

src/renderer/gl_engine/tvgGlShaderSrc.cpp

issue: https://github.com/thorvg/thorvg/issues/3072

gl_engine: corrected ColorDodge, ColorBurn equation

---

src/bindings/wasm/tvgWasmLottieAnimation.cpp
src/renderer/gl_engine/tvgGlRenderer.cpp

Fixed wasm build issues from latest webgl changes.

wasm: fix build issues

---

src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwPostEffect.cpp
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/sw_engine/tvgSwRenderer.h
src/renderer/tvgRender.h
src/renderer/tvgScene.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h

RenderMethod effects methods would have changes:
- update()               //update the effects if any
- prepare() -> region()  //update the effect drawing region
- effect() -> render()   //draw the effect

renderer: improved engine for scalable effects

---

src/renderer/sw_engine/tvgSwRasterTexmap.h

Compromed the translucent/opaque logic by unifying them, for code size and maintenance.

sw_engine/texmap: tuning the blending logic

---

src/renderer/sw_engine/tvgSwPostEffect.cpp

Applied the compromised approach for the gaussian blur since the effect is a bit burdensome for cpu processing as animatable effects.
- Optimized performance and quality with negligible observable differences.
- Disabled the border option until specific use cases are identified.

sw_engine: Improved the blur performance by 12%

---

src/loaders/lottie/tvgLottieBuilder.h
src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieParser.h

expressions is an optional feature,
do not prepare expressions if the engine doesn't support it.

lottie: expressions compactness++

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h
src/loaders/svg/tvgSvgSceneBuilder.cpp

```
<svg width="230" height="120" xmlns="http://www.w3.org/2000/svg">
<filter id="blurMe">
<feGaussianBlur stdDeviation="5"/>
</filter>
<circle cx="60" cy="60" r="50" fill="green" />
<g filter="url(#blurMe)">
<circle cx="170" cy="60" r="50" fill="green"  />
</g>
</svg>
```
issue: https://github.com/thorvg/thorvg/issues/1367

svg: added filter node support

---

src/renderer/gl_engine/tvgGlRenderer.cpp

sample:
```
if (!canvas) return false;
//Shape 1
shape1->appendRect(50, 50, 200, 200);
shape1->fill(250, 0, 0);
shape1->strokeFill(0, 255, 0);
shape1->strokeWidth(30);                       
shape1->order(true);
//Shape 2
auto shape2 = tvg::Shape::gen();
shape2->appendRect(200, 150, 200, 200);
shape2->fill(0, 0, 255);
shape2->strokeFill(0, 255, 0);
shape2->strokeWidth(30);
shape2->order(false);
canvas->push(shape2);
```
before (left - sw, right - gl):
after (left - sw, right - gl):

gl_engine: add support for stroke/fill ordering

---

src/loaders/svg/tvgSvgLoader.cpp

Removed unnecessary initialization of variables
to 0/false in memory allocated by calloc.

svg_loader: loc--

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieBuilder.h
src/loaders/lottie/tvgLottieExpressions.h
src/loaders/lottie/tvgLottieProperty.h

- renamed internal variable for improved simplicity. no logical changes.
- Unified the property expression and default version.
- improved readability and maintenance by separating the path modifier from the default path operation.

lottie: code refactoring++

---

examples/Example.h

include <cstring> in examples/Example.h

---

src/common/tvgArray.h
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.cpp

introduced ARRAY_REVERSE_FOREACH() macro.

commmon: ++neat code

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieExpressions.h
src/loaders/lottie/tvgLottieModifier.cpp
src/loaders/lottie/tvgLottieModifier.h
src/loaders/lottie/tvgLottieProperty.h
src/renderer/tvgRender.h

introduced RenderPath to minimize the path parameters.

lottie: ++compact & neat code

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieBuilder.h
src/loaders/lottie/tvgLottieExpressions.h
src/loaders/lottie/tvgLottieModifier.cpp
src/loaders/lottie/tvgLottieModifier.h
src/loaders/lottie/tvgLottieProperty.h
src/renderer/tvgRender.h

- use a reusable buffer for intermediate path generation.
- use a decoration style for path-modification chaining.
- ++minor code refactoring

lottie: minor optimization

---

src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgCompositor.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h
src/renderer/wg_engine/tvgWgShaderTypes.cpp
src/renderer/wg_engine/tvgWgShaderTypes.h

Introduce blur effect for webgpu renderer
Supported gamma and direction properties and scale
Both/Horisontal/Vertical
Svg example

wg_engine: gaussian blur basic implementation

---

src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/gl_engine/tvgGlTessellator.h
src/renderer/meson.build
src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwShape.cpp
src/renderer/tvgRender.h
src/renderer/tvgShape.h
src/renderer/tvgTrimPath.cpp
src/renderer/tvgTrimPath.h
src/renderer/wg_engine/tvgWgGeometry.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h

refactoring + https://github.com/thorvg/thorvg/issues/3053 fixed

common: trimmed fill

---

src/renderer/gl_engine/tvgGlTessellator.cpp

Incorrect condition for drawing segments in cubics;
missing checks.
@issue: https://github.com/thorvg/thorvg/issues/2729
@issue: https://github.com/thorvg/thorvg/issues/3222
before:
after (guy ona bike - improved but not solved yet):
before (sw - left, gl - right):
after (sw - left, gl - right):

gl_engine: fix dashing

---

src/renderer/wg_engine/tvgWgRenderer.cpp

wg_engine: Fix undefined error in task scheduler usage

---

src/bindings/wasm/tvgWasmLottieAnimation.cpp

wasm: fix ambigious symbols

---

src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgCompositor.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h
src/renderer/wg_engine/tvgWgShaderTypes.cpp
src/renderer/wg_engine/tvgWgShaderTypes.h

Supported _color, angle, distance, sigma, quality params_
See **EffectDropShadow** example
https://github.com/user-attachments/assets/1f7d2470-bccb-4299-85c5-0ce8e579800d

wg_engine: Introduce drop shadow effect for webgpu renderer

---

src/renderer/wg_engine/tvgWgCompositor.cpp
src/renderer/wg_engine/tvgWgCompositor.h
src/renderer/wg_engine/tvgWgPipelines.cpp
src/renderer/wg_engine/tvgWgPipelines.h
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderer.cpp
src/renderer/wg_engine/tvgWgRenderer.h
src/renderer/wg_engine/tvgWgShaderSrc.cpp
src/renderer/wg_engine/tvgWgShaderSrc.h
src/renderer/wg_engine/tvgWgShaderTypes.cpp
src/renderer/wg_engine/tvgWgShaderTypes.h

Supported color param
See SceneEffects example

wg_engine: Introduce fill effect for webgpu renderer

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieData.h
src/loaders/lottie/tvgLottieParser.cpp

removed the duplicate logic,
improved for neat and easy maintainance

lottie: revise the text justify logic

---

src/renderer/wg_engine/tvgWgCompositor.cpp

Issue: https://github.com/thorvg/thorvg/issues/3298
sw/wg

wg_engine: stroke clipping issue

---

src/common/tvgStr.cpp
src/common/tvgStr.h
src/loaders/lottie/tvgLottieInterpolator.cpp
src/loaders/lottie/tvgLottieLoader.cpp
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieParserHandler.cpp
src/loaders/lottie/tvgLottieProperty.h
src/loaders/svg/tvgSvgCssStyle.cpp
src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgPath.cpp
src/loaders/svg/tvgXmlParser.cpp
src/renderer/tvgLoader.cpp
src/renderer/tvgSaver.cpp
src/renderer/tvgText.h
src/savers/gif/tvgGifSaver.cpp

renamed the prefix to be slimmer and more compact.

common: str refactoring

---

src/loaders/lottie/tvgLottieBuilder.cpp

Added missing carriage return support in local font case.
issue: #3301

lottie/text: render carriage return with local font

---

src/renderer/sw_engine/tvgSwMath.cpp
src/renderer/sw_engine/tvgSwRle.cpp

https://github.com/thorvg/thorvg/issues/2657

sw_engine: hotfix 

---

src/renderer/gl_engine/tvgGlTessellator.cpp
src/renderer/gl_engine/tvgGlTessellator.h
src/renderer/sw_engine/tvgSwRenderer.cpp
src/renderer/sw_engine/tvgSwShape.cpp
src/renderer/tvgRender.h
src/renderer/tvgShape.h
src/renderer/wg_engine/tvgWgGeometry.h
src/renderer/wg_engine/tvgWgRenderData.cpp

introdced the length to avoid duplicate among engines

common: refactoring the dash pattern

---

src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgXmlParser.cpp
src/loaders/svg/tvgXmlParser.h

svg: clean & neat code++

---

src/renderer/gl_engine/tvgGlShaderSrc.cpp

Fix luma equation for opengl renderer
https://github.com/thorvg/thorvg/issues/3045

gl_engine: luma visual differneces fix

---

src/loaders/lottie/tvgLottieModel.cpp
src/loaders/svg/tvgSvgSceneBuilder.cpp
src/renderer/tvgLoader.cpp
src/renderer/tvgTaskScheduler.cpp
src/renderer/tvgTaskScheduler.h

fortitfy the thread safety
in multi-threaded resource loading.
issue: https://github.com/thorvg/thorvg/issues/3306

common: ++loader thread safety

---

src/loaders/ttf/tvgTtfLoader.cpp
src/loaders/ttf/tvgTtfLoader.h
src/loaders/ttf/tvgTtfReader.cpp
src/loaders/ttf/tvgTtfReader.h
src/renderer/tvgLoadModule.h
src/renderer/tvgLoader.cpp
src/renderer/tvgText.h

Properly allow the ttf loader sharable among threads.
issue: https://github.com/thorvg/thorvg/issues/3165

ttf: ++thread safety

---

src/bindings/capi/thorvg_capi.h
src/bindings/capi/tvgCapi.cpp

This patch adds basic Accessor API to the C bindings.

api: exposed Accessor to C

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieParser.cpp

reverted stroke optimization from the previous cullting stragtegy. introduced by d386a5654a238bde2209a6fb07f94a87baeab256

lottie: ++safety

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieBuilder.h
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h

merge the scene with more accurate condition to allow the evenodd pathes among the lottie render tree.

lottie: improve the compatiblity

---

src/bindings/wasm/tvgWasmLottieAnimation.cpp

removed a bunch of #ifdefs and consolidated
implementations across engines.

binding/wasm: code refactoring

---

src/loaders/external_webp/tvgWebpLoader.cpp
src/loaders/jpg/tvgJpgLoader.cpp
src/loaders/png/tvgPngLoader.cpp
src/loaders/svg/tvgSvgLoader.cpp
src/loaders/webp/tvgWebpLoader.cpp

make it sync before deleting the loaders.

loaders: ++static loader thread safty

---

src/renderer/gl_engine/tvgGlCommon.h
src/renderer/gl_engine/tvgGlRenderTask.cpp
src/renderer/gl_engine/tvgGlRenderTask.h
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/gl_engine/tvgGlShaderSrc.cpp
src/renderer/gl_engine/tvgGlShaderSrc.h

fully integrated into existing passes/tasks/fbo/viewports/buffers/pools pipelines
issue: https://github.com/thorvg/thorvg/issues/3054

gl_engine: Introduce gauss blur effect for opengl renderer v2

---

src/renderer/gl_engine/tvgGlCommon.h
src/renderer/gl_engine/tvgGlRenderTask.cpp
src/renderer/gl_engine/tvgGlRenderTask.h
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/gl_engine/tvgGlShaderSrc.cpp
src/renderer/gl_engine/tvgGlShaderSrc.h

issue: https://github.com/thorvg/thorvg/issues/3054
see EffectDropShadow example

gl_engine: introduce dropshadow effect for opengl renderer

---

inc/thorvg.h
src/loaders/lottie/thorvg_lottie.h
src/loaders/lottie/tvgLottieAnimation.cpp

something wrong with typeinfo missing in destructor (don't know reason) and this resolves the problem.

api: fixed a build linking issue on lottie

---

src/renderer/tvgScene.h

return success if any scene children are drawable.

renderer: tweak rendering behavior

---

src/loaders/svg/tvgSvgSceneBuilder.cpp

Clipping for the <use> node when a <symbol> was used, was being overridden when 'overflowVisible' was 'true' (the default value), which caused the 'clip-path' applied to the <use> node to have no visible effect.
The clipping for the <use> node (without <symbol> node) was transformed in an incorrect order, resulting in a visually incorrect results.
@Issue: https://github.com/thorvg/thorvg/issues/3392
before:
after (as expected):
samples:

svg_loader: fix clipping in use/symbol nodes

---

src/renderer/wg_engine/tvgWgRenderer.cpp

Allows the target texture to be updated without forcing the size to changed.

wg_engine: fixed target texture update

---

src/renderer/wg_engine/tvgWgRenderer.cpp

Allows the target **surface** to be updated without forcing the size to changed.

wg_engine: fixed target surface update

---

src/bindings/capi/thorvg_capi.h

Adds missing mask methods to the capi

capi: added missing mask methods

---

src/loaders/lottie/tvgLottieModel.cpp

The first margin value shifts the starting point where the text begins along the path. Now cases where firstMargin < 0 are handled, for both closed and open paths.
before:
after (tested together with #3391):
samples:
[follow_close_ell.json](https://github.com/user-attachments/files/19674564/follow_close_ell.json)
[follow_close_rect.json](https://github.com/user-attachments/files/19674565/follow_close_rect.json)
[follow_ellips.json](https://github.com/user-attachments/files/19674566/follow_ellips.json)
[follow_open.json](https://github.com/user-attachments/files/19674567/follow_open.json)
[follow_rect.json](https://github.com/user-attachments/files/19674568/follow_rect.json)

lottie: support for firstMargin < 0 in text follow path

---

src/loaders/jpg/tvgJpgd.cpp

Replaced non-portable setjmp/longjmp-based error handling with conventional return-based error propagation.
This approach improves compatibility with Rust and other environments that do not support stack manipulation via jump buffers.

jpg: removed setjmp usage for better portability

---

src/renderer/sw_engine/tvgSwRasterTexmap.h

- Replaced `modff()` with a custom method, boosting texture mapping performance by ~15%.
- Unified opacity/non-opacity logic for improved binary size efficiency(-0.5kb).
- Implemented minor changes for better cache effectiveness.

sw_engine: texture mapping performance optimization

---

src/renderer/sw_engine/tvgSwRasterTexmap.h

The old approach often produced incorrect results, especially when the fixed pixel had a noticeably
different color from the texture due to the AA
target blending position was fixed.
Although the previous method worked well as an analytical AA solution with good speed and fair quality, it couldn't overcome the above limitation.
The new approach still applies AA only to polygon edges for efficiency. While the quality may be slightly reduced, it offers greater stability.
- binary size: -1.1kb
- performance diff: ignoreable
issue: https://github.com/thorvg/thorvg/issues/1729

sw_engine: replaced texture mapping AA with 4x sampling interp

---

src/renderer/tvgScene.h

reuse cached scene viewport data if scene had no update before, just a minor optimization

renderer: caching the viewport update

---

src/loaders/lottie/tvgLottieAnimation.cpp
src/renderer/tvgAnimation.cpp
src/renderer/tvgPaint.cpp
src/renderer/tvgPaint.h
src/renderer/tvgPicture.h
src/renderer/tvgShape.h
src/renderer/tvgText.h

clear out the render update flag to skip any
unnecessary update situation.

renderer: clean up the render update condition

---

examples/Example.h
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.h

lottie: fixed an issue where the last frame was missing

---

src/renderer/sw_engine/tvgSwRaster.cpp

A potential memory violation issue was present when accessing image buffers, especially when the image was offset outside the visible screen region.
This issue was accidentally discovered while testing particle effects. It is now properly handled with cleaner and safer code.

sw_engine: Fix potential memory violation in direct image drawing

---

src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp

previously, only layer-level blending was supported. Now, blending has been extended to support group-level as well.

lottie: support group-level blending

---

src/renderer/sw_engine/tvgSwCommon.h

slightly adjusted the equation for adobe/figma alignment

sw_engine: rectified softlight blending equation

---

src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwRaster.cpp
src/renderer/sw_engine/tvgSwRasterTexmap.h
src/renderer/sw_engine/tvgSwRenderer.cpp

enhanced anti-aliasing in image blending by properly applying unpremultiply/premultiply computations during blending operations.

sw_engine: improved blending quality

---

src/renderer/gl_engine/meson.build
src/renderer/gl_engine/tvgGlCommon.h
src/renderer/gl_engine/tvgGlEffect.cpp
src/renderer/gl_engine/tvgGlEffect.h
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/gl_engine/tvgGlRenderer.h
src/renderer/gl_engine/tvgGlShaderSrc.h

- consolidated the effect implementation from renderer
- applied the deferred initialization

gl_engine: revised the effect logic

---

src/common/meson.build
src/common/tvgColor.cpp
src/common/tvgColor.h
src/loaders/lottie/tvgLottieBuilder.cpp
src/loaders/lottie/tvgLottieData.h
src/loaders/lottie/tvgLottieExpressions.cpp
src/loaders/lottie/tvgLottieExpressions.h
src/loaders/lottie/tvgLottieModel.cpp
src/loaders/lottie/tvgLottieModel.h
src/loaders/lottie/tvgLottieParser.cpp
src/loaders/lottie/tvgLottieParser.h
src/loaders/lottie/tvgLottieProperty.h
src/loaders/svg/tvgSvgLoader.cpp
src/loaders/svg/tvgSvgLoaderCommon.h
src/renderer/tvgRender.h

- Introduced RGB, RGBA, and HSL structures
- Migrated hsl2Rgb() from SVG loader to common module
This is a refactoring for upcoming hsl color functionlaities.

common: consolidate color-related functions

---

test/testAccessor.cpp
test/testPaint.cpp
test/testPicture.cpp
test/testScene.cpp
test/testSwCanvas.cpp
test/testSwEngine.cpp
test/testText.cpp

- Revise Sw Engine & Canvas Tests
- Enabled the disabled tests.
- Fixed compilation errors.
- Resolved the test fail cases.
- Use ARGB8888 colorspace for speed.

test: updated coverage

---

src/renderer/sw_engine/tvgSwRenderer.cpp

logic is reverted by a mistake.
issue: https://github.com/thorvg/thorvg/issues/3679

sw_engine: hotfix a partial rendering condition

---

src/renderer/sw_engine/tvgSwRenderer.cpp

fixed a corner case that rendering is not properly updated only if the opacity is updated.

sw_engine: stability++

---

src/renderer/sw_engine/tvgSwRenderer.cpp

Streamlined the update logic computation
with a more accurate retained drawing region.
This fixes the performance regression introduced by commit b2875b6c1428528e1235197e116c8ff724787d7b.

sw_engine: recovered performance regression after v1.0-pre26

---

src/renderer/sw_engine/tvgSwCommon.h
src/renderer/sw_engine/tvgSwMemPool.cpp
src/renderer/sw_engine/tvgSwShape.cpp

Unified memory pool possible between shapes and dash outlines.

sw_engine: memory optimization++

---

inc/thorvg.h
src/renderer/tvgPaint.cpp

Just let it allow to all paints type.
Composition blending method is still experimental.

api: doc++

---

src/loaders/lottie/tvgLottieExpressions.cpp

Fixes issue where nested property access was not recognized
- Added .value property to Vector and Scalar type objects in expressions
- Enables access to property values via `transform.position.value` syntax
issue: https://github.com/thorvg/thorvg/issues/3693

lottie/expressions: add .value property accessor support

---

src/loaders/jpg/tvgJpgd.cpp

- fine-tune jpg loader with better lightweight and fast.
- fix MCU block offset handling
size: -27kb
issue: https://github.com/thorvg/thorvg/issues/3699

loader/jpg: enhancement++

---

src/renderer/tvgPaint.cpp
src/renderer/tvgPicture.h
src/renderer/tvgRender.h
src/renderer/tvgScene.h
src/renderer/tvgShape.h
src/renderer/tvgText.h

supplemented a few missing properites at duplicate()

renderer: paint duplication++

---

src/loaders/ttf/tvgTtfLoader.cpp

Simplify the logic by unifying it
into the text processing iteration.

ttf: optimize codepoint conversion

---

src/renderer/gl_engine/tvgGlCommon.h
src/renderer/gl_engine/tvgGlGeometry.cpp
src/renderer/gl_engine/tvgGlRenderer.cpp
src/renderer/wg_engine/tvgWgRenderData.cpp
src/renderer/wg_engine/tvgWgRenderData.h
src/renderer/wg_engine/tvgWgRenderer.cpp

Support hit detection by gl, wgpu in geometry level
Supported shapes and strokes geometries, including clipping
https://github.com/user-attachments/assets/0340ebc2-202b-40bc-9697-58d26662beae
https://github.com/thorvg/thorvg/issues/3746

wg/gl: hit detection support

---

src/loaders/lottie/tvgLottieBuilder.cpp

issue: https://github.com/thorvg/thorvg/issues/3808

lottie: corrected dropshadow distance
